// GENERATED BY scripts/gen-dart-clients.py — DO NOT EDIT BY HAND.
//
// Regenerate with:  scripts/gen-dart-clients.py
// The source of truth is the service's .proto. CI fails when they disagree.

import '../generated/planning.pb.dart' as planning_pb;
import 'base_service.dart';

/// ConnectRPC client for `agriculture.planning.v1.PlanningService`.
class PlanningServiceClient extends BaseService {
  PlanningServiceClient({
    required super.baseUrl,
    super.httpClient,
    super.interceptors,
  });

  @override
  String get serviceName => 'agriculture.planning.v1.PlanningService';

  /// Calls `CreatePlan`.
  Future<planning_pb.CreatePlanResponse> createPlan(
    planning_pb.CreatePlanRequest request,
  ) async {
    final bytes = await callUnary('CreatePlan', request);
    return planning_pb.CreatePlanResponse.fromBuffer(bytes);
  }

  /// Calls `GetPlan`.
  Future<planning_pb.GetPlanResponse> getPlan(
    planning_pb.GetPlanRequest request,
  ) async {
    final bytes = await callUnary('GetPlan', request);
    return planning_pb.GetPlanResponse.fromBuffer(bytes);
  }

  /// Calls `ListPlans`.
  Future<planning_pb.ListPlansResponse> listPlans(
    planning_pb.ListPlansRequest request,
  ) async {
    final bytes = await callUnary('ListPlans', request);
    return planning_pb.ListPlansResponse.fromBuffer(bytes);
  }

  /// Calls `UpdatePlan`.
  Future<planning_pb.UpdatePlanResponse> updatePlan(
    planning_pb.UpdatePlanRequest request,
  ) async {
    final bytes = await callUnary('UpdatePlan', request);
    return planning_pb.UpdatePlanResponse.fromBuffer(bytes);
  }

  /// Calls `CommitPlan`.
  Future<planning_pb.CommitPlanResponse> commitPlan(
    planning_pb.CommitPlanRequest request,
  ) async {
    final bytes = await callUnary('CommitPlan', request);
    return planning_pb.CommitPlanResponse.fromBuffer(bytes);
  }

  /// Calls `CheckRotation`.
  Future<planning_pb.CheckRotationResponse> checkRotation(
    planning_pb.CheckRotationRequest request,
  ) async {
    final bytes = await callUnary('CheckRotation', request);
    return planning_pb.CheckRotationResponse.fromBuffer(bytes);
  }

  /// Calls `GetSowingWindow`.
  Future<planning_pb.GetSowingWindowResponse> getSowingWindow(
    planning_pb.GetSowingWindowRequest request,
  ) async {
    final bytes = await callUnary('GetSowingWindow', request);
    return planning_pb.GetSowingWindowResponse.fromBuffer(bytes);
  }
}
