// GENERATED BY scripts/gen-dart-clients.py — DO NOT EDIT BY HAND.
//
// Regenerate with:  scripts/gen-dart-clients.py
// The source of truth is the service's .proto. CI fails when they disagree.

import '../generated/sustainability.pb.dart' as sustainability_pb;
import 'base_service.dart';

/// ConnectRPC client for `agriculture.sustainability.v1.SustainabilityService`.
class SustainabilityServiceClient extends BaseService {
  SustainabilityServiceClient({
    required super.baseUrl,
    super.httpClient,
    super.interceptors,
  });

  @override
  String get serviceName => 'agriculture.sustainability.v1.SustainabilityService';

  /// Calls `RecordInputUse`.
  Future<sustainability_pb.RecordInputUseResponse> recordInputUse(
    sustainability_pb.RecordInputUseRequest request,
  ) async {
    final bytes = await callUnary('RecordInputUse', request);
    return sustainability_pb.RecordInputUseResponse.fromBuffer(bytes);
  }

  /// Calls `ListInputUse`.
  Future<sustainability_pb.ListInputUseResponse> listInputUse(
    sustainability_pb.ListInputUseRequest request,
  ) async {
    final bytes = await callUnary('ListInputUse', request);
    return sustainability_pb.ListInputUseResponse.fromBuffer(bytes);
  }

  /// Calls `ComputeFootprint`.
  Future<sustainability_pb.ComputeFootprintResponse> computeFootprint(
    sustainability_pb.ComputeFootprintRequest request,
  ) async {
    final bytes = await callUnary('ComputeFootprint', request);
    return sustainability_pb.ComputeFootprintResponse.fromBuffer(bytes);
  }

  /// Calls `GetFootprint`.
  Future<sustainability_pb.GetFootprintResponse> getFootprint(
    sustainability_pb.GetFootprintRequest request,
  ) async {
    final bytes = await callUnary('GetFootprint', request);
    return sustainability_pb.GetFootprintResponse.fromBuffer(bytes);
  }

  /// Calls `ListFootprints`.
  Future<sustainability_pb.ListFootprintsResponse> listFootprints(
    sustainability_pb.ListFootprintsRequest request,
  ) async {
    final bytes = await callUnary('ListFootprints', request);
    return sustainability_pb.ListFootprintsResponse.fromBuffer(bytes);
  }

  /// Calls `CheckCertification`.
  Future<sustainability_pb.CheckCertificationResponse> checkCertification(
    sustainability_pb.CheckCertificationRequest request,
  ) async {
    final bytes = await callUnary('CheckCertification', request);
    return sustainability_pb.CheckCertificationResponse.fromBuffer(bytes);
  }

  /// Calls `ExportCertificationPack`.
  Future<sustainability_pb.ExportCertificationPackResponse> exportCertificationPack(
    sustainability_pb.ExportCertificationPackRequest request,
  ) async {
    final bytes = await callUnary('ExportCertificationPack', request);
    return sustainability_pb.ExportCertificationPackResponse.fromBuffer(bytes);
  }
}
