// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: sensor.proto

package sensorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SensorService_RegisterSensor_FullMethodName      = "/agriculture.sensor.v1.SensorService/RegisterSensor"
	SensorService_GetSensor_FullMethodName           = "/agriculture.sensor.v1.SensorService/GetSensor"
	SensorService_ListSensors_FullMethodName         = "/agriculture.sensor.v1.SensorService/ListSensors"
	SensorService_UpdateSensor_FullMethodName        = "/agriculture.sensor.v1.SensorService/UpdateSensor"
	SensorService_DecommissionSensor_FullMethodName  = "/agriculture.sensor.v1.SensorService/DecommissionSensor"
	SensorService_IngestReading_FullMethodName       = "/agriculture.sensor.v1.SensorService/IngestReading"
	SensorService_BatchIngestReadings_FullMethodName = "/agriculture.sensor.v1.SensorService/BatchIngestReadings"
	SensorService_GetLatestReading_FullMethodName    = "/agriculture.sensor.v1.SensorService/GetLatestReading"
	SensorService_GetReadingHistory_FullMethodName   = "/agriculture.sensor.v1.SensorService/GetReadingHistory"
	SensorService_CreateAlert_FullMethodName         = "/agriculture.sensor.v1.SensorService/CreateAlert"
	SensorService_ListAlerts_FullMethodName          = "/agriculture.sensor.v1.SensorService/ListAlerts"
	SensorService_AcknowledgeAlert_FullMethodName    = "/agriculture.sensor.v1.SensorService/AcknowledgeAlert"
	SensorService_GetSensorNetwork_FullMethodName    = "/agriculture.sensor.v1.SensorService/GetSensorNetwork"
	SensorService_CalibrateSensor_FullMethodName     = "/agriculture.sensor.v1.SensorService/CalibrateSensor"
)

// SensorServiceClient is the client API for SensorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SensorServiceClient interface {
	// Sensor lifecycle management
	RegisterSensor(ctx context.Context, in *RegisterSensorRequest, opts ...grpc.CallOption) (*RegisterSensorResponse, error)
	GetSensor(ctx context.Context, in *GetSensorRequest, opts ...grpc.CallOption) (*GetSensorResponse, error)
	ListSensors(ctx context.Context, in *ListSensorsRequest, opts ...grpc.CallOption) (*ListSensorsResponse, error)
	UpdateSensor(ctx context.Context, in *UpdateSensorRequest, opts ...grpc.CallOption) (*UpdateSensorResponse, error)
	DecommissionSensor(ctx context.Context, in *DecommissionSensorRequest, opts ...grpc.CallOption) (*DecommissionSensorResponse, error)
	// Data ingestion
	IngestReading(ctx context.Context, in *IngestReadingRequest, opts ...grpc.CallOption) (*IngestReadingResponse, error)
	BatchIngestReadings(ctx context.Context, in *BatchIngestReadingsRequest, opts ...grpc.CallOption) (*BatchIngestReadingsResponse, error)
	GetLatestReading(ctx context.Context, in *GetLatestReadingRequest, opts ...grpc.CallOption) (*GetLatestReadingResponse, error)
	GetReadingHistory(ctx context.Context, in *GetReadingHistoryRequest, opts ...grpc.CallOption) (*GetReadingHistoryResponse, error)
	// Alerting
	CreateAlert(ctx context.Context, in *CreateAlertRequest, opts ...grpc.CallOption) (*CreateAlertResponse, error)
	ListAlerts(ctx context.Context, in *ListAlertsRequest, opts ...grpc.CallOption) (*ListAlertsResponse, error)
	AcknowledgeAlert(ctx context.Context, in *AcknowledgeAlertRequest, opts ...grpc.CallOption) (*AcknowledgeAlertResponse, error)
	// Network and calibration
	GetSensorNetwork(ctx context.Context, in *GetSensorNetworkRequest, opts ...grpc.CallOption) (*GetSensorNetworkResponse, error)
	CalibrateSensor(ctx context.Context, in *CalibrateSensorRequest, opts ...grpc.CallOption) (*CalibrateSensorResponse, error)
}

type sensorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSensorServiceClient(cc grpc.ClientConnInterface) SensorServiceClient {
	return &sensorServiceClient{cc}
}

func (c *sensorServiceClient) RegisterSensor(ctx context.Context, in *RegisterSensorRequest, opts ...grpc.CallOption) (*RegisterSensorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterSensorResponse)
	err := c.cc.Invoke(ctx, SensorService_RegisterSensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorServiceClient) GetSensor(ctx context.Context, in *GetSensorRequest, opts ...grpc.CallOption) (*GetSensorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSensorResponse)
	err := c.cc.Invoke(ctx, SensorService_GetSensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorServiceClient) ListSensors(ctx context.Context, in *ListSensorsRequest, opts ...grpc.CallOption) (*ListSensorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSensorsResponse)
	err := c.cc.Invoke(ctx, SensorService_ListSensors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorServiceClient) UpdateSensor(ctx context.Context, in *UpdateSensorRequest, opts ...grpc.CallOption) (*UpdateSensorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSensorResponse)
	err := c.cc.Invoke(ctx, SensorService_UpdateSensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorServiceClient) DecommissionSensor(ctx context.Context, in *DecommissionSensorRequest, opts ...grpc.CallOption) (*DecommissionSensorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecommissionSensorResponse)
	err := c.cc.Invoke(ctx, SensorService_DecommissionSensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorServiceClient) IngestReading(ctx context.Context, in *IngestReadingRequest, opts ...grpc.CallOption) (*IngestReadingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestReadingResponse)
	err := c.cc.Invoke(ctx, SensorService_IngestReading_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorServiceClient) BatchIngestReadings(ctx context.Context, in *BatchIngestReadingsRequest, opts ...grpc.CallOption) (*BatchIngestReadingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchIngestReadingsResponse)
	err := c.cc.Invoke(ctx, SensorService_BatchIngestReadings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorServiceClient) GetLatestReading(ctx context.Context, in *GetLatestReadingRequest, opts ...grpc.CallOption) (*GetLatestReadingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestReadingResponse)
	err := c.cc.Invoke(ctx, SensorService_GetLatestReading_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorServiceClient) GetReadingHistory(ctx context.Context, in *GetReadingHistoryRequest, opts ...grpc.CallOption) (*GetReadingHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReadingHistoryResponse)
	err := c.cc.Invoke(ctx, SensorService_GetReadingHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorServiceClient) CreateAlert(ctx context.Context, in *CreateAlertRequest, opts ...grpc.CallOption) (*CreateAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAlertResponse)
	err := c.cc.Invoke(ctx, SensorService_CreateAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorServiceClient) ListAlerts(ctx context.Context, in *ListAlertsRequest, opts ...grpc.CallOption) (*ListAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAlertsResponse)
	err := c.cc.Invoke(ctx, SensorService_ListAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorServiceClient) AcknowledgeAlert(ctx context.Context, in *AcknowledgeAlertRequest, opts ...grpc.CallOption) (*AcknowledgeAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcknowledgeAlertResponse)
	err := c.cc.Invoke(ctx, SensorService_AcknowledgeAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorServiceClient) GetSensorNetwork(ctx context.Context, in *GetSensorNetworkRequest, opts ...grpc.CallOption) (*GetSensorNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSensorNetworkResponse)
	err := c.cc.Invoke(ctx, SensorService_GetSensorNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorServiceClient) CalibrateSensor(ctx context.Context, in *CalibrateSensorRequest, opts ...grpc.CallOption) (*CalibrateSensorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalibrateSensorResponse)
	err := c.cc.Invoke(ctx, SensorService_CalibrateSensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SensorServiceServer is the server API for SensorService service.
// All implementations must embed UnimplementedSensorServiceServer
// for forward compatibility.
type SensorServiceServer interface {
	// Sensor lifecycle management
	RegisterSensor(context.Context, *RegisterSensorRequest) (*RegisterSensorResponse, error)
	GetSensor(context.Context, *GetSensorRequest) (*GetSensorResponse, error)
	ListSensors(context.Context, *ListSensorsRequest) (*ListSensorsResponse, error)
	UpdateSensor(context.Context, *UpdateSensorRequest) (*UpdateSensorResponse, error)
	DecommissionSensor(context.Context, *DecommissionSensorRequest) (*DecommissionSensorResponse, error)
	// Data ingestion
	IngestReading(context.Context, *IngestReadingRequest) (*IngestReadingResponse, error)
	BatchIngestReadings(context.Context, *BatchIngestReadingsRequest) (*BatchIngestReadingsResponse, error)
	GetLatestReading(context.Context, *GetLatestReadingRequest) (*GetLatestReadingResponse, error)
	GetReadingHistory(context.Context, *GetReadingHistoryRequest) (*GetReadingHistoryResponse, error)
	// Alerting
	CreateAlert(context.Context, *CreateAlertRequest) (*CreateAlertResponse, error)
	ListAlerts(context.Context, *ListAlertsRequest) (*ListAlertsResponse, error)
	AcknowledgeAlert(context.Context, *AcknowledgeAlertRequest) (*AcknowledgeAlertResponse, error)
	// Network and calibration
	GetSensorNetwork(context.Context, *GetSensorNetworkRequest) (*GetSensorNetworkResponse, error)
	CalibrateSensor(context.Context, *CalibrateSensorRequest) (*CalibrateSensorResponse, error)
	mustEmbedUnimplementedSensorServiceServer()
}

// UnimplementedSensorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSensorServiceServer struct{}

func (UnimplementedSensorServiceServer) RegisterSensor(context.Context, *RegisterSensorRequest) (*RegisterSensorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterSensor not implemented")
}
func (UnimplementedSensorServiceServer) GetSensor(context.Context, *GetSensorRequest) (*GetSensorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSensor not implemented")
}
func (UnimplementedSensorServiceServer) ListSensors(context.Context, *ListSensorsRequest) (*ListSensorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSensors not implemented")
}
func (UnimplementedSensorServiceServer) UpdateSensor(context.Context, *UpdateSensorRequest) (*UpdateSensorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSensor not implemented")
}
func (UnimplementedSensorServiceServer) DecommissionSensor(context.Context, *DecommissionSensorRequest) (*DecommissionSensorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecommissionSensor not implemented")
}
func (UnimplementedSensorServiceServer) IngestReading(context.Context, *IngestReadingRequest) (*IngestReadingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestReading not implemented")
}
func (UnimplementedSensorServiceServer) BatchIngestReadings(context.Context, *BatchIngestReadingsRequest) (*BatchIngestReadingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchIngestReadings not implemented")
}
func (UnimplementedSensorServiceServer) GetLatestReading(context.Context, *GetLatestReadingRequest) (*GetLatestReadingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestReading not implemented")
}
func (UnimplementedSensorServiceServer) GetReadingHistory(context.Context, *GetReadingHistoryRequest) (*GetReadingHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReadingHistory not implemented")
}
func (UnimplementedSensorServiceServer) CreateAlert(context.Context, *CreateAlertRequest) (*CreateAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAlert not implemented")
}
func (UnimplementedSensorServiceServer) ListAlerts(context.Context, *ListAlertsRequest) (*ListAlertsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAlerts not implemented")
}
func (UnimplementedSensorServiceServer) AcknowledgeAlert(context.Context, *AcknowledgeAlertRequest) (*AcknowledgeAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcknowledgeAlert not implemented")
}
func (UnimplementedSensorServiceServer) GetSensorNetwork(context.Context, *GetSensorNetworkRequest) (*GetSensorNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSensorNetwork not implemented")
}
func (UnimplementedSensorServiceServer) CalibrateSensor(context.Context, *CalibrateSensorRequest) (*CalibrateSensorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalibrateSensor not implemented")
}
func (UnimplementedSensorServiceServer) mustEmbedUnimplementedSensorServiceServer() {}
func (UnimplementedSensorServiceServer) testEmbeddedByValue()                       {}

// UnsafeSensorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SensorServiceServer will
// result in compilation errors.
type UnsafeSensorServiceServer interface {
	mustEmbedUnimplementedSensorServiceServer()
}

func RegisterSensorServiceServer(s grpc.ServiceRegistrar, srv SensorServiceServer) {
	// If the following call panics, it indicates UnimplementedSensorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SensorService_ServiceDesc, srv)
}

func _SensorService_RegisterSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServiceServer).RegisterSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorService_RegisterSensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServiceServer).RegisterSensor(ctx, req.(*RegisterSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorService_GetSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServiceServer).GetSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorService_GetSensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServiceServer).GetSensor(ctx, req.(*GetSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorService_ListSensors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSensorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServiceServer).ListSensors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorService_ListSensors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServiceServer).ListSensors(ctx, req.(*ListSensorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorService_UpdateSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServiceServer).UpdateSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorService_UpdateSensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServiceServer).UpdateSensor(ctx, req.(*UpdateSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorService_DecommissionSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecommissionSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServiceServer).DecommissionSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorService_DecommissionSensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServiceServer).DecommissionSensor(ctx, req.(*DecommissionSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorService_IngestReading_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestReadingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServiceServer).IngestReading(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorService_IngestReading_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServiceServer).IngestReading(ctx, req.(*IngestReadingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorService_BatchIngestReadings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchIngestReadingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServiceServer).BatchIngestReadings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorService_BatchIngestReadings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServiceServer).BatchIngestReadings(ctx, req.(*BatchIngestReadingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorService_GetLatestReading_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestReadingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServiceServer).GetLatestReading(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorService_GetLatestReading_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServiceServer).GetLatestReading(ctx, req.(*GetLatestReadingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorService_GetReadingHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReadingHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServiceServer).GetReadingHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorService_GetReadingHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServiceServer).GetReadingHistory(ctx, req.(*GetReadingHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorService_CreateAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServiceServer).CreateAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorService_CreateAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServiceServer).CreateAlert(ctx, req.(*CreateAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorService_ListAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServiceServer).ListAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorService_ListAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServiceServer).ListAlerts(ctx, req.(*ListAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorService_AcknowledgeAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServiceServer).AcknowledgeAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorService_AcknowledgeAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServiceServer).AcknowledgeAlert(ctx, req.(*AcknowledgeAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorService_GetSensorNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSensorNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServiceServer).GetSensorNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorService_GetSensorNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServiceServer).GetSensorNetwork(ctx, req.(*GetSensorNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorService_CalibrateSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalibrateSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServiceServer).CalibrateSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorService_CalibrateSensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServiceServer).CalibrateSensor(ctx, req.(*CalibrateSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SensorService_ServiceDesc is the grpc.ServiceDesc for SensorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SensorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agriculture.sensor.v1.SensorService",
	HandlerType: (*SensorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSensor",
			Handler:    _SensorService_RegisterSensor_Handler,
		},
		{
			MethodName: "GetSensor",
			Handler:    _SensorService_GetSensor_Handler,
		},
		{
			MethodName: "ListSensors",
			Handler:    _SensorService_ListSensors_Handler,
		},
		{
			MethodName: "UpdateSensor",
			Handler:    _SensorService_UpdateSensor_Handler,
		},
		{
			MethodName: "DecommissionSensor",
			Handler:    _SensorService_DecommissionSensor_Handler,
		},
		{
			MethodName: "IngestReading",
			Handler:    _SensorService_IngestReading_Handler,
		},
		{
			MethodName: "BatchIngestReadings",
			Handler:    _SensorService_BatchIngestReadings_Handler,
		},
		{
			MethodName: "GetLatestReading",
			Handler:    _SensorService_GetLatestReading_Handler,
		},
		{
			MethodName: "GetReadingHistory",
			Handler:    _SensorService_GetReadingHistory_Handler,
		},
		{
			MethodName: "CreateAlert",
			Handler:    _SensorService_CreateAlert_Handler,
		},
		{
			MethodName: "ListAlerts",
			Handler:    _SensorService_ListAlerts_Handler,
		},
		{
			MethodName: "AcknowledgeAlert",
			Handler:    _SensorService_AcknowledgeAlert_Handler,
		},
		{
			MethodName: "GetSensorNetwork",
			Handler:    _SensorService_GetSensorNetwork_Handler,
		},
		{
			MethodName: "CalibrateSensor",
			Handler:    _SensorService_CalibrateSensor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sensor.proto",
}
