// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: assistant.proto

package advisoryv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "p9e.in/samavaya/agriculture/advisory-service/api/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AdvisoryServiceName is the fully-qualified name of the AdvisoryService service.
	AdvisoryServiceName = "agriculture.advisory.v1.AdvisoryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdvisoryServiceAskProcedure is the fully-qualified name of the AdvisoryService's Ask RPC.
	AdvisoryServiceAskProcedure = "/agriculture.advisory.v1.AdvisoryService/Ask"
	// AdvisoryServiceGetConversationProcedure is the fully-qualified name of the AdvisoryService's
	// GetConversation RPC.
	AdvisoryServiceGetConversationProcedure = "/agriculture.advisory.v1.AdvisoryService/GetConversation"
	// AdvisoryServiceListConversationsProcedure is the fully-qualified name of the AdvisoryService's
	// ListConversations RPC.
	AdvisoryServiceListConversationsProcedure = "/agriculture.advisory.v1.AdvisoryService/ListConversations"
	// AdvisoryServiceListExchangesProcedure is the fully-qualified name of the AdvisoryService's
	// ListExchanges RPC.
	AdvisoryServiceListExchangesProcedure = "/agriculture.advisory.v1.AdvisoryService/ListExchanges"
	// AdvisoryServiceReviewExchangeProcedure is the fully-qualified name of the AdvisoryService's
	// ReviewExchange RPC.
	AdvisoryServiceReviewExchangeProcedure = "/agriculture.advisory.v1.AdvisoryService/ReviewExchange"
	// AdvisoryServiceGetTenantBudgetProcedure is the fully-qualified name of the AdvisoryService's
	// GetTenantBudget RPC.
	AdvisoryServiceGetTenantBudgetProcedure = "/agriculture.advisory.v1.AdvisoryService/GetTenantBudget"
	// AdvisoryServiceSetTenantBudgetProcedure is the fully-qualified name of the AdvisoryService's
	// SetTenantBudget RPC.
	AdvisoryServiceSetTenantBudgetProcedure = "/agriculture.advisory.v1.AdvisoryService/SetTenantBudget"
	// AdvisoryServiceIngestDocumentProcedure is the fully-qualified name of the AdvisoryService's
	// IngestDocument RPC.
	AdvisoryServiceIngestDocumentProcedure = "/agriculture.advisory.v1.AdvisoryService/IngestDocument"
	// AdvisoryServiceListDocumentsProcedure is the fully-qualified name of the AdvisoryService's
	// ListDocuments RPC.
	AdvisoryServiceListDocumentsProcedure = "/agriculture.advisory.v1.AdvisoryService/ListDocuments"
	// AdvisoryServiceDeleteDocumentProcedure is the fully-qualified name of the AdvisoryService's
	// DeleteDocument RPC.
	AdvisoryServiceDeleteDocumentProcedure = "/agriculture.advisory.v1.AdvisoryService/DeleteDocument"
	// AdvisoryServiceSearchReferenceProcedure is the fully-qualified name of the AdvisoryService's
	// SearchReference RPC.
	AdvisoryServiceSearchReferenceProcedure = "/agriculture.advisory.v1.AdvisoryService/SearchReference"
)

// AdvisoryServiceClient is a client for the agriculture.advisory.v1.AdvisoryService service.
type AdvisoryServiceClient interface {
	Ask(context.Context, *connect.Request[v1.AskRequest]) (*connect.Response[v1.AskResponse], error)
	GetConversation(context.Context, *connect.Request[v1.GetConversationRequest]) (*connect.Response[v1.GetConversationResponse], error)
	ListConversations(context.Context, *connect.Request[v1.ListConversationsRequest]) (*connect.Response[v1.ListConversationsResponse], error)
	// The review queue, and the reviewer's verdict on one exchange.
	ListExchanges(context.Context, *connect.Request[v1.ListExchangesRequest]) (*connect.Response[v1.ListExchangesResponse], error)
	ReviewExchange(context.Context, *connect.Request[v1.ReviewExchangeRequest]) (*connect.Response[v1.ReviewExchangeResponse], error)
	GetTenantBudget(context.Context, *connect.Request[v1.GetTenantBudgetRequest]) (*connect.Response[v1.GetTenantBudgetResponse], error)
	SetTenantBudget(context.Context, *connect.Request[v1.SetTenantBudgetRequest]) (*connect.Response[v1.SetTenantBudgetResponse], error)
	IngestDocument(context.Context, *connect.Request[v1.IngestDocumentRequest]) (*connect.Response[v1.IngestDocumentResponse], error)
	ListDocuments(context.Context, *connect.Request[v1.ListDocumentsRequest]) (*connect.Response[v1.ListDocumentsResponse], error)
	DeleteDocument(context.Context, *connect.Request[v1.DeleteDocumentRequest]) (*connect.Response[v1.DeleteDocumentResponse], error)
	// Retrieval on its own, without an answer. Used by the citations panel and
	// by anyone checking what the assistant would have been given.
	SearchReference(context.Context, *connect.Request[v1.SearchReferenceRequest]) (*connect.Response[v1.SearchReferenceResponse], error)
}

// NewAdvisoryServiceClient constructs a client for the agriculture.advisory.v1.AdvisoryService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdvisoryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdvisoryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	advisoryServiceMethods := v1.File_assistant_proto.Services().ByName("AdvisoryService").Methods()
	return &advisoryServiceClient{
		ask: connect.NewClient[v1.AskRequest, v1.AskResponse](
			httpClient,
			baseURL+AdvisoryServiceAskProcedure,
			connect.WithSchema(advisoryServiceMethods.ByName("Ask")),
			connect.WithClientOptions(opts...),
		),
		getConversation: connect.NewClient[v1.GetConversationRequest, v1.GetConversationResponse](
			httpClient,
			baseURL+AdvisoryServiceGetConversationProcedure,
			connect.WithSchema(advisoryServiceMethods.ByName("GetConversation")),
			connect.WithClientOptions(opts...),
		),
		listConversations: connect.NewClient[v1.ListConversationsRequest, v1.ListConversationsResponse](
			httpClient,
			baseURL+AdvisoryServiceListConversationsProcedure,
			connect.WithSchema(advisoryServiceMethods.ByName("ListConversations")),
			connect.WithClientOptions(opts...),
		),
		listExchanges: connect.NewClient[v1.ListExchangesRequest, v1.ListExchangesResponse](
			httpClient,
			baseURL+AdvisoryServiceListExchangesProcedure,
			connect.WithSchema(advisoryServiceMethods.ByName("ListExchanges")),
			connect.WithClientOptions(opts...),
		),
		reviewExchange: connect.NewClient[v1.ReviewExchangeRequest, v1.ReviewExchangeResponse](
			httpClient,
			baseURL+AdvisoryServiceReviewExchangeProcedure,
			connect.WithSchema(advisoryServiceMethods.ByName("ReviewExchange")),
			connect.WithClientOptions(opts...),
		),
		getTenantBudget: connect.NewClient[v1.GetTenantBudgetRequest, v1.GetTenantBudgetResponse](
			httpClient,
			baseURL+AdvisoryServiceGetTenantBudgetProcedure,
			connect.WithSchema(advisoryServiceMethods.ByName("GetTenantBudget")),
			connect.WithClientOptions(opts...),
		),
		setTenantBudget: connect.NewClient[v1.SetTenantBudgetRequest, v1.SetTenantBudgetResponse](
			httpClient,
			baseURL+AdvisoryServiceSetTenantBudgetProcedure,
			connect.WithSchema(advisoryServiceMethods.ByName("SetTenantBudget")),
			connect.WithClientOptions(opts...),
		),
		ingestDocument: connect.NewClient[v1.IngestDocumentRequest, v1.IngestDocumentResponse](
			httpClient,
			baseURL+AdvisoryServiceIngestDocumentProcedure,
			connect.WithSchema(advisoryServiceMethods.ByName("IngestDocument")),
			connect.WithClientOptions(opts...),
		),
		listDocuments: connect.NewClient[v1.ListDocumentsRequest, v1.ListDocumentsResponse](
			httpClient,
			baseURL+AdvisoryServiceListDocumentsProcedure,
			connect.WithSchema(advisoryServiceMethods.ByName("ListDocuments")),
			connect.WithClientOptions(opts...),
		),
		deleteDocument: connect.NewClient[v1.DeleteDocumentRequest, v1.DeleteDocumentResponse](
			httpClient,
			baseURL+AdvisoryServiceDeleteDocumentProcedure,
			connect.WithSchema(advisoryServiceMethods.ByName("DeleteDocument")),
			connect.WithClientOptions(opts...),
		),
		searchReference: connect.NewClient[v1.SearchReferenceRequest, v1.SearchReferenceResponse](
			httpClient,
			baseURL+AdvisoryServiceSearchReferenceProcedure,
			connect.WithSchema(advisoryServiceMethods.ByName("SearchReference")),
			connect.WithClientOptions(opts...),
		),
	}
}

// advisoryServiceClient implements AdvisoryServiceClient.
type advisoryServiceClient struct {
	ask               *connect.Client[v1.AskRequest, v1.AskResponse]
	getConversation   *connect.Client[v1.GetConversationRequest, v1.GetConversationResponse]
	listConversations *connect.Client[v1.ListConversationsRequest, v1.ListConversationsResponse]
	listExchanges     *connect.Client[v1.ListExchangesRequest, v1.ListExchangesResponse]
	reviewExchange    *connect.Client[v1.ReviewExchangeRequest, v1.ReviewExchangeResponse]
	getTenantBudget   *connect.Client[v1.GetTenantBudgetRequest, v1.GetTenantBudgetResponse]
	setTenantBudget   *connect.Client[v1.SetTenantBudgetRequest, v1.SetTenantBudgetResponse]
	ingestDocument    *connect.Client[v1.IngestDocumentRequest, v1.IngestDocumentResponse]
	listDocuments     *connect.Client[v1.ListDocumentsRequest, v1.ListDocumentsResponse]
	deleteDocument    *connect.Client[v1.DeleteDocumentRequest, v1.DeleteDocumentResponse]
	searchReference   *connect.Client[v1.SearchReferenceRequest, v1.SearchReferenceResponse]
}

// Ask calls agriculture.advisory.v1.AdvisoryService.Ask.
func (c *advisoryServiceClient) Ask(ctx context.Context, req *connect.Request[v1.AskRequest]) (*connect.Response[v1.AskResponse], error) {
	return c.ask.CallUnary(ctx, req)
}

// GetConversation calls agriculture.advisory.v1.AdvisoryService.GetConversation.
func (c *advisoryServiceClient) GetConversation(ctx context.Context, req *connect.Request[v1.GetConversationRequest]) (*connect.Response[v1.GetConversationResponse], error) {
	return c.getConversation.CallUnary(ctx, req)
}

// ListConversations calls agriculture.advisory.v1.AdvisoryService.ListConversations.
func (c *advisoryServiceClient) ListConversations(ctx context.Context, req *connect.Request[v1.ListConversationsRequest]) (*connect.Response[v1.ListConversationsResponse], error) {
	return c.listConversations.CallUnary(ctx, req)
}

// ListExchanges calls agriculture.advisory.v1.AdvisoryService.ListExchanges.
func (c *advisoryServiceClient) ListExchanges(ctx context.Context, req *connect.Request[v1.ListExchangesRequest]) (*connect.Response[v1.ListExchangesResponse], error) {
	return c.listExchanges.CallUnary(ctx, req)
}

// ReviewExchange calls agriculture.advisory.v1.AdvisoryService.ReviewExchange.
func (c *advisoryServiceClient) ReviewExchange(ctx context.Context, req *connect.Request[v1.ReviewExchangeRequest]) (*connect.Response[v1.ReviewExchangeResponse], error) {
	return c.reviewExchange.CallUnary(ctx, req)
}

// GetTenantBudget calls agriculture.advisory.v1.AdvisoryService.GetTenantBudget.
func (c *advisoryServiceClient) GetTenantBudget(ctx context.Context, req *connect.Request[v1.GetTenantBudgetRequest]) (*connect.Response[v1.GetTenantBudgetResponse], error) {
	return c.getTenantBudget.CallUnary(ctx, req)
}

// SetTenantBudget calls agriculture.advisory.v1.AdvisoryService.SetTenantBudget.
func (c *advisoryServiceClient) SetTenantBudget(ctx context.Context, req *connect.Request[v1.SetTenantBudgetRequest]) (*connect.Response[v1.SetTenantBudgetResponse], error) {
	return c.setTenantBudget.CallUnary(ctx, req)
}

// IngestDocument calls agriculture.advisory.v1.AdvisoryService.IngestDocument.
func (c *advisoryServiceClient) IngestDocument(ctx context.Context, req *connect.Request[v1.IngestDocumentRequest]) (*connect.Response[v1.IngestDocumentResponse], error) {
	return c.ingestDocument.CallUnary(ctx, req)
}

// ListDocuments calls agriculture.advisory.v1.AdvisoryService.ListDocuments.
func (c *advisoryServiceClient) ListDocuments(ctx context.Context, req *connect.Request[v1.ListDocumentsRequest]) (*connect.Response[v1.ListDocumentsResponse], error) {
	return c.listDocuments.CallUnary(ctx, req)
}

// DeleteDocument calls agriculture.advisory.v1.AdvisoryService.DeleteDocument.
func (c *advisoryServiceClient) DeleteDocument(ctx context.Context, req *connect.Request[v1.DeleteDocumentRequest]) (*connect.Response[v1.DeleteDocumentResponse], error) {
	return c.deleteDocument.CallUnary(ctx, req)
}

// SearchReference calls agriculture.advisory.v1.AdvisoryService.SearchReference.
func (c *advisoryServiceClient) SearchReference(ctx context.Context, req *connect.Request[v1.SearchReferenceRequest]) (*connect.Response[v1.SearchReferenceResponse], error) {
	return c.searchReference.CallUnary(ctx, req)
}

// AdvisoryServiceHandler is an implementation of the agriculture.advisory.v1.AdvisoryService
// service.
type AdvisoryServiceHandler interface {
	Ask(context.Context, *connect.Request[v1.AskRequest]) (*connect.Response[v1.AskResponse], error)
	GetConversation(context.Context, *connect.Request[v1.GetConversationRequest]) (*connect.Response[v1.GetConversationResponse], error)
	ListConversations(context.Context, *connect.Request[v1.ListConversationsRequest]) (*connect.Response[v1.ListConversationsResponse], error)
	// The review queue, and the reviewer's verdict on one exchange.
	ListExchanges(context.Context, *connect.Request[v1.ListExchangesRequest]) (*connect.Response[v1.ListExchangesResponse], error)
	ReviewExchange(context.Context, *connect.Request[v1.ReviewExchangeRequest]) (*connect.Response[v1.ReviewExchangeResponse], error)
	GetTenantBudget(context.Context, *connect.Request[v1.GetTenantBudgetRequest]) (*connect.Response[v1.GetTenantBudgetResponse], error)
	SetTenantBudget(context.Context, *connect.Request[v1.SetTenantBudgetRequest]) (*connect.Response[v1.SetTenantBudgetResponse], error)
	IngestDocument(context.Context, *connect.Request[v1.IngestDocumentRequest]) (*connect.Response[v1.IngestDocumentResponse], error)
	ListDocuments(context.Context, *connect.Request[v1.ListDocumentsRequest]) (*connect.Response[v1.ListDocumentsResponse], error)
	DeleteDocument(context.Context, *connect.Request[v1.DeleteDocumentRequest]) (*connect.Response[v1.DeleteDocumentResponse], error)
	// Retrieval on its own, without an answer. Used by the citations panel and
	// by anyone checking what the assistant would have been given.
	SearchReference(context.Context, *connect.Request[v1.SearchReferenceRequest]) (*connect.Response[v1.SearchReferenceResponse], error)
}

// NewAdvisoryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdvisoryServiceHandler(svc AdvisoryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	advisoryServiceMethods := v1.File_assistant_proto.Services().ByName("AdvisoryService").Methods()
	advisoryServiceAskHandler := connect.NewUnaryHandler(
		AdvisoryServiceAskProcedure,
		svc.Ask,
		connect.WithSchema(advisoryServiceMethods.ByName("Ask")),
		connect.WithHandlerOptions(opts...),
	)
	advisoryServiceGetConversationHandler := connect.NewUnaryHandler(
		AdvisoryServiceGetConversationProcedure,
		svc.GetConversation,
		connect.WithSchema(advisoryServiceMethods.ByName("GetConversation")),
		connect.WithHandlerOptions(opts...),
	)
	advisoryServiceListConversationsHandler := connect.NewUnaryHandler(
		AdvisoryServiceListConversationsProcedure,
		svc.ListConversations,
		connect.WithSchema(advisoryServiceMethods.ByName("ListConversations")),
		connect.WithHandlerOptions(opts...),
	)
	advisoryServiceListExchangesHandler := connect.NewUnaryHandler(
		AdvisoryServiceListExchangesProcedure,
		svc.ListExchanges,
		connect.WithSchema(advisoryServiceMethods.ByName("ListExchanges")),
		connect.WithHandlerOptions(opts...),
	)
	advisoryServiceReviewExchangeHandler := connect.NewUnaryHandler(
		AdvisoryServiceReviewExchangeProcedure,
		svc.ReviewExchange,
		connect.WithSchema(advisoryServiceMethods.ByName("ReviewExchange")),
		connect.WithHandlerOptions(opts...),
	)
	advisoryServiceGetTenantBudgetHandler := connect.NewUnaryHandler(
		AdvisoryServiceGetTenantBudgetProcedure,
		svc.GetTenantBudget,
		connect.WithSchema(advisoryServiceMethods.ByName("GetTenantBudget")),
		connect.WithHandlerOptions(opts...),
	)
	advisoryServiceSetTenantBudgetHandler := connect.NewUnaryHandler(
		AdvisoryServiceSetTenantBudgetProcedure,
		svc.SetTenantBudget,
		connect.WithSchema(advisoryServiceMethods.ByName("SetTenantBudget")),
		connect.WithHandlerOptions(opts...),
	)
	advisoryServiceIngestDocumentHandler := connect.NewUnaryHandler(
		AdvisoryServiceIngestDocumentProcedure,
		svc.IngestDocument,
		connect.WithSchema(advisoryServiceMethods.ByName("IngestDocument")),
		connect.WithHandlerOptions(opts...),
	)
	advisoryServiceListDocumentsHandler := connect.NewUnaryHandler(
		AdvisoryServiceListDocumentsProcedure,
		svc.ListDocuments,
		connect.WithSchema(advisoryServiceMethods.ByName("ListDocuments")),
		connect.WithHandlerOptions(opts...),
	)
	advisoryServiceDeleteDocumentHandler := connect.NewUnaryHandler(
		AdvisoryServiceDeleteDocumentProcedure,
		svc.DeleteDocument,
		connect.WithSchema(advisoryServiceMethods.ByName("DeleteDocument")),
		connect.WithHandlerOptions(opts...),
	)
	advisoryServiceSearchReferenceHandler := connect.NewUnaryHandler(
		AdvisoryServiceSearchReferenceProcedure,
		svc.SearchReference,
		connect.WithSchema(advisoryServiceMethods.ByName("SearchReference")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agriculture.advisory.v1.AdvisoryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdvisoryServiceAskProcedure:
			advisoryServiceAskHandler.ServeHTTP(w, r)
		case AdvisoryServiceGetConversationProcedure:
			advisoryServiceGetConversationHandler.ServeHTTP(w, r)
		case AdvisoryServiceListConversationsProcedure:
			advisoryServiceListConversationsHandler.ServeHTTP(w, r)
		case AdvisoryServiceListExchangesProcedure:
			advisoryServiceListExchangesHandler.ServeHTTP(w, r)
		case AdvisoryServiceReviewExchangeProcedure:
			advisoryServiceReviewExchangeHandler.ServeHTTP(w, r)
		case AdvisoryServiceGetTenantBudgetProcedure:
			advisoryServiceGetTenantBudgetHandler.ServeHTTP(w, r)
		case AdvisoryServiceSetTenantBudgetProcedure:
			advisoryServiceSetTenantBudgetHandler.ServeHTTP(w, r)
		case AdvisoryServiceIngestDocumentProcedure:
			advisoryServiceIngestDocumentHandler.ServeHTTP(w, r)
		case AdvisoryServiceListDocumentsProcedure:
			advisoryServiceListDocumentsHandler.ServeHTTP(w, r)
		case AdvisoryServiceDeleteDocumentProcedure:
			advisoryServiceDeleteDocumentHandler.ServeHTTP(w, r)
		case AdvisoryServiceSearchReferenceProcedure:
			advisoryServiceSearchReferenceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdvisoryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdvisoryServiceHandler struct{}

func (UnimplementedAdvisoryServiceHandler) Ask(context.Context, *connect.Request[v1.AskRequest]) (*connect.Response[v1.AskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.advisory.v1.AdvisoryService.Ask is not implemented"))
}

func (UnimplementedAdvisoryServiceHandler) GetConversation(context.Context, *connect.Request[v1.GetConversationRequest]) (*connect.Response[v1.GetConversationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.advisory.v1.AdvisoryService.GetConversation is not implemented"))
}

func (UnimplementedAdvisoryServiceHandler) ListConversations(context.Context, *connect.Request[v1.ListConversationsRequest]) (*connect.Response[v1.ListConversationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.advisory.v1.AdvisoryService.ListConversations is not implemented"))
}

func (UnimplementedAdvisoryServiceHandler) ListExchanges(context.Context, *connect.Request[v1.ListExchangesRequest]) (*connect.Response[v1.ListExchangesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.advisory.v1.AdvisoryService.ListExchanges is not implemented"))
}

func (UnimplementedAdvisoryServiceHandler) ReviewExchange(context.Context, *connect.Request[v1.ReviewExchangeRequest]) (*connect.Response[v1.ReviewExchangeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.advisory.v1.AdvisoryService.ReviewExchange is not implemented"))
}

func (UnimplementedAdvisoryServiceHandler) GetTenantBudget(context.Context, *connect.Request[v1.GetTenantBudgetRequest]) (*connect.Response[v1.GetTenantBudgetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.advisory.v1.AdvisoryService.GetTenantBudget is not implemented"))
}

func (UnimplementedAdvisoryServiceHandler) SetTenantBudget(context.Context, *connect.Request[v1.SetTenantBudgetRequest]) (*connect.Response[v1.SetTenantBudgetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.advisory.v1.AdvisoryService.SetTenantBudget is not implemented"))
}

func (UnimplementedAdvisoryServiceHandler) IngestDocument(context.Context, *connect.Request[v1.IngestDocumentRequest]) (*connect.Response[v1.IngestDocumentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.advisory.v1.AdvisoryService.IngestDocument is not implemented"))
}

func (UnimplementedAdvisoryServiceHandler) ListDocuments(context.Context, *connect.Request[v1.ListDocumentsRequest]) (*connect.Response[v1.ListDocumentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.advisory.v1.AdvisoryService.ListDocuments is not implemented"))
}

func (UnimplementedAdvisoryServiceHandler) DeleteDocument(context.Context, *connect.Request[v1.DeleteDocumentRequest]) (*connect.Response[v1.DeleteDocumentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.advisory.v1.AdvisoryService.DeleteDocument is not implemented"))
}

func (UnimplementedAdvisoryServiceHandler) SearchReference(context.Context, *connect.Request[v1.SearchReferenceRequest]) (*connect.Response[v1.SearchReferenceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.advisory.v1.AdvisoryService.SearchReference is not implemented"))
}
