// Package clients contains Connect client adapters for peer services.
package clients

import (
	"context"
	"net/http"

	"connectrpc.com/connect"

	// Generated by buf generate
	cropv1 "p9e.in/samavaya/agriculture/crop-service/api/v1"
	cropv1connect "p9e.in/samavaya/agriculture/crop-service/api/v1/cropv1connect"
	"p9e.in/samavaya/agriculture/field-service/internal/ports/outbound"
)

type cropClient struct {
	client cropv1connect.CropServiceClient
}

// NewCropClient creates a Connect-backed CropClient.
func NewCropClient(baseURL string, httpClient *http.Client, opts ...connect.ClientOption) outbound.CropClient {
	return &cropClient{
		client: cropv1connect.NewCropServiceClient(httpClient, baseURL, opts...),
	}
}

func (c *cropClient) CropExists(ctx context.Context, uuid, tenantID string) (bool, error) {
	resp, err := c.client.GetCrop(ctx, connect.NewRequest(&cropv1.GetCropRequest{Id: uuid}))
	if err != nil {
		if connect.CodeOf(err) == connect.CodeNotFound {
			return false, nil
		}
		return false, err
	}
	return resp.Msg.GetCrop() != nil, nil
}
