import 'dart:convert';

import 'package:drift/drift.dart';
import 'package:logging/logging.dart';

import '../models/farm_model.dart';
import '../models/field_model.dart';

/// Local data source for farm operations using Drift (SQLite).
abstract class FarmLocalDataSource {
  Future<List<FarmModel>> getFarms(String userId);
  Future<FarmModel?> getFarmById(String farmId);
  Future<void> cacheFarms(List<FarmModel> farms);
  Future<void> cacheFarm(FarmModel farm);
  Future<void> deleteFarm(String farmId);
  Future<List<FieldModel>> getFieldsByFarmId(String farmId);
  Future<void> cacheField(FieldModel field);
  Future<void> deleteField(String fieldId);
  Future<void> clearAll();
}

// --------------------------------------------------------------------------
// Drift table definitions
// --------------------------------------------------------------------------

/// Drift table for cached farms.
class CachedFarms extends Table {
  TextColumn get id => text()();
  TextColumn get name => text()();
  TextColumn get ownerId => text()();
  TextColumn get dataJson => text()();
  DateTimeColumn get cachedAt => dateTime().withDefault(currentDateAndTime)();

  @override
  Set<Column> get primaryKey => {id};
}

/// Drift table for cached fields.
class CachedFields extends Table {
  TextColumn get id => text()();
  TextColumn get farmId => text()();
  TextColumn get dataJson => text()();
  DateTimeColumn get cachedAt => dateTime().withDefault(currentDateAndTime)();

  @override
  Set<Column> get primaryKey => {id};
}

// --------------------------------------------------------------------------
// Drift database definition
// --------------------------------------------------------------------------

@DriftDatabase(tables: [CachedFarms, CachedFields])
class FarmDatabase extends GeneratedDatabase {
  FarmDatabase(QueryExecutor e) : super(e);

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) async {
          await m.createAll();
        },
      );

  @override
  Iterable<TableInfo<Table, dynamic>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, dynamic>>();

  @override
  Iterable<DatabaseSchemaEntity> get allSchemaEntities {
    // Manual schema entity declarations for the two tables.
    return [cachedFarms, cachedFields];
  }

  // Table accessors
  late final $CachedFarmsTable cachedFarms = $CachedFarmsTable(this);
  late final $CachedFieldsTable cachedFields = $CachedFieldsTable(this);
}

// --------------------------------------------------------------------------
// Generated table classes (normally generated by drift_dev)
// --------------------------------------------------------------------------

class $CachedFarmsTable extends CachedFarms
    with TableInfo<$CachedFarmsTable, CachedFarmEntry> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;

  $CachedFarmsTable(this.attachedDatabase, [this._alias]);

  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => 'cached_farms';

  @override
  Set<GeneratedColumn> get $primaryKey => {id};

  late final GeneratedColumn<String> id =
      GeneratedColumn<String>('id', aliasedName, false,
          type: DriftSqlType.string);
  late final GeneratedColumn<String> name =
      GeneratedColumn<String>('name', aliasedName, false,
          type: DriftSqlType.string);
  late final GeneratedColumn<String> ownerId =
      GeneratedColumn<String>('owner_id', aliasedName, false,
          type: DriftSqlType.string);
  late final GeneratedColumn<String> dataJson =
      GeneratedColumn<String>('data_json', aliasedName, false,
          type: DriftSqlType.string);
  late final GeneratedColumn<DateTime> cachedAt =
      GeneratedColumn<DateTime>('cached_at', aliasedName, false,
          type: DriftSqlType.dateTime,
          defaultValue: currentDateAndTime);

  @override
  List<GeneratedColumn> get $columns => [id, name, ownerId, dataJson, cachedAt];

  @override
  $CachedFarmsTable createAlias(String alias) =>
      $CachedFarmsTable(attachedDatabase, alias);

  @override
  CachedFarmEntry map(Map<String, dynamic> data, {String? tablePrefix}) {
    final prefix = tablePrefix != null ? '$tablePrefix.' : '';
    return CachedFarmEntry(
      id: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${prefix}id'])!,
      name: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${prefix}name'])!,
      ownerId: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${prefix}owner_id'])!,
      dataJson: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${prefix}data_json'])!,
      cachedAt: attachedDatabase.typeMapping
          .read(DriftSqlType.dateTime, data['${prefix}cached_at'])!,
    );
  }
}

class CachedFarmEntry extends DataClass {
  final String id;
  final String name;
  final String ownerId;
  final String dataJson;
  final DateTime cachedAt;

  const CachedFarmEntry({
    required this.id,
    required this.name,
    required this.ownerId,
    required this.dataJson,
    required this.cachedAt,
  });
}

class CachedFarmsCompanion extends UpdateCompanion<CachedFarmEntry> {
  final Value<String> id;
  final Value<String> name;
  final Value<String> ownerId;
  final Value<String> dataJson;
  final Value<DateTime> cachedAt;

  const CachedFarmsCompanion({
    this.id = const Value.absent(),
    this.name = const Value.absent(),
    this.ownerId = const Value.absent(),
    this.dataJson = const Value.absent(),
    this.cachedAt = const Value.absent(),
  });

  CachedFarmsCompanion.insert({
    required String id,
    required String name,
    required String ownerId,
    required String dataJson,
    this.cachedAt = const Value.absent(),
  })  : id = Value(id),
        name = Value(name),
        ownerId = Value(ownerId),
        dataJson = Value(dataJson);

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) map['id'] = Variable<String>(id.value);
    if (name.present) map['name'] = Variable<String>(name.value);
    if (ownerId.present) map['owner_id'] = Variable<String>(ownerId.value);
    if (dataJson.present) map['data_json'] = Variable<String>(dataJson.value);
    if (cachedAt.present) map['cached_at'] = Variable<DateTime>(cachedAt.value);
    return map;
  }
}

class $CachedFieldsTable extends CachedFields
    with TableInfo<$CachedFieldsTable, CachedFieldEntry> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;

  $CachedFieldsTable(this.attachedDatabase, [this._alias]);

  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => 'cached_fields';

  @override
  Set<GeneratedColumn> get $primaryKey => {id};

  late final GeneratedColumn<String> id =
      GeneratedColumn<String>('id', aliasedName, false,
          type: DriftSqlType.string);
  late final GeneratedColumn<String> farmId =
      GeneratedColumn<String>('farm_id', aliasedName, false,
          type: DriftSqlType.string);
  late final GeneratedColumn<String> dataJson =
      GeneratedColumn<String>('data_json', aliasedName, false,
          type: DriftSqlType.string);
  late final GeneratedColumn<DateTime> cachedAt =
      GeneratedColumn<DateTime>('cached_at', aliasedName, false,
          type: DriftSqlType.dateTime,
          defaultValue: currentDateAndTime);

  @override
  List<GeneratedColumn> get $columns => [id, farmId, dataJson, cachedAt];

  @override
  $CachedFieldsTable createAlias(String alias) =>
      $CachedFieldsTable(attachedDatabase, alias);

  @override
  CachedFieldEntry map(Map<String, dynamic> data, {String? tablePrefix}) {
    final prefix = tablePrefix != null ? '$tablePrefix.' : '';
    return CachedFieldEntry(
      id: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${prefix}id'])!,
      farmId: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${prefix}farm_id'])!,
      dataJson: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${prefix}data_json'])!,
      cachedAt: attachedDatabase.typeMapping
          .read(DriftSqlType.dateTime, data['${prefix}cached_at'])!,
    );
  }
}

class CachedFieldEntry extends DataClass {
  final String id;
  final String farmId;
  final String dataJson;
  final DateTime cachedAt;

  const CachedFieldEntry({
    required this.id,
    required this.farmId,
    required this.dataJson,
    required this.cachedAt,
  });
}

class CachedFieldsCompanion extends UpdateCompanion<CachedFieldEntry> {
  final Value<String> id;
  final Value<String> farmId;
  final Value<String> dataJson;
  final Value<DateTime> cachedAt;

  const CachedFieldsCompanion({
    this.id = const Value.absent(),
    this.farmId = const Value.absent(),
    this.dataJson = const Value.absent(),
    this.cachedAt = const Value.absent(),
  });

  CachedFieldsCompanion.insert({
    required String id,
    required String farmId,
    required String dataJson,
    this.cachedAt = const Value.absent(),
  })  : id = Value(id),
        farmId = Value(farmId),
        dataJson = Value(dataJson);

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) map['id'] = Variable<String>(id.value);
    if (farmId.present) map['farm_id'] = Variable<String>(farmId.value);
    if (dataJson.present) map['data_json'] = Variable<String>(dataJson.value);
    if (cachedAt.present) map['cached_at'] = Variable<DateTime>(cachedAt.value);
    return map;
  }
}

// --------------------------------------------------------------------------
// Implementation
// --------------------------------------------------------------------------

/// Drift-based implementation of [FarmLocalDataSource].
class FarmLocalDataSourceImpl implements FarmLocalDataSource {
  final FarmDatabase _db;
  final _log = Logger('FarmLocalDataSource');

  FarmLocalDataSourceImpl({required FarmDatabase database}) : _db = database;

  @override
  Future<List<FarmModel>> getFarms(String userId) async {
    _log.fine('Loading cached farms for user $userId');
    final query = _db.select(_db.cachedFarms)
      ..where((t) => t.ownerId.equals(userId));
    final rows = await query.get();
    return rows.map((row) {
      final json = jsonDecode(row.dataJson) as Map<String, dynamic>;
      return FarmModel.fromJson(json);
    }).toList();
  }

  @override
  Future<FarmModel?> getFarmById(String farmId) async {
    final query = _db.select(_db.cachedFarms)
      ..where((t) => t.id.equals(farmId));
    final row = await query.getSingleOrNull();
    if (row == null) return null;
    final json = jsonDecode(row.dataJson) as Map<String, dynamic>;
    return FarmModel.fromJson(json);
  }

  @override
  Future<void> cacheFarms(List<FarmModel> farms) async {
    _log.fine('Caching ${farms.length} farms');
    await _db.batch((batch) {
      for (final farm in farms) {
        batch.insert(
          _db.cachedFarms,
          CachedFarmsCompanion.insert(
            id: farm.id,
            name: farm.name,
            ownerId: farm.ownerId,
            dataJson: jsonEncode(farm.toJson()),
          ),
          mode: InsertMode.insertOrReplace,
        );
      }
    });
  }

  @override
  Future<void> cacheFarm(FarmModel farm) async {
    await _db.into(_db.cachedFarms).insertOnConflictUpdate(
          CachedFarmsCompanion.insert(
            id: farm.id,
            name: farm.name,
            ownerId: farm.ownerId,
            dataJson: jsonEncode(farm.toJson()),
          ),
        );
  }

  @override
  Future<void> deleteFarm(String farmId) async {
    await (_db.delete(_db.cachedFarms)..where((t) => t.id.equals(farmId)))
        .go();
    await (_db.delete(_db.cachedFields)
          ..where((t) => t.farmId.equals(farmId)))
        .go();
  }

  @override
  Future<List<FieldModel>> getFieldsByFarmId(String farmId) async {
    final query = _db.select(_db.cachedFields)
      ..where((t) => t.farmId.equals(farmId));
    final rows = await query.get();
    return rows.map((row) {
      final json = jsonDecode(row.dataJson) as Map<String, dynamic>;
      return FieldModel.fromJson(json);
    }).toList();
  }

  @override
  Future<void> cacheField(FieldModel field) async {
    await _db.into(_db.cachedFields).insertOnConflictUpdate(
          CachedFieldsCompanion.insert(
            id: field.id,
            farmId: field.farmId,
            dataJson: jsonEncode(field.toJson()),
          ),
        );
  }

  @override
  Future<void> deleteField(String fieldId) async {
    await (_db.delete(_db.cachedFields)..where((t) => t.id.equals(fieldId)))
        .go();
  }

  @override
  Future<void> clearAll() async {
    await _db.delete(_db.cachedFarms).go();
    await _db.delete(_db.cachedFields).go();
  }
}
