// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: soillab.proto

package soillabv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "p9e.in/samavaya/agriculture/soil-lab-service/api/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SoilLabServiceName is the fully-qualified name of the SoilLabService service.
	SoilLabServiceName = "agriculture.soillab.v1.SoilLabService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SoilLabServiceRegisterLabProcedure is the fully-qualified name of the SoilLabService's
	// RegisterLab RPC.
	SoilLabServiceRegisterLabProcedure = "/agriculture.soillab.v1.SoilLabService/RegisterLab"
	// SoilLabServiceListLabsProcedure is the fully-qualified name of the SoilLabService's ListLabs RPC.
	SoilLabServiceListLabsProcedure = "/agriculture.soillab.v1.SoilLabService/ListLabs"
	// SoilLabServiceUploadReportProcedure is the fully-qualified name of the SoilLabService's
	// UploadReport RPC.
	SoilLabServiceUploadReportProcedure = "/agriculture.soillab.v1.SoilLabService/UploadReport"
	// SoilLabServiceGetReportProcedure is the fully-qualified name of the SoilLabService's GetReport
	// RPC.
	SoilLabServiceGetReportProcedure = "/agriculture.soillab.v1.SoilLabService/GetReport"
	// SoilLabServiceListReportsProcedure is the fully-qualified name of the SoilLabService's
	// ListReports RPC.
	SoilLabServiceListReportsProcedure = "/agriculture.soillab.v1.SoilLabService/ListReports"
	// SoilLabServiceApplyReportProcedure is the fully-qualified name of the SoilLabService's
	// ApplyReport RPC.
	SoilLabServiceApplyReportProcedure = "/agriculture.soillab.v1.SoilLabService/ApplyReport"
	// SoilLabServiceRejectReportProcedure is the fully-qualified name of the SoilLabService's
	// RejectReport RPC.
	SoilLabServiceRejectReportProcedure = "/agriculture.soillab.v1.SoilLabService/RejectReport"
)

// SoilLabServiceClient is a client for the agriculture.soillab.v1.SoilLabService service.
type SoilLabServiceClient interface {
	RegisterLab(context.Context, *connect.Request[v1.RegisterLabRequest]) (*connect.Response[v1.RegisterLabResponse], error)
	ListLabs(context.Context, *connect.Request[v1.ListLabsRequest]) (*connect.Response[v1.ListLabsResponse], error)
	UploadReport(context.Context, *connect.Request[v1.UploadReportRequest]) (*connect.Response[v1.UploadReportResponse], error)
	GetReport(context.Context, *connect.Request[v1.GetReportRequest]) (*connect.Response[v1.GetReportResponse], error)
	ListReports(context.Context, *connect.Request[v1.ListReportsRequest]) (*connect.Response[v1.ListReportsResponse], error)
	ApplyReport(context.Context, *connect.Request[v1.ApplyReportRequest]) (*connect.Response[v1.ApplyReportResponse], error)
	RejectReport(context.Context, *connect.Request[v1.RejectReportRequest]) (*connect.Response[v1.RejectReportResponse], error)
}

// NewSoilLabServiceClient constructs a client for the agriculture.soillab.v1.SoilLabService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSoilLabServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SoilLabServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	soilLabServiceMethods := v1.File_soillab_proto.Services().ByName("SoilLabService").Methods()
	return &soilLabServiceClient{
		registerLab: connect.NewClient[v1.RegisterLabRequest, v1.RegisterLabResponse](
			httpClient,
			baseURL+SoilLabServiceRegisterLabProcedure,
			connect.WithSchema(soilLabServiceMethods.ByName("RegisterLab")),
			connect.WithClientOptions(opts...),
		),
		listLabs: connect.NewClient[v1.ListLabsRequest, v1.ListLabsResponse](
			httpClient,
			baseURL+SoilLabServiceListLabsProcedure,
			connect.WithSchema(soilLabServiceMethods.ByName("ListLabs")),
			connect.WithClientOptions(opts...),
		),
		uploadReport: connect.NewClient[v1.UploadReportRequest, v1.UploadReportResponse](
			httpClient,
			baseURL+SoilLabServiceUploadReportProcedure,
			connect.WithSchema(soilLabServiceMethods.ByName("UploadReport")),
			connect.WithClientOptions(opts...),
		),
		getReport: connect.NewClient[v1.GetReportRequest, v1.GetReportResponse](
			httpClient,
			baseURL+SoilLabServiceGetReportProcedure,
			connect.WithSchema(soilLabServiceMethods.ByName("GetReport")),
			connect.WithClientOptions(opts...),
		),
		listReports: connect.NewClient[v1.ListReportsRequest, v1.ListReportsResponse](
			httpClient,
			baseURL+SoilLabServiceListReportsProcedure,
			connect.WithSchema(soilLabServiceMethods.ByName("ListReports")),
			connect.WithClientOptions(opts...),
		),
		applyReport: connect.NewClient[v1.ApplyReportRequest, v1.ApplyReportResponse](
			httpClient,
			baseURL+SoilLabServiceApplyReportProcedure,
			connect.WithSchema(soilLabServiceMethods.ByName("ApplyReport")),
			connect.WithClientOptions(opts...),
		),
		rejectReport: connect.NewClient[v1.RejectReportRequest, v1.RejectReportResponse](
			httpClient,
			baseURL+SoilLabServiceRejectReportProcedure,
			connect.WithSchema(soilLabServiceMethods.ByName("RejectReport")),
			connect.WithClientOptions(opts...),
		),
	}
}

// soilLabServiceClient implements SoilLabServiceClient.
type soilLabServiceClient struct {
	registerLab  *connect.Client[v1.RegisterLabRequest, v1.RegisterLabResponse]
	listLabs     *connect.Client[v1.ListLabsRequest, v1.ListLabsResponse]
	uploadReport *connect.Client[v1.UploadReportRequest, v1.UploadReportResponse]
	getReport    *connect.Client[v1.GetReportRequest, v1.GetReportResponse]
	listReports  *connect.Client[v1.ListReportsRequest, v1.ListReportsResponse]
	applyReport  *connect.Client[v1.ApplyReportRequest, v1.ApplyReportResponse]
	rejectReport *connect.Client[v1.RejectReportRequest, v1.RejectReportResponse]
}

// RegisterLab calls agriculture.soillab.v1.SoilLabService.RegisterLab.
func (c *soilLabServiceClient) RegisterLab(ctx context.Context, req *connect.Request[v1.RegisterLabRequest]) (*connect.Response[v1.RegisterLabResponse], error) {
	return c.registerLab.CallUnary(ctx, req)
}

// ListLabs calls agriculture.soillab.v1.SoilLabService.ListLabs.
func (c *soilLabServiceClient) ListLabs(ctx context.Context, req *connect.Request[v1.ListLabsRequest]) (*connect.Response[v1.ListLabsResponse], error) {
	return c.listLabs.CallUnary(ctx, req)
}

// UploadReport calls agriculture.soillab.v1.SoilLabService.UploadReport.
func (c *soilLabServiceClient) UploadReport(ctx context.Context, req *connect.Request[v1.UploadReportRequest]) (*connect.Response[v1.UploadReportResponse], error) {
	return c.uploadReport.CallUnary(ctx, req)
}

// GetReport calls agriculture.soillab.v1.SoilLabService.GetReport.
func (c *soilLabServiceClient) GetReport(ctx context.Context, req *connect.Request[v1.GetReportRequest]) (*connect.Response[v1.GetReportResponse], error) {
	return c.getReport.CallUnary(ctx, req)
}

// ListReports calls agriculture.soillab.v1.SoilLabService.ListReports.
func (c *soilLabServiceClient) ListReports(ctx context.Context, req *connect.Request[v1.ListReportsRequest]) (*connect.Response[v1.ListReportsResponse], error) {
	return c.listReports.CallUnary(ctx, req)
}

// ApplyReport calls agriculture.soillab.v1.SoilLabService.ApplyReport.
func (c *soilLabServiceClient) ApplyReport(ctx context.Context, req *connect.Request[v1.ApplyReportRequest]) (*connect.Response[v1.ApplyReportResponse], error) {
	return c.applyReport.CallUnary(ctx, req)
}

// RejectReport calls agriculture.soillab.v1.SoilLabService.RejectReport.
func (c *soilLabServiceClient) RejectReport(ctx context.Context, req *connect.Request[v1.RejectReportRequest]) (*connect.Response[v1.RejectReportResponse], error) {
	return c.rejectReport.CallUnary(ctx, req)
}

// SoilLabServiceHandler is an implementation of the agriculture.soillab.v1.SoilLabService service.
type SoilLabServiceHandler interface {
	RegisterLab(context.Context, *connect.Request[v1.RegisterLabRequest]) (*connect.Response[v1.RegisterLabResponse], error)
	ListLabs(context.Context, *connect.Request[v1.ListLabsRequest]) (*connect.Response[v1.ListLabsResponse], error)
	UploadReport(context.Context, *connect.Request[v1.UploadReportRequest]) (*connect.Response[v1.UploadReportResponse], error)
	GetReport(context.Context, *connect.Request[v1.GetReportRequest]) (*connect.Response[v1.GetReportResponse], error)
	ListReports(context.Context, *connect.Request[v1.ListReportsRequest]) (*connect.Response[v1.ListReportsResponse], error)
	ApplyReport(context.Context, *connect.Request[v1.ApplyReportRequest]) (*connect.Response[v1.ApplyReportResponse], error)
	RejectReport(context.Context, *connect.Request[v1.RejectReportRequest]) (*connect.Response[v1.RejectReportResponse], error)
}

// NewSoilLabServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSoilLabServiceHandler(svc SoilLabServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	soilLabServiceMethods := v1.File_soillab_proto.Services().ByName("SoilLabService").Methods()
	soilLabServiceRegisterLabHandler := connect.NewUnaryHandler(
		SoilLabServiceRegisterLabProcedure,
		svc.RegisterLab,
		connect.WithSchema(soilLabServiceMethods.ByName("RegisterLab")),
		connect.WithHandlerOptions(opts...),
	)
	soilLabServiceListLabsHandler := connect.NewUnaryHandler(
		SoilLabServiceListLabsProcedure,
		svc.ListLabs,
		connect.WithSchema(soilLabServiceMethods.ByName("ListLabs")),
		connect.WithHandlerOptions(opts...),
	)
	soilLabServiceUploadReportHandler := connect.NewUnaryHandler(
		SoilLabServiceUploadReportProcedure,
		svc.UploadReport,
		connect.WithSchema(soilLabServiceMethods.ByName("UploadReport")),
		connect.WithHandlerOptions(opts...),
	)
	soilLabServiceGetReportHandler := connect.NewUnaryHandler(
		SoilLabServiceGetReportProcedure,
		svc.GetReport,
		connect.WithSchema(soilLabServiceMethods.ByName("GetReport")),
		connect.WithHandlerOptions(opts...),
	)
	soilLabServiceListReportsHandler := connect.NewUnaryHandler(
		SoilLabServiceListReportsProcedure,
		svc.ListReports,
		connect.WithSchema(soilLabServiceMethods.ByName("ListReports")),
		connect.WithHandlerOptions(opts...),
	)
	soilLabServiceApplyReportHandler := connect.NewUnaryHandler(
		SoilLabServiceApplyReportProcedure,
		svc.ApplyReport,
		connect.WithSchema(soilLabServiceMethods.ByName("ApplyReport")),
		connect.WithHandlerOptions(opts...),
	)
	soilLabServiceRejectReportHandler := connect.NewUnaryHandler(
		SoilLabServiceRejectReportProcedure,
		svc.RejectReport,
		connect.WithSchema(soilLabServiceMethods.ByName("RejectReport")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agriculture.soillab.v1.SoilLabService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SoilLabServiceRegisterLabProcedure:
			soilLabServiceRegisterLabHandler.ServeHTTP(w, r)
		case SoilLabServiceListLabsProcedure:
			soilLabServiceListLabsHandler.ServeHTTP(w, r)
		case SoilLabServiceUploadReportProcedure:
			soilLabServiceUploadReportHandler.ServeHTTP(w, r)
		case SoilLabServiceGetReportProcedure:
			soilLabServiceGetReportHandler.ServeHTTP(w, r)
		case SoilLabServiceListReportsProcedure:
			soilLabServiceListReportsHandler.ServeHTTP(w, r)
		case SoilLabServiceApplyReportProcedure:
			soilLabServiceApplyReportHandler.ServeHTTP(w, r)
		case SoilLabServiceRejectReportProcedure:
			soilLabServiceRejectReportHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSoilLabServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSoilLabServiceHandler struct{}

func (UnimplementedSoilLabServiceHandler) RegisterLab(context.Context, *connect.Request[v1.RegisterLabRequest]) (*connect.Response[v1.RegisterLabResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.soillab.v1.SoilLabService.RegisterLab is not implemented"))
}

func (UnimplementedSoilLabServiceHandler) ListLabs(context.Context, *connect.Request[v1.ListLabsRequest]) (*connect.Response[v1.ListLabsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.soillab.v1.SoilLabService.ListLabs is not implemented"))
}

func (UnimplementedSoilLabServiceHandler) UploadReport(context.Context, *connect.Request[v1.UploadReportRequest]) (*connect.Response[v1.UploadReportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.soillab.v1.SoilLabService.UploadReport is not implemented"))
}

func (UnimplementedSoilLabServiceHandler) GetReport(context.Context, *connect.Request[v1.GetReportRequest]) (*connect.Response[v1.GetReportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.soillab.v1.SoilLabService.GetReport is not implemented"))
}

func (UnimplementedSoilLabServiceHandler) ListReports(context.Context, *connect.Request[v1.ListReportsRequest]) (*connect.Response[v1.ListReportsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.soillab.v1.SoilLabService.ListReports is not implemented"))
}

func (UnimplementedSoilLabServiceHandler) ApplyReport(context.Context, *connect.Request[v1.ApplyReportRequest]) (*connect.Response[v1.ApplyReportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.soillab.v1.SoilLabService.ApplyReport is not implemented"))
}

func (UnimplementedSoilLabServiceHandler) RejectReport(context.Context, *connect.Request[v1.RejectReportRequest]) (*connect.Response[v1.RejectReportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.soillab.v1.SoilLabService.RejectReport is not implemented"))
}
