// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: analytics.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StressType int32

const (
	StressType_STRESS_TYPE_UNSPECIFIED StressType = 0
	StressType_STRESS_TYPE_WATER       StressType = 1
	StressType_STRESS_TYPE_NUTRIENT    StressType = 2
	StressType_STRESS_TYPE_DISEASE     StressType = 3
	StressType_STRESS_TYPE_PEST        StressType = 4
	StressType_STRESS_TYPE_HEAT        StressType = 5
	StressType_STRESS_TYPE_FROST       StressType = 6
)

// Enum value maps for StressType.
var (
	StressType_name = map[int32]string{
		0: "STRESS_TYPE_UNSPECIFIED",
		1: "STRESS_TYPE_WATER",
		2: "STRESS_TYPE_NUTRIENT",
		3: "STRESS_TYPE_DISEASE",
		4: "STRESS_TYPE_PEST",
		5: "STRESS_TYPE_HEAT",
		6: "STRESS_TYPE_FROST",
	}
	StressType_value = map[string]int32{
		"STRESS_TYPE_UNSPECIFIED": 0,
		"STRESS_TYPE_WATER":       1,
		"STRESS_TYPE_NUTRIENT":    2,
		"STRESS_TYPE_DISEASE":     3,
		"STRESS_TYPE_PEST":        4,
		"STRESS_TYPE_HEAT":        5,
		"STRESS_TYPE_FROST":       6,
	}
)

func (x StressType) Enum() *StressType {
	p := new(StressType)
	*p = x
	return p
}

func (x StressType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StressType) Descriptor() protoreflect.EnumDescriptor {
	return file_analytics_proto_enumTypes[0].Descriptor()
}

func (StressType) Type() protoreflect.EnumType {
	return &file_analytics_proto_enumTypes[0]
}

func (x StressType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StressType.Descriptor instead.
func (StressType) EnumDescriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

type SeverityLevel int32

const (
	SeverityLevel_SEVERITY_LEVEL_UNSPECIFIED SeverityLevel = 0
	SeverityLevel_SEVERITY_LEVEL_LOW         SeverityLevel = 1
	SeverityLevel_SEVERITY_LEVEL_MEDIUM      SeverityLevel = 2
	SeverityLevel_SEVERITY_LEVEL_HIGH        SeverityLevel = 3
	SeverityLevel_SEVERITY_LEVEL_CRITICAL    SeverityLevel = 4
)

// Enum value maps for SeverityLevel.
var (
	SeverityLevel_name = map[int32]string{
		0: "SEVERITY_LEVEL_UNSPECIFIED",
		1: "SEVERITY_LEVEL_LOW",
		2: "SEVERITY_LEVEL_MEDIUM",
		3: "SEVERITY_LEVEL_HIGH",
		4: "SEVERITY_LEVEL_CRITICAL",
	}
	SeverityLevel_value = map[string]int32{
		"SEVERITY_LEVEL_UNSPECIFIED": 0,
		"SEVERITY_LEVEL_LOW":         1,
		"SEVERITY_LEVEL_MEDIUM":      2,
		"SEVERITY_LEVEL_HIGH":        3,
		"SEVERITY_LEVEL_CRITICAL":    4,
	}
)

func (x SeverityLevel) Enum() *SeverityLevel {
	p := new(SeverityLevel)
	*p = x
	return p
}

func (x SeverityLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SeverityLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_analytics_proto_enumTypes[1].Descriptor()
}

func (SeverityLevel) Type() protoreflect.EnumType {
	return &file_analytics_proto_enumTypes[1]
}

func (x SeverityLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SeverityLevel.Descriptor instead.
func (SeverityLevel) EnumDescriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

type AnalysisType int32

const (
	AnalysisType_ANALYSIS_TYPE_UNSPECIFIED         AnalysisType = 0
	AnalysisType_ANALYSIS_TYPE_STRESS_DETECTION    AnalysisType = 1
	AnalysisType_ANALYSIS_TYPE_CHANGE_DETECTION    AnalysisType = 2
	AnalysisType_ANALYSIS_TYPE_TEMPORAL_TREND      AnalysisType = 3
	AnalysisType_ANALYSIS_TYPE_ANOMALY_DETECTION   AnalysisType = 4
	AnalysisType_ANALYSIS_TYPE_CROP_CLASSIFICATION AnalysisType = 5
)

// Enum value maps for AnalysisType.
var (
	AnalysisType_name = map[int32]string{
		0: "ANALYSIS_TYPE_UNSPECIFIED",
		1: "ANALYSIS_TYPE_STRESS_DETECTION",
		2: "ANALYSIS_TYPE_CHANGE_DETECTION",
		3: "ANALYSIS_TYPE_TEMPORAL_TREND",
		4: "ANALYSIS_TYPE_ANOMALY_DETECTION",
		5: "ANALYSIS_TYPE_CROP_CLASSIFICATION",
	}
	AnalysisType_value = map[string]int32{
		"ANALYSIS_TYPE_UNSPECIFIED":         0,
		"ANALYSIS_TYPE_STRESS_DETECTION":    1,
		"ANALYSIS_TYPE_CHANGE_DETECTION":    2,
		"ANALYSIS_TYPE_TEMPORAL_TREND":      3,
		"ANALYSIS_TYPE_ANOMALY_DETECTION":   4,
		"ANALYSIS_TYPE_CROP_CLASSIFICATION": 5,
	}
)

func (x AnalysisType) Enum() *AnalysisType {
	p := new(AnalysisType)
	*p = x
	return p
}

func (x AnalysisType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnalysisType) Descriptor() protoreflect.EnumDescriptor {
	return file_analytics_proto_enumTypes[2].Descriptor()
}

func (AnalysisType) Type() protoreflect.EnumType {
	return &file_analytics_proto_enumTypes[2]
}

func (x AnalysisType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnalysisType.Descriptor instead.
func (AnalysisType) EnumDescriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{2}
}

type StressAlert struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId             string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	FarmId               string                 `protobuf:"bytes,3,opt,name=farm_id,json=farmId,proto3" json:"farm_id,omitempty"`
	FieldId              string                 `protobuf:"bytes,4,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	StressType           StressType             `protobuf:"varint,5,opt,name=stress_type,json=stressType,proto3,enum=agriculture.satellite.analytics.v1.StressType" json:"stress_type,omitempty"`
	Severity             SeverityLevel          `protobuf:"varint,6,opt,name=severity,proto3,enum=agriculture.satellite.analytics.v1.SeverityLevel" json:"severity,omitempty"`
	Confidence           float64                `protobuf:"fixed64,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	AffectedAreaHectares float64                `protobuf:"fixed64,8,opt,name=affected_area_hectares,json=affectedAreaHectares,proto3" json:"affected_area_hectares,omitempty"`
	AffectedPercentage   float64                `protobuf:"fixed64,9,opt,name=affected_percentage,json=affectedPercentage,proto3" json:"affected_percentage,omitempty"`
	BboxGeojson          string                 `protobuf:"bytes,10,opt,name=bbox_geojson,json=bboxGeojson,proto3" json:"bbox_geojson,omitempty"`
	Description          string                 `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	Recommendation       string                 `protobuf:"bytes,12,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	Acknowledged         bool                   `protobuf:"varint,13,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	DetectedAt           *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StressAlert) Reset() {
	*x = StressAlert{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StressAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StressAlert) ProtoMessage() {}

func (x *StressAlert) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StressAlert.ProtoReflect.Descriptor instead.
func (*StressAlert) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *StressAlert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StressAlert) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *StressAlert) GetFarmId() string {
	if x != nil {
		return x.FarmId
	}
	return ""
}

func (x *StressAlert) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *StressAlert) GetStressType() StressType {
	if x != nil {
		return x.StressType
	}
	return StressType_STRESS_TYPE_UNSPECIFIED
}

func (x *StressAlert) GetSeverity() SeverityLevel {
	if x != nil {
		return x.Severity
	}
	return SeverityLevel_SEVERITY_LEVEL_UNSPECIFIED
}

func (x *StressAlert) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *StressAlert) GetAffectedAreaHectares() float64 {
	if x != nil {
		return x.AffectedAreaHectares
	}
	return 0
}

func (x *StressAlert) GetAffectedPercentage() float64 {
	if x != nil {
		return x.AffectedPercentage
	}
	return 0
}

func (x *StressAlert) GetBboxGeojson() string {
	if x != nil {
		return x.BboxGeojson
	}
	return ""
}

func (x *StressAlert) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StressAlert) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

func (x *StressAlert) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *StressAlert) GetDetectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DetectedAt
	}
	return nil
}

func (x *StressAlert) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type TemporalAnalysis struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId         string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	FarmId           string                 `protobuf:"bytes,3,opt,name=farm_id,json=farmId,proto3" json:"farm_id,omitempty"`
	FieldId          string                 `protobuf:"bytes,4,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	AnalysisType     AnalysisType           `protobuf:"varint,5,opt,name=analysis_type,json=analysisType,proto3,enum=agriculture.satellite.analytics.v1.AnalysisType" json:"analysis_type,omitempty"`
	MetricName       string                 `protobuf:"bytes,6,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	TrendSlope       float64                `protobuf:"fixed64,7,opt,name=trend_slope,json=trendSlope,proto3" json:"trend_slope,omitempty"`
	TrendRSquared    float64                `protobuf:"fixed64,8,opt,name=trend_r_squared,json=trendRSquared,proto3" json:"trend_r_squared,omitempty"`
	CurrentValue     float64                `protobuf:"fixed64,9,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`
	BaselineValue    float64                `protobuf:"fixed64,10,opt,name=baseline_value,json=baselineValue,proto3" json:"baseline_value,omitempty"`
	DeviationPercent float64                `protobuf:"fixed64,11,opt,name=deviation_percent,json=deviationPercent,proto3" json:"deviation_percent,omitempty"`
	PeriodStart      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TemporalAnalysis) Reset() {
	*x = TemporalAnalysis{}
	mi := &file_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporalAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporalAnalysis) ProtoMessage() {}

func (x *TemporalAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporalAnalysis.ProtoReflect.Descriptor instead.
func (*TemporalAnalysis) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *TemporalAnalysis) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TemporalAnalysis) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TemporalAnalysis) GetFarmId() string {
	if x != nil {
		return x.FarmId
	}
	return ""
}

func (x *TemporalAnalysis) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *TemporalAnalysis) GetAnalysisType() AnalysisType {
	if x != nil {
		return x.AnalysisType
	}
	return AnalysisType_ANALYSIS_TYPE_UNSPECIFIED
}

func (x *TemporalAnalysis) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *TemporalAnalysis) GetTrendSlope() float64 {
	if x != nil {
		return x.TrendSlope
	}
	return 0
}

func (x *TemporalAnalysis) GetTrendRSquared() float64 {
	if x != nil {
		return x.TrendRSquared
	}
	return 0
}

func (x *TemporalAnalysis) GetCurrentValue() float64 {
	if x != nil {
		return x.CurrentValue
	}
	return 0
}

func (x *TemporalAnalysis) GetBaselineValue() float64 {
	if x != nil {
		return x.BaselineValue
	}
	return 0
}

func (x *TemporalAnalysis) GetDeviationPercent() float64 {
	if x != nil {
		return x.DeviationPercent
	}
	return 0
}

func (x *TemporalAnalysis) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *TemporalAnalysis) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

func (x *TemporalAnalysis) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DetectStressRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FarmId          string                 `protobuf:"bytes,1,opt,name=farm_id,json=farmId,proto3" json:"farm_id,omitempty"`
	FieldId         string                 `protobuf:"bytes,2,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	ProcessingJobId string                 `protobuf:"bytes,3,opt,name=processing_job_id,json=processingJobId,proto3" json:"processing_job_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DetectStressRequest) Reset() {
	*x = DetectStressRequest{}
	mi := &file_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectStressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectStressRequest) ProtoMessage() {}

func (x *DetectStressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectStressRequest.ProtoReflect.Descriptor instead.
func (*DetectStressRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *DetectStressRequest) GetFarmId() string {
	if x != nil {
		return x.FarmId
	}
	return ""
}

func (x *DetectStressRequest) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *DetectStressRequest) GetProcessingJobId() string {
	if x != nil {
		return x.ProcessingJobId
	}
	return ""
}

type DetectStressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*StressAlert         `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectStressResponse) Reset() {
	*x = DetectStressResponse{}
	mi := &file_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectStressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectStressResponse) ProtoMessage() {}

func (x *DetectStressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectStressResponse.ProtoReflect.Descriptor instead.
func (*DetectStressResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *DetectStressResponse) GetAlerts() []*StressAlert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

type ListStressAlertsRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PageSize           int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken          string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	FarmId             string                 `protobuf:"bytes,3,opt,name=farm_id,json=farmId,proto3" json:"farm_id,omitempty"`
	StressType         StressType             `protobuf:"varint,4,opt,name=stress_type,json=stressType,proto3,enum=agriculture.satellite.analytics.v1.StressType" json:"stress_type,omitempty"`
	MinSeverity        SeverityLevel          `protobuf:"varint,5,opt,name=min_severity,json=minSeverity,proto3,enum=agriculture.satellite.analytics.v1.SeverityLevel" json:"min_severity,omitempty"`
	UnacknowledgedOnly bool                   `protobuf:"varint,6,opt,name=unacknowledged_only,json=unacknowledgedOnly,proto3" json:"unacknowledged_only,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListStressAlertsRequest) Reset() {
	*x = ListStressAlertsRequest{}
	mi := &file_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStressAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStressAlertsRequest) ProtoMessage() {}

func (x *ListStressAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStressAlertsRequest.ProtoReflect.Descriptor instead.
func (*ListStressAlertsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *ListStressAlertsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListStressAlertsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListStressAlertsRequest) GetFarmId() string {
	if x != nil {
		return x.FarmId
	}
	return ""
}

func (x *ListStressAlertsRequest) GetStressType() StressType {
	if x != nil {
		return x.StressType
	}
	return StressType_STRESS_TYPE_UNSPECIFIED
}

func (x *ListStressAlertsRequest) GetMinSeverity() SeverityLevel {
	if x != nil {
		return x.MinSeverity
	}
	return SeverityLevel_SEVERITY_LEVEL_UNSPECIFIED
}

func (x *ListStressAlertsRequest) GetUnacknowledgedOnly() bool {
	if x != nil {
		return x.UnacknowledgedOnly
	}
	return false
}

type ListStressAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*StressAlert         `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStressAlertsResponse) Reset() {
	*x = ListStressAlertsResponse{}
	mi := &file_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStressAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStressAlertsResponse) ProtoMessage() {}

func (x *ListStressAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStressAlertsResponse.ProtoReflect.Descriptor instead.
func (*ListStressAlertsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *ListStressAlertsResponse) GetAlerts() []*StressAlert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

func (x *ListStressAlertsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListStressAlertsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type AcknowledgeAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeAlertRequest) Reset() {
	*x = AcknowledgeAlertRequest{}
	mi := &file_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeAlertRequest) ProtoMessage() {}

func (x *AcknowledgeAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeAlertRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeAlertRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *AcknowledgeAlertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AcknowledgeAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeAlertResponse) Reset() {
	*x = AcknowledgeAlertResponse{}
	mi := &file_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeAlertResponse) ProtoMessage() {}

func (x *AcknowledgeAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeAlertResponse.ProtoReflect.Descriptor instead.
func (*AcknowledgeAlertResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *AcknowledgeAlertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RunTemporalAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FarmId        string                 `protobuf:"bytes,1,opt,name=farm_id,json=farmId,proto3" json:"farm_id,omitempty"`
	FieldId       string                 `protobuf:"bytes,2,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	AnalysisType  AnalysisType           `protobuf:"varint,3,opt,name=analysis_type,json=analysisType,proto3,enum=agriculture.satellite.analytics.v1.AnalysisType" json:"analysis_type,omitempty"`
	PeriodStart   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTemporalAnalysisRequest) Reset() {
	*x = RunTemporalAnalysisRequest{}
	mi := &file_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTemporalAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTemporalAnalysisRequest) ProtoMessage() {}

func (x *RunTemporalAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTemporalAnalysisRequest.ProtoReflect.Descriptor instead.
func (*RunTemporalAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *RunTemporalAnalysisRequest) GetFarmId() string {
	if x != nil {
		return x.FarmId
	}
	return ""
}

func (x *RunTemporalAnalysisRequest) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *RunTemporalAnalysisRequest) GetAnalysisType() AnalysisType {
	if x != nil {
		return x.AnalysisType
	}
	return AnalysisType_ANALYSIS_TYPE_UNSPECIFIED
}

func (x *RunTemporalAnalysisRequest) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *RunTemporalAnalysisRequest) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

type RunTemporalAnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analysis      *TemporalAnalysis      `protobuf:"bytes,1,opt,name=analysis,proto3" json:"analysis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTemporalAnalysisResponse) Reset() {
	*x = RunTemporalAnalysisResponse{}
	mi := &file_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTemporalAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTemporalAnalysisResponse) ProtoMessage() {}

func (x *RunTemporalAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTemporalAnalysisResponse.ProtoReflect.Descriptor instead.
func (*RunTemporalAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *RunTemporalAnalysisResponse) GetAnalysis() *TemporalAnalysis {
	if x != nil {
		return x.Analysis
	}
	return nil
}

type GetFieldAnalyticsSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FarmId        string                 `protobuf:"bytes,1,opt,name=farm_id,json=farmId,proto3" json:"farm_id,omitempty"`
	FieldId       string                 `protobuf:"bytes,2,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFieldAnalyticsSummaryRequest) Reset() {
	*x = GetFieldAnalyticsSummaryRequest{}
	mi := &file_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFieldAnalyticsSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldAnalyticsSummaryRequest) ProtoMessage() {}

func (x *GetFieldAnalyticsSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldAnalyticsSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetFieldAnalyticsSummaryRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *GetFieldAnalyticsSummaryRequest) GetFarmId() string {
	if x != nil {
		return x.FarmId
	}
	return ""
}

func (x *GetFieldAnalyticsSummaryRequest) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

type GetFieldAnalyticsSummaryResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ActiveStressAlerts int32                  `protobuf:"varint,1,opt,name=active_stress_alerts,json=activeStressAlerts,proto3" json:"active_stress_alerts,omitempty"`
	HealthScore        float64                `protobuf:"fixed64,2,opt,name=health_score,json=healthScore,proto3" json:"health_score,omitempty"`
	NdviTrend          float64                `protobuf:"fixed64,3,opt,name=ndvi_trend,json=ndviTrend,proto3" json:"ndvi_trend,omitempty"`
	DominantStressType string                 `protobuf:"bytes,4,opt,name=dominant_stress_type,json=dominantStressType,proto3" json:"dominant_stress_type,omitempty"`
	LastAnalysis       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_analysis,json=lastAnalysis,proto3" json:"last_analysis,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetFieldAnalyticsSummaryResponse) Reset() {
	*x = GetFieldAnalyticsSummaryResponse{}
	mi := &file_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFieldAnalyticsSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldAnalyticsSummaryResponse) ProtoMessage() {}

func (x *GetFieldAnalyticsSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldAnalyticsSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetFieldAnalyticsSummaryResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *GetFieldAnalyticsSummaryResponse) GetActiveStressAlerts() int32 {
	if x != nil {
		return x.ActiveStressAlerts
	}
	return 0
}

func (x *GetFieldAnalyticsSummaryResponse) GetHealthScore() float64 {
	if x != nil {
		return x.HealthScore
	}
	return 0
}

func (x *GetFieldAnalyticsSummaryResponse) GetNdviTrend() float64 {
	if x != nil {
		return x.NdviTrend
	}
	return 0
}

func (x *GetFieldAnalyticsSummaryResponse) GetDominantStressType() string {
	if x != nil {
		return x.DominantStressType
	}
	return ""
}

func (x *GetFieldAnalyticsSummaryResponse) GetLastAnalysis() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAnalysis
	}
	return nil
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\x12\"agriculture.satellite.analytics.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x05\n" +
	"\vStressAlert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\afarm_id\x18\x03 \x01(\tR\x06farmId\x12\x19\n" +
	"\bfield_id\x18\x04 \x01(\tR\afieldId\x12O\n" +
	"\vstress_type\x18\x05 \x01(\x0e2..agriculture.satellite.analytics.v1.StressTypeR\n" +
	"stressType\x12M\n" +
	"\bseverity\x18\x06 \x01(\x0e21.agriculture.satellite.analytics.v1.SeverityLevelR\bseverity\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x01R\n" +
	"confidence\x124\n" +
	"\x16affected_area_hectares\x18\b \x01(\x01R\x14affectedAreaHectares\x12/\n" +
	"\x13affected_percentage\x18\t \x01(\x01R\x12affectedPercentage\x12!\n" +
	"\fbbox_geojson\x18\n" +
	" \x01(\tR\vbboxGeojson\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\x12&\n" +
	"\x0erecommendation\x18\f \x01(\tR\x0erecommendation\x12\"\n" +
	"\facknowledged\x18\r \x01(\bR\facknowledged\x12;\n" +
	"\vdetected_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"detectedAt\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xe2\x04\n" +
	"\x10TemporalAnalysis\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\afarm_id\x18\x03 \x01(\tR\x06farmId\x12\x19\n" +
	"\bfield_id\x18\x04 \x01(\tR\afieldId\x12U\n" +
	"\ranalysis_type\x18\x05 \x01(\x0e20.agriculture.satellite.analytics.v1.AnalysisTypeR\fanalysisType\x12\x1f\n" +
	"\vmetric_name\x18\x06 \x01(\tR\n" +
	"metricName\x12\x1f\n" +
	"\vtrend_slope\x18\a \x01(\x01R\n" +
	"trendSlope\x12&\n" +
	"\x0ftrend_r_squared\x18\b \x01(\x01R\rtrendRSquared\x12#\n" +
	"\rcurrent_value\x18\t \x01(\x01R\fcurrentValue\x12%\n" +
	"\x0ebaseline_value\x18\n" +
	" \x01(\x01R\rbaselineValue\x12+\n" +
	"\x11deviation_percent\x18\v \x01(\x01R\x10deviationPercent\x12=\n" +
	"\fperiod_start\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"u\n" +
	"\x13DetectStressRequest\x12\x17\n" +
	"\afarm_id\x18\x01 \x01(\tR\x06farmId\x12\x19\n" +
	"\bfield_id\x18\x02 \x01(\tR\afieldId\x12*\n" +
	"\x11processing_job_id\x18\x03 \x01(\tR\x0fprocessingJobId\"_\n" +
	"\x14DetectStressResponse\x12G\n" +
	"\x06alerts\x18\x01 \x03(\v2/.agriculture.satellite.analytics.v1.StressAlertR\x06alerts\"\xc6\x02\n" +
	"\x17ListStressAlertsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x17\n" +
	"\afarm_id\x18\x03 \x01(\tR\x06farmId\x12O\n" +
	"\vstress_type\x18\x04 \x01(\x0e2..agriculture.satellite.analytics.v1.StressTypeR\n" +
	"stressType\x12T\n" +
	"\fmin_severity\x18\x05 \x01(\x0e21.agriculture.satellite.analytics.v1.SeverityLevelR\vminSeverity\x12/\n" +
	"\x13unacknowledged_only\x18\x06 \x01(\bR\x12unacknowledgedOnly\"\xac\x01\n" +
	"\x18ListStressAlertsResponse\x12G\n" +
	"\x06alerts\x18\x01 \x03(\v2/.agriculture.satellite.analytics.v1.StressAlertR\x06alerts\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\")\n" +
	"\x17AcknowledgeAlertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x18AcknowledgeAlertResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa1\x02\n" +
	"\x1aRunTemporalAnalysisRequest\x12\x17\n" +
	"\afarm_id\x18\x01 \x01(\tR\x06farmId\x12\x19\n" +
	"\bfield_id\x18\x02 \x01(\tR\afieldId\x12U\n" +
	"\ranalysis_type\x18\x03 \x01(\x0e20.agriculture.satellite.analytics.v1.AnalysisTypeR\fanalysisType\x12=\n" +
	"\fperiod_start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\"o\n" +
	"\x1bRunTemporalAnalysisResponse\x12P\n" +
	"\banalysis\x18\x01 \x01(\v24.agriculture.satellite.analytics.v1.TemporalAnalysisR\banalysis\"U\n" +
	"\x1fGetFieldAnalyticsSummaryRequest\x12\x17\n" +
	"\afarm_id\x18\x01 \x01(\tR\x06farmId\x12\x19\n" +
	"\bfield_id\x18\x02 \x01(\tR\afieldId\"\x89\x02\n" +
	" GetFieldAnalyticsSummaryResponse\x120\n" +
	"\x14active_stress_alerts\x18\x01 \x01(\x05R\x12activeStressAlerts\x12!\n" +
	"\fhealth_score\x18\x02 \x01(\x01R\vhealthScore\x12\x1d\n" +
	"\n" +
	"ndvi_trend\x18\x03 \x01(\x01R\tndviTrend\x120\n" +
	"\x14dominant_stress_type\x18\x04 \x01(\tR\x12dominantStressType\x12?\n" +
	"\rlast_analysis\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\flastAnalysis*\xb6\x01\n" +
	"\n" +
	"StressType\x12\x1b\n" +
	"\x17STRESS_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11STRESS_TYPE_WATER\x10\x01\x12\x18\n" +
	"\x14STRESS_TYPE_NUTRIENT\x10\x02\x12\x17\n" +
	"\x13STRESS_TYPE_DISEASE\x10\x03\x12\x14\n" +
	"\x10STRESS_TYPE_PEST\x10\x04\x12\x14\n" +
	"\x10STRESS_TYPE_HEAT\x10\x05\x12\x15\n" +
	"\x11STRESS_TYPE_FROST\x10\x06*\x98\x01\n" +
	"\rSeverityLevel\x12\x1e\n" +
	"\x1aSEVERITY_LEVEL_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SEVERITY_LEVEL_LOW\x10\x01\x12\x19\n" +
	"\x15SEVERITY_LEVEL_MEDIUM\x10\x02\x12\x17\n" +
	"\x13SEVERITY_LEVEL_HIGH\x10\x03\x12\x1b\n" +
	"\x17SEVERITY_LEVEL_CRITICAL\x10\x04*\xe3\x01\n" +
	"\fAnalysisType\x12\x1d\n" +
	"\x19ANALYSIS_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eANALYSIS_TYPE_STRESS_DETECTION\x10\x01\x12\"\n" +
	"\x1eANALYSIS_TYPE_CHANGE_DETECTION\x10\x02\x12 \n" +
	"\x1cANALYSIS_TYPE_TEMPORAL_TREND\x10\x03\x12#\n" +
	"\x1fANALYSIS_TYPE_ANOMALY_DETECTION\x10\x04\x12%\n" +
	"!ANALYSIS_TYPE_CROP_CLASSIFICATION\x10\x052\x80\x06\n" +
	"\x19SatelliteAnalyticsService\x12\x81\x01\n" +
	"\fDetectStress\x127.agriculture.satellite.analytics.v1.DetectStressRequest\x1a8.agriculture.satellite.analytics.v1.DetectStressResponse\x12\x8d\x01\n" +
	"\x10ListStressAlerts\x12;.agriculture.satellite.analytics.v1.ListStressAlertsRequest\x1a<.agriculture.satellite.analytics.v1.ListStressAlertsResponse\x12\x8d\x01\n" +
	"\x10AcknowledgeAlert\x12;.agriculture.satellite.analytics.v1.AcknowledgeAlertRequest\x1a<.agriculture.satellite.analytics.v1.AcknowledgeAlertResponse\x12\x96\x01\n" +
	"\x13RunTemporalAnalysis\x12>.agriculture.satellite.analytics.v1.RunTemporalAnalysisRequest\x1a?.agriculture.satellite.analytics.v1.RunTemporalAnalysisResponse\x12\xa5\x01\n" +
	"\x18GetFieldAnalyticsSummary\x12C.agriculture.satellite.analytics.v1.GetFieldAnalyticsSummaryRequest\x1aD.agriculture.satellite.analytics.v1.GetFieldAnalyticsSummaryResponseB@Z>p9e.in/samavaya/agriculture/satellite-analytics-service/api/v1b\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_analytics_proto_goTypes = []any{
	(StressType)(0),                          // 0: agriculture.satellite.analytics.v1.StressType
	(SeverityLevel)(0),                       // 1: agriculture.satellite.analytics.v1.SeverityLevel
	(AnalysisType)(0),                        // 2: agriculture.satellite.analytics.v1.AnalysisType
	(*StressAlert)(nil),                      // 3: agriculture.satellite.analytics.v1.StressAlert
	(*TemporalAnalysis)(nil),                 // 4: agriculture.satellite.analytics.v1.TemporalAnalysis
	(*DetectStressRequest)(nil),              // 5: agriculture.satellite.analytics.v1.DetectStressRequest
	(*DetectStressResponse)(nil),             // 6: agriculture.satellite.analytics.v1.DetectStressResponse
	(*ListStressAlertsRequest)(nil),          // 7: agriculture.satellite.analytics.v1.ListStressAlertsRequest
	(*ListStressAlertsResponse)(nil),         // 8: agriculture.satellite.analytics.v1.ListStressAlertsResponse
	(*AcknowledgeAlertRequest)(nil),          // 9: agriculture.satellite.analytics.v1.AcknowledgeAlertRequest
	(*AcknowledgeAlertResponse)(nil),         // 10: agriculture.satellite.analytics.v1.AcknowledgeAlertResponse
	(*RunTemporalAnalysisRequest)(nil),       // 11: agriculture.satellite.analytics.v1.RunTemporalAnalysisRequest
	(*RunTemporalAnalysisResponse)(nil),      // 12: agriculture.satellite.analytics.v1.RunTemporalAnalysisResponse
	(*GetFieldAnalyticsSummaryRequest)(nil),  // 13: agriculture.satellite.analytics.v1.GetFieldAnalyticsSummaryRequest
	(*GetFieldAnalyticsSummaryResponse)(nil), // 14: agriculture.satellite.analytics.v1.GetFieldAnalyticsSummaryResponse
	(*timestamppb.Timestamp)(nil),            // 15: google.protobuf.Timestamp
}
var file_analytics_proto_depIdxs = []int32{
	0,  // 0: agriculture.satellite.analytics.v1.StressAlert.stress_type:type_name -> agriculture.satellite.analytics.v1.StressType
	1,  // 1: agriculture.satellite.analytics.v1.StressAlert.severity:type_name -> agriculture.satellite.analytics.v1.SeverityLevel
	15, // 2: agriculture.satellite.analytics.v1.StressAlert.detected_at:type_name -> google.protobuf.Timestamp
	15, // 3: agriculture.satellite.analytics.v1.StressAlert.created_at:type_name -> google.protobuf.Timestamp
	2,  // 4: agriculture.satellite.analytics.v1.TemporalAnalysis.analysis_type:type_name -> agriculture.satellite.analytics.v1.AnalysisType
	15, // 5: agriculture.satellite.analytics.v1.TemporalAnalysis.period_start:type_name -> google.protobuf.Timestamp
	15, // 6: agriculture.satellite.analytics.v1.TemporalAnalysis.period_end:type_name -> google.protobuf.Timestamp
	15, // 7: agriculture.satellite.analytics.v1.TemporalAnalysis.created_at:type_name -> google.protobuf.Timestamp
	3,  // 8: agriculture.satellite.analytics.v1.DetectStressResponse.alerts:type_name -> agriculture.satellite.analytics.v1.StressAlert
	0,  // 9: agriculture.satellite.analytics.v1.ListStressAlertsRequest.stress_type:type_name -> agriculture.satellite.analytics.v1.StressType
	1,  // 10: agriculture.satellite.analytics.v1.ListStressAlertsRequest.min_severity:type_name -> agriculture.satellite.analytics.v1.SeverityLevel
	3,  // 11: agriculture.satellite.analytics.v1.ListStressAlertsResponse.alerts:type_name -> agriculture.satellite.analytics.v1.StressAlert
	2,  // 12: agriculture.satellite.analytics.v1.RunTemporalAnalysisRequest.analysis_type:type_name -> agriculture.satellite.analytics.v1.AnalysisType
	15, // 13: agriculture.satellite.analytics.v1.RunTemporalAnalysisRequest.period_start:type_name -> google.protobuf.Timestamp
	15, // 14: agriculture.satellite.analytics.v1.RunTemporalAnalysisRequest.period_end:type_name -> google.protobuf.Timestamp
	4,  // 15: agriculture.satellite.analytics.v1.RunTemporalAnalysisResponse.analysis:type_name -> agriculture.satellite.analytics.v1.TemporalAnalysis
	15, // 16: agriculture.satellite.analytics.v1.GetFieldAnalyticsSummaryResponse.last_analysis:type_name -> google.protobuf.Timestamp
	5,  // 17: agriculture.satellite.analytics.v1.SatelliteAnalyticsService.DetectStress:input_type -> agriculture.satellite.analytics.v1.DetectStressRequest
	7,  // 18: agriculture.satellite.analytics.v1.SatelliteAnalyticsService.ListStressAlerts:input_type -> agriculture.satellite.analytics.v1.ListStressAlertsRequest
	9,  // 19: agriculture.satellite.analytics.v1.SatelliteAnalyticsService.AcknowledgeAlert:input_type -> agriculture.satellite.analytics.v1.AcknowledgeAlertRequest
	11, // 20: agriculture.satellite.analytics.v1.SatelliteAnalyticsService.RunTemporalAnalysis:input_type -> agriculture.satellite.analytics.v1.RunTemporalAnalysisRequest
	13, // 21: agriculture.satellite.analytics.v1.SatelliteAnalyticsService.GetFieldAnalyticsSummary:input_type -> agriculture.satellite.analytics.v1.GetFieldAnalyticsSummaryRequest
	6,  // 22: agriculture.satellite.analytics.v1.SatelliteAnalyticsService.DetectStress:output_type -> agriculture.satellite.analytics.v1.DetectStressResponse
	8,  // 23: agriculture.satellite.analytics.v1.SatelliteAnalyticsService.ListStressAlerts:output_type -> agriculture.satellite.analytics.v1.ListStressAlertsResponse
	10, // 24: agriculture.satellite.analytics.v1.SatelliteAnalyticsService.AcknowledgeAlert:output_type -> agriculture.satellite.analytics.v1.AcknowledgeAlertResponse
	12, // 25: agriculture.satellite.analytics.v1.SatelliteAnalyticsService.RunTemporalAnalysis:output_type -> agriculture.satellite.analytics.v1.RunTemporalAnalysisResponse
	14, // 26: agriculture.satellite.analytics.v1.SatelliteAnalyticsService.GetFieldAnalyticsSummary:output_type -> agriculture.satellite.analytics.v1.GetFieldAnalyticsSummaryResponse
	22, // [22:27] is the sub-list for method output_type
	17, // [17:22] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		EnumInfos:         file_analytics_proto_enumTypes,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
