// Package main wires all traceability-service layers together and starts the HTTP server.
// Pre-requisites: run `buf generate` in traceability-service/ to produce api/v1/*.pb.go
package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"connectrpc.com/connect"
	"github.com/IBM/sarama"
	"github.com/jackc/pgx/v5/pgxpool"
	"go.uber.org/zap"

	"p9e.in/samavaya/packages/connect/interceptors"
	connectserver "p9e.in/samavaya/packages/connect/server"
	"p9e.in/samavaya/packages/p9log"

	// Generated by buf generate — run `buf generate` in traceability-service/ first.
	traceabilityv1connect "p9e.in/samavaya/agriculture/traceability-service/api/v1/traceabilityv1connect"

	grpcadapter "p9e.in/samavaya/agriculture/traceability-service/internal/adapters/inbound/grpc"
	clientsadapter "p9e.in/samavaya/agriculture/traceability-service/internal/adapters/outbound/clients"
	kafkaadapter "p9e.in/samavaya/agriculture/traceability-service/internal/adapters/outbound/kafka"
	postgresadapter "p9e.in/samavaya/agriculture/traceability-service/internal/adapters/outbound/postgres"
	"p9e.in/samavaya/agriculture/traceability-service/internal/application"
)

func main() {
	zapLogger, err := zap.NewProduction()
	if err != nil {
		log.Fatalf("failed to create logger: %v", err)
	}
	defer zapLogger.Sync() //nolint:errcheck
	logger := p9log.NewZapLogger(zapLogger)

	dsn := envOr("DATABASE_URL", "postgres://localhost:5432/traceability_service?sslmode=disable")
	kafkaBroker := os.Getenv("KAFKA_BROKER")
	farmServiceURL := envOr("FARM_SERVICE_URL", "http://localhost:8081")
	fieldServiceURL := envOr("FIELD_SERVICE_URL", "http://localhost:8082")
	yieldServiceURL := envOr("YIELD_SERVICE_URL", "http://localhost:8083")
	port := envOr("PORT", "8080")

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		log.Fatalf("failed to connect to database: %v", err)
	}
	defer pool.Close()

	if err := pool.Ping(ctx); err != nil {
		log.Fatalf("database ping failed: %v", err)
	}

	var kafkaProducer sarama.SyncProducer
	if kafkaBroker != "" {
		cfg := sarama.NewConfig()
		cfg.Producer.Return.Successes = true
		kafkaProducer, err = sarama.NewSyncProducer([]string{kafkaBroker}, cfg)
		if err != nil {
			log.Printf("WARNING: failed to create Kafka producer: %v", err)
		} else {
			defer kafkaProducer.Close()
		}
	}

	// Outbound adapters
	repo := postgresadapter.NewTraceabilityRepository(pool, logger)
	pub := kafkaadapter.NewEventPublisher(kafkaProducer, logger)
	farmClient := clientsadapter.NewFarmClient(farmServiceURL, http.DefaultClient)
	fieldClient := clientsadapter.NewFieldClient(fieldServiceURL, http.DefaultClient)
	yieldClient := clientsadapter.NewYieldClient(yieldServiceURL, http.DefaultClient)

	// Application service
	svc := application.NewTraceabilityService(repo, pub,
		farmClient,
		fieldClient,
		yieldClient,
		pool, logger)

	// Inbound adapters
	handler := grpcadapter.NewTraceabilityHandler(svc, logger)

	mwCfg := connectserver.MiddlewareConfig{
		EnableRecovery:  true,
		EnableRequestID: true,
		EnableLogging:   true,
		EnableDB:        true,
		DBPool:          pool,
	}
	connectOpt := connectserver.NewConnectOption(mwCfg)

	mux := http.NewServeMux()
	path, traceabilityHandler := traceabilityv1connect.NewTraceabilityServiceHandler(handler,
		connect.WithInterceptors(
			interceptors.RequestIDInterceptor(),
			interceptors.NewLoggingInterceptor(logger),
		),
		connectOpt,
	)
	mux.Handle(path, traceabilityHandler)

	mux.HandleFunc("/health", func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte(`{"status":"ok"}`))
	})
	mux.HandleFunc("/ready", func(w http.ResponseWriter, _ *http.Request) {
		if err := pool.Ping(context.Background()); err != nil {
			w.WriteHeader(http.StatusServiceUnavailable)
			return
		}
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte(`{"status":"ready"}`))
	})

	serverCfg := connectserver.DefaultServerConfig(port)
	srv := connectserver.NewHTTPServer(serverCfg, mux)

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		p9log.NewHelper(logger).Infow("msg", "traceability-service starting", "port", port)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("server error: %v", err)
		}
	}()

	<-quit
	p9log.NewHelper(logger).Infow("msg", "shutting down traceability-service")

	shutCtx, shutCancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer shutCancel()
	if err := srv.Shutdown(shutCtx); err != nil {
		log.Printf("graceful shutdown error: %v", err)
	}
}

func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
