// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: prescription.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "p9e.in/samavaya/agriculture/prescription-service/api/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PrescriptionServiceName is the fully-qualified name of the PrescriptionService service.
	PrescriptionServiceName = "agriculture.prescription.v1.PrescriptionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PrescriptionServiceListPrescriptionsProcedure is the fully-qualified name of the
	// PrescriptionService's ListPrescriptions RPC.
	PrescriptionServiceListPrescriptionsProcedure = "/agriculture.prescription.v1.PrescriptionService/ListPrescriptions"
	// PrescriptionServiceGetPrescriptionProcedure is the fully-qualified name of the
	// PrescriptionService's GetPrescription RPC.
	PrescriptionServiceGetPrescriptionProcedure = "/agriculture.prescription.v1.PrescriptionService/GetPrescription"
	// PrescriptionServiceGeneratePrescriptionProcedure is the fully-qualified name of the
	// PrescriptionService's GeneratePrescription RPC.
	PrescriptionServiceGeneratePrescriptionProcedure = "/agriculture.prescription.v1.PrescriptionService/GeneratePrescription"
	// PrescriptionServiceExportPrescriptionProcedure is the fully-qualified name of the
	// PrescriptionService's ExportPrescription RPC.
	PrescriptionServiceExportPrescriptionProcedure = "/agriculture.prescription.v1.PrescriptionService/ExportPrescription"
)

// PrescriptionServiceClient is a client for the agriculture.prescription.v1.PrescriptionService
// service.
type PrescriptionServiceClient interface {
	// ListPrescriptions lists prescriptions with optional type filter and
	// pagination.
	ListPrescriptions(context.Context, *connect.Request[v1.ListPrescriptionsRequest]) (*connect.Response[v1.ListPrescriptionsResponse], error)
	// GetPrescription returns a single prescription bundle by ID.
	GetPrescription(context.Context, *connect.Request[v1.GetPrescriptionRequest]) (*connect.Response[v1.GetPrescriptionResponse], error)
	// GeneratePrescription generates a new variable-rate prescription for a
	// field.
	GeneratePrescription(context.Context, *connect.Request[v1.GeneratePrescriptionRequest]) (*connect.Response[v1.GeneratePrescriptionResponse], error)
	// ExportPrescription exports a prescription in the requested format and
	// returns a download URL.
	ExportPrescription(context.Context, *connect.Request[v1.ExportPrescriptionRequest]) (*connect.Response[v1.ExportPrescriptionResponse], error)
}

// NewPrescriptionServiceClient constructs a client for the
// agriculture.prescription.v1.PrescriptionService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPrescriptionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PrescriptionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	prescriptionServiceMethods := v1.File_prescription_proto.Services().ByName("PrescriptionService").Methods()
	return &prescriptionServiceClient{
		listPrescriptions: connect.NewClient[v1.ListPrescriptionsRequest, v1.ListPrescriptionsResponse](
			httpClient,
			baseURL+PrescriptionServiceListPrescriptionsProcedure,
			connect.WithSchema(prescriptionServiceMethods.ByName("ListPrescriptions")),
			connect.WithClientOptions(opts...),
		),
		getPrescription: connect.NewClient[v1.GetPrescriptionRequest, v1.GetPrescriptionResponse](
			httpClient,
			baseURL+PrescriptionServiceGetPrescriptionProcedure,
			connect.WithSchema(prescriptionServiceMethods.ByName("GetPrescription")),
			connect.WithClientOptions(opts...),
		),
		generatePrescription: connect.NewClient[v1.GeneratePrescriptionRequest, v1.GeneratePrescriptionResponse](
			httpClient,
			baseURL+PrescriptionServiceGeneratePrescriptionProcedure,
			connect.WithSchema(prescriptionServiceMethods.ByName("GeneratePrescription")),
			connect.WithClientOptions(opts...),
		),
		exportPrescription: connect.NewClient[v1.ExportPrescriptionRequest, v1.ExportPrescriptionResponse](
			httpClient,
			baseURL+PrescriptionServiceExportPrescriptionProcedure,
			connect.WithSchema(prescriptionServiceMethods.ByName("ExportPrescription")),
			connect.WithClientOptions(opts...),
		),
	}
}

// prescriptionServiceClient implements PrescriptionServiceClient.
type prescriptionServiceClient struct {
	listPrescriptions    *connect.Client[v1.ListPrescriptionsRequest, v1.ListPrescriptionsResponse]
	getPrescription      *connect.Client[v1.GetPrescriptionRequest, v1.GetPrescriptionResponse]
	generatePrescription *connect.Client[v1.GeneratePrescriptionRequest, v1.GeneratePrescriptionResponse]
	exportPrescription   *connect.Client[v1.ExportPrescriptionRequest, v1.ExportPrescriptionResponse]
}

// ListPrescriptions calls agriculture.prescription.v1.PrescriptionService.ListPrescriptions.
func (c *prescriptionServiceClient) ListPrescriptions(ctx context.Context, req *connect.Request[v1.ListPrescriptionsRequest]) (*connect.Response[v1.ListPrescriptionsResponse], error) {
	return c.listPrescriptions.CallUnary(ctx, req)
}

// GetPrescription calls agriculture.prescription.v1.PrescriptionService.GetPrescription.
func (c *prescriptionServiceClient) GetPrescription(ctx context.Context, req *connect.Request[v1.GetPrescriptionRequest]) (*connect.Response[v1.GetPrescriptionResponse], error) {
	return c.getPrescription.CallUnary(ctx, req)
}

// GeneratePrescription calls agriculture.prescription.v1.PrescriptionService.GeneratePrescription.
func (c *prescriptionServiceClient) GeneratePrescription(ctx context.Context, req *connect.Request[v1.GeneratePrescriptionRequest]) (*connect.Response[v1.GeneratePrescriptionResponse], error) {
	return c.generatePrescription.CallUnary(ctx, req)
}

// ExportPrescription calls agriculture.prescription.v1.PrescriptionService.ExportPrescription.
func (c *prescriptionServiceClient) ExportPrescription(ctx context.Context, req *connect.Request[v1.ExportPrescriptionRequest]) (*connect.Response[v1.ExportPrescriptionResponse], error) {
	return c.exportPrescription.CallUnary(ctx, req)
}

// PrescriptionServiceHandler is an implementation of the
// agriculture.prescription.v1.PrescriptionService service.
type PrescriptionServiceHandler interface {
	// ListPrescriptions lists prescriptions with optional type filter and
	// pagination.
	ListPrescriptions(context.Context, *connect.Request[v1.ListPrescriptionsRequest]) (*connect.Response[v1.ListPrescriptionsResponse], error)
	// GetPrescription returns a single prescription bundle by ID.
	GetPrescription(context.Context, *connect.Request[v1.GetPrescriptionRequest]) (*connect.Response[v1.GetPrescriptionResponse], error)
	// GeneratePrescription generates a new variable-rate prescription for a
	// field.
	GeneratePrescription(context.Context, *connect.Request[v1.GeneratePrescriptionRequest]) (*connect.Response[v1.GeneratePrescriptionResponse], error)
	// ExportPrescription exports a prescription in the requested format and
	// returns a download URL.
	ExportPrescription(context.Context, *connect.Request[v1.ExportPrescriptionRequest]) (*connect.Response[v1.ExportPrescriptionResponse], error)
}

// NewPrescriptionServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPrescriptionServiceHandler(svc PrescriptionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	prescriptionServiceMethods := v1.File_prescription_proto.Services().ByName("PrescriptionService").Methods()
	prescriptionServiceListPrescriptionsHandler := connect.NewUnaryHandler(
		PrescriptionServiceListPrescriptionsProcedure,
		svc.ListPrescriptions,
		connect.WithSchema(prescriptionServiceMethods.ByName("ListPrescriptions")),
		connect.WithHandlerOptions(opts...),
	)
	prescriptionServiceGetPrescriptionHandler := connect.NewUnaryHandler(
		PrescriptionServiceGetPrescriptionProcedure,
		svc.GetPrescription,
		connect.WithSchema(prescriptionServiceMethods.ByName("GetPrescription")),
		connect.WithHandlerOptions(opts...),
	)
	prescriptionServiceGeneratePrescriptionHandler := connect.NewUnaryHandler(
		PrescriptionServiceGeneratePrescriptionProcedure,
		svc.GeneratePrescription,
		connect.WithSchema(prescriptionServiceMethods.ByName("GeneratePrescription")),
		connect.WithHandlerOptions(opts...),
	)
	prescriptionServiceExportPrescriptionHandler := connect.NewUnaryHandler(
		PrescriptionServiceExportPrescriptionProcedure,
		svc.ExportPrescription,
		connect.WithSchema(prescriptionServiceMethods.ByName("ExportPrescription")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agriculture.prescription.v1.PrescriptionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PrescriptionServiceListPrescriptionsProcedure:
			prescriptionServiceListPrescriptionsHandler.ServeHTTP(w, r)
		case PrescriptionServiceGetPrescriptionProcedure:
			prescriptionServiceGetPrescriptionHandler.ServeHTTP(w, r)
		case PrescriptionServiceGeneratePrescriptionProcedure:
			prescriptionServiceGeneratePrescriptionHandler.ServeHTTP(w, r)
		case PrescriptionServiceExportPrescriptionProcedure:
			prescriptionServiceExportPrescriptionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPrescriptionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPrescriptionServiceHandler struct{}

func (UnimplementedPrescriptionServiceHandler) ListPrescriptions(context.Context, *connect.Request[v1.ListPrescriptionsRequest]) (*connect.Response[v1.ListPrescriptionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.prescription.v1.PrescriptionService.ListPrescriptions is not implemented"))
}

func (UnimplementedPrescriptionServiceHandler) GetPrescription(context.Context, *connect.Request[v1.GetPrescriptionRequest]) (*connect.Response[v1.GetPrescriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.prescription.v1.PrescriptionService.GetPrescription is not implemented"))
}

func (UnimplementedPrescriptionServiceHandler) GeneratePrescription(context.Context, *connect.Request[v1.GeneratePrescriptionRequest]) (*connect.Response[v1.GeneratePrescriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.prescription.v1.PrescriptionService.GeneratePrescription is not implemented"))
}

func (UnimplementedPrescriptionServiceHandler) ExportPrescription(context.Context, *connect.Request[v1.ExportPrescriptionRequest]) (*connect.Response[v1.ExportPrescriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.prescription.v1.PrescriptionService.ExportPrescription is not implemented"))
}
