// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: yield.proto

package yieldv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "p9e.in/samavaya/agriculture/yield-service/api/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// YieldServiceName is the fully-qualified name of the YieldService service.
	YieldServiceName = "agriculture.yield.v1.YieldService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// YieldServicePredictYieldProcedure is the fully-qualified name of the YieldService's PredictYield
	// RPC.
	YieldServicePredictYieldProcedure = "/agriculture.yield.v1.YieldService/PredictYield"
	// YieldServiceGetPredictionProcedure is the fully-qualified name of the YieldService's
	// GetPrediction RPC.
	YieldServiceGetPredictionProcedure = "/agriculture.yield.v1.YieldService/GetPrediction"
	// YieldServiceListPredictionsProcedure is the fully-qualified name of the YieldService's
	// ListPredictions RPC.
	YieldServiceListPredictionsProcedure = "/agriculture.yield.v1.YieldService/ListPredictions"
	// YieldServiceRecordYieldProcedure is the fully-qualified name of the YieldService's RecordYield
	// RPC.
	YieldServiceRecordYieldProcedure = "/agriculture.yield.v1.YieldService/RecordYield"
	// YieldServiceGetYieldHistoryProcedure is the fully-qualified name of the YieldService's
	// GetYieldHistory RPC.
	YieldServiceGetYieldHistoryProcedure = "/agriculture.yield.v1.YieldService/GetYieldHistory"
	// YieldServiceCreateHarvestPlanProcedure is the fully-qualified name of the YieldService's
	// CreateHarvestPlan RPC.
	YieldServiceCreateHarvestPlanProcedure = "/agriculture.yield.v1.YieldService/CreateHarvestPlan"
	// YieldServiceGetHarvestPlanProcedure is the fully-qualified name of the YieldService's
	// GetHarvestPlan RPC.
	YieldServiceGetHarvestPlanProcedure = "/agriculture.yield.v1.YieldService/GetHarvestPlan"
	// YieldServiceListHarvestPlansProcedure is the fully-qualified name of the YieldService's
	// ListHarvestPlans RPC.
	YieldServiceListHarvestPlansProcedure = "/agriculture.yield.v1.YieldService/ListHarvestPlans"
	// YieldServiceGetCropPerformanceProcedure is the fully-qualified name of the YieldService's
	// GetCropPerformance RPC.
	YieldServiceGetCropPerformanceProcedure = "/agriculture.yield.v1.YieldService/GetCropPerformance"
	// YieldServiceCompareYieldsProcedure is the fully-qualified name of the YieldService's
	// CompareYields RPC.
	YieldServiceCompareYieldsProcedure = "/agriculture.yield.v1.YieldService/CompareYields"
)

// YieldServiceClient is a client for the agriculture.yield.v1.YieldService service.
type YieldServiceClient interface {
	// PredictYield generates a yield prediction using multi-factor analysis.
	PredictYield(context.Context, *connect.Request[v1.PredictYieldRequest]) (*connect.Response[v1.PredictYieldResponse], error)
	// GetPrediction retrieves a yield prediction by ID.
	GetPrediction(context.Context, *connect.Request[v1.GetPredictionRequest]) (*connect.Response[v1.GetPredictionResponse], error)
	// ListPredictions lists yield predictions with filtering and pagination.
	ListPredictions(context.Context, *connect.Request[v1.ListPredictionsRequest]) (*connect.Response[v1.ListPredictionsResponse], error)
	// RecordYield records an actual harvest yield.
	RecordYield(context.Context, *connect.Request[v1.RecordYieldRequest]) (*connect.Response[v1.RecordYieldResponse], error)
	// GetYieldHistory retrieves historical yield records.
	GetYieldHistory(context.Context, *connect.Request[v1.GetYieldHistoryRequest]) (*connect.Response[v1.GetYieldHistoryResponse], error)
	// CreateHarvestPlan creates a new harvest plan.
	CreateHarvestPlan(context.Context, *connect.Request[v1.CreateHarvestPlanRequest]) (*connect.Response[v1.CreateHarvestPlanResponse], error)
	// GetHarvestPlan retrieves a harvest plan by ID.
	GetHarvestPlan(context.Context, *connect.Request[v1.GetHarvestPlanRequest]) (*connect.Response[v1.GetHarvestPlanResponse], error)
	// ListHarvestPlans lists harvest plans with filtering and pagination.
	ListHarvestPlans(context.Context, *connect.Request[v1.ListHarvestPlansRequest]) (*connect.Response[v1.ListHarvestPlansResponse], error)
	// GetCropPerformance retrieves crop performance analytics.
	GetCropPerformance(context.Context, *connect.Request[v1.GetCropPerformanceRequest]) (*connect.Response[v1.GetCropPerformanceResponse], error)
	// CompareYields compares yield performance between two seasons or years.
	CompareYields(context.Context, *connect.Request[v1.CompareYieldsRequest]) (*connect.Response[v1.CompareYieldsResponse], error)
}

// NewYieldServiceClient constructs a client for the agriculture.yield.v1.YieldService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewYieldServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) YieldServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	yieldServiceMethods := v1.File_yield_proto.Services().ByName("YieldService").Methods()
	return &yieldServiceClient{
		predictYield: connect.NewClient[v1.PredictYieldRequest, v1.PredictYieldResponse](
			httpClient,
			baseURL+YieldServicePredictYieldProcedure,
			connect.WithSchema(yieldServiceMethods.ByName("PredictYield")),
			connect.WithClientOptions(opts...),
		),
		getPrediction: connect.NewClient[v1.GetPredictionRequest, v1.GetPredictionResponse](
			httpClient,
			baseURL+YieldServiceGetPredictionProcedure,
			connect.WithSchema(yieldServiceMethods.ByName("GetPrediction")),
			connect.WithClientOptions(opts...),
		),
		listPredictions: connect.NewClient[v1.ListPredictionsRequest, v1.ListPredictionsResponse](
			httpClient,
			baseURL+YieldServiceListPredictionsProcedure,
			connect.WithSchema(yieldServiceMethods.ByName("ListPredictions")),
			connect.WithClientOptions(opts...),
		),
		recordYield: connect.NewClient[v1.RecordYieldRequest, v1.RecordYieldResponse](
			httpClient,
			baseURL+YieldServiceRecordYieldProcedure,
			connect.WithSchema(yieldServiceMethods.ByName("RecordYield")),
			connect.WithClientOptions(opts...),
		),
		getYieldHistory: connect.NewClient[v1.GetYieldHistoryRequest, v1.GetYieldHistoryResponse](
			httpClient,
			baseURL+YieldServiceGetYieldHistoryProcedure,
			connect.WithSchema(yieldServiceMethods.ByName("GetYieldHistory")),
			connect.WithClientOptions(opts...),
		),
		createHarvestPlan: connect.NewClient[v1.CreateHarvestPlanRequest, v1.CreateHarvestPlanResponse](
			httpClient,
			baseURL+YieldServiceCreateHarvestPlanProcedure,
			connect.WithSchema(yieldServiceMethods.ByName("CreateHarvestPlan")),
			connect.WithClientOptions(opts...),
		),
		getHarvestPlan: connect.NewClient[v1.GetHarvestPlanRequest, v1.GetHarvestPlanResponse](
			httpClient,
			baseURL+YieldServiceGetHarvestPlanProcedure,
			connect.WithSchema(yieldServiceMethods.ByName("GetHarvestPlan")),
			connect.WithClientOptions(opts...),
		),
		listHarvestPlans: connect.NewClient[v1.ListHarvestPlansRequest, v1.ListHarvestPlansResponse](
			httpClient,
			baseURL+YieldServiceListHarvestPlansProcedure,
			connect.WithSchema(yieldServiceMethods.ByName("ListHarvestPlans")),
			connect.WithClientOptions(opts...),
		),
		getCropPerformance: connect.NewClient[v1.GetCropPerformanceRequest, v1.GetCropPerformanceResponse](
			httpClient,
			baseURL+YieldServiceGetCropPerformanceProcedure,
			connect.WithSchema(yieldServiceMethods.ByName("GetCropPerformance")),
			connect.WithClientOptions(opts...),
		),
		compareYields: connect.NewClient[v1.CompareYieldsRequest, v1.CompareYieldsResponse](
			httpClient,
			baseURL+YieldServiceCompareYieldsProcedure,
			connect.WithSchema(yieldServiceMethods.ByName("CompareYields")),
			connect.WithClientOptions(opts...),
		),
	}
}

// yieldServiceClient implements YieldServiceClient.
type yieldServiceClient struct {
	predictYield       *connect.Client[v1.PredictYieldRequest, v1.PredictYieldResponse]
	getPrediction      *connect.Client[v1.GetPredictionRequest, v1.GetPredictionResponse]
	listPredictions    *connect.Client[v1.ListPredictionsRequest, v1.ListPredictionsResponse]
	recordYield        *connect.Client[v1.RecordYieldRequest, v1.RecordYieldResponse]
	getYieldHistory    *connect.Client[v1.GetYieldHistoryRequest, v1.GetYieldHistoryResponse]
	createHarvestPlan  *connect.Client[v1.CreateHarvestPlanRequest, v1.CreateHarvestPlanResponse]
	getHarvestPlan     *connect.Client[v1.GetHarvestPlanRequest, v1.GetHarvestPlanResponse]
	listHarvestPlans   *connect.Client[v1.ListHarvestPlansRequest, v1.ListHarvestPlansResponse]
	getCropPerformance *connect.Client[v1.GetCropPerformanceRequest, v1.GetCropPerformanceResponse]
	compareYields      *connect.Client[v1.CompareYieldsRequest, v1.CompareYieldsResponse]
}

// PredictYield calls agriculture.yield.v1.YieldService.PredictYield.
func (c *yieldServiceClient) PredictYield(ctx context.Context, req *connect.Request[v1.PredictYieldRequest]) (*connect.Response[v1.PredictYieldResponse], error) {
	return c.predictYield.CallUnary(ctx, req)
}

// GetPrediction calls agriculture.yield.v1.YieldService.GetPrediction.
func (c *yieldServiceClient) GetPrediction(ctx context.Context, req *connect.Request[v1.GetPredictionRequest]) (*connect.Response[v1.GetPredictionResponse], error) {
	return c.getPrediction.CallUnary(ctx, req)
}

// ListPredictions calls agriculture.yield.v1.YieldService.ListPredictions.
func (c *yieldServiceClient) ListPredictions(ctx context.Context, req *connect.Request[v1.ListPredictionsRequest]) (*connect.Response[v1.ListPredictionsResponse], error) {
	return c.listPredictions.CallUnary(ctx, req)
}

// RecordYield calls agriculture.yield.v1.YieldService.RecordYield.
func (c *yieldServiceClient) RecordYield(ctx context.Context, req *connect.Request[v1.RecordYieldRequest]) (*connect.Response[v1.RecordYieldResponse], error) {
	return c.recordYield.CallUnary(ctx, req)
}

// GetYieldHistory calls agriculture.yield.v1.YieldService.GetYieldHistory.
func (c *yieldServiceClient) GetYieldHistory(ctx context.Context, req *connect.Request[v1.GetYieldHistoryRequest]) (*connect.Response[v1.GetYieldHistoryResponse], error) {
	return c.getYieldHistory.CallUnary(ctx, req)
}

// CreateHarvestPlan calls agriculture.yield.v1.YieldService.CreateHarvestPlan.
func (c *yieldServiceClient) CreateHarvestPlan(ctx context.Context, req *connect.Request[v1.CreateHarvestPlanRequest]) (*connect.Response[v1.CreateHarvestPlanResponse], error) {
	return c.createHarvestPlan.CallUnary(ctx, req)
}

// GetHarvestPlan calls agriculture.yield.v1.YieldService.GetHarvestPlan.
func (c *yieldServiceClient) GetHarvestPlan(ctx context.Context, req *connect.Request[v1.GetHarvestPlanRequest]) (*connect.Response[v1.GetHarvestPlanResponse], error) {
	return c.getHarvestPlan.CallUnary(ctx, req)
}

// ListHarvestPlans calls agriculture.yield.v1.YieldService.ListHarvestPlans.
func (c *yieldServiceClient) ListHarvestPlans(ctx context.Context, req *connect.Request[v1.ListHarvestPlansRequest]) (*connect.Response[v1.ListHarvestPlansResponse], error) {
	return c.listHarvestPlans.CallUnary(ctx, req)
}

// GetCropPerformance calls agriculture.yield.v1.YieldService.GetCropPerformance.
func (c *yieldServiceClient) GetCropPerformance(ctx context.Context, req *connect.Request[v1.GetCropPerformanceRequest]) (*connect.Response[v1.GetCropPerformanceResponse], error) {
	return c.getCropPerformance.CallUnary(ctx, req)
}

// CompareYields calls agriculture.yield.v1.YieldService.CompareYields.
func (c *yieldServiceClient) CompareYields(ctx context.Context, req *connect.Request[v1.CompareYieldsRequest]) (*connect.Response[v1.CompareYieldsResponse], error) {
	return c.compareYields.CallUnary(ctx, req)
}

// YieldServiceHandler is an implementation of the agriculture.yield.v1.YieldService service.
type YieldServiceHandler interface {
	// PredictYield generates a yield prediction using multi-factor analysis.
	PredictYield(context.Context, *connect.Request[v1.PredictYieldRequest]) (*connect.Response[v1.PredictYieldResponse], error)
	// GetPrediction retrieves a yield prediction by ID.
	GetPrediction(context.Context, *connect.Request[v1.GetPredictionRequest]) (*connect.Response[v1.GetPredictionResponse], error)
	// ListPredictions lists yield predictions with filtering and pagination.
	ListPredictions(context.Context, *connect.Request[v1.ListPredictionsRequest]) (*connect.Response[v1.ListPredictionsResponse], error)
	// RecordYield records an actual harvest yield.
	RecordYield(context.Context, *connect.Request[v1.RecordYieldRequest]) (*connect.Response[v1.RecordYieldResponse], error)
	// GetYieldHistory retrieves historical yield records.
	GetYieldHistory(context.Context, *connect.Request[v1.GetYieldHistoryRequest]) (*connect.Response[v1.GetYieldHistoryResponse], error)
	// CreateHarvestPlan creates a new harvest plan.
	CreateHarvestPlan(context.Context, *connect.Request[v1.CreateHarvestPlanRequest]) (*connect.Response[v1.CreateHarvestPlanResponse], error)
	// GetHarvestPlan retrieves a harvest plan by ID.
	GetHarvestPlan(context.Context, *connect.Request[v1.GetHarvestPlanRequest]) (*connect.Response[v1.GetHarvestPlanResponse], error)
	// ListHarvestPlans lists harvest plans with filtering and pagination.
	ListHarvestPlans(context.Context, *connect.Request[v1.ListHarvestPlansRequest]) (*connect.Response[v1.ListHarvestPlansResponse], error)
	// GetCropPerformance retrieves crop performance analytics.
	GetCropPerformance(context.Context, *connect.Request[v1.GetCropPerformanceRequest]) (*connect.Response[v1.GetCropPerformanceResponse], error)
	// CompareYields compares yield performance between two seasons or years.
	CompareYields(context.Context, *connect.Request[v1.CompareYieldsRequest]) (*connect.Response[v1.CompareYieldsResponse], error)
}

// NewYieldServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewYieldServiceHandler(svc YieldServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	yieldServiceMethods := v1.File_yield_proto.Services().ByName("YieldService").Methods()
	yieldServicePredictYieldHandler := connect.NewUnaryHandler(
		YieldServicePredictYieldProcedure,
		svc.PredictYield,
		connect.WithSchema(yieldServiceMethods.ByName("PredictYield")),
		connect.WithHandlerOptions(opts...),
	)
	yieldServiceGetPredictionHandler := connect.NewUnaryHandler(
		YieldServiceGetPredictionProcedure,
		svc.GetPrediction,
		connect.WithSchema(yieldServiceMethods.ByName("GetPrediction")),
		connect.WithHandlerOptions(opts...),
	)
	yieldServiceListPredictionsHandler := connect.NewUnaryHandler(
		YieldServiceListPredictionsProcedure,
		svc.ListPredictions,
		connect.WithSchema(yieldServiceMethods.ByName("ListPredictions")),
		connect.WithHandlerOptions(opts...),
	)
	yieldServiceRecordYieldHandler := connect.NewUnaryHandler(
		YieldServiceRecordYieldProcedure,
		svc.RecordYield,
		connect.WithSchema(yieldServiceMethods.ByName("RecordYield")),
		connect.WithHandlerOptions(opts...),
	)
	yieldServiceGetYieldHistoryHandler := connect.NewUnaryHandler(
		YieldServiceGetYieldHistoryProcedure,
		svc.GetYieldHistory,
		connect.WithSchema(yieldServiceMethods.ByName("GetYieldHistory")),
		connect.WithHandlerOptions(opts...),
	)
	yieldServiceCreateHarvestPlanHandler := connect.NewUnaryHandler(
		YieldServiceCreateHarvestPlanProcedure,
		svc.CreateHarvestPlan,
		connect.WithSchema(yieldServiceMethods.ByName("CreateHarvestPlan")),
		connect.WithHandlerOptions(opts...),
	)
	yieldServiceGetHarvestPlanHandler := connect.NewUnaryHandler(
		YieldServiceGetHarvestPlanProcedure,
		svc.GetHarvestPlan,
		connect.WithSchema(yieldServiceMethods.ByName("GetHarvestPlan")),
		connect.WithHandlerOptions(opts...),
	)
	yieldServiceListHarvestPlansHandler := connect.NewUnaryHandler(
		YieldServiceListHarvestPlansProcedure,
		svc.ListHarvestPlans,
		connect.WithSchema(yieldServiceMethods.ByName("ListHarvestPlans")),
		connect.WithHandlerOptions(opts...),
	)
	yieldServiceGetCropPerformanceHandler := connect.NewUnaryHandler(
		YieldServiceGetCropPerformanceProcedure,
		svc.GetCropPerformance,
		connect.WithSchema(yieldServiceMethods.ByName("GetCropPerformance")),
		connect.WithHandlerOptions(opts...),
	)
	yieldServiceCompareYieldsHandler := connect.NewUnaryHandler(
		YieldServiceCompareYieldsProcedure,
		svc.CompareYields,
		connect.WithSchema(yieldServiceMethods.ByName("CompareYields")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agriculture.yield.v1.YieldService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case YieldServicePredictYieldProcedure:
			yieldServicePredictYieldHandler.ServeHTTP(w, r)
		case YieldServiceGetPredictionProcedure:
			yieldServiceGetPredictionHandler.ServeHTTP(w, r)
		case YieldServiceListPredictionsProcedure:
			yieldServiceListPredictionsHandler.ServeHTTP(w, r)
		case YieldServiceRecordYieldProcedure:
			yieldServiceRecordYieldHandler.ServeHTTP(w, r)
		case YieldServiceGetYieldHistoryProcedure:
			yieldServiceGetYieldHistoryHandler.ServeHTTP(w, r)
		case YieldServiceCreateHarvestPlanProcedure:
			yieldServiceCreateHarvestPlanHandler.ServeHTTP(w, r)
		case YieldServiceGetHarvestPlanProcedure:
			yieldServiceGetHarvestPlanHandler.ServeHTTP(w, r)
		case YieldServiceListHarvestPlansProcedure:
			yieldServiceListHarvestPlansHandler.ServeHTTP(w, r)
		case YieldServiceGetCropPerformanceProcedure:
			yieldServiceGetCropPerformanceHandler.ServeHTTP(w, r)
		case YieldServiceCompareYieldsProcedure:
			yieldServiceCompareYieldsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedYieldServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedYieldServiceHandler struct{}

func (UnimplementedYieldServiceHandler) PredictYield(context.Context, *connect.Request[v1.PredictYieldRequest]) (*connect.Response[v1.PredictYieldResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.yield.v1.YieldService.PredictYield is not implemented"))
}

func (UnimplementedYieldServiceHandler) GetPrediction(context.Context, *connect.Request[v1.GetPredictionRequest]) (*connect.Response[v1.GetPredictionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.yield.v1.YieldService.GetPrediction is not implemented"))
}

func (UnimplementedYieldServiceHandler) ListPredictions(context.Context, *connect.Request[v1.ListPredictionsRequest]) (*connect.Response[v1.ListPredictionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.yield.v1.YieldService.ListPredictions is not implemented"))
}

func (UnimplementedYieldServiceHandler) RecordYield(context.Context, *connect.Request[v1.RecordYieldRequest]) (*connect.Response[v1.RecordYieldResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.yield.v1.YieldService.RecordYield is not implemented"))
}

func (UnimplementedYieldServiceHandler) GetYieldHistory(context.Context, *connect.Request[v1.GetYieldHistoryRequest]) (*connect.Response[v1.GetYieldHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.yield.v1.YieldService.GetYieldHistory is not implemented"))
}

func (UnimplementedYieldServiceHandler) CreateHarvestPlan(context.Context, *connect.Request[v1.CreateHarvestPlanRequest]) (*connect.Response[v1.CreateHarvestPlanResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.yield.v1.YieldService.CreateHarvestPlan is not implemented"))
}

func (UnimplementedYieldServiceHandler) GetHarvestPlan(context.Context, *connect.Request[v1.GetHarvestPlanRequest]) (*connect.Response[v1.GetHarvestPlanResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.yield.v1.YieldService.GetHarvestPlan is not implemented"))
}

func (UnimplementedYieldServiceHandler) ListHarvestPlans(context.Context, *connect.Request[v1.ListHarvestPlansRequest]) (*connect.Response[v1.ListHarvestPlansResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.yield.v1.YieldService.ListHarvestPlans is not implemented"))
}

func (UnimplementedYieldServiceHandler) GetCropPerformance(context.Context, *connect.Request[v1.GetCropPerformanceRequest]) (*connect.Response[v1.GetCropPerformanceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.yield.v1.YieldService.GetCropPerformance is not implemented"))
}

func (UnimplementedYieldServiceHandler) CompareYields(context.Context, *connect.Request[v1.CompareYieldsRequest]) (*connect.Response[v1.CompareYieldsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.yield.v1.YieldService.CompareYields is not implemented"))
}
