// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: device.proto

package devicev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "p9e.in/samavaya/agriculture/device-service/api/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DeviceServiceName is the fully-qualified name of the DeviceService service.
	DeviceServiceName = "agriculture.device.v1.DeviceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DeviceServiceProvisionDeviceProcedure is the fully-qualified name of the DeviceService's
	// ProvisionDevice RPC.
	DeviceServiceProvisionDeviceProcedure = "/agriculture.device.v1.DeviceService/ProvisionDevice"
	// DeviceServiceGetDeviceProcedure is the fully-qualified name of the DeviceService's GetDevice RPC.
	DeviceServiceGetDeviceProcedure = "/agriculture.device.v1.DeviceService/GetDevice"
	// DeviceServiceListDevicesProcedure is the fully-qualified name of the DeviceService's ListDevices
	// RPC.
	DeviceServiceListDevicesProcedure = "/agriculture.device.v1.DeviceService/ListDevices"
	// DeviceServiceRecordHeartbeatsProcedure is the fully-qualified name of the DeviceService's
	// RecordHeartbeats RPC.
	DeviceServiceRecordHeartbeatsProcedure = "/agriculture.device.v1.DeviceService/RecordHeartbeats"
	// DeviceServiceRetireDeviceProcedure is the fully-qualified name of the DeviceService's
	// RetireDevice RPC.
	DeviceServiceRetireDeviceProcedure = "/agriculture.device.v1.DeviceService/RetireDevice"
	// DeviceServiceGetFleetHealthProcedure is the fully-qualified name of the DeviceService's
	// GetFleetHealth RPC.
	DeviceServiceGetFleetHealthProcedure = "/agriculture.device.v1.DeviceService/GetFleetHealth"
	// DeviceServiceCreateRolloutProcedure is the fully-qualified name of the DeviceService's
	// CreateRollout RPC.
	DeviceServiceCreateRolloutProcedure = "/agriculture.device.v1.DeviceService/CreateRollout"
	// DeviceServiceAdvanceRolloutProcedure is the fully-qualified name of the DeviceService's
	// AdvanceRollout RPC.
	DeviceServiceAdvanceRolloutProcedure = "/agriculture.device.v1.DeviceService/AdvanceRollout"
	// DeviceServiceReportUpdateProcedure is the fully-qualified name of the DeviceService's
	// ReportUpdate RPC.
	DeviceServiceReportUpdateProcedure = "/agriculture.device.v1.DeviceService/ReportUpdate"
	// DeviceServiceListRolloutsProcedure is the fully-qualified name of the DeviceService's
	// ListRollouts RPC.
	DeviceServiceListRolloutsProcedure = "/agriculture.device.v1.DeviceService/ListRollouts"
)

// DeviceServiceClient is a client for the agriculture.device.v1.DeviceService service.
type DeviceServiceClient interface {
	ProvisionDevice(context.Context, *connect.Request[v1.ProvisionDeviceRequest]) (*connect.Response[v1.ProvisionDeviceResponse], error)
	GetDevice(context.Context, *connect.Request[v1.GetDeviceRequest]) (*connect.Response[v1.GetDeviceResponse], error)
	ListDevices(context.Context, *connect.Request[v1.ListDevicesRequest]) (*connect.Response[v1.ListDevicesResponse], error)
	RecordHeartbeats(context.Context, *connect.Request[v1.RecordHeartbeatsRequest]) (*connect.Response[v1.RecordHeartbeatsResponse], error)
	RetireDevice(context.Context, *connect.Request[v1.RetireDeviceRequest]) (*connect.Response[v1.RetireDeviceResponse], error)
	GetFleetHealth(context.Context, *connect.Request[v1.GetFleetHealthRequest]) (*connect.Response[v1.GetFleetHealthResponse], error)
	CreateRollout(context.Context, *connect.Request[v1.CreateRolloutRequest]) (*connect.Response[v1.CreateRolloutResponse], error)
	AdvanceRollout(context.Context, *connect.Request[v1.AdvanceRolloutRequest]) (*connect.Response[v1.AdvanceRolloutResponse], error)
	ReportUpdate(context.Context, *connect.Request[v1.ReportUpdateRequest]) (*connect.Response[v1.ReportUpdateResponse], error)
	ListRollouts(context.Context, *connect.Request[v1.ListRolloutsRequest]) (*connect.Response[v1.ListRolloutsResponse], error)
}

// NewDeviceServiceClient constructs a client for the agriculture.device.v1.DeviceService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDeviceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DeviceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	deviceServiceMethods := v1.File_device_proto.Services().ByName("DeviceService").Methods()
	return &deviceServiceClient{
		provisionDevice: connect.NewClient[v1.ProvisionDeviceRequest, v1.ProvisionDeviceResponse](
			httpClient,
			baseURL+DeviceServiceProvisionDeviceProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("ProvisionDevice")),
			connect.WithClientOptions(opts...),
		),
		getDevice: connect.NewClient[v1.GetDeviceRequest, v1.GetDeviceResponse](
			httpClient,
			baseURL+DeviceServiceGetDeviceProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("GetDevice")),
			connect.WithClientOptions(opts...),
		),
		listDevices: connect.NewClient[v1.ListDevicesRequest, v1.ListDevicesResponse](
			httpClient,
			baseURL+DeviceServiceListDevicesProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("ListDevices")),
			connect.WithClientOptions(opts...),
		),
		recordHeartbeats: connect.NewClient[v1.RecordHeartbeatsRequest, v1.RecordHeartbeatsResponse](
			httpClient,
			baseURL+DeviceServiceRecordHeartbeatsProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("RecordHeartbeats")),
			connect.WithClientOptions(opts...),
		),
		retireDevice: connect.NewClient[v1.RetireDeviceRequest, v1.RetireDeviceResponse](
			httpClient,
			baseURL+DeviceServiceRetireDeviceProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("RetireDevice")),
			connect.WithClientOptions(opts...),
		),
		getFleetHealth: connect.NewClient[v1.GetFleetHealthRequest, v1.GetFleetHealthResponse](
			httpClient,
			baseURL+DeviceServiceGetFleetHealthProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("GetFleetHealth")),
			connect.WithClientOptions(opts...),
		),
		createRollout: connect.NewClient[v1.CreateRolloutRequest, v1.CreateRolloutResponse](
			httpClient,
			baseURL+DeviceServiceCreateRolloutProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("CreateRollout")),
			connect.WithClientOptions(opts...),
		),
		advanceRollout: connect.NewClient[v1.AdvanceRolloutRequest, v1.AdvanceRolloutResponse](
			httpClient,
			baseURL+DeviceServiceAdvanceRolloutProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("AdvanceRollout")),
			connect.WithClientOptions(opts...),
		),
		reportUpdate: connect.NewClient[v1.ReportUpdateRequest, v1.ReportUpdateResponse](
			httpClient,
			baseURL+DeviceServiceReportUpdateProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("ReportUpdate")),
			connect.WithClientOptions(opts...),
		),
		listRollouts: connect.NewClient[v1.ListRolloutsRequest, v1.ListRolloutsResponse](
			httpClient,
			baseURL+DeviceServiceListRolloutsProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("ListRollouts")),
			connect.WithClientOptions(opts...),
		),
	}
}

// deviceServiceClient implements DeviceServiceClient.
type deviceServiceClient struct {
	provisionDevice  *connect.Client[v1.ProvisionDeviceRequest, v1.ProvisionDeviceResponse]
	getDevice        *connect.Client[v1.GetDeviceRequest, v1.GetDeviceResponse]
	listDevices      *connect.Client[v1.ListDevicesRequest, v1.ListDevicesResponse]
	recordHeartbeats *connect.Client[v1.RecordHeartbeatsRequest, v1.RecordHeartbeatsResponse]
	retireDevice     *connect.Client[v1.RetireDeviceRequest, v1.RetireDeviceResponse]
	getFleetHealth   *connect.Client[v1.GetFleetHealthRequest, v1.GetFleetHealthResponse]
	createRollout    *connect.Client[v1.CreateRolloutRequest, v1.CreateRolloutResponse]
	advanceRollout   *connect.Client[v1.AdvanceRolloutRequest, v1.AdvanceRolloutResponse]
	reportUpdate     *connect.Client[v1.ReportUpdateRequest, v1.ReportUpdateResponse]
	listRollouts     *connect.Client[v1.ListRolloutsRequest, v1.ListRolloutsResponse]
}

// ProvisionDevice calls agriculture.device.v1.DeviceService.ProvisionDevice.
func (c *deviceServiceClient) ProvisionDevice(ctx context.Context, req *connect.Request[v1.ProvisionDeviceRequest]) (*connect.Response[v1.ProvisionDeviceResponse], error) {
	return c.provisionDevice.CallUnary(ctx, req)
}

// GetDevice calls agriculture.device.v1.DeviceService.GetDevice.
func (c *deviceServiceClient) GetDevice(ctx context.Context, req *connect.Request[v1.GetDeviceRequest]) (*connect.Response[v1.GetDeviceResponse], error) {
	return c.getDevice.CallUnary(ctx, req)
}

// ListDevices calls agriculture.device.v1.DeviceService.ListDevices.
func (c *deviceServiceClient) ListDevices(ctx context.Context, req *connect.Request[v1.ListDevicesRequest]) (*connect.Response[v1.ListDevicesResponse], error) {
	return c.listDevices.CallUnary(ctx, req)
}

// RecordHeartbeats calls agriculture.device.v1.DeviceService.RecordHeartbeats.
func (c *deviceServiceClient) RecordHeartbeats(ctx context.Context, req *connect.Request[v1.RecordHeartbeatsRequest]) (*connect.Response[v1.RecordHeartbeatsResponse], error) {
	return c.recordHeartbeats.CallUnary(ctx, req)
}

// RetireDevice calls agriculture.device.v1.DeviceService.RetireDevice.
func (c *deviceServiceClient) RetireDevice(ctx context.Context, req *connect.Request[v1.RetireDeviceRequest]) (*connect.Response[v1.RetireDeviceResponse], error) {
	return c.retireDevice.CallUnary(ctx, req)
}

// GetFleetHealth calls agriculture.device.v1.DeviceService.GetFleetHealth.
func (c *deviceServiceClient) GetFleetHealth(ctx context.Context, req *connect.Request[v1.GetFleetHealthRequest]) (*connect.Response[v1.GetFleetHealthResponse], error) {
	return c.getFleetHealth.CallUnary(ctx, req)
}

// CreateRollout calls agriculture.device.v1.DeviceService.CreateRollout.
func (c *deviceServiceClient) CreateRollout(ctx context.Context, req *connect.Request[v1.CreateRolloutRequest]) (*connect.Response[v1.CreateRolloutResponse], error) {
	return c.createRollout.CallUnary(ctx, req)
}

// AdvanceRollout calls agriculture.device.v1.DeviceService.AdvanceRollout.
func (c *deviceServiceClient) AdvanceRollout(ctx context.Context, req *connect.Request[v1.AdvanceRolloutRequest]) (*connect.Response[v1.AdvanceRolloutResponse], error) {
	return c.advanceRollout.CallUnary(ctx, req)
}

// ReportUpdate calls agriculture.device.v1.DeviceService.ReportUpdate.
func (c *deviceServiceClient) ReportUpdate(ctx context.Context, req *connect.Request[v1.ReportUpdateRequest]) (*connect.Response[v1.ReportUpdateResponse], error) {
	return c.reportUpdate.CallUnary(ctx, req)
}

// ListRollouts calls agriculture.device.v1.DeviceService.ListRollouts.
func (c *deviceServiceClient) ListRollouts(ctx context.Context, req *connect.Request[v1.ListRolloutsRequest]) (*connect.Response[v1.ListRolloutsResponse], error) {
	return c.listRollouts.CallUnary(ctx, req)
}

// DeviceServiceHandler is an implementation of the agriculture.device.v1.DeviceService service.
type DeviceServiceHandler interface {
	ProvisionDevice(context.Context, *connect.Request[v1.ProvisionDeviceRequest]) (*connect.Response[v1.ProvisionDeviceResponse], error)
	GetDevice(context.Context, *connect.Request[v1.GetDeviceRequest]) (*connect.Response[v1.GetDeviceResponse], error)
	ListDevices(context.Context, *connect.Request[v1.ListDevicesRequest]) (*connect.Response[v1.ListDevicesResponse], error)
	RecordHeartbeats(context.Context, *connect.Request[v1.RecordHeartbeatsRequest]) (*connect.Response[v1.RecordHeartbeatsResponse], error)
	RetireDevice(context.Context, *connect.Request[v1.RetireDeviceRequest]) (*connect.Response[v1.RetireDeviceResponse], error)
	GetFleetHealth(context.Context, *connect.Request[v1.GetFleetHealthRequest]) (*connect.Response[v1.GetFleetHealthResponse], error)
	CreateRollout(context.Context, *connect.Request[v1.CreateRolloutRequest]) (*connect.Response[v1.CreateRolloutResponse], error)
	AdvanceRollout(context.Context, *connect.Request[v1.AdvanceRolloutRequest]) (*connect.Response[v1.AdvanceRolloutResponse], error)
	ReportUpdate(context.Context, *connect.Request[v1.ReportUpdateRequest]) (*connect.Response[v1.ReportUpdateResponse], error)
	ListRollouts(context.Context, *connect.Request[v1.ListRolloutsRequest]) (*connect.Response[v1.ListRolloutsResponse], error)
}

// NewDeviceServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDeviceServiceHandler(svc DeviceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	deviceServiceMethods := v1.File_device_proto.Services().ByName("DeviceService").Methods()
	deviceServiceProvisionDeviceHandler := connect.NewUnaryHandler(
		DeviceServiceProvisionDeviceProcedure,
		svc.ProvisionDevice,
		connect.WithSchema(deviceServiceMethods.ByName("ProvisionDevice")),
		connect.WithHandlerOptions(opts...),
	)
	deviceServiceGetDeviceHandler := connect.NewUnaryHandler(
		DeviceServiceGetDeviceProcedure,
		svc.GetDevice,
		connect.WithSchema(deviceServiceMethods.ByName("GetDevice")),
		connect.WithHandlerOptions(opts...),
	)
	deviceServiceListDevicesHandler := connect.NewUnaryHandler(
		DeviceServiceListDevicesProcedure,
		svc.ListDevices,
		connect.WithSchema(deviceServiceMethods.ByName("ListDevices")),
		connect.WithHandlerOptions(opts...),
	)
	deviceServiceRecordHeartbeatsHandler := connect.NewUnaryHandler(
		DeviceServiceRecordHeartbeatsProcedure,
		svc.RecordHeartbeats,
		connect.WithSchema(deviceServiceMethods.ByName("RecordHeartbeats")),
		connect.WithHandlerOptions(opts...),
	)
	deviceServiceRetireDeviceHandler := connect.NewUnaryHandler(
		DeviceServiceRetireDeviceProcedure,
		svc.RetireDevice,
		connect.WithSchema(deviceServiceMethods.ByName("RetireDevice")),
		connect.WithHandlerOptions(opts...),
	)
	deviceServiceGetFleetHealthHandler := connect.NewUnaryHandler(
		DeviceServiceGetFleetHealthProcedure,
		svc.GetFleetHealth,
		connect.WithSchema(deviceServiceMethods.ByName("GetFleetHealth")),
		connect.WithHandlerOptions(opts...),
	)
	deviceServiceCreateRolloutHandler := connect.NewUnaryHandler(
		DeviceServiceCreateRolloutProcedure,
		svc.CreateRollout,
		connect.WithSchema(deviceServiceMethods.ByName("CreateRollout")),
		connect.WithHandlerOptions(opts...),
	)
	deviceServiceAdvanceRolloutHandler := connect.NewUnaryHandler(
		DeviceServiceAdvanceRolloutProcedure,
		svc.AdvanceRollout,
		connect.WithSchema(deviceServiceMethods.ByName("AdvanceRollout")),
		connect.WithHandlerOptions(opts...),
	)
	deviceServiceReportUpdateHandler := connect.NewUnaryHandler(
		DeviceServiceReportUpdateProcedure,
		svc.ReportUpdate,
		connect.WithSchema(deviceServiceMethods.ByName("ReportUpdate")),
		connect.WithHandlerOptions(opts...),
	)
	deviceServiceListRolloutsHandler := connect.NewUnaryHandler(
		DeviceServiceListRolloutsProcedure,
		svc.ListRollouts,
		connect.WithSchema(deviceServiceMethods.ByName("ListRollouts")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agriculture.device.v1.DeviceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DeviceServiceProvisionDeviceProcedure:
			deviceServiceProvisionDeviceHandler.ServeHTTP(w, r)
		case DeviceServiceGetDeviceProcedure:
			deviceServiceGetDeviceHandler.ServeHTTP(w, r)
		case DeviceServiceListDevicesProcedure:
			deviceServiceListDevicesHandler.ServeHTTP(w, r)
		case DeviceServiceRecordHeartbeatsProcedure:
			deviceServiceRecordHeartbeatsHandler.ServeHTTP(w, r)
		case DeviceServiceRetireDeviceProcedure:
			deviceServiceRetireDeviceHandler.ServeHTTP(w, r)
		case DeviceServiceGetFleetHealthProcedure:
			deviceServiceGetFleetHealthHandler.ServeHTTP(w, r)
		case DeviceServiceCreateRolloutProcedure:
			deviceServiceCreateRolloutHandler.ServeHTTP(w, r)
		case DeviceServiceAdvanceRolloutProcedure:
			deviceServiceAdvanceRolloutHandler.ServeHTTP(w, r)
		case DeviceServiceReportUpdateProcedure:
			deviceServiceReportUpdateHandler.ServeHTTP(w, r)
		case DeviceServiceListRolloutsProcedure:
			deviceServiceListRolloutsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDeviceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDeviceServiceHandler struct{}

func (UnimplementedDeviceServiceHandler) ProvisionDevice(context.Context, *connect.Request[v1.ProvisionDeviceRequest]) (*connect.Response[v1.ProvisionDeviceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.device.v1.DeviceService.ProvisionDevice is not implemented"))
}

func (UnimplementedDeviceServiceHandler) GetDevice(context.Context, *connect.Request[v1.GetDeviceRequest]) (*connect.Response[v1.GetDeviceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.device.v1.DeviceService.GetDevice is not implemented"))
}

func (UnimplementedDeviceServiceHandler) ListDevices(context.Context, *connect.Request[v1.ListDevicesRequest]) (*connect.Response[v1.ListDevicesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.device.v1.DeviceService.ListDevices is not implemented"))
}

func (UnimplementedDeviceServiceHandler) RecordHeartbeats(context.Context, *connect.Request[v1.RecordHeartbeatsRequest]) (*connect.Response[v1.RecordHeartbeatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.device.v1.DeviceService.RecordHeartbeats is not implemented"))
}

func (UnimplementedDeviceServiceHandler) RetireDevice(context.Context, *connect.Request[v1.RetireDeviceRequest]) (*connect.Response[v1.RetireDeviceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.device.v1.DeviceService.RetireDevice is not implemented"))
}

func (UnimplementedDeviceServiceHandler) GetFleetHealth(context.Context, *connect.Request[v1.GetFleetHealthRequest]) (*connect.Response[v1.GetFleetHealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.device.v1.DeviceService.GetFleetHealth is not implemented"))
}

func (UnimplementedDeviceServiceHandler) CreateRollout(context.Context, *connect.Request[v1.CreateRolloutRequest]) (*connect.Response[v1.CreateRolloutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.device.v1.DeviceService.CreateRollout is not implemented"))
}

func (UnimplementedDeviceServiceHandler) AdvanceRollout(context.Context, *connect.Request[v1.AdvanceRolloutRequest]) (*connect.Response[v1.AdvanceRolloutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.device.v1.DeviceService.AdvanceRollout is not implemented"))
}

func (UnimplementedDeviceServiceHandler) ReportUpdate(context.Context, *connect.Request[v1.ReportUpdateRequest]) (*connect.Response[v1.ReportUpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.device.v1.DeviceService.ReportUpdate is not implemented"))
}

func (UnimplementedDeviceServiceHandler) ListRollouts(context.Context, *connect.Request[v1.ListRolloutsRequest]) (*connect.Response[v1.ListRolloutsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.device.v1.DeviceService.ListRollouts is not implemented"))
}
