// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: traceability.proto

package traceabilityv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "p9e.in/samavaya/agriculture/traceability-service/api/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TraceabilityServiceName is the fully-qualified name of the TraceabilityService service.
	TraceabilityServiceName = "agriculture.traceability.v1.TraceabilityService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TraceabilityServiceCreateRecordProcedure is the fully-qualified name of the TraceabilityService's
	// CreateRecord RPC.
	TraceabilityServiceCreateRecordProcedure = "/agriculture.traceability.v1.TraceabilityService/CreateRecord"
	// TraceabilityServiceGetRecordProcedure is the fully-qualified name of the TraceabilityService's
	// GetRecord RPC.
	TraceabilityServiceGetRecordProcedure = "/agriculture.traceability.v1.TraceabilityService/GetRecord"
	// TraceabilityServiceListRecordsProcedure is the fully-qualified name of the TraceabilityService's
	// ListRecords RPC.
	TraceabilityServiceListRecordsProcedure = "/agriculture.traceability.v1.TraceabilityService/ListRecords"
	// TraceabilityServiceAddSupplyChainEventProcedure is the fully-qualified name of the
	// TraceabilityService's AddSupplyChainEvent RPC.
	TraceabilityServiceAddSupplyChainEventProcedure = "/agriculture.traceability.v1.TraceabilityService/AddSupplyChainEvent"
	// TraceabilityServiceGetSupplyChainProcedure is the fully-qualified name of the
	// TraceabilityService's GetSupplyChain RPC.
	TraceabilityServiceGetSupplyChainProcedure = "/agriculture.traceability.v1.TraceabilityService/GetSupplyChain"
	// TraceabilityServiceCreateCertificationProcedure is the fully-qualified name of the
	// TraceabilityService's CreateCertification RPC.
	TraceabilityServiceCreateCertificationProcedure = "/agriculture.traceability.v1.TraceabilityService/CreateCertification"
	// TraceabilityServiceGetCertificationProcedure is the fully-qualified name of the
	// TraceabilityService's GetCertification RPC.
	TraceabilityServiceGetCertificationProcedure = "/agriculture.traceability.v1.TraceabilityService/GetCertification"
	// TraceabilityServiceListCertificationsProcedure is the fully-qualified name of the
	// TraceabilityService's ListCertifications RPC.
	TraceabilityServiceListCertificationsProcedure = "/agriculture.traceability.v1.TraceabilityService/ListCertifications"
	// TraceabilityServiceVerifyCertificationProcedure is the fully-qualified name of the
	// TraceabilityService's VerifyCertification RPC.
	TraceabilityServiceVerifyCertificationProcedure = "/agriculture.traceability.v1.TraceabilityService/VerifyCertification"
	// TraceabilityServiceCreateBatchProcedure is the fully-qualified name of the TraceabilityService's
	// CreateBatch RPC.
	TraceabilityServiceCreateBatchProcedure = "/agriculture.traceability.v1.TraceabilityService/CreateBatch"
	// TraceabilityServiceGetBatchProcedure is the fully-qualified name of the TraceabilityService's
	// GetBatch RPC.
	TraceabilityServiceGetBatchProcedure = "/agriculture.traceability.v1.TraceabilityService/GetBatch"
	// TraceabilityServiceListBatchesProcedure is the fully-qualified name of the TraceabilityService's
	// ListBatches RPC.
	TraceabilityServiceListBatchesProcedure = "/agriculture.traceability.v1.TraceabilityService/ListBatches"
	// TraceabilityServiceGenerateQRCodeProcedure is the fully-qualified name of the
	// TraceabilityService's GenerateQRCode RPC.
	TraceabilityServiceGenerateQRCodeProcedure = "/agriculture.traceability.v1.TraceabilityService/GenerateQRCode"
	// TraceabilityServiceVerifyQRCodeProcedure is the fully-qualified name of the TraceabilityService's
	// VerifyQRCode RPC.
	TraceabilityServiceVerifyQRCodeProcedure = "/agriculture.traceability.v1.TraceabilityService/VerifyQRCode"
	// TraceabilityServiceGenerateComplianceReportProcedure is the fully-qualified name of the
	// TraceabilityService's GenerateComplianceReport RPC.
	TraceabilityServiceGenerateComplianceReportProcedure = "/agriculture.traceability.v1.TraceabilityService/GenerateComplianceReport"
	// TraceabilityServiceCreateQualityCheckpointProcedure is the fully-qualified name of the
	// TraceabilityService's CreateQualityCheckpoint RPC.
	TraceabilityServiceCreateQualityCheckpointProcedure = "/agriculture.traceability.v1.TraceabilityService/CreateQualityCheckpoint"
	// TraceabilityServiceGetQualityCheckpointProcedure is the fully-qualified name of the
	// TraceabilityService's GetQualityCheckpoint RPC.
	TraceabilityServiceGetQualityCheckpointProcedure = "/agriculture.traceability.v1.TraceabilityService/GetQualityCheckpoint"
	// TraceabilityServiceListQualityCheckpointsProcedure is the fully-qualified name of the
	// TraceabilityService's ListQualityCheckpoints RPC.
	TraceabilityServiceListQualityCheckpointsProcedure = "/agriculture.traceability.v1.TraceabilityService/ListQualityCheckpoints"
	// TraceabilityServiceUpdateRecordProcedure is the fully-qualified name of the TraceabilityService's
	// UpdateRecord RPC.
	TraceabilityServiceUpdateRecordProcedure = "/agriculture.traceability.v1.TraceabilityService/UpdateRecord"
	// TraceabilityServiceRevokeCertificationProcedure is the fully-qualified name of the
	// TraceabilityService's RevokeCertification RPC.
	TraceabilityServiceRevokeCertificationProcedure = "/agriculture.traceability.v1.TraceabilityService/RevokeCertification"
	// TraceabilityServiceGetComplianceReportProcedure is the fully-qualified name of the
	// TraceabilityService's GetComplianceReport RPC.
	TraceabilityServiceGetComplianceReportProcedure = "/agriculture.traceability.v1.TraceabilityService/GetComplianceReport"
	// TraceabilityServiceListComplianceReportsProcedure is the fully-qualified name of the
	// TraceabilityService's ListComplianceReports RPC.
	TraceabilityServiceListComplianceReportsProcedure = "/agriculture.traceability.v1.TraceabilityService/ListComplianceReports"
)

// TraceabilityServiceClient is a client for the agriculture.traceability.v1.TraceabilityService
// service.
type TraceabilityServiceClient interface {
	// CreateRecord creates a new traceability record.
	CreateRecord(context.Context, *connect.Request[v1.CreateRecordRequest]) (*connect.Response[v1.CreateRecordResponse], error)
	// GetRecord retrieves a traceability record by ID.
	GetRecord(context.Context, *connect.Request[v1.GetRecordRequest]) (*connect.Response[v1.GetRecordResponse], error)
	// ListRecords lists traceability records with filtering and pagination.
	ListRecords(context.Context, *connect.Request[v1.ListRecordsRequest]) (*connect.Response[v1.ListRecordsResponse], error)
	// AddSupplyChainEvent adds a new event to the supply chain.
	AddSupplyChainEvent(context.Context, *connect.Request[v1.AddSupplyChainEventRequest]) (*connect.Response[v1.AddSupplyChainEventResponse], error)
	// GetSupplyChain retrieves the full supply chain for a record.
	GetSupplyChain(context.Context, *connect.Request[v1.GetSupplyChainRequest]) (*connect.Response[v1.GetSupplyChainResponse], error)
	// CreateCertification creates a new certification for a record.
	CreateCertification(context.Context, *connect.Request[v1.CreateCertificationRequest]) (*connect.Response[v1.CreateCertificationResponse], error)
	// GetCertification retrieves a certification by ID.
	GetCertification(context.Context, *connect.Request[v1.GetCertificationRequest]) (*connect.Response[v1.GetCertificationResponse], error)
	// ListCertifications lists certifications with filtering and pagination.
	ListCertifications(context.Context, *connect.Request[v1.ListCertificationsRequest]) (*connect.Response[v1.ListCertificationsResponse], error)
	// VerifyCertification verifies a certification.
	VerifyCertification(context.Context, *connect.Request[v1.VerifyCertificationRequest]) (*connect.Response[v1.VerifyCertificationResponse], error)
	// CreateBatch creates a new batch record.
	CreateBatch(context.Context, *connect.Request[v1.CreateBatchRequest]) (*connect.Response[v1.CreateBatchResponse], error)
	// GetBatch retrieves a batch record by ID.
	GetBatch(context.Context, *connect.Request[v1.GetBatchRequest]) (*connect.Response[v1.GetBatchResponse], error)
	// ListBatches lists batch records with filtering and pagination.
	ListBatches(context.Context, *connect.Request[v1.ListBatchesRequest]) (*connect.Response[v1.ListBatchesResponse], error)
	// GenerateQRCode generates a QR code for a record or batch.
	GenerateQRCode(context.Context, *connect.Request[v1.GenerateQRCodeRequest]) (*connect.Response[v1.GenerateQRCodeResponse], error)
	// VerifyQRCode verifies a QR code and returns the associated record.
	VerifyQRCode(context.Context, *connect.Request[v1.VerifyQRCodeRequest]) (*connect.Response[v1.VerifyQRCodeResponse], error)
	// GenerateComplianceReport generates a compliance report for a record.
	GenerateComplianceReport(context.Context, *connect.Request[v1.GenerateComplianceReportRequest]) (*connect.Response[v1.GenerateComplianceReportResponse], error)
	// Quality Checkpoints
	CreateQualityCheckpoint(context.Context, *connect.Request[v1.CreateQualityCheckpointRequest]) (*connect.Response[v1.CreateQualityCheckpointResponse], error)
	GetQualityCheckpoint(context.Context, *connect.Request[v1.GetQualityCheckpointRequest]) (*connect.Response[v1.GetQualityCheckpointResponse], error)
	ListQualityCheckpoints(context.Context, *connect.Request[v1.ListQualityCheckpointsRequest]) (*connect.Response[v1.ListQualityCheckpointsResponse], error)
	// Record updates
	UpdateRecord(context.Context, *connect.Request[v1.UpdateRecordRequest]) (*connect.Response[v1.UpdateRecordResponse], error)
	// Certification lifecycle
	RevokeCertification(context.Context, *connect.Request[v1.RevokeCertificationRequest]) (*connect.Response[v1.RevokeCertificationResponse], error)
	// Compliance report retrieval
	GetComplianceReport(context.Context, *connect.Request[v1.GetComplianceReportRequest]) (*connect.Response[v1.GetComplianceReportResponse], error)
	ListComplianceReports(context.Context, *connect.Request[v1.ListComplianceReportsRequest]) (*connect.Response[v1.ListComplianceReportsResponse], error)
}

// NewTraceabilityServiceClient constructs a client for the
// agriculture.traceability.v1.TraceabilityService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTraceabilityServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TraceabilityServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	traceabilityServiceMethods := v1.File_traceability_proto.Services().ByName("TraceabilityService").Methods()
	return &traceabilityServiceClient{
		createRecord: connect.NewClient[v1.CreateRecordRequest, v1.CreateRecordResponse](
			httpClient,
			baseURL+TraceabilityServiceCreateRecordProcedure,
			connect.WithSchema(traceabilityServiceMethods.ByName("CreateRecord")),
			connect.WithClientOptions(opts...),
		),
		getRecord: connect.NewClient[v1.GetRecordRequest, v1.GetRecordResponse](
			httpClient,
			baseURL+TraceabilityServiceGetRecordProcedure,
			connect.WithSchema(traceabilityServiceMethods.ByName("GetRecord")),
			connect.WithClientOptions(opts...),
		),
		listRecords: connect.NewClient[v1.ListRecordsRequest, v1.ListRecordsResponse](
			httpClient,
			baseURL+TraceabilityServiceListRecordsProcedure,
			connect.WithSchema(traceabilityServiceMethods.ByName("ListRecords")),
			connect.WithClientOptions(opts...),
		),
		addSupplyChainEvent: connect.NewClient[v1.AddSupplyChainEventRequest, v1.AddSupplyChainEventResponse](
			httpClient,
			baseURL+TraceabilityServiceAddSupplyChainEventProcedure,
			connect.WithSchema(traceabilityServiceMethods.ByName("AddSupplyChainEvent")),
			connect.WithClientOptions(opts...),
		),
		getSupplyChain: connect.NewClient[v1.GetSupplyChainRequest, v1.GetSupplyChainResponse](
			httpClient,
			baseURL+TraceabilityServiceGetSupplyChainProcedure,
			connect.WithSchema(traceabilityServiceMethods.ByName("GetSupplyChain")),
			connect.WithClientOptions(opts...),
		),
		createCertification: connect.NewClient[v1.CreateCertificationRequest, v1.CreateCertificationResponse](
			httpClient,
			baseURL+TraceabilityServiceCreateCertificationProcedure,
			connect.WithSchema(traceabilityServiceMethods.ByName("CreateCertification")),
			connect.WithClientOptions(opts...),
		),
		getCertification: connect.NewClient[v1.GetCertificationRequest, v1.GetCertificationResponse](
			httpClient,
			baseURL+TraceabilityServiceGetCertificationProcedure,
			connect.WithSchema(traceabilityServiceMethods.ByName("GetCertification")),
			connect.WithClientOptions(opts...),
		),
		listCertifications: connect.NewClient[v1.ListCertificationsRequest, v1.ListCertificationsResponse](
			httpClient,
			baseURL+TraceabilityServiceListCertificationsProcedure,
			connect.WithSchema(traceabilityServiceMethods.ByName("ListCertifications")),
			connect.WithClientOptions(opts...),
		),
		verifyCertification: connect.NewClient[v1.VerifyCertificationRequest, v1.VerifyCertificationResponse](
			httpClient,
			baseURL+TraceabilityServiceVerifyCertificationProcedure,
			connect.WithSchema(traceabilityServiceMethods.ByName("VerifyCertification")),
			connect.WithClientOptions(opts...),
		),
		createBatch: connect.NewClient[v1.CreateBatchRequest, v1.CreateBatchResponse](
			httpClient,
			baseURL+TraceabilityServiceCreateBatchProcedure,
			connect.WithSchema(traceabilityServiceMethods.ByName("CreateBatch")),
			connect.WithClientOptions(opts...),
		),
		getBatch: connect.NewClient[v1.GetBatchRequest, v1.GetBatchResponse](
			httpClient,
			baseURL+TraceabilityServiceGetBatchProcedure,
			connect.WithSchema(traceabilityServiceMethods.ByName("GetBatch")),
			connect.WithClientOptions(opts...),
		),
		listBatches: connect.NewClient[v1.ListBatchesRequest, v1.ListBatchesResponse](
			httpClient,
			baseURL+TraceabilityServiceListBatchesProcedure,
			connect.WithSchema(traceabilityServiceMethods.ByName("ListBatches")),
			connect.WithClientOptions(opts...),
		),
		generateQRCode: connect.NewClient[v1.GenerateQRCodeRequest, v1.GenerateQRCodeResponse](
			httpClient,
			baseURL+TraceabilityServiceGenerateQRCodeProcedure,
			connect.WithSchema(traceabilityServiceMethods.ByName("GenerateQRCode")),
			connect.WithClientOptions(opts...),
		),
		verifyQRCode: connect.NewClient[v1.VerifyQRCodeRequest, v1.VerifyQRCodeResponse](
			httpClient,
			baseURL+TraceabilityServiceVerifyQRCodeProcedure,
			connect.WithSchema(traceabilityServiceMethods.ByName("VerifyQRCode")),
			connect.WithClientOptions(opts...),
		),
		generateComplianceReport: connect.NewClient[v1.GenerateComplianceReportRequest, v1.GenerateComplianceReportResponse](
			httpClient,
			baseURL+TraceabilityServiceGenerateComplianceReportProcedure,
			connect.WithSchema(traceabilityServiceMethods.ByName("GenerateComplianceReport")),
			connect.WithClientOptions(opts...),
		),
		createQualityCheckpoint: connect.NewClient[v1.CreateQualityCheckpointRequest, v1.CreateQualityCheckpointResponse](
			httpClient,
			baseURL+TraceabilityServiceCreateQualityCheckpointProcedure,
			connect.WithSchema(traceabilityServiceMethods.ByName("CreateQualityCheckpoint")),
			connect.WithClientOptions(opts...),
		),
		getQualityCheckpoint: connect.NewClient[v1.GetQualityCheckpointRequest, v1.GetQualityCheckpointResponse](
			httpClient,
			baseURL+TraceabilityServiceGetQualityCheckpointProcedure,
			connect.WithSchema(traceabilityServiceMethods.ByName("GetQualityCheckpoint")),
			connect.WithClientOptions(opts...),
		),
		listQualityCheckpoints: connect.NewClient[v1.ListQualityCheckpointsRequest, v1.ListQualityCheckpointsResponse](
			httpClient,
			baseURL+TraceabilityServiceListQualityCheckpointsProcedure,
			connect.WithSchema(traceabilityServiceMethods.ByName("ListQualityCheckpoints")),
			connect.WithClientOptions(opts...),
		),
		updateRecord: connect.NewClient[v1.UpdateRecordRequest, v1.UpdateRecordResponse](
			httpClient,
			baseURL+TraceabilityServiceUpdateRecordProcedure,
			connect.WithSchema(traceabilityServiceMethods.ByName("UpdateRecord")),
			connect.WithClientOptions(opts...),
		),
		revokeCertification: connect.NewClient[v1.RevokeCertificationRequest, v1.RevokeCertificationResponse](
			httpClient,
			baseURL+TraceabilityServiceRevokeCertificationProcedure,
			connect.WithSchema(traceabilityServiceMethods.ByName("RevokeCertification")),
			connect.WithClientOptions(opts...),
		),
		getComplianceReport: connect.NewClient[v1.GetComplianceReportRequest, v1.GetComplianceReportResponse](
			httpClient,
			baseURL+TraceabilityServiceGetComplianceReportProcedure,
			connect.WithSchema(traceabilityServiceMethods.ByName("GetComplianceReport")),
			connect.WithClientOptions(opts...),
		),
		listComplianceReports: connect.NewClient[v1.ListComplianceReportsRequest, v1.ListComplianceReportsResponse](
			httpClient,
			baseURL+TraceabilityServiceListComplianceReportsProcedure,
			connect.WithSchema(traceabilityServiceMethods.ByName("ListComplianceReports")),
			connect.WithClientOptions(opts...),
		),
	}
}

// traceabilityServiceClient implements TraceabilityServiceClient.
type traceabilityServiceClient struct {
	createRecord             *connect.Client[v1.CreateRecordRequest, v1.CreateRecordResponse]
	getRecord                *connect.Client[v1.GetRecordRequest, v1.GetRecordResponse]
	listRecords              *connect.Client[v1.ListRecordsRequest, v1.ListRecordsResponse]
	addSupplyChainEvent      *connect.Client[v1.AddSupplyChainEventRequest, v1.AddSupplyChainEventResponse]
	getSupplyChain           *connect.Client[v1.GetSupplyChainRequest, v1.GetSupplyChainResponse]
	createCertification      *connect.Client[v1.CreateCertificationRequest, v1.CreateCertificationResponse]
	getCertification         *connect.Client[v1.GetCertificationRequest, v1.GetCertificationResponse]
	listCertifications       *connect.Client[v1.ListCertificationsRequest, v1.ListCertificationsResponse]
	verifyCertification      *connect.Client[v1.VerifyCertificationRequest, v1.VerifyCertificationResponse]
	createBatch              *connect.Client[v1.CreateBatchRequest, v1.CreateBatchResponse]
	getBatch                 *connect.Client[v1.GetBatchRequest, v1.GetBatchResponse]
	listBatches              *connect.Client[v1.ListBatchesRequest, v1.ListBatchesResponse]
	generateQRCode           *connect.Client[v1.GenerateQRCodeRequest, v1.GenerateQRCodeResponse]
	verifyQRCode             *connect.Client[v1.VerifyQRCodeRequest, v1.VerifyQRCodeResponse]
	generateComplianceReport *connect.Client[v1.GenerateComplianceReportRequest, v1.GenerateComplianceReportResponse]
	createQualityCheckpoint  *connect.Client[v1.CreateQualityCheckpointRequest, v1.CreateQualityCheckpointResponse]
	getQualityCheckpoint     *connect.Client[v1.GetQualityCheckpointRequest, v1.GetQualityCheckpointResponse]
	listQualityCheckpoints   *connect.Client[v1.ListQualityCheckpointsRequest, v1.ListQualityCheckpointsResponse]
	updateRecord             *connect.Client[v1.UpdateRecordRequest, v1.UpdateRecordResponse]
	revokeCertification      *connect.Client[v1.RevokeCertificationRequest, v1.RevokeCertificationResponse]
	getComplianceReport      *connect.Client[v1.GetComplianceReportRequest, v1.GetComplianceReportResponse]
	listComplianceReports    *connect.Client[v1.ListComplianceReportsRequest, v1.ListComplianceReportsResponse]
}

// CreateRecord calls agriculture.traceability.v1.TraceabilityService.CreateRecord.
func (c *traceabilityServiceClient) CreateRecord(ctx context.Context, req *connect.Request[v1.CreateRecordRequest]) (*connect.Response[v1.CreateRecordResponse], error) {
	return c.createRecord.CallUnary(ctx, req)
}

// GetRecord calls agriculture.traceability.v1.TraceabilityService.GetRecord.
func (c *traceabilityServiceClient) GetRecord(ctx context.Context, req *connect.Request[v1.GetRecordRequest]) (*connect.Response[v1.GetRecordResponse], error) {
	return c.getRecord.CallUnary(ctx, req)
}

// ListRecords calls agriculture.traceability.v1.TraceabilityService.ListRecords.
func (c *traceabilityServiceClient) ListRecords(ctx context.Context, req *connect.Request[v1.ListRecordsRequest]) (*connect.Response[v1.ListRecordsResponse], error) {
	return c.listRecords.CallUnary(ctx, req)
}

// AddSupplyChainEvent calls agriculture.traceability.v1.TraceabilityService.AddSupplyChainEvent.
func (c *traceabilityServiceClient) AddSupplyChainEvent(ctx context.Context, req *connect.Request[v1.AddSupplyChainEventRequest]) (*connect.Response[v1.AddSupplyChainEventResponse], error) {
	return c.addSupplyChainEvent.CallUnary(ctx, req)
}

// GetSupplyChain calls agriculture.traceability.v1.TraceabilityService.GetSupplyChain.
func (c *traceabilityServiceClient) GetSupplyChain(ctx context.Context, req *connect.Request[v1.GetSupplyChainRequest]) (*connect.Response[v1.GetSupplyChainResponse], error) {
	return c.getSupplyChain.CallUnary(ctx, req)
}

// CreateCertification calls agriculture.traceability.v1.TraceabilityService.CreateCertification.
func (c *traceabilityServiceClient) CreateCertification(ctx context.Context, req *connect.Request[v1.CreateCertificationRequest]) (*connect.Response[v1.CreateCertificationResponse], error) {
	return c.createCertification.CallUnary(ctx, req)
}

// GetCertification calls agriculture.traceability.v1.TraceabilityService.GetCertification.
func (c *traceabilityServiceClient) GetCertification(ctx context.Context, req *connect.Request[v1.GetCertificationRequest]) (*connect.Response[v1.GetCertificationResponse], error) {
	return c.getCertification.CallUnary(ctx, req)
}

// ListCertifications calls agriculture.traceability.v1.TraceabilityService.ListCertifications.
func (c *traceabilityServiceClient) ListCertifications(ctx context.Context, req *connect.Request[v1.ListCertificationsRequest]) (*connect.Response[v1.ListCertificationsResponse], error) {
	return c.listCertifications.CallUnary(ctx, req)
}

// VerifyCertification calls agriculture.traceability.v1.TraceabilityService.VerifyCertification.
func (c *traceabilityServiceClient) VerifyCertification(ctx context.Context, req *connect.Request[v1.VerifyCertificationRequest]) (*connect.Response[v1.VerifyCertificationResponse], error) {
	return c.verifyCertification.CallUnary(ctx, req)
}

// CreateBatch calls agriculture.traceability.v1.TraceabilityService.CreateBatch.
func (c *traceabilityServiceClient) CreateBatch(ctx context.Context, req *connect.Request[v1.CreateBatchRequest]) (*connect.Response[v1.CreateBatchResponse], error) {
	return c.createBatch.CallUnary(ctx, req)
}

// GetBatch calls agriculture.traceability.v1.TraceabilityService.GetBatch.
func (c *traceabilityServiceClient) GetBatch(ctx context.Context, req *connect.Request[v1.GetBatchRequest]) (*connect.Response[v1.GetBatchResponse], error) {
	return c.getBatch.CallUnary(ctx, req)
}

// ListBatches calls agriculture.traceability.v1.TraceabilityService.ListBatches.
func (c *traceabilityServiceClient) ListBatches(ctx context.Context, req *connect.Request[v1.ListBatchesRequest]) (*connect.Response[v1.ListBatchesResponse], error) {
	return c.listBatches.CallUnary(ctx, req)
}

// GenerateQRCode calls agriculture.traceability.v1.TraceabilityService.GenerateQRCode.
func (c *traceabilityServiceClient) GenerateQRCode(ctx context.Context, req *connect.Request[v1.GenerateQRCodeRequest]) (*connect.Response[v1.GenerateQRCodeResponse], error) {
	return c.generateQRCode.CallUnary(ctx, req)
}

// VerifyQRCode calls agriculture.traceability.v1.TraceabilityService.VerifyQRCode.
func (c *traceabilityServiceClient) VerifyQRCode(ctx context.Context, req *connect.Request[v1.VerifyQRCodeRequest]) (*connect.Response[v1.VerifyQRCodeResponse], error) {
	return c.verifyQRCode.CallUnary(ctx, req)
}

// GenerateComplianceReport calls
// agriculture.traceability.v1.TraceabilityService.GenerateComplianceReport.
func (c *traceabilityServiceClient) GenerateComplianceReport(ctx context.Context, req *connect.Request[v1.GenerateComplianceReportRequest]) (*connect.Response[v1.GenerateComplianceReportResponse], error) {
	return c.generateComplianceReport.CallUnary(ctx, req)
}

// CreateQualityCheckpoint calls
// agriculture.traceability.v1.TraceabilityService.CreateQualityCheckpoint.
func (c *traceabilityServiceClient) CreateQualityCheckpoint(ctx context.Context, req *connect.Request[v1.CreateQualityCheckpointRequest]) (*connect.Response[v1.CreateQualityCheckpointResponse], error) {
	return c.createQualityCheckpoint.CallUnary(ctx, req)
}

// GetQualityCheckpoint calls agriculture.traceability.v1.TraceabilityService.GetQualityCheckpoint.
func (c *traceabilityServiceClient) GetQualityCheckpoint(ctx context.Context, req *connect.Request[v1.GetQualityCheckpointRequest]) (*connect.Response[v1.GetQualityCheckpointResponse], error) {
	return c.getQualityCheckpoint.CallUnary(ctx, req)
}

// ListQualityCheckpoints calls
// agriculture.traceability.v1.TraceabilityService.ListQualityCheckpoints.
func (c *traceabilityServiceClient) ListQualityCheckpoints(ctx context.Context, req *connect.Request[v1.ListQualityCheckpointsRequest]) (*connect.Response[v1.ListQualityCheckpointsResponse], error) {
	return c.listQualityCheckpoints.CallUnary(ctx, req)
}

// UpdateRecord calls agriculture.traceability.v1.TraceabilityService.UpdateRecord.
func (c *traceabilityServiceClient) UpdateRecord(ctx context.Context, req *connect.Request[v1.UpdateRecordRequest]) (*connect.Response[v1.UpdateRecordResponse], error) {
	return c.updateRecord.CallUnary(ctx, req)
}

// RevokeCertification calls agriculture.traceability.v1.TraceabilityService.RevokeCertification.
func (c *traceabilityServiceClient) RevokeCertification(ctx context.Context, req *connect.Request[v1.RevokeCertificationRequest]) (*connect.Response[v1.RevokeCertificationResponse], error) {
	return c.revokeCertification.CallUnary(ctx, req)
}

// GetComplianceReport calls agriculture.traceability.v1.TraceabilityService.GetComplianceReport.
func (c *traceabilityServiceClient) GetComplianceReport(ctx context.Context, req *connect.Request[v1.GetComplianceReportRequest]) (*connect.Response[v1.GetComplianceReportResponse], error) {
	return c.getComplianceReport.CallUnary(ctx, req)
}

// ListComplianceReports calls
// agriculture.traceability.v1.TraceabilityService.ListComplianceReports.
func (c *traceabilityServiceClient) ListComplianceReports(ctx context.Context, req *connect.Request[v1.ListComplianceReportsRequest]) (*connect.Response[v1.ListComplianceReportsResponse], error) {
	return c.listComplianceReports.CallUnary(ctx, req)
}

// TraceabilityServiceHandler is an implementation of the
// agriculture.traceability.v1.TraceabilityService service.
type TraceabilityServiceHandler interface {
	// CreateRecord creates a new traceability record.
	CreateRecord(context.Context, *connect.Request[v1.CreateRecordRequest]) (*connect.Response[v1.CreateRecordResponse], error)
	// GetRecord retrieves a traceability record by ID.
	GetRecord(context.Context, *connect.Request[v1.GetRecordRequest]) (*connect.Response[v1.GetRecordResponse], error)
	// ListRecords lists traceability records with filtering and pagination.
	ListRecords(context.Context, *connect.Request[v1.ListRecordsRequest]) (*connect.Response[v1.ListRecordsResponse], error)
	// AddSupplyChainEvent adds a new event to the supply chain.
	AddSupplyChainEvent(context.Context, *connect.Request[v1.AddSupplyChainEventRequest]) (*connect.Response[v1.AddSupplyChainEventResponse], error)
	// GetSupplyChain retrieves the full supply chain for a record.
	GetSupplyChain(context.Context, *connect.Request[v1.GetSupplyChainRequest]) (*connect.Response[v1.GetSupplyChainResponse], error)
	// CreateCertification creates a new certification for a record.
	CreateCertification(context.Context, *connect.Request[v1.CreateCertificationRequest]) (*connect.Response[v1.CreateCertificationResponse], error)
	// GetCertification retrieves a certification by ID.
	GetCertification(context.Context, *connect.Request[v1.GetCertificationRequest]) (*connect.Response[v1.GetCertificationResponse], error)
	// ListCertifications lists certifications with filtering and pagination.
	ListCertifications(context.Context, *connect.Request[v1.ListCertificationsRequest]) (*connect.Response[v1.ListCertificationsResponse], error)
	// VerifyCertification verifies a certification.
	VerifyCertification(context.Context, *connect.Request[v1.VerifyCertificationRequest]) (*connect.Response[v1.VerifyCertificationResponse], error)
	// CreateBatch creates a new batch record.
	CreateBatch(context.Context, *connect.Request[v1.CreateBatchRequest]) (*connect.Response[v1.CreateBatchResponse], error)
	// GetBatch retrieves a batch record by ID.
	GetBatch(context.Context, *connect.Request[v1.GetBatchRequest]) (*connect.Response[v1.GetBatchResponse], error)
	// ListBatches lists batch records with filtering and pagination.
	ListBatches(context.Context, *connect.Request[v1.ListBatchesRequest]) (*connect.Response[v1.ListBatchesResponse], error)
	// GenerateQRCode generates a QR code for a record or batch.
	GenerateQRCode(context.Context, *connect.Request[v1.GenerateQRCodeRequest]) (*connect.Response[v1.GenerateQRCodeResponse], error)
	// VerifyQRCode verifies a QR code and returns the associated record.
	VerifyQRCode(context.Context, *connect.Request[v1.VerifyQRCodeRequest]) (*connect.Response[v1.VerifyQRCodeResponse], error)
	// GenerateComplianceReport generates a compliance report for a record.
	GenerateComplianceReport(context.Context, *connect.Request[v1.GenerateComplianceReportRequest]) (*connect.Response[v1.GenerateComplianceReportResponse], error)
	// Quality Checkpoints
	CreateQualityCheckpoint(context.Context, *connect.Request[v1.CreateQualityCheckpointRequest]) (*connect.Response[v1.CreateQualityCheckpointResponse], error)
	GetQualityCheckpoint(context.Context, *connect.Request[v1.GetQualityCheckpointRequest]) (*connect.Response[v1.GetQualityCheckpointResponse], error)
	ListQualityCheckpoints(context.Context, *connect.Request[v1.ListQualityCheckpointsRequest]) (*connect.Response[v1.ListQualityCheckpointsResponse], error)
	// Record updates
	UpdateRecord(context.Context, *connect.Request[v1.UpdateRecordRequest]) (*connect.Response[v1.UpdateRecordResponse], error)
	// Certification lifecycle
	RevokeCertification(context.Context, *connect.Request[v1.RevokeCertificationRequest]) (*connect.Response[v1.RevokeCertificationResponse], error)
	// Compliance report retrieval
	GetComplianceReport(context.Context, *connect.Request[v1.GetComplianceReportRequest]) (*connect.Response[v1.GetComplianceReportResponse], error)
	ListComplianceReports(context.Context, *connect.Request[v1.ListComplianceReportsRequest]) (*connect.Response[v1.ListComplianceReportsResponse], error)
}

// NewTraceabilityServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTraceabilityServiceHandler(svc TraceabilityServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	traceabilityServiceMethods := v1.File_traceability_proto.Services().ByName("TraceabilityService").Methods()
	traceabilityServiceCreateRecordHandler := connect.NewUnaryHandler(
		TraceabilityServiceCreateRecordProcedure,
		svc.CreateRecord,
		connect.WithSchema(traceabilityServiceMethods.ByName("CreateRecord")),
		connect.WithHandlerOptions(opts...),
	)
	traceabilityServiceGetRecordHandler := connect.NewUnaryHandler(
		TraceabilityServiceGetRecordProcedure,
		svc.GetRecord,
		connect.WithSchema(traceabilityServiceMethods.ByName("GetRecord")),
		connect.WithHandlerOptions(opts...),
	)
	traceabilityServiceListRecordsHandler := connect.NewUnaryHandler(
		TraceabilityServiceListRecordsProcedure,
		svc.ListRecords,
		connect.WithSchema(traceabilityServiceMethods.ByName("ListRecords")),
		connect.WithHandlerOptions(opts...),
	)
	traceabilityServiceAddSupplyChainEventHandler := connect.NewUnaryHandler(
		TraceabilityServiceAddSupplyChainEventProcedure,
		svc.AddSupplyChainEvent,
		connect.WithSchema(traceabilityServiceMethods.ByName("AddSupplyChainEvent")),
		connect.WithHandlerOptions(opts...),
	)
	traceabilityServiceGetSupplyChainHandler := connect.NewUnaryHandler(
		TraceabilityServiceGetSupplyChainProcedure,
		svc.GetSupplyChain,
		connect.WithSchema(traceabilityServiceMethods.ByName("GetSupplyChain")),
		connect.WithHandlerOptions(opts...),
	)
	traceabilityServiceCreateCertificationHandler := connect.NewUnaryHandler(
		TraceabilityServiceCreateCertificationProcedure,
		svc.CreateCertification,
		connect.WithSchema(traceabilityServiceMethods.ByName("CreateCertification")),
		connect.WithHandlerOptions(opts...),
	)
	traceabilityServiceGetCertificationHandler := connect.NewUnaryHandler(
		TraceabilityServiceGetCertificationProcedure,
		svc.GetCertification,
		connect.WithSchema(traceabilityServiceMethods.ByName("GetCertification")),
		connect.WithHandlerOptions(opts...),
	)
	traceabilityServiceListCertificationsHandler := connect.NewUnaryHandler(
		TraceabilityServiceListCertificationsProcedure,
		svc.ListCertifications,
		connect.WithSchema(traceabilityServiceMethods.ByName("ListCertifications")),
		connect.WithHandlerOptions(opts...),
	)
	traceabilityServiceVerifyCertificationHandler := connect.NewUnaryHandler(
		TraceabilityServiceVerifyCertificationProcedure,
		svc.VerifyCertification,
		connect.WithSchema(traceabilityServiceMethods.ByName("VerifyCertification")),
		connect.WithHandlerOptions(opts...),
	)
	traceabilityServiceCreateBatchHandler := connect.NewUnaryHandler(
		TraceabilityServiceCreateBatchProcedure,
		svc.CreateBatch,
		connect.WithSchema(traceabilityServiceMethods.ByName("CreateBatch")),
		connect.WithHandlerOptions(opts...),
	)
	traceabilityServiceGetBatchHandler := connect.NewUnaryHandler(
		TraceabilityServiceGetBatchProcedure,
		svc.GetBatch,
		connect.WithSchema(traceabilityServiceMethods.ByName("GetBatch")),
		connect.WithHandlerOptions(opts...),
	)
	traceabilityServiceListBatchesHandler := connect.NewUnaryHandler(
		TraceabilityServiceListBatchesProcedure,
		svc.ListBatches,
		connect.WithSchema(traceabilityServiceMethods.ByName("ListBatches")),
		connect.WithHandlerOptions(opts...),
	)
	traceabilityServiceGenerateQRCodeHandler := connect.NewUnaryHandler(
		TraceabilityServiceGenerateQRCodeProcedure,
		svc.GenerateQRCode,
		connect.WithSchema(traceabilityServiceMethods.ByName("GenerateQRCode")),
		connect.WithHandlerOptions(opts...),
	)
	traceabilityServiceVerifyQRCodeHandler := connect.NewUnaryHandler(
		TraceabilityServiceVerifyQRCodeProcedure,
		svc.VerifyQRCode,
		connect.WithSchema(traceabilityServiceMethods.ByName("VerifyQRCode")),
		connect.WithHandlerOptions(opts...),
	)
	traceabilityServiceGenerateComplianceReportHandler := connect.NewUnaryHandler(
		TraceabilityServiceGenerateComplianceReportProcedure,
		svc.GenerateComplianceReport,
		connect.WithSchema(traceabilityServiceMethods.ByName("GenerateComplianceReport")),
		connect.WithHandlerOptions(opts...),
	)
	traceabilityServiceCreateQualityCheckpointHandler := connect.NewUnaryHandler(
		TraceabilityServiceCreateQualityCheckpointProcedure,
		svc.CreateQualityCheckpoint,
		connect.WithSchema(traceabilityServiceMethods.ByName("CreateQualityCheckpoint")),
		connect.WithHandlerOptions(opts...),
	)
	traceabilityServiceGetQualityCheckpointHandler := connect.NewUnaryHandler(
		TraceabilityServiceGetQualityCheckpointProcedure,
		svc.GetQualityCheckpoint,
		connect.WithSchema(traceabilityServiceMethods.ByName("GetQualityCheckpoint")),
		connect.WithHandlerOptions(opts...),
	)
	traceabilityServiceListQualityCheckpointsHandler := connect.NewUnaryHandler(
		TraceabilityServiceListQualityCheckpointsProcedure,
		svc.ListQualityCheckpoints,
		connect.WithSchema(traceabilityServiceMethods.ByName("ListQualityCheckpoints")),
		connect.WithHandlerOptions(opts...),
	)
	traceabilityServiceUpdateRecordHandler := connect.NewUnaryHandler(
		TraceabilityServiceUpdateRecordProcedure,
		svc.UpdateRecord,
		connect.WithSchema(traceabilityServiceMethods.ByName("UpdateRecord")),
		connect.WithHandlerOptions(opts...),
	)
	traceabilityServiceRevokeCertificationHandler := connect.NewUnaryHandler(
		TraceabilityServiceRevokeCertificationProcedure,
		svc.RevokeCertification,
		connect.WithSchema(traceabilityServiceMethods.ByName("RevokeCertification")),
		connect.WithHandlerOptions(opts...),
	)
	traceabilityServiceGetComplianceReportHandler := connect.NewUnaryHandler(
		TraceabilityServiceGetComplianceReportProcedure,
		svc.GetComplianceReport,
		connect.WithSchema(traceabilityServiceMethods.ByName("GetComplianceReport")),
		connect.WithHandlerOptions(opts...),
	)
	traceabilityServiceListComplianceReportsHandler := connect.NewUnaryHandler(
		TraceabilityServiceListComplianceReportsProcedure,
		svc.ListComplianceReports,
		connect.WithSchema(traceabilityServiceMethods.ByName("ListComplianceReports")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agriculture.traceability.v1.TraceabilityService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TraceabilityServiceCreateRecordProcedure:
			traceabilityServiceCreateRecordHandler.ServeHTTP(w, r)
		case TraceabilityServiceGetRecordProcedure:
			traceabilityServiceGetRecordHandler.ServeHTTP(w, r)
		case TraceabilityServiceListRecordsProcedure:
			traceabilityServiceListRecordsHandler.ServeHTTP(w, r)
		case TraceabilityServiceAddSupplyChainEventProcedure:
			traceabilityServiceAddSupplyChainEventHandler.ServeHTTP(w, r)
		case TraceabilityServiceGetSupplyChainProcedure:
			traceabilityServiceGetSupplyChainHandler.ServeHTTP(w, r)
		case TraceabilityServiceCreateCertificationProcedure:
			traceabilityServiceCreateCertificationHandler.ServeHTTP(w, r)
		case TraceabilityServiceGetCertificationProcedure:
			traceabilityServiceGetCertificationHandler.ServeHTTP(w, r)
		case TraceabilityServiceListCertificationsProcedure:
			traceabilityServiceListCertificationsHandler.ServeHTTP(w, r)
		case TraceabilityServiceVerifyCertificationProcedure:
			traceabilityServiceVerifyCertificationHandler.ServeHTTP(w, r)
		case TraceabilityServiceCreateBatchProcedure:
			traceabilityServiceCreateBatchHandler.ServeHTTP(w, r)
		case TraceabilityServiceGetBatchProcedure:
			traceabilityServiceGetBatchHandler.ServeHTTP(w, r)
		case TraceabilityServiceListBatchesProcedure:
			traceabilityServiceListBatchesHandler.ServeHTTP(w, r)
		case TraceabilityServiceGenerateQRCodeProcedure:
			traceabilityServiceGenerateQRCodeHandler.ServeHTTP(w, r)
		case TraceabilityServiceVerifyQRCodeProcedure:
			traceabilityServiceVerifyQRCodeHandler.ServeHTTP(w, r)
		case TraceabilityServiceGenerateComplianceReportProcedure:
			traceabilityServiceGenerateComplianceReportHandler.ServeHTTP(w, r)
		case TraceabilityServiceCreateQualityCheckpointProcedure:
			traceabilityServiceCreateQualityCheckpointHandler.ServeHTTP(w, r)
		case TraceabilityServiceGetQualityCheckpointProcedure:
			traceabilityServiceGetQualityCheckpointHandler.ServeHTTP(w, r)
		case TraceabilityServiceListQualityCheckpointsProcedure:
			traceabilityServiceListQualityCheckpointsHandler.ServeHTTP(w, r)
		case TraceabilityServiceUpdateRecordProcedure:
			traceabilityServiceUpdateRecordHandler.ServeHTTP(w, r)
		case TraceabilityServiceRevokeCertificationProcedure:
			traceabilityServiceRevokeCertificationHandler.ServeHTTP(w, r)
		case TraceabilityServiceGetComplianceReportProcedure:
			traceabilityServiceGetComplianceReportHandler.ServeHTTP(w, r)
		case TraceabilityServiceListComplianceReportsProcedure:
			traceabilityServiceListComplianceReportsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTraceabilityServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTraceabilityServiceHandler struct{}

func (UnimplementedTraceabilityServiceHandler) CreateRecord(context.Context, *connect.Request[v1.CreateRecordRequest]) (*connect.Response[v1.CreateRecordResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.traceability.v1.TraceabilityService.CreateRecord is not implemented"))
}

func (UnimplementedTraceabilityServiceHandler) GetRecord(context.Context, *connect.Request[v1.GetRecordRequest]) (*connect.Response[v1.GetRecordResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.traceability.v1.TraceabilityService.GetRecord is not implemented"))
}

func (UnimplementedTraceabilityServiceHandler) ListRecords(context.Context, *connect.Request[v1.ListRecordsRequest]) (*connect.Response[v1.ListRecordsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.traceability.v1.TraceabilityService.ListRecords is not implemented"))
}

func (UnimplementedTraceabilityServiceHandler) AddSupplyChainEvent(context.Context, *connect.Request[v1.AddSupplyChainEventRequest]) (*connect.Response[v1.AddSupplyChainEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.traceability.v1.TraceabilityService.AddSupplyChainEvent is not implemented"))
}

func (UnimplementedTraceabilityServiceHandler) GetSupplyChain(context.Context, *connect.Request[v1.GetSupplyChainRequest]) (*connect.Response[v1.GetSupplyChainResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.traceability.v1.TraceabilityService.GetSupplyChain is not implemented"))
}

func (UnimplementedTraceabilityServiceHandler) CreateCertification(context.Context, *connect.Request[v1.CreateCertificationRequest]) (*connect.Response[v1.CreateCertificationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.traceability.v1.TraceabilityService.CreateCertification is not implemented"))
}

func (UnimplementedTraceabilityServiceHandler) GetCertification(context.Context, *connect.Request[v1.GetCertificationRequest]) (*connect.Response[v1.GetCertificationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.traceability.v1.TraceabilityService.GetCertification is not implemented"))
}

func (UnimplementedTraceabilityServiceHandler) ListCertifications(context.Context, *connect.Request[v1.ListCertificationsRequest]) (*connect.Response[v1.ListCertificationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.traceability.v1.TraceabilityService.ListCertifications is not implemented"))
}

func (UnimplementedTraceabilityServiceHandler) VerifyCertification(context.Context, *connect.Request[v1.VerifyCertificationRequest]) (*connect.Response[v1.VerifyCertificationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.traceability.v1.TraceabilityService.VerifyCertification is not implemented"))
}

func (UnimplementedTraceabilityServiceHandler) CreateBatch(context.Context, *connect.Request[v1.CreateBatchRequest]) (*connect.Response[v1.CreateBatchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.traceability.v1.TraceabilityService.CreateBatch is not implemented"))
}

func (UnimplementedTraceabilityServiceHandler) GetBatch(context.Context, *connect.Request[v1.GetBatchRequest]) (*connect.Response[v1.GetBatchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.traceability.v1.TraceabilityService.GetBatch is not implemented"))
}

func (UnimplementedTraceabilityServiceHandler) ListBatches(context.Context, *connect.Request[v1.ListBatchesRequest]) (*connect.Response[v1.ListBatchesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.traceability.v1.TraceabilityService.ListBatches is not implemented"))
}

func (UnimplementedTraceabilityServiceHandler) GenerateQRCode(context.Context, *connect.Request[v1.GenerateQRCodeRequest]) (*connect.Response[v1.GenerateQRCodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.traceability.v1.TraceabilityService.GenerateQRCode is not implemented"))
}

func (UnimplementedTraceabilityServiceHandler) VerifyQRCode(context.Context, *connect.Request[v1.VerifyQRCodeRequest]) (*connect.Response[v1.VerifyQRCodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.traceability.v1.TraceabilityService.VerifyQRCode is not implemented"))
}

func (UnimplementedTraceabilityServiceHandler) GenerateComplianceReport(context.Context, *connect.Request[v1.GenerateComplianceReportRequest]) (*connect.Response[v1.GenerateComplianceReportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.traceability.v1.TraceabilityService.GenerateComplianceReport is not implemented"))
}

func (UnimplementedTraceabilityServiceHandler) CreateQualityCheckpoint(context.Context, *connect.Request[v1.CreateQualityCheckpointRequest]) (*connect.Response[v1.CreateQualityCheckpointResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.traceability.v1.TraceabilityService.CreateQualityCheckpoint is not implemented"))
}

func (UnimplementedTraceabilityServiceHandler) GetQualityCheckpoint(context.Context, *connect.Request[v1.GetQualityCheckpointRequest]) (*connect.Response[v1.GetQualityCheckpointResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.traceability.v1.TraceabilityService.GetQualityCheckpoint is not implemented"))
}

func (UnimplementedTraceabilityServiceHandler) ListQualityCheckpoints(context.Context, *connect.Request[v1.ListQualityCheckpointsRequest]) (*connect.Response[v1.ListQualityCheckpointsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.traceability.v1.TraceabilityService.ListQualityCheckpoints is not implemented"))
}

func (UnimplementedTraceabilityServiceHandler) UpdateRecord(context.Context, *connect.Request[v1.UpdateRecordRequest]) (*connect.Response[v1.UpdateRecordResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.traceability.v1.TraceabilityService.UpdateRecord is not implemented"))
}

func (UnimplementedTraceabilityServiceHandler) RevokeCertification(context.Context, *connect.Request[v1.RevokeCertificationRequest]) (*connect.Response[v1.RevokeCertificationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.traceability.v1.TraceabilityService.RevokeCertification is not implemented"))
}

func (UnimplementedTraceabilityServiceHandler) GetComplianceReport(context.Context, *connect.Request[v1.GetComplianceReportRequest]) (*connect.Response[v1.GetComplianceReportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.traceability.v1.TraceabilityService.GetComplianceReport is not implemented"))
}

func (UnimplementedTraceabilityServiceHandler) ListComplianceReports(context.Context, *connect.Request[v1.ListComplianceReportsRequest]) (*connect.Response[v1.ListComplianceReportsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.traceability.v1.TraceabilityService.ListComplianceReports is not implemented"))
}
