// Package grpc contains the inbound ConnectRPC adapter for the traceability-service.
// NOTE: proto types are generated by buf generate.
package grpc

import (
	"context"
	"encoding/json"
	"time"

	"connectrpc.com/connect"
	"p9e.in/samavaya/packages/errors"
	"p9e.in/samavaya/packages/p9log"

	"google.golang.org/protobuf/types/known/timestamppb"

	// Generated by buf generate
	pb "p9e.in/samavaya/agriculture/traceability-service/api/v1"
	"p9e.in/samavaya/agriculture/traceability-service/api/v1/traceabilityv1connect"
	"p9e.in/samavaya/agriculture/traceability-service/internal/models"
	"p9e.in/samavaya/agriculture/traceability-service/internal/ports/inbound"
)

// TraceabilityHandler is the ConnectRPC inbound adapter.
type TraceabilityHandler struct {
	traceabilityv1connect.UnimplementedTraceabilityServiceHandler
	svc inbound.TraceabilityService
	log *p9log.Helper
}

// NewTraceabilityHandler creates a new ConnectRPC traceability handler.
func NewTraceabilityHandler(svc inbound.TraceabilityService, log p9log.Logger) *TraceabilityHandler {
	return &TraceabilityHandler{
		svc: svc,
		log: p9log.NewHelper(p9log.With(log, "component", "TraceabilityHandler")),
	}
}

// --- Records ---

// CreateRecord handles creation requests.
func (h *TraceabilityHandler) CreateRecord(ctx context.Context, req *connect.Request[pb.CreateRecordRequest]) (*connect.Response[pb.CreateRecordResponse], error) {
	input := models.CreateRecordInput{
		FarmID:         req.Msg.GetFarmId(),
		FieldID:        req.Msg.GetFieldId(),
		CropID:         req.Msg.GetCropId(),
		BatchNumber:    req.Msg.GetBatchNumber(),
		ProductType:    req.Msg.GetProductType(),
		OriginCountry:  req.Msg.GetOriginCountry(),
		OriginRegion:   req.Msg.GetOriginRegion(),
		SeedSource:     req.Msg.GetSeedSource(),
		PlantingDate:   tsToTimePtr(req.Msg.GetPlantingDate()),
		HarvestDate:    tsToTimePtr(req.Msg.GetHarvestDate()),
		ProcessingDate: tsToTimePtr(req.Msg.GetProcessingDate()),
		PackagingDate:  tsToTimePtr(req.Msg.GetPackagingDate()),
		Metadata:       req.Msg.GetMetadata(),
	}
	record, err := h.svc.CreateRecord(ctx, input)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.CreateRecordResponse{Record: recordToProto(record)}), nil
}

// GetRecord handles get requests.
func (h *TraceabilityHandler) GetRecord(ctx context.Context, req *connect.Request[pb.GetRecordRequest]) (*connect.Response[pb.GetRecordResponse], error) {
	record, err := h.svc.GetRecord(ctx, req.Msg.GetId())
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.GetRecordResponse{Record: recordToProto(record)}), nil
}

// ListRecords handles list requests.
func (h *TraceabilityHandler) ListRecords(ctx context.Context, req *connect.Request[pb.ListRecordsRequest]) (*connect.Response[pb.ListRecordsResponse], error) {
	filter := models.ListRecordsFilter{
		FarmID:        req.Msg.GetFarmId(),
		CropID:        req.Msg.GetCropId(),
		ProductType:   req.Msg.GetProductType(),
		OriginCountry: req.Msg.GetOriginCountry(),
		Search:        req.Msg.GetSearch(),
		PageSize:      req.Msg.GetPageSize(),
	}
	if req.Msg.GetComplianceStatus() != pb.ComplianceStatus_COMPLIANCE_STATUS_UNSPECIFIED {
		filter.ComplianceStatus = complianceStatusProtoToModel(req.Msg.GetComplianceStatus())
	}

	records, total, err := h.svc.ListRecords(ctx, filter)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}

	protos := make([]*pb.TraceabilityRecord, 0, len(records))
	for i := range records {
		protos = append(protos, recordToProto(&records[i]))
	}
	return connect.NewResponse(&pb.ListRecordsResponse{
		Records:    protos,
		TotalCount: int32(total),
	}), nil
}

// --- Supply Chain Events ---

// AddSupplyChainEvent handles adding a supply chain event.
func (h *TraceabilityHandler) AddSupplyChainEvent(ctx context.Context, req *connect.Request[pb.AddSupplyChainEventRequest]) (*connect.Response[pb.AddSupplyChainEventResponse], error) {
	ts := time.Now()
	if req.Msg.GetTimestamp() != nil {
		ts = req.Msg.GetTimestamp().AsTime()
	}
	input := models.AddSupplyChainEventInput{
		RecordID:  req.Msg.GetRecordId(),
		EventType: supplyChainEventTypeProtoToModel(req.Msg.GetEventType()),
		Timestamp: ts,
		Location:  req.Msg.GetLocation(),
		Actor:     req.Msg.GetActor(),
		Details:   req.Msg.GetDetails(),
	}
	event, err := h.svc.AddSupplyChainEvent(ctx, input)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.AddSupplyChainEventResponse{Event: supplyChainEventToProto(event)}), nil
}

// GetSupplyChain returns the supply chain events for a record.
func (h *TraceabilityHandler) GetSupplyChain(ctx context.Context, req *connect.Request[pb.GetSupplyChainRequest]) (*connect.Response[pb.GetSupplyChainResponse], error) {
	events, err := h.svc.GetSupplyChain(ctx, req.Msg.GetRecordId())
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	protos := make([]*pb.SupplyChainEvent, 0, len(events))
	for i := range events {
		protos = append(protos, supplyChainEventToProto(&events[i]))
	}
	return connect.NewResponse(&pb.GetSupplyChainResponse{Events: protos}), nil
}

// --- Certifications ---

// CreateCertification creates a new certification.
func (h *TraceabilityHandler) CreateCertification(ctx context.Context, req *connect.Request[pb.CreateCertificationRequest]) (*connect.Response[pb.CreateCertificationResponse], error) {
	input := models.CreateCertificationInput{
		RecordID:   req.Msg.GetRecordId(),
		CertType:   certTypeProtoToModel(req.Msg.GetCertType()),
		CertNumber: req.Msg.GetCertNumber(),
		IssuedBy:   req.Msg.GetIssuedBy(),
		IssuedDate: tsToTimePtr(req.Msg.GetIssuedDate()),
		ExpiryDate: tsToTimePtr(req.Msg.GetExpiryDate()),
		Metadata:   req.Msg.GetMetadata(),
	}
	cert, err := h.svc.CreateCertification(ctx, input)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.CreateCertificationResponse{Certification: certToProto(cert)}), nil
}

// GetCertification retrieves a certification by ID.
func (h *TraceabilityHandler) GetCertification(ctx context.Context, req *connect.Request[pb.GetCertificationRequest]) (*connect.Response[pb.GetCertificationResponse], error) {
	cert, err := h.svc.GetCertification(ctx, req.Msg.GetId())
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.GetCertificationResponse{Certification: certToProto(cert)}), nil
}

// ListCertifications lists certifications with filtering.
func (h *TraceabilityHandler) ListCertifications(ctx context.Context, req *connect.Request[pb.ListCertificationsRequest]) (*connect.Response[pb.ListCertificationsResponse], error) {
	filter := models.ListCertificationsFilter{
		RecordID: req.Msg.GetRecordId(),
		PageSize: req.Msg.GetPageSize(),
	}
	if req.Msg.GetCertType() != pb.CertificationType_CERTIFICATION_TYPE_UNSPECIFIED {
		filter.CertType = string(certTypeProtoToModel(req.Msg.GetCertType()))
	}
	if req.Msg.GetStatus() != pb.CertificationStatus_CERTIFICATION_STATUS_UNSPECIFIED {
		filter.Status = string(certStatusProtoToModel(req.Msg.GetStatus()))
	}

	certs, total, err := h.svc.ListCertifications(ctx, filter)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}

	protos := make([]*pb.Certification, 0, len(certs))
	for i := range certs {
		protos = append(protos, certToProto(&certs[i]))
	}
	return connect.NewResponse(&pb.ListCertificationsResponse{
		Certifications: protos,
		TotalCount:     int32(total),
	}), nil
}

// VerifyCertification verifies a certification.
func (h *TraceabilityHandler) VerifyCertification(ctx context.Context, req *connect.Request[pb.VerifyCertificationRequest]) (*connect.Response[pb.VerifyCertificationResponse], error) {
	cert, err := h.svc.VerifyCertification(ctx, req.Msg.GetId(), req.Msg.GetVerifiedBy())
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.VerifyCertificationResponse{Certification: certToProto(cert)}), nil
}

// --- Batches ---

// CreateBatch creates a new batch record.
func (h *TraceabilityHandler) CreateBatch(ctx context.Context, req *connect.Request[pb.CreateBatchRequest]) (*connect.Response[pb.CreateBatchResponse], error) {
	input := models.CreateBatchInput{
		RecordID:          req.Msg.GetRecordId(),
		BatchNumber:       req.Msg.GetBatchNumber(),
		Quantity:          req.Msg.GetQuantity(),
		Unit:              req.Msg.GetUnit(),
		ProductionDate:    tsToTimePtr(req.Msg.GetProductionDate()),
		ExpiryDate:        tsToTimePtr(req.Msg.GetExpiryDate()),
		StorageConditions: req.Msg.GetStorageConditions(),
		QualityGrade:      req.Msg.GetQualityGrade(),
		Metadata:          req.Msg.GetMetadata(),
	}
	batch, err := h.svc.CreateBatch(ctx, input)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.CreateBatchResponse{Batch: batchToProto(batch)}), nil
}

// GetBatch retrieves a batch by ID.
func (h *TraceabilityHandler) GetBatch(ctx context.Context, req *connect.Request[pb.GetBatchRequest]) (*connect.Response[pb.GetBatchResponse], error) {
	batch, err := h.svc.GetBatch(ctx, req.Msg.GetId())
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.GetBatchResponse{Batch: batchToProto(batch)}), nil
}

// ListBatches lists batches with filtering.
func (h *TraceabilityHandler) ListBatches(ctx context.Context, req *connect.Request[pb.ListBatchesRequest]) (*connect.Response[pb.ListBatchesResponse], error) {
	filter := models.ListBatchesFilter{
		RecordID: req.Msg.GetRecordId(),
		PageSize: req.Msg.GetPageSize(),
	}
	batches, total, err := h.svc.ListBatches(ctx, filter)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}

	protos := make([]*pb.BatchRecord, 0, len(batches))
	for i := range batches {
		protos = append(protos, batchToProto(&batches[i]))
	}
	return connect.NewResponse(&pb.ListBatchesResponse{
		Batches:    protos,
		TotalCount: int32(total),
	}), nil
}

// --- QR Codes ---

// GenerateQRCode generates a QR code for a record.
func (h *TraceabilityHandler) GenerateQRCode(ctx context.Context, req *connect.Request[pb.GenerateQRCodeRequest]) (*connect.Response[pb.GenerateQRCodeResponse], error) {
	input := models.GenerateQRCodeInput{
		RecordID: req.Msg.GetRecordId(),
		BatchID:  req.Msg.GetBatchId(),
		BaseURL:  req.Msg.GetBaseUrl(),
	}
	qr, err := h.svc.GenerateQRCode(ctx, input)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.GenerateQRCodeResponse{QrCode: qrCodeToProto(qr)}), nil
}

// VerifyQRCode verifies a QR code and returns associated record/batch.
func (h *TraceabilityHandler) VerifyQRCode(ctx context.Context, req *connect.Request[pb.VerifyQRCodeRequest]) (*connect.Response[pb.VerifyQRCodeResponse], error) {
	record, batch, err := h.svc.VerifyQRCode(ctx, req.Msg.GetQrData())
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	resp := &pb.VerifyQRCodeResponse{
		Valid:  true,
		Record: recordToProto(record),
	}
	if batch != nil {
		resp.Batch = batchToProto(batch)
	}
	return connect.NewResponse(resp), nil
}

// --- Compliance ---

// GenerateComplianceReport generates a compliance report for a record.
func (h *TraceabilityHandler) GenerateComplianceReport(ctx context.Context, req *connect.Request[pb.GenerateComplianceReportRequest]) (*connect.Response[pb.GenerateComplianceReportResponse], error) {
	input := models.GenerateComplianceReportInput{
		RecordID:   req.Msg.GetRecordId(),
		ReportType: req.Msg.GetReportType(),
		Auditor:    req.Msg.GetAuditor(),
	}
	report, err := h.svc.GenerateComplianceReport(ctx, input)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.GenerateComplianceReportResponse{Report: complianceReportToProto(report)}), nil
}

// ===================================================================
// Proto-to-Model and Model-to-Proto conversion helpers
// ===================================================================

// --- Timestamp helpers ---

func tsToTimePtr(ts *timestamppb.Timestamp) *time.Time {
	if ts == nil {
		return nil
	}
	t := ts.AsTime()
	return &t
}

func timePtrToTs(t *time.Time) *timestamppb.Timestamp {
	if t == nil {
		return nil
	}
	return timestamppb.New(*t)
}

func timeToTs(t time.Time) *timestamppb.Timestamp {
	return timestamppb.New(t)
}

// --- Record conversion ---

func recordToProto(r *models.TraceabilityRecord) *pb.TraceabilityRecord {
	if r == nil {
		return nil
	}
	proto := &pb.TraceabilityRecord{
		Id:               r.ID,
		TenantId:         r.TenantID,
		FarmId:           r.FarmID,
		FieldId:          r.FieldID,
		CropId:           r.CropID,
		BatchNumber:      r.BatchNumber,
		ProductType:      r.ProductType,
		OriginCountry:    r.OriginCountry,
		OriginRegion:     r.OriginRegion,
		SeedSource:       r.SeedSource,
		PlantingDate:     timePtrToTs(r.PlantingDate),
		HarvestDate:      timePtrToTs(r.HarvestDate),
		ProcessingDate:   timePtrToTs(r.ProcessingDate),
		PackagingDate:    timePtrToTs(r.PackagingDate),
		QrCodeData:       r.QRCodeData,
		BlockchainHash:   r.BlockchainHash,
		ChainOfCustody:   r.ChainOfCustody,
		ComplianceStatus: complianceStatusModelToProto(r.ComplianceStatus),
		Metadata:         metadataJSONToMap(r.Metadata),
		Version:          r.Version,
		CreatedBy:        r.CreatedBy,
		UpdatedBy:        r.UpdatedBy,
		CreatedAt:        timeToTs(r.CreatedAt),
		UpdatedAt:        timeToTs(r.UpdatedAt),
	}

	if len(r.SupplyChainEvents) > 0 {
		proto.SupplyChainEvents = make([]*pb.SupplyChainEvent, 0, len(r.SupplyChainEvents))
		for i := range r.SupplyChainEvents {
			proto.SupplyChainEvents = append(proto.SupplyChainEvents, supplyChainEventToProto(&r.SupplyChainEvents[i]))
		}
	}

	if len(r.Certifications) > 0 {
		proto.Certifications = make([]*pb.Certification, 0, len(r.Certifications))
		for i := range r.Certifications {
			proto.Certifications = append(proto.Certifications, certToProto(&r.Certifications[i]))
		}
	}

	return proto
}

// --- Supply Chain Event conversion ---

func supplyChainEventToProto(e *models.SupplyChainEvent) *pb.SupplyChainEvent {
	if e == nil {
		return nil
	}
	return &pb.SupplyChainEvent{
		Id:               e.ID,
		RecordId:         e.RecordID,
		EventType:        supplyChainEventTypeModelToProto(e.EventType),
		Timestamp:        timeToTs(e.EventTimestamp),
		Location:         e.Location,
		Actor:            e.Actor,
		Details:          e.Details,
		VerificationHash: e.VerificationHash,
		CreatedAt:        timeToTs(e.CreatedAt),
	}
}

// --- Certification conversion ---

func certToProto(c *models.Certification) *pb.Certification {
	if c == nil {
		return nil
	}
	return &pb.Certification{
		Id:         c.ID,
		TenantId:   c.TenantID,
		RecordId:   c.RecordID,
		CertType:   certTypeModelToProto(c.CertType),
		CertNumber: c.CertNumber,
		IssuedBy:   c.IssuedBy,
		IssuedDate: timePtrToTs(c.IssuedDate),
		ExpiryDate: timePtrToTs(c.ExpiryDate),
		Status:     certStatusModelToProto(c.Status),
		VerifiedBy: c.VerifiedBy,
		VerifiedAt: timePtrToTs(c.VerifiedAt),
		Metadata:   metadataJSONToMap(c.Metadata),
		CreatedAt:  timeToTs(c.CreatedAt),
		UpdatedAt:  timeToTs(c.UpdatedAt),
		Version:    c.Version,
	}
}

// --- Batch conversion ---

func batchToProto(b *models.BatchRecord) *pb.BatchRecord {
	if b == nil {
		return nil
	}
	return &pb.BatchRecord{
		Id:                b.ID,
		TenantId:          b.TenantID,
		RecordId:          b.RecordID,
		BatchNumber:       b.BatchNumber,
		Quantity:          b.Quantity,
		Unit:              b.Unit,
		ProductionDate:    timePtrToTs(b.ProductionDate),
		ExpiryDate:        timePtrToTs(b.ExpiryDate),
		StorageConditions: b.StorageConditions,
		QualityGrade:      b.QualityGrade,
		Metadata:          metadataJSONToMap(b.Metadata),
		CreatedAt:         timeToTs(b.CreatedAt),
		UpdatedAt:         timeToTs(b.UpdatedAt),
		Version:           b.Version,
	}
}

// --- QR Code conversion ---

func qrCodeToProto(q *models.QRCodeRecord) *pb.QRCode {
	if q == nil {
		return nil
	}
	return &pb.QRCode{
		Id:          q.ID,
		RecordId:    q.RecordID,
		BatchId:     q.BatchID,
		QrData:      q.QRData,
		QrImageUrl:  q.QRImageURL,
		ScanUrl:     q.ScanURL,
		GeneratedAt: timeToTs(q.GeneratedAt),
		ExpiresAt:   timePtrToTs(q.ExpiresAt),
		IsActive:    q.IsActive,
	}
}

// --- Compliance Report conversion ---

func complianceReportToProto(r *models.ComplianceReport) *pb.ComplianceReport {
	if r == nil {
		return nil
	}
	return &pb.ComplianceReport{
		Id:              r.ID,
		TenantId:        r.TenantID,
		RecordId:        r.RecordID,
		Status:          complianceStatusModelToProto(r.Status),
		ReportType:      r.ReportType,
		Findings:        r.Findings,
		Recommendations: r.Recommendations,
		Auditor:         r.Auditor,
		AuditDate:       timePtrToTs(r.AuditDate),
		NextAuditDate:   timePtrToTs(r.NextAuditDate),
		ComplianceScore: r.ComplianceScore,
		Metadata:        metadataJSONToMap(r.Metadata),
		CreatedAt:       timeToTs(r.CreatedAt),
	}
}

// --- Enum conversion: Supply Chain Event Type ---

var supplyChainEventTypeToProto = map[models.SupplyChainEventType]pb.SupplyChainEventType{
	models.SupplyChainEventTypePlanted:    pb.SupplyChainEventType_SUPPLY_CHAIN_EVENT_TYPE_PLANTED,
	models.SupplyChainEventTypeFertilized: pb.SupplyChainEventType_SUPPLY_CHAIN_EVENT_TYPE_FERTILIZED,
	models.SupplyChainEventTypeIrrigated:  pb.SupplyChainEventType_SUPPLY_CHAIN_EVENT_TYPE_IRRIGATED,
	models.SupplyChainEventTypeSprayed:    pb.SupplyChainEventType_SUPPLY_CHAIN_EVENT_TYPE_SPRAYED,
	models.SupplyChainEventTypeHarvested:  pb.SupplyChainEventType_SUPPLY_CHAIN_EVENT_TYPE_HARVESTED,
	models.SupplyChainEventTypeProcessed:  pb.SupplyChainEventType_SUPPLY_CHAIN_EVENT_TYPE_PROCESSED,
	models.SupplyChainEventTypePackaged:   pb.SupplyChainEventType_SUPPLY_CHAIN_EVENT_TYPE_PACKAGED,
	models.SupplyChainEventTypeShipped:    pb.SupplyChainEventType_SUPPLY_CHAIN_EVENT_TYPE_SHIPPED,
	models.SupplyChainEventTypeReceived:   pb.SupplyChainEventType_SUPPLY_CHAIN_EVENT_TYPE_RECEIVED,
	models.SupplyChainEventTypeSold:       pb.SupplyChainEventType_SUPPLY_CHAIN_EVENT_TYPE_SOLD,
}

var supplyChainEventTypeToModel = map[pb.SupplyChainEventType]models.SupplyChainEventType{
	pb.SupplyChainEventType_SUPPLY_CHAIN_EVENT_TYPE_PLANTED:    models.SupplyChainEventTypePlanted,
	pb.SupplyChainEventType_SUPPLY_CHAIN_EVENT_TYPE_FERTILIZED: models.SupplyChainEventTypeFertilized,
	pb.SupplyChainEventType_SUPPLY_CHAIN_EVENT_TYPE_IRRIGATED:  models.SupplyChainEventTypeIrrigated,
	pb.SupplyChainEventType_SUPPLY_CHAIN_EVENT_TYPE_SPRAYED:    models.SupplyChainEventTypeSprayed,
	pb.SupplyChainEventType_SUPPLY_CHAIN_EVENT_TYPE_HARVESTED:  models.SupplyChainEventTypeHarvested,
	pb.SupplyChainEventType_SUPPLY_CHAIN_EVENT_TYPE_PROCESSED:  models.SupplyChainEventTypeProcessed,
	pb.SupplyChainEventType_SUPPLY_CHAIN_EVENT_TYPE_PACKAGED:   models.SupplyChainEventTypePackaged,
	pb.SupplyChainEventType_SUPPLY_CHAIN_EVENT_TYPE_SHIPPED:    models.SupplyChainEventTypeShipped,
	pb.SupplyChainEventType_SUPPLY_CHAIN_EVENT_TYPE_RECEIVED:   models.SupplyChainEventTypeReceived,
	pb.SupplyChainEventType_SUPPLY_CHAIN_EVENT_TYPE_SOLD:       models.SupplyChainEventTypeSold,
}

func supplyChainEventTypeModelToProto(t models.SupplyChainEventType) pb.SupplyChainEventType {
	if v, ok := supplyChainEventTypeToProto[t]; ok {
		return v
	}
	return pb.SupplyChainEventType_SUPPLY_CHAIN_EVENT_TYPE_UNSPECIFIED
}

func supplyChainEventTypeProtoToModel(t pb.SupplyChainEventType) models.SupplyChainEventType {
	if v, ok := supplyChainEventTypeToModel[t]; ok {
		return v
	}
	return ""
}

// --- Enum conversion: Certification Type ---

var certTypeToProto = map[models.CertificationType]pb.CertificationType{
	models.CertificationTypeOrganic:            pb.CertificationType_CERTIFICATION_TYPE_ORGANIC,
	models.CertificationTypeGAP:                pb.CertificationType_CERTIFICATION_TYPE_GAP,
	models.CertificationTypeFairtrade:          pb.CertificationType_CERTIFICATION_TYPE_FAIRTRADE,
	models.CertificationTypeRainforestAlliance: pb.CertificationType_CERTIFICATION_TYPE_RAINFOREST_ALLIANCE,
	models.CertificationTypeUSDAOrganic:        pb.CertificationType_CERTIFICATION_TYPE_USDA_ORGANIC,
	models.CertificationTypeEUOrganic:          pb.CertificationType_CERTIFICATION_TYPE_EU_ORGANIC,
}

var certTypeToModel = map[pb.CertificationType]models.CertificationType{
	pb.CertificationType_CERTIFICATION_TYPE_ORGANIC:             models.CertificationTypeOrganic,
	pb.CertificationType_CERTIFICATION_TYPE_GAP:                 models.CertificationTypeGAP,
	pb.CertificationType_CERTIFICATION_TYPE_FAIRTRADE:           models.CertificationTypeFairtrade,
	pb.CertificationType_CERTIFICATION_TYPE_RAINFOREST_ALLIANCE: models.CertificationTypeRainforestAlliance,
	pb.CertificationType_CERTIFICATION_TYPE_USDA_ORGANIC:        models.CertificationTypeUSDAOrganic,
	pb.CertificationType_CERTIFICATION_TYPE_EU_ORGANIC:          models.CertificationTypeEUOrganic,
}

func certTypeModelToProto(t models.CertificationType) pb.CertificationType {
	if v, ok := certTypeToProto[t]; ok {
		return v
	}
	return pb.CertificationType_CERTIFICATION_TYPE_UNSPECIFIED
}

func certTypeProtoToModel(t pb.CertificationType) models.CertificationType {
	if v, ok := certTypeToModel[t]; ok {
		return v
	}
	return ""
}

// --- Enum conversion: Certification Status ---

var certStatusToProto = map[models.CertificationStatus]pb.CertificationStatus{
	models.CertificationStatusActive:  pb.CertificationStatus_CERTIFICATION_STATUS_ACTIVE,
	models.CertificationStatusExpired: pb.CertificationStatus_CERTIFICATION_STATUS_EXPIRED,
	models.CertificationStatusRevoked: pb.CertificationStatus_CERTIFICATION_STATUS_REVOKED,
	models.CertificationStatusPending: pb.CertificationStatus_CERTIFICATION_STATUS_PENDING,
}

var certStatusToModel = map[pb.CertificationStatus]models.CertificationStatus{
	pb.CertificationStatus_CERTIFICATION_STATUS_ACTIVE:  models.CertificationStatusActive,
	pb.CertificationStatus_CERTIFICATION_STATUS_EXPIRED: models.CertificationStatusExpired,
	pb.CertificationStatus_CERTIFICATION_STATUS_REVOKED: models.CertificationStatusRevoked,
	pb.CertificationStatus_CERTIFICATION_STATUS_PENDING: models.CertificationStatusPending,
}

func certStatusModelToProto(s models.CertificationStatus) pb.CertificationStatus {
	if v, ok := certStatusToProto[s]; ok {
		return v
	}
	return pb.CertificationStatus_CERTIFICATION_STATUS_UNSPECIFIED
}

func certStatusProtoToModel(s pb.CertificationStatus) models.CertificationStatus {
	if v, ok := certStatusToModel[s]; ok {
		return v
	}
	return ""
}

// --- Enum conversion: Compliance Status ---

var complianceStatusToProto = map[models.ComplianceStatusType]pb.ComplianceStatus{
	models.ComplianceStatusCompliant:    pb.ComplianceStatus_COMPLIANCE_STATUS_COMPLIANT,
	models.ComplianceStatusNonCompliant: pb.ComplianceStatus_COMPLIANCE_STATUS_NON_COMPLIANT,
	models.ComplianceStatusPending:      pb.ComplianceStatus_COMPLIANCE_STATUS_PENDING_REVIEW,
}

func complianceStatusModelToProto(s models.ComplianceStatusType) pb.ComplianceStatus {
	if v, ok := complianceStatusToProto[s]; ok {
		return v
	}
	return pb.ComplianceStatus_COMPLIANCE_STATUS_UNSPECIFIED
}

func complianceStatusProtoToModel(s pb.ComplianceStatus) string {
	switch s {
	case pb.ComplianceStatus_COMPLIANCE_STATUS_COMPLIANT:
		return string(models.ComplianceStatusCompliant)
	case pb.ComplianceStatus_COMPLIANCE_STATUS_NON_COMPLIANT:
		return string(models.ComplianceStatusNonCompliant)
	case pb.ComplianceStatus_COMPLIANCE_STATUS_PENDING_REVIEW:
		return string(models.ComplianceStatusPending)
	default:
		return ""
	}
}

// --- Metadata conversion ---

func metadataJSONToMap(raw json.RawMessage) map[string]string {
	if len(raw) == 0 || string(raw) == "{}" || string(raw) == "null" {
		return nil
	}
	m := make(map[string]string)
	if err := json.Unmarshal(raw, &m); err != nil {
		return nil
	}
	return m
}
