// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: agriculture/agronomy/v1/inspection.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "p9e.in/samavaya/agriculture/agronomy-service/api/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// InspectionServiceName is the fully-qualified name of the InspectionService service.
	InspectionServiceName = "agriculture.agronomy.v1.InspectionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// InspectionServiceGetInspectionProcedure is the fully-qualified name of the InspectionService's
	// GetInspection RPC.
	InspectionServiceGetInspectionProcedure = "/agriculture.agronomy.v1.InspectionService/GetInspection"
	// InspectionServiceListInspectionsProcedure is the fully-qualified name of the InspectionService's
	// ListInspections RPC.
	InspectionServiceListInspectionsProcedure = "/agriculture.agronomy.v1.InspectionService/ListInspections"
	// InspectionServiceCreateInspectionProcedure is the fully-qualified name of the InspectionService's
	// CreateInspection RPC.
	InspectionServiceCreateInspectionProcedure = "/agriculture.agronomy.v1.InspectionService/CreateInspection"
	// InspectionServiceSubmitInspectionProcedure is the fully-qualified name of the InspectionService's
	// SubmitInspection RPC.
	InspectionServiceSubmitInspectionProcedure = "/agriculture.agronomy.v1.InspectionService/SubmitInspection"
)

// InspectionServiceClient is a client for the agriculture.agronomy.v1.InspectionService service.
type InspectionServiceClient interface {
	GetInspection(context.Context, *connect.Request[v1.GetInspectionRequest]) (*connect.Response[v1.GetInspectionResponse], error)
	ListInspections(context.Context, *connect.Request[v1.ListInspectionsRequest]) (*connect.Response[v1.ListInspectionsResponse], error)
	CreateInspection(context.Context, *connect.Request[v1.CreateInspectionRequest]) (*connect.Response[v1.CreateInspectionResponse], error)
	SubmitInspection(context.Context, *connect.Request[v1.SubmitInspectionRequest]) (*connect.Response[v1.SubmitInspectionResponse], error)
}

// NewInspectionServiceClient constructs a client for the agriculture.agronomy.v1.InspectionService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInspectionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) InspectionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	inspectionServiceMethods := v1.File_agriculture_agronomy_v1_inspection_proto.Services().ByName("InspectionService").Methods()
	return &inspectionServiceClient{
		getInspection: connect.NewClient[v1.GetInspectionRequest, v1.GetInspectionResponse](
			httpClient,
			baseURL+InspectionServiceGetInspectionProcedure,
			connect.WithSchema(inspectionServiceMethods.ByName("GetInspection")),
			connect.WithClientOptions(opts...),
		),
		listInspections: connect.NewClient[v1.ListInspectionsRequest, v1.ListInspectionsResponse](
			httpClient,
			baseURL+InspectionServiceListInspectionsProcedure,
			connect.WithSchema(inspectionServiceMethods.ByName("ListInspections")),
			connect.WithClientOptions(opts...),
		),
		createInspection: connect.NewClient[v1.CreateInspectionRequest, v1.CreateInspectionResponse](
			httpClient,
			baseURL+InspectionServiceCreateInspectionProcedure,
			connect.WithSchema(inspectionServiceMethods.ByName("CreateInspection")),
			connect.WithClientOptions(opts...),
		),
		submitInspection: connect.NewClient[v1.SubmitInspectionRequest, v1.SubmitInspectionResponse](
			httpClient,
			baseURL+InspectionServiceSubmitInspectionProcedure,
			connect.WithSchema(inspectionServiceMethods.ByName("SubmitInspection")),
			connect.WithClientOptions(opts...),
		),
	}
}

// inspectionServiceClient implements InspectionServiceClient.
type inspectionServiceClient struct {
	getInspection    *connect.Client[v1.GetInspectionRequest, v1.GetInspectionResponse]
	listInspections  *connect.Client[v1.ListInspectionsRequest, v1.ListInspectionsResponse]
	createInspection *connect.Client[v1.CreateInspectionRequest, v1.CreateInspectionResponse]
	submitInspection *connect.Client[v1.SubmitInspectionRequest, v1.SubmitInspectionResponse]
}

// GetInspection calls agriculture.agronomy.v1.InspectionService.GetInspection.
func (c *inspectionServiceClient) GetInspection(ctx context.Context, req *connect.Request[v1.GetInspectionRequest]) (*connect.Response[v1.GetInspectionResponse], error) {
	return c.getInspection.CallUnary(ctx, req)
}

// ListInspections calls agriculture.agronomy.v1.InspectionService.ListInspections.
func (c *inspectionServiceClient) ListInspections(ctx context.Context, req *connect.Request[v1.ListInspectionsRequest]) (*connect.Response[v1.ListInspectionsResponse], error) {
	return c.listInspections.CallUnary(ctx, req)
}

// CreateInspection calls agriculture.agronomy.v1.InspectionService.CreateInspection.
func (c *inspectionServiceClient) CreateInspection(ctx context.Context, req *connect.Request[v1.CreateInspectionRequest]) (*connect.Response[v1.CreateInspectionResponse], error) {
	return c.createInspection.CallUnary(ctx, req)
}

// SubmitInspection calls agriculture.agronomy.v1.InspectionService.SubmitInspection.
func (c *inspectionServiceClient) SubmitInspection(ctx context.Context, req *connect.Request[v1.SubmitInspectionRequest]) (*connect.Response[v1.SubmitInspectionResponse], error) {
	return c.submitInspection.CallUnary(ctx, req)
}

// InspectionServiceHandler is an implementation of the agriculture.agronomy.v1.InspectionService
// service.
type InspectionServiceHandler interface {
	GetInspection(context.Context, *connect.Request[v1.GetInspectionRequest]) (*connect.Response[v1.GetInspectionResponse], error)
	ListInspections(context.Context, *connect.Request[v1.ListInspectionsRequest]) (*connect.Response[v1.ListInspectionsResponse], error)
	CreateInspection(context.Context, *connect.Request[v1.CreateInspectionRequest]) (*connect.Response[v1.CreateInspectionResponse], error)
	SubmitInspection(context.Context, *connect.Request[v1.SubmitInspectionRequest]) (*connect.Response[v1.SubmitInspectionResponse], error)
}

// NewInspectionServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInspectionServiceHandler(svc InspectionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	inspectionServiceMethods := v1.File_agriculture_agronomy_v1_inspection_proto.Services().ByName("InspectionService").Methods()
	inspectionServiceGetInspectionHandler := connect.NewUnaryHandler(
		InspectionServiceGetInspectionProcedure,
		svc.GetInspection,
		connect.WithSchema(inspectionServiceMethods.ByName("GetInspection")),
		connect.WithHandlerOptions(opts...),
	)
	inspectionServiceListInspectionsHandler := connect.NewUnaryHandler(
		InspectionServiceListInspectionsProcedure,
		svc.ListInspections,
		connect.WithSchema(inspectionServiceMethods.ByName("ListInspections")),
		connect.WithHandlerOptions(opts...),
	)
	inspectionServiceCreateInspectionHandler := connect.NewUnaryHandler(
		InspectionServiceCreateInspectionProcedure,
		svc.CreateInspection,
		connect.WithSchema(inspectionServiceMethods.ByName("CreateInspection")),
		connect.WithHandlerOptions(opts...),
	)
	inspectionServiceSubmitInspectionHandler := connect.NewUnaryHandler(
		InspectionServiceSubmitInspectionProcedure,
		svc.SubmitInspection,
		connect.WithSchema(inspectionServiceMethods.ByName("SubmitInspection")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agriculture.agronomy.v1.InspectionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InspectionServiceGetInspectionProcedure:
			inspectionServiceGetInspectionHandler.ServeHTTP(w, r)
		case InspectionServiceListInspectionsProcedure:
			inspectionServiceListInspectionsHandler.ServeHTTP(w, r)
		case InspectionServiceCreateInspectionProcedure:
			inspectionServiceCreateInspectionHandler.ServeHTTP(w, r)
		case InspectionServiceSubmitInspectionProcedure:
			inspectionServiceSubmitInspectionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInspectionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInspectionServiceHandler struct{}

func (UnimplementedInspectionServiceHandler) GetInspection(context.Context, *connect.Request[v1.GetInspectionRequest]) (*connect.Response[v1.GetInspectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.agronomy.v1.InspectionService.GetInspection is not implemented"))
}

func (UnimplementedInspectionServiceHandler) ListInspections(context.Context, *connect.Request[v1.ListInspectionsRequest]) (*connect.Response[v1.ListInspectionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.agronomy.v1.InspectionService.ListInspections is not implemented"))
}

func (UnimplementedInspectionServiceHandler) CreateInspection(context.Context, *connect.Request[v1.CreateInspectionRequest]) (*connect.Response[v1.CreateInspectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.agronomy.v1.InspectionService.CreateInspection is not implemented"))
}

func (UnimplementedInspectionServiceHandler) SubmitInspection(context.Context, *connect.Request[v1.SubmitInspectionRequest]) (*connect.Response[v1.SubmitInspectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.agronomy.v1.InspectionService.SubmitInspection is not implemented"))
}
