// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: farm.proto

package farmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FarmService_CreateFarm_FullMethodName           = "/agriculture.farm.v1.FarmService/CreateFarm"
	FarmService_GetFarm_FullMethodName              = "/agriculture.farm.v1.FarmService/GetFarm"
	FarmService_ListFarms_FullMethodName            = "/agriculture.farm.v1.FarmService/ListFarms"
	FarmService_UpdateFarm_FullMethodName           = "/agriculture.farm.v1.FarmService/UpdateFarm"
	FarmService_DeleteFarm_FullMethodName           = "/agriculture.farm.v1.FarmService/DeleteFarm"
	FarmService_SetFarmBoundary_FullMethodName      = "/agriculture.farm.v1.FarmService/SetFarmBoundary"
	FarmService_GetFarmBoundary_FullMethodName      = "/agriculture.farm.v1.FarmService/GetFarmBoundary"
	FarmService_TransferOwnership_FullMethodName    = "/agriculture.farm.v1.FarmService/TransferOwnership"
	FarmService_CreateManagementUnit_FullMethodName = "/agriculture.farm.v1.FarmService/CreateManagementUnit"
	FarmService_GetManagementUnit_FullMethodName    = "/agriculture.farm.v1.FarmService/GetManagementUnit"
	FarmService_ListManagementUnits_FullMethodName  = "/agriculture.farm.v1.FarmService/ListManagementUnits"
	FarmService_UpdateManagementUnit_FullMethodName = "/agriculture.farm.v1.FarmService/UpdateManagementUnit"
	FarmService_DeleteManagementUnit_FullMethodName = "/agriculture.farm.v1.FarmService/DeleteManagementUnit"
	FarmService_AssignFieldsToUnit_FullMethodName   = "/agriculture.farm.v1.FarmService/AssignFieldsToUnit"
	FarmService_RemoveFieldsFromUnit_FullMethodName = "/agriculture.farm.v1.FarmService/RemoveFieldsFromUnit"
)

// FarmServiceClient is the client API for FarmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FarmService provides farm management operations.
type FarmServiceClient interface {
	CreateFarm(ctx context.Context, in *CreateFarmRequest, opts ...grpc.CallOption) (*CreateFarmResponse, error)
	GetFarm(ctx context.Context, in *GetFarmRequest, opts ...grpc.CallOption) (*GetFarmResponse, error)
	ListFarms(ctx context.Context, in *ListFarmsRequest, opts ...grpc.CallOption) (*ListFarmsResponse, error)
	UpdateFarm(ctx context.Context, in *UpdateFarmRequest, opts ...grpc.CallOption) (*UpdateFarmResponse, error)
	DeleteFarm(ctx context.Context, in *DeleteFarmRequest, opts ...grpc.CallOption) (*DeleteFarmResponse, error)
	SetFarmBoundary(ctx context.Context, in *SetFarmBoundaryRequest, opts ...grpc.CallOption) (*SetFarmBoundaryResponse, error)
	GetFarmBoundary(ctx context.Context, in *GetFarmBoundaryRequest, opts ...grpc.CallOption) (*GetFarmBoundaryResponse, error)
	TransferOwnership(ctx context.Context, in *TransferOwnershipRequest, opts ...grpc.CallOption) (*TransferOwnershipResponse, error)
	CreateManagementUnit(ctx context.Context, in *CreateManagementUnitRequest, opts ...grpc.CallOption) (*CreateManagementUnitResponse, error)
	GetManagementUnit(ctx context.Context, in *GetManagementUnitRequest, opts ...grpc.CallOption) (*GetManagementUnitResponse, error)
	ListManagementUnits(ctx context.Context, in *ListManagementUnitsRequest, opts ...grpc.CallOption) (*ListManagementUnitsResponse, error)
	UpdateManagementUnit(ctx context.Context, in *UpdateManagementUnitRequest, opts ...grpc.CallOption) (*UpdateManagementUnitResponse, error)
	DeleteManagementUnit(ctx context.Context, in *DeleteManagementUnitRequest, opts ...grpc.CallOption) (*DeleteManagementUnitResponse, error)
	AssignFieldsToUnit(ctx context.Context, in *AssignFieldsToUnitRequest, opts ...grpc.CallOption) (*AssignFieldsToUnitResponse, error)
	RemoveFieldsFromUnit(ctx context.Context, in *RemoveFieldsFromUnitRequest, opts ...grpc.CallOption) (*RemoveFieldsFromUnitResponse, error)
}

type farmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFarmServiceClient(cc grpc.ClientConnInterface) FarmServiceClient {
	return &farmServiceClient{cc}
}

func (c *farmServiceClient) CreateFarm(ctx context.Context, in *CreateFarmRequest, opts ...grpc.CallOption) (*CreateFarmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFarmResponse)
	err := c.cc.Invoke(ctx, FarmService_CreateFarm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) GetFarm(ctx context.Context, in *GetFarmRequest, opts ...grpc.CallOption) (*GetFarmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFarmResponse)
	err := c.cc.Invoke(ctx, FarmService_GetFarm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) ListFarms(ctx context.Context, in *ListFarmsRequest, opts ...grpc.CallOption) (*ListFarmsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFarmsResponse)
	err := c.cc.Invoke(ctx, FarmService_ListFarms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) UpdateFarm(ctx context.Context, in *UpdateFarmRequest, opts ...grpc.CallOption) (*UpdateFarmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFarmResponse)
	err := c.cc.Invoke(ctx, FarmService_UpdateFarm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) DeleteFarm(ctx context.Context, in *DeleteFarmRequest, opts ...grpc.CallOption) (*DeleteFarmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFarmResponse)
	err := c.cc.Invoke(ctx, FarmService_DeleteFarm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) SetFarmBoundary(ctx context.Context, in *SetFarmBoundaryRequest, opts ...grpc.CallOption) (*SetFarmBoundaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetFarmBoundaryResponse)
	err := c.cc.Invoke(ctx, FarmService_SetFarmBoundary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) GetFarmBoundary(ctx context.Context, in *GetFarmBoundaryRequest, opts ...grpc.CallOption) (*GetFarmBoundaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFarmBoundaryResponse)
	err := c.cc.Invoke(ctx, FarmService_GetFarmBoundary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) TransferOwnership(ctx context.Context, in *TransferOwnershipRequest, opts ...grpc.CallOption) (*TransferOwnershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferOwnershipResponse)
	err := c.cc.Invoke(ctx, FarmService_TransferOwnership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) CreateManagementUnit(ctx context.Context, in *CreateManagementUnitRequest, opts ...grpc.CallOption) (*CreateManagementUnitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateManagementUnitResponse)
	err := c.cc.Invoke(ctx, FarmService_CreateManagementUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) GetManagementUnit(ctx context.Context, in *GetManagementUnitRequest, opts ...grpc.CallOption) (*GetManagementUnitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetManagementUnitResponse)
	err := c.cc.Invoke(ctx, FarmService_GetManagementUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) ListManagementUnits(ctx context.Context, in *ListManagementUnitsRequest, opts ...grpc.CallOption) (*ListManagementUnitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListManagementUnitsResponse)
	err := c.cc.Invoke(ctx, FarmService_ListManagementUnits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) UpdateManagementUnit(ctx context.Context, in *UpdateManagementUnitRequest, opts ...grpc.CallOption) (*UpdateManagementUnitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateManagementUnitResponse)
	err := c.cc.Invoke(ctx, FarmService_UpdateManagementUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) DeleteManagementUnit(ctx context.Context, in *DeleteManagementUnitRequest, opts ...grpc.CallOption) (*DeleteManagementUnitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteManagementUnitResponse)
	err := c.cc.Invoke(ctx, FarmService_DeleteManagementUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) AssignFieldsToUnit(ctx context.Context, in *AssignFieldsToUnitRequest, opts ...grpc.CallOption) (*AssignFieldsToUnitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignFieldsToUnitResponse)
	err := c.cc.Invoke(ctx, FarmService_AssignFieldsToUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) RemoveFieldsFromUnit(ctx context.Context, in *RemoveFieldsFromUnitRequest, opts ...grpc.CallOption) (*RemoveFieldsFromUnitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFieldsFromUnitResponse)
	err := c.cc.Invoke(ctx, FarmService_RemoveFieldsFromUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FarmServiceServer is the server API for FarmService service.
// All implementations must embed UnimplementedFarmServiceServer
// for forward compatibility.
//
// FarmService provides farm management operations.
type FarmServiceServer interface {
	CreateFarm(context.Context, *CreateFarmRequest) (*CreateFarmResponse, error)
	GetFarm(context.Context, *GetFarmRequest) (*GetFarmResponse, error)
	ListFarms(context.Context, *ListFarmsRequest) (*ListFarmsResponse, error)
	UpdateFarm(context.Context, *UpdateFarmRequest) (*UpdateFarmResponse, error)
	DeleteFarm(context.Context, *DeleteFarmRequest) (*DeleteFarmResponse, error)
	SetFarmBoundary(context.Context, *SetFarmBoundaryRequest) (*SetFarmBoundaryResponse, error)
	GetFarmBoundary(context.Context, *GetFarmBoundaryRequest) (*GetFarmBoundaryResponse, error)
	TransferOwnership(context.Context, *TransferOwnershipRequest) (*TransferOwnershipResponse, error)
	CreateManagementUnit(context.Context, *CreateManagementUnitRequest) (*CreateManagementUnitResponse, error)
	GetManagementUnit(context.Context, *GetManagementUnitRequest) (*GetManagementUnitResponse, error)
	ListManagementUnits(context.Context, *ListManagementUnitsRequest) (*ListManagementUnitsResponse, error)
	UpdateManagementUnit(context.Context, *UpdateManagementUnitRequest) (*UpdateManagementUnitResponse, error)
	DeleteManagementUnit(context.Context, *DeleteManagementUnitRequest) (*DeleteManagementUnitResponse, error)
	AssignFieldsToUnit(context.Context, *AssignFieldsToUnitRequest) (*AssignFieldsToUnitResponse, error)
	RemoveFieldsFromUnit(context.Context, *RemoveFieldsFromUnitRequest) (*RemoveFieldsFromUnitResponse, error)
	mustEmbedUnimplementedFarmServiceServer()
}

// UnimplementedFarmServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFarmServiceServer struct{}

func (UnimplementedFarmServiceServer) CreateFarm(context.Context, *CreateFarmRequest) (*CreateFarmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFarm not implemented")
}
func (UnimplementedFarmServiceServer) GetFarm(context.Context, *GetFarmRequest) (*GetFarmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFarm not implemented")
}
func (UnimplementedFarmServiceServer) ListFarms(context.Context, *ListFarmsRequest) (*ListFarmsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFarms not implemented")
}
func (UnimplementedFarmServiceServer) UpdateFarm(context.Context, *UpdateFarmRequest) (*UpdateFarmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFarm not implemented")
}
func (UnimplementedFarmServiceServer) DeleteFarm(context.Context, *DeleteFarmRequest) (*DeleteFarmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFarm not implemented")
}
func (UnimplementedFarmServiceServer) SetFarmBoundary(context.Context, *SetFarmBoundaryRequest) (*SetFarmBoundaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetFarmBoundary not implemented")
}
func (UnimplementedFarmServiceServer) GetFarmBoundary(context.Context, *GetFarmBoundaryRequest) (*GetFarmBoundaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFarmBoundary not implemented")
}
func (UnimplementedFarmServiceServer) TransferOwnership(context.Context, *TransferOwnershipRequest) (*TransferOwnershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferOwnership not implemented")
}
func (UnimplementedFarmServiceServer) CreateManagementUnit(context.Context, *CreateManagementUnitRequest) (*CreateManagementUnitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateManagementUnit not implemented")
}
func (UnimplementedFarmServiceServer) GetManagementUnit(context.Context, *GetManagementUnitRequest) (*GetManagementUnitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetManagementUnit not implemented")
}
func (UnimplementedFarmServiceServer) ListManagementUnits(context.Context, *ListManagementUnitsRequest) (*ListManagementUnitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListManagementUnits not implemented")
}
func (UnimplementedFarmServiceServer) UpdateManagementUnit(context.Context, *UpdateManagementUnitRequest) (*UpdateManagementUnitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateManagementUnit not implemented")
}
func (UnimplementedFarmServiceServer) DeleteManagementUnit(context.Context, *DeleteManagementUnitRequest) (*DeleteManagementUnitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteManagementUnit not implemented")
}
func (UnimplementedFarmServiceServer) AssignFieldsToUnit(context.Context, *AssignFieldsToUnitRequest) (*AssignFieldsToUnitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignFieldsToUnit not implemented")
}
func (UnimplementedFarmServiceServer) RemoveFieldsFromUnit(context.Context, *RemoveFieldsFromUnitRequest) (*RemoveFieldsFromUnitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFieldsFromUnit not implemented")
}
func (UnimplementedFarmServiceServer) mustEmbedUnimplementedFarmServiceServer() {}
func (UnimplementedFarmServiceServer) testEmbeddedByValue()                     {}

// UnsafeFarmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FarmServiceServer will
// result in compilation errors.
type UnsafeFarmServiceServer interface {
	mustEmbedUnimplementedFarmServiceServer()
}

func RegisterFarmServiceServer(s grpc.ServiceRegistrar, srv FarmServiceServer) {
	// If the following call panics, it indicates UnimplementedFarmServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FarmService_ServiceDesc, srv)
}

func _FarmService_CreateFarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).CreateFarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FarmService_CreateFarm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).CreateFarm(ctx, req.(*CreateFarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_GetFarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).GetFarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FarmService_GetFarm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).GetFarm(ctx, req.(*GetFarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_ListFarms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFarmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).ListFarms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FarmService_ListFarms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).ListFarms(ctx, req.(*ListFarmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_UpdateFarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).UpdateFarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FarmService_UpdateFarm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).UpdateFarm(ctx, req.(*UpdateFarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_DeleteFarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).DeleteFarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FarmService_DeleteFarm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).DeleteFarm(ctx, req.(*DeleteFarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_SetFarmBoundary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFarmBoundaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).SetFarmBoundary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FarmService_SetFarmBoundary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).SetFarmBoundary(ctx, req.(*SetFarmBoundaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_GetFarmBoundary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFarmBoundaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).GetFarmBoundary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FarmService_GetFarmBoundary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).GetFarmBoundary(ctx, req.(*GetFarmBoundaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_TransferOwnership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferOwnershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).TransferOwnership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FarmService_TransferOwnership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).TransferOwnership(ctx, req.(*TransferOwnershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_CreateManagementUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateManagementUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).CreateManagementUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FarmService_CreateManagementUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).CreateManagementUnit(ctx, req.(*CreateManagementUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_GetManagementUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManagementUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).GetManagementUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FarmService_GetManagementUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).GetManagementUnit(ctx, req.(*GetManagementUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_ListManagementUnits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListManagementUnitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).ListManagementUnits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FarmService_ListManagementUnits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).ListManagementUnits(ctx, req.(*ListManagementUnitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_UpdateManagementUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateManagementUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).UpdateManagementUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FarmService_UpdateManagementUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).UpdateManagementUnit(ctx, req.(*UpdateManagementUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_DeleteManagementUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteManagementUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).DeleteManagementUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FarmService_DeleteManagementUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).DeleteManagementUnit(ctx, req.(*DeleteManagementUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_AssignFieldsToUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignFieldsToUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).AssignFieldsToUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FarmService_AssignFieldsToUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).AssignFieldsToUnit(ctx, req.(*AssignFieldsToUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_RemoveFieldsFromUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFieldsFromUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).RemoveFieldsFromUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FarmService_RemoveFieldsFromUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).RemoveFieldsFromUnit(ctx, req.(*RemoveFieldsFromUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FarmService_ServiceDesc is the grpc.ServiceDesc for FarmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FarmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agriculture.farm.v1.FarmService",
	HandlerType: (*FarmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFarm",
			Handler:    _FarmService_CreateFarm_Handler,
		},
		{
			MethodName: "GetFarm",
			Handler:    _FarmService_GetFarm_Handler,
		},
		{
			MethodName: "ListFarms",
			Handler:    _FarmService_ListFarms_Handler,
		},
		{
			MethodName: "UpdateFarm",
			Handler:    _FarmService_UpdateFarm_Handler,
		},
		{
			MethodName: "DeleteFarm",
			Handler:    _FarmService_DeleteFarm_Handler,
		},
		{
			MethodName: "SetFarmBoundary",
			Handler:    _FarmService_SetFarmBoundary_Handler,
		},
		{
			MethodName: "GetFarmBoundary",
			Handler:    _FarmService_GetFarmBoundary_Handler,
		},
		{
			MethodName: "TransferOwnership",
			Handler:    _FarmService_TransferOwnership_Handler,
		},
		{
			MethodName: "CreateManagementUnit",
			Handler:    _FarmService_CreateManagementUnit_Handler,
		},
		{
			MethodName: "GetManagementUnit",
			Handler:    _FarmService_GetManagementUnit_Handler,
		},
		{
			MethodName: "ListManagementUnits",
			Handler:    _FarmService_ListManagementUnits_Handler,
		},
		{
			MethodName: "UpdateManagementUnit",
			Handler:    _FarmService_UpdateManagementUnit_Handler,
		},
		{
			MethodName: "DeleteManagementUnit",
			Handler:    _FarmService_DeleteManagementUnit_Handler,
		},
		{
			MethodName: "AssignFieldsToUnit",
			Handler:    _FarmService_AssignFieldsToUnit_Handler,
		},
		{
			MethodName: "RemoveFieldsFromUnit",
			Handler:    _FarmService_RemoveFieldsFromUnit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "farm.proto",
}
