#!/usr/bin/env python3
"""Generate the Dart ConnectRPC client for a service, from its proto.

Why this is generated and the older clients are not
--------------------------------------------------
mobile/packages/flutter_proto had eighteen hand-written clients against
thirty-one services, so thirteen finished backends — alert, commerce, device,
field analytics, finance, inspection, market, planning, prescription, soil lab,
sustainability, weather and agronomy's advisories — had no way to be called from
the Flutter app. Nothing failed: a client that does not exist is not an error.

One hundred and one RPCs is more than anyone should transcribe by hand, and the
transcription is exactly where a wrong method name or a mismatched response type
slips in — neither of which the Dart analyzer can catch, because the method name
is a string and the response is decoded from bytes. So they are generated.

The eighteen older clients are left alone. They carry convenience overloads that
a generator cannot invent (``getTask(id)`` rather than
``getTask(GetTaskRequest(id: id))``) and rewriting them would throw that away to
gain consistency nobody asked for. New clients start generated; a hand-written
convenience layer on top is a separate, deliberate choice.

Usage:
    scripts/gen-dart-clients.py            # write the generated clients
    scripts/gen-dart-clients.py --check    # fail if they are out of date
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "mobile" / "packages" / "flutter_proto" / "lib" / "src" / "services"
BARREL = ROOT / "mobile" / "packages" / "flutter_proto" / "lib" / "flutter_proto.dart"

SERVICE_RE = re.compile(r"^\s*service\s+(\w+)\s*\{", re.M)
PACKAGE_RE = re.compile(r"^\s*package\s+([\w.]+)\s*;", re.M)
RPC_RE = re.compile(r"^\s*rpc\s+(\w+)\s*\(\s*(\w+)\s*\)\s*returns\s*\(\s*(\w+)\s*\)", re.M)

BANNER = (
    "// GENERATED BY scripts/gen-dart-clients.py — DO NOT EDIT BY HAND.\n"
    "//\n"
    "// Regenerate with:  scripts/gen-dart-clients.py\n"
    "// The source of truth is the service's .proto. CI fails when they disagree.\n"
)

# The protos to generate a client for, as proto path -> (dart file stem, class
# name). Everything else in the tree already has a hand-written client.
#
# agronomy-service/proto/advisory.proto is not advisory-service's: the two
# declare a service with the same bare name in different packages — one keeps
# crop advisories, the other answers questions — and the existing
# AdvisoryServiceClient is the latter. Naming this one after its own service
# would shadow a client that is already in use.
TARGETS: dict[str, tuple[str, str]] = {
    "alert-service/proto/alert.proto": ("alert_service", "AlertServiceClient"),
    "commerce-service/proto/commerce.proto": ("commerce_service", "CommerceServiceClient"),
    "device-service/proto/device.proto": ("device_service", "DeviceServiceClient"),
    "analytics-service/proto/field_analytics.proto": (
        "field_analytics_service", "FieldAnalyticsServiceClient"),
    "finance-service/proto/finance.proto": ("finance_service", "FinanceServiceClient"),
    "agronomy-service/proto/inspection.proto": (
        "inspection_service", "InspectionServiceClient"),
    "market-service/proto/market.proto": ("market_service", "MarketServiceClient"),
    "planning-service/proto/planning.proto": ("planning_service", "PlanningServiceClient"),
    "prescription-service/proto/prescription.proto": (
        "prescription_service", "PrescriptionServiceClient"),
    "soil-lab-service/proto/soillab.proto": ("soillab_service", "SoilLabServiceClient"),
    "sustainability-service/proto/sustainability.proto": (
        "sustainability_service", "SustainabilityServiceClient"),
    "weather-service/proto/weather.proto": ("weather_service", "WeatherServiceClient"),
    "agronomy-service/proto/advisory.proto": (
        "agronomy_advisory_service", "AgronomyAdvisoryServiceClient"),
}


def lower_camel(name: str) -> str:
    """GetAlert -> getAlert, and RPCs that start with an acronym stay readable."""
    if not name:
        return name
    # Leading run of capitals is an acronym: AIAnalyse -> aiAnalyse.
    match = re.match(r"^([A-Z]+)(?=[A-Z][a-z]|$)", name)
    if match and len(match.group(1)) > 1:
        head = match.group(1)
        return head.lower() + name[len(head):]
    return name[0].lower() + name[1:]


def render(proto_path: Path, dart_stem: str, class_name: str) -> str:
    text = proto_path.read_text()

    package = PACKAGE_RE.search(text)
    if not package:
        raise SystemExit(f"error: {proto_path} has no package declaration")

    services = SERVICE_RE.findall(text)
    if len(services) != 1:
        raise SystemExit(
            f"error: {proto_path} declares {len(services)} services; this "
            f"generator writes one client per proto"
        )
    service_name = services[0]

    pb_alias = f"{proto_path.stem}_pb"
    lines = [
        BANNER,
        f"import '../generated/{proto_path.stem}.pb.dart' as {pb_alias};",
        "import 'base_service.dart';",
        "",
        f"/// ConnectRPC client for `{package.group(1)}.{service_name}`.",
        f"class {class_name} extends BaseService {{",
        f"  {class_name}({{",
        "    required super.baseUrl,",
        "    super.httpClient,",
        "    super.interceptors,",
        "  });",
        "",
        "  @override",
        f"  String get serviceName => '{package.group(1)}.{service_name}';",
    ]

    for method, request, response in RPC_RE.findall(text):
        lines += [
            "",
            f"  /// Calls `{method}`.",
            f"  Future<{pb_alias}.{response}> {lower_camel(method)}(",
            f"    {pb_alias}.{request} request,",
            "  ) async {",
            f"    final bytes = await callUnary('{method}', request);",
            f"    return {pb_alias}.{response}.fromBuffer(bytes);",
            "  }",
        ]

    lines += ["}", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="do not write; exit non-zero if a file is stale")
    args = parser.parse_args()

    stale: list[str] = []
    missing_export: list[str] = []
    barrel = BARREL.read_text()

    for rel, (stem, class_name) in sorted(TARGETS.items()):
        proto = ROOT / rel
        if not proto.is_file():
            print(f"error: {rel} does not exist", file=sys.stderr)
            return 1

        content = render(proto, stem, class_name)
        out = OUT_DIR / f"{stem}.dart"

        if args.check:
            if not out.exists() or out.read_text() != content:
                stale.append(f"{out.relative_to(ROOT)}")
        else:
            out.write_text(content)
            print(f"wrote {out.relative_to(ROOT)}")

        if f"export 'src/services/{stem}.dart';" not in barrel:
            missing_export.append(stem)

    problems = []
    if stale:
        problems.append(
            "out of date — run scripts/gen-dart-clients.py:\n    "
            + "\n    ".join(stale)
        )
    if missing_export:
        problems.append(
            "generated and not exported from lib/flutter_proto.dart:\n    "
            + "\n    ".join(f"export 'src/services/{s}.dart';" for s in missing_export)
        )

    if problems:
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        print("\nA client that is stale or unexported is a service the app cannot "
              "call, and\nnothing else in the build will say so.", file=sys.stderr)
        return 1

    print(f"ok: {len(TARGETS)} generated clients, all current and exported")
    return 0


if __name__ == "__main__":
    sys.exit(main())
