#!/usr/bin/env python3
"""Generate the Kubernetes base manifests from docker-compose.yml.

Why generate rather than hand-write
-----------------------------------
The hand-written base listed three services. The platform has thirty. The CD
pipeline applied `k8s/base/*.yaml`, saw no error, waited for a rollout of the
three deployments that did exist, and reported a successful deploy — for
twenty-seven services that were never deployed at all. Nothing in the pipeline
could have told anyone: a manifest that is absent produces no error, and
`kubectl rollout status` on a label selector that matches three deployments
exits zero.

docker-compose.yml is the one description of every service that is kept
current, because it is the file people actually run. Deriving the manifests
from it means a new service is deployable the moment it is runnable locally,
and `--check` in CI fails the build when the two drift apart.

Usage
-----
    scripts/k8s-manifests.py            # rewrite the generated files
    scripts/k8s-manifests.py --check    # fail if they are out of date
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
COMPOSE = ROOT / "docker-compose.yml"
SERVICES_OUT = ROOT / "k8s" / "base" / "services.yaml"
SECRETS_OUT = ROOT / "k8s" / "base" / "secrets.yaml"
INITDB_OUT = ROOT / "scripts" / "init-databases.sh"
INITVEC_OUT = ROOT / "scripts" / "init-vector-db.sh"
CI_WORKFLOW = ROOT / ".github" / "workflows" / "ci.yml"
CD_WORKFLOW = ROOT / ".github" / "workflows" / "cd.yml"
HELM_VALUES = ROOT / "k8s" / "helm" / "yieldpoint" / "values.yaml"

BANNER = (
    "# GENERATED BY scripts/k8s-manifests.py — DO NOT EDIT BY HAND.\n"
    "#\n"
    "# Regenerate with:  scripts/k8s-manifests.py\n"
    "# The source of truth is docker-compose.yml, which is the description of\n"
    "# every service that stays current because people run it. CI fails when\n"
    "# this file and that one disagree.\n"
)

# Infrastructure endpoints that mean something different inside a cluster.
#
# Compose points at container names on a user-defined network; Kubernetes
# resolves the same names through cluster DNS, so peer service URLs
# (http://field-service:8080) carry over unchanged. Only the shared
# infrastructure needs rewriting.
INFRA_REWRITES = {
    "kafka:9092": "kafka.yieldpoint.svc.cluster.local:9092",
    "http://minio:9000": "http://minio.yieldpoint.svc.cluster.local:9000",
}

# Environment variables that come from a Secret rather than being written into
# a Deployment. A password in a manifest is a password in git history.
SECRET_ENV = {
    "JWT_SECRET": ("yieldpoint-secrets", "JWT_SECRET"),
    "S3_ACCESS_KEY_ID": ("yieldpoint-secrets", "S3_ACCESS_KEY_ID"),
    "S3_SECRET_ACCESS_KEY": ("yieldpoint-secrets", "S3_SECRET_ACCESS_KEY"),
}

# Services that carry more than the default request load, and the ceiling their
# autoscaler is allowed to reach. Everything absent from here gets the default.
#
# Named rather than uniform because the shapes genuinely differ: tile serving is
# a fan-out of small reads, satellite processing is a handful of long CPU-bound
# jobs, and giving them the same limits either starves one or wastes the other.
RESOURCE_PROFILES = {
    "satellite-processing-service": {"cpu": "2000m", "memory": "2Gi", "max": 6},
    "satellite-ingestion-service": {"cpu": "1000m", "memory": "1Gi", "max": 6},
    "satellite-analytics-service": {"cpu": "1000m", "memory": "1Gi", "max": 6},
    "satellite-tile-service": {"cpu": "1000m", "memory": "1Gi", "max": 12},
    "vegetation-index-service": {"cpu": "1000m", "memory": "1Gi", "max": 6},
    "plant-diagnosis-service": {"cpu": "1000m", "memory": "1Gi", "max": 8},
    "analytics-service": {"cpu": "1000m", "memory": "1Gi", "max": 6},
}

DEFAULT_PROFILE = {"cpu": "500m", "memory": "512Mi", "max": 8}

BASE_REPLICAS = 2


def load_services() -> dict[str, dict]:
    """Every Go microservice in compose, keyed by name."""
    compose = yaml.safe_load(COMPOSE.read_text())
    out = {}
    for name, spec in compose.get("services", {}).items():
        build = spec.get("build")
        if not isinstance(build, dict):
            continue
        args = build.get("args") or {}
        if "SERVICE" not in args:
            continue
        out[name] = spec
    return dict(sorted(out.items()))


def database_key(name: str) -> str:
    """The key in the database-urls Secret for a service."""
    return name.replace("-", "_").upper() + "_DATABASE_URL"


def resolve_env(name: str, spec: dict) -> tuple[list[tuple[str, str]], list[str]]:
    """Split a service's compose environment into plain values and secrets.

    Returns the literal (name, value) pairs and the names that come from a
    Secret. A compose interpolation like ``${FOO:-default}`` is resolved to its
    default, which is what a local run uses; one with no default
    (``${FOO:?message}``) has no safe value and is either a known secret or is
    dropped with a warning rather than being written out as the literal string
    ``${FOO}``.
    """
    env = spec.get("environment") or {}
    literals: list[tuple[str, str]] = []
    secrets: list[str] = []

    for key, raw in env.items():
        if key in SECRET_ENV:
            secrets.append(key)
            continue
        if key == "DATABASE_URL":
            secrets.append(key)
            continue

        value = str(raw)
        # ${VAR:-default} → default; the default is what the service runs on.
        value = re.sub(r"\$\{[A-Za-z_][A-Za-z0-9_]*:-([^}]*)\}", r"\1", value)
        if "${" in value:
            # ${VAR:?...} or a bare ${VAR}: no value this file can know.
            print(
                f"note: {name}: {key} has no default in compose and is not a known "
                f"secret; it is left for the cluster's ConfigMap to supply",
                file=sys.stderr,
            )
            continue

        for old, new in INFRA_REWRITES.items():
            value = value.replace(old, new)
        literals.append((key, value))

    return literals, secrets


def render_service(name: str, spec: dict) -> str:
    profile = RESOURCE_PROFILES.get(name, DEFAULT_PROFILE)
    literals, secrets = resolve_env(name, spec)

    env_block = ""
    for key, (secret_name, secret_key) in SECRET_ENV.items():
        if key in secrets:
            env_block += (
                f"            - name: {key}\n"
                f"              valueFrom:\n"
                f"                secretKeyRef:\n"
                f"                  name: {secret_name}\n"
                f"                  key: {secret_key}\n"
            )
    if "DATABASE_URL" in secrets:
        env_block += (
            f"            - name: DATABASE_URL\n"
            f"              valueFrom:\n"
            f"                secretKeyRef:\n"
            f"                  name: database-urls\n"
            f"                  key: {database_key(name)}\n"
        )
    for key, value in literals:
        env_block += f'            - name: {key}\n              value: "{value}"\n'

    return f"""---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  namespace: yieldpoint
  labels:
    app.kubernetes.io/name: {name}
    app.kubernetes.io/part-of: yieldpoint
spec:
  replicas: {BASE_REPLICAS}
  selector:
    matchLabels:
      app.kubernetes.io/name: {name}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # One new pod at a time and never fewer than the current count: a
      # rolling deploy that is allowed to take a pod down first drops requests
      # on a two-replica service.
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {name}
        app.kubernetes.io/part-of: yieldpoint
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {name}
          image: ghcr.io/ppusapati/yieldpoint/{name}:latest
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: yieldpoint-config
          env:
{env_block}          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "{profile['memory']}"
              cpu: "{profile['cpu']}"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          # Readiness gates traffic; liveness restarts a wedged process. They
          # point at different endpoints on purpose — /ready checks the
          # database, and a database blip must take the pod out of the load
          # balancer without restarting it into a crash loop.
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: http
            # Migrations run at startup, so first boot after a schema change
            # can take a while. Without this the liveness probe kills the pod
            # mid-migration and the next one starts the same migration again.
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 60
---
apiVersion: v1
kind: Service
metadata:
  name: {name}
  namespace: yieldpoint
  labels:
    app.kubernetes.io/name: {name}
    app.kubernetes.io/part-of: yieldpoint
spec:
  selector:
    app.kubernetes.io/name: {name}
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {name}
  namespace: yieldpoint
spec:
  # One pod may go at a time during a node drain. Without a budget the cluster
  # autoscaler is free to evict both replicas of a two-replica service at once.
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {name}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {name}
  namespace: yieldpoint
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {name}
  minReplicas: {BASE_REPLICAS}
  maxReplicas: {profile['max']}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleDown:
      # Five minutes before scaling down. A shorter window makes the autoscaler
      # chase a spiky load up and down, which costs more than the replicas it
      # removes.
      stabilizationWindowSeconds: 300
"""


def render_ai_gateway() -> str:
    """The Rust inference gateway.

    Hand-shaped rather than generated: it speaks gRPC on 50051 with no HTTP
    health endpoint, holds model weights in memory, and is the one component
    here whose cost is GPU-shaped. Running it through the Go service template
    would give it an HTTP probe against a port that does not serve HTTP, and
    the pod would be restarted for ever.
    """
    return """---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-gateway
  namespace: yieldpoint
  labels:
    app.kubernetes.io/name: ai-gateway
    app.kubernetes.io/part-of: yieldpoint
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ai-gateway
        app.kubernetes.io/part-of: yieldpoint
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ai-gateway
          image: ghcr.io/ppusapati/yieldpoint/ai-gateway:latest
          ports:
            - containerPort: 50051
              name: grpc
          env:
            - name: RUST_LOG
              value: "ai_gateway=info"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "2000m"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          readinessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 15
            periodSeconds: 20
          startupProbe:
            grpc:
              port: 50051
            # Model weights are loaded and warmed at startup, which takes far
            # longer than a Go service's boot.
            periodSeconds: 10
            failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: ai-gateway
  namespace: yieldpoint
  labels:
    app.kubernetes.io/name: ai-gateway
    app.kubernetes.io/part-of: yieldpoint
spec:
  selector:
    app.kubernetes.io/name: ai-gateway
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ai-gateway
  namespace: yieldpoint
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-gateway
"""


def render_api_gateway() -> str:
    """The Caddy edge gateway.

    Every request to the platform passes through it, so it runs more replicas
    than anything behind it and is the one Deployment whose PodDisruptionBudget
    is written as a minimum rather than a maximum: losing all of it takes the
    platform down regardless of how healthy the services behind it are.
    """
    return """---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: yieldpoint
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: yieldpoint
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-gateway
        app.kubernetes.io/part-of: yieldpoint
    spec:
      # Spread across nodes. Three replicas on one node is one node away from
      # no gateway at all.
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: api-gateway
      containers:
        - name: api-gateway
          image: ghcr.io/ppusapati/yieldpoint/api-gateway:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: GATEWAY_PORT
              value: "8080"
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: yieldpoint-config
                  key: CORS_ORIGIN
                  optional: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: yieldpoint
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: yieldpoint
spec:
  selector:
    app.kubernetes.io/name: api-gateway
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway
  namespace: yieldpoint
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway
  namespace: yieldpoint
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
"""


def render_realtime() -> str:
    """The real-time transport: /ws and /events.

    Written out rather than run through the service template, because the one
    assumption that template makes about every service is the one thing this
    binary cannot do: scale out.

    The hub, the presence registry and the collaborative-inspection sessions are
    all in process memory, and no backplane joins two copies of them. At two
    replicas a field's watchers are split across pods and each half sees only
    its own half's events; two people editing the same inspection get two
    sessions that silently diverge and the last writer wins. So: one replica, no
    autoscaler, and Recreate rather than RollingUpdate — a rolling deploy runs
    the new pod alongside the old one, which is the split-room state again for
    as long as the rollout takes. Clients reconnect, which they must handle
    anyway; a tractor drives out of signal several times a day.

    Nothing about that is permanent. A Redis or Kafka fan-out behind the hub
    would make this horizontally scalable, and then it belongs in the template
    like everything else.
    """
    return """---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime
  namespace: yieldpoint
  labels:
    app.kubernetes.io/name: realtime
    app.kubernetes.io/part-of: yieldpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: realtime
  strategy:
    # See render_realtime(): two live pods split every room, so the old one goes
    # before the new one arrives.
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: realtime
        app.kubernetes.io/part-of: yieldpoint
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      # Longer than the 30s shutdown in cmd/realtime/main.go. At the default of
      # 30s the kubelet's SIGKILL lands exactly as the server gives up on its
      # own deadline, so a drain would cut open WebSockets mid-frame every time.
      terminationGracePeriodSeconds: 45
      containers:
        - name: realtime
          image: ghcr.io/ppusapati/yieldpoint/realtime:latest
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: yieldpoint-config
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: yieldpoint-secrets
                  key: JWT_SECRET
            - name: PORT
              value: "8080"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              # Memory is the dimension that matters: one entry per open
              # connection, per room member and per live inspection session.
              memory: "512Mi"
              cpu: "500m"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: realtime
  namespace: yieldpoint
  labels:
    app.kubernetes.io/name: realtime
    app.kubernetes.io/part-of: yieldpoint
spec:
  selector:
    app.kubernetes.io/name: realtime
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: realtime
  namespace: yieldpoint
spec:
  # A single replica, so this cannot protect availability — it can only refuse
  # to let a node drain, for ever. It is written as "one may go" deliberately:
  # the transport is reconnectable and a stuck drain is worse than a reconnect.
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: realtime
"""



def service_database(name: str, spec: dict) -> tuple[str, str] | None:
    """The (host, database) a service connects to, read out of its compose DSN."""
    env = spec.get("environment") or {}
    dsn = env.get("DATABASE_URL")
    if not isinstance(dsn, str):
        return None
    # The value is ${FOO_DATABASE_URL:-postgres://user:${PW:?...}@postgres:5432/foo_service?...}.
    # Anchored on the host and port rather than on "postgres://", because the
    # credentials in between contain a nested ${...} whose braces and spaces
    # end a naive character class early — which silently yielded one database
    # out of twenty-nine when the DSNs moved off the superuser.
    match = re.search(r"@([A-Za-z0-9_-]+):\d+/([A-Za-z0-9_]+)", dsn)
    return match.groups() if match else None


def render_initdb(services: dict[str, dict], host: str, purpose: str) -> str:
    """The cluster bootstrap script docker-compose mounts into postgres.

    Generated because the hand-written one had gone seven databases stale:
    advisory, device, finance, market, planning, soil-lab and sustainability
    all had migrations and no database to apply them to, so those containers
    could not start at all. A list of services maintained by hand goes out of
    date the moment somebody adds a service, and nothing says so.
    """
    databases = sorted(
        {
            target[1]
            for name, spec in services.items()
            if (target := service_database(name, spec)) and target[0] == host
        }
    )
    listing = "\n".join(f"  {db}" for db in databases)
    return f"""#!/usr/bin/env bash
# Generated by scripts/k8s-manifests.py from docker-compose.yml. Do not edit.
#
# Creates the roles services connect with, and one database per service, inside
# {purpose}. Mounted as a docker-entrypoint-initdb.d
# script by docker-compose, so it runs once on an empty cluster.
#
# Three roles, because one would defeat row-level security:
#
#   yp_migrator  owns the schema and is the only role that runs DDL. Services
#                migrate as this at boot and then drop it.
#   yp_app       DML only, and NOT a superuser, so the RLS policies apply to
#                it. This is what the request path connects as.
#   yp_system    DML with BYPASSRLS, for the two things that legitimately read
#                across tenants: alert-service's rule scanner and
#                irrigation-service's run-closing sweep. A scoped role would
#                leave both reading nothing, silently.
#
# Compose used to run every service as the superuser, which bypasses RLS
# entirely — so the policies had never run anywhere, in development or in CI.
set -euo pipefail

DATABASES=(
{listing}
)

psql -v ON_ERROR_STOP=1 \
  -v migrator_pw="${{DB_MIGRATOR_PASSWORD}}" \
  -v app_pw="${{DB_APP_PASSWORD}}" \
  -v system_pw="${{DB_SYSTEM_PASSWORD}}" \
  --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<'SQL'
-- \gexec rather than a DO block: psql does not substitute :'variables'
-- inside dollar-quoted strings, so a password would be sent literally as
-- ":'app_pw'".
SELECT format('CREATE ROLE yp_migrator LOGIN PASSWORD %L', :'migrator_pw')
WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'yp_migrator')\gexec

SELECT format('CREATE ROLE yp_app LOGIN PASSWORD %L', :'app_pw')
WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'yp_app')\gexec

-- BYPASSRLS, and only this role has it.
SELECT format('CREATE ROLE yp_system LOGIN BYPASSRLS PASSWORD %L', :'system_pw')
WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'yp_system')\gexec
SQL

for db in "${{DATABASES[@]}}"; do
  echo "Creating database: $db"
  psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-SQL
    SELECT 'CREATE DATABASE $db OWNER yp_migrator'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$db')\gexec
SQL

  # Grants inside the database. The default privileges matter more than the
  # explicit ones: migrations have not run yet, so every table a service uses
  # is created after this, by yp_migrator, and would otherwise be readable by
  # nobody but its owner.
  psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$db" <<-SQL
    GRANT ALL ON SCHEMA public TO yp_migrator;
    GRANT USAGE ON SCHEMA public TO yp_app, yp_system;

    ALTER DEFAULT PRIVILEGES FOR ROLE yp_migrator IN SCHEMA public
      GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO yp_app, yp_system;
    ALTER DEFAULT PRIVILEGES FOR ROLE yp_migrator IN SCHEMA public
      GRANT USAGE, SELECT ON SEQUENCES TO yp_app, yp_system;
SQL
done

echo "Created ${{#DATABASES[@]}} databases and the yp_migrator/yp_app/yp_system roles."
"""


def render_services(services: dict[str, dict]) -> str:
    parts = [BANNER]
    for name, spec in services.items():
        parts.append(render_service(name, spec))
    # realtime serves /ws and /events and is built from the shared Dockerfile
    # with CMD_PATH rather than SERVICE, so it is not in load_services() either.
    # It had no Kubernetes manifest at all until now, and neither did the
    # monolith it replaces — which means the real-time features have never run
    # in a cluster, only under compose.
    parts.append(render_realtime())
    # The two gateways are not Go microservices and are not built from the
    # shared Dockerfile, so compose does not describe them with a SERVICE arg.
    # They are still deployed, and leaving them out of the generated base would
    # reintroduce exactly the hole this script exists to close.
    parts.append(render_ai_gateway())
    parts.append(render_api_gateway())
    return "".join(parts)


def render_secrets(services: dict[str, dict]) -> str:
    keys = []
    for name, spec in services.items():
        env = spec.get("environment") or {}
        if "DATABASE_URL" in env:
            keys.append(database_key(name))

    rows = "".join(f'  {key}: ""\n' for key in sorted(keys))
    return f"""{BANNER}#
# The values are empty on purpose. They are filled by the cluster's secret
# manager — sealed-secrets, External Secrets or the CD pipeline — and a real
# connection string committed here would be a credential in git history that
# rotating the database does not remove.
apiVersion: v1
kind: Secret
metadata:
  name: yieldpoint-secrets
  namespace: yieldpoint
type: Opaque
stringData:
  POSTGRES_PASSWORD: ""
  POSTGRES_REPLICATION_PASSWORD: ""
  JWT_SECRET: ""
  S3_ACCESS_KEY_ID: ""
  S3_SECRET_ACCESS_KEY: ""
  EXTERNAL_API_KEY: ""
  GRAFANA_ADMIN_PASSWORD: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: database-urls
  namespace: yieldpoint
type: Opaque
stringData:
{rows}"""


def workflow_matrix(path: Path) -> set[str]:
    """The service names in a workflow's build matrix."""
    text = path.read_text()
    names: set[str] = set()
    for match in re.finditer(r"^\s+service:\s*$", text, re.M):
        for line in text[match.end():].splitlines()[1:]:
            entry = re.match(r"^\s+- ([a-z0-9-]+)\s*$", line)
            if not entry:
                break
            names.add(entry.group(1))
    return names


def helm_services() -> set[str]:
    values = yaml.safe_load(HELM_VALUES.read_text())
    return {f"{key}-service" for key in (values.get("services") or {})}


def check_consumers(services: dict[str, dict]) -> list[str]:
    """Every place that keeps its own copy of the service list must agree."""
    expected = set(services)
    problems = []

    for label, actual in [
        ("the CI build matrix (.github/workflows/ci.yml)", workflow_matrix(CI_WORKFLOW)),
        ("the CD build matrix (.github/workflows/cd.yml)", workflow_matrix(CD_WORKFLOW)),
        ("the Helm chart's services (k8s/helm/yieldpoint/values.yaml)", helm_services()),
    ]:
        missing = sorted(expected - actual)
        extra = sorted(actual - expected)
        if missing:
            problems.append(f"{label} is missing: {', '.join(missing)}")
        if extra:
            problems.append(f"{label} lists services compose does not build: {', '.join(extra)}")

    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit non-zero if the generated files are stale",
    )
    args = parser.parse_args()

    services = load_services()
    if not services:
        print("error: no services found in docker-compose.yml", file=sys.stderr)
        return 1

    outputs = {
        SERVICES_OUT: render_services(services),
        SECRETS_OUT: render_secrets(services),
        INITDB_OUT: render_initdb(
            services, "postgres", "the shared PostgreSQL instance"
        ),
        INITVEC_OUT: render_initdb(
            services,
            "pgvector",
            "the pgvector instance, which advisory-service uses for its "
            "retrieval embeddings",
        ),
    }

    problems = check_consumers(services)

    if args.check:
        for path, content in outputs.items():
            existing = path.read_text() if path.exists() else ""
            if existing != content:
                problems.append(
                    f"{path.relative_to(ROOT)} is out of date — run scripts/k8s-manifests.py"
                )
        if problems:
            print(
                f"\n{len(problems)} problem(s). The deployed manifests and the service "
                f"list have drifted apart, which is how a service ends up built by CI, "
                f"pushed by CD, and never deployed:\n",
                file=sys.stderr,
            )
            for problem in problems:
                print(f"  - {problem}", file=sys.stderr)
            return 1
        print(f"ok: {len(services)} services, manifests up to date")
        return 0

    for path, content in outputs.items():
        path.write_text(content)
        if path.suffix == ".sh":
            path.chmod(0o755)
        print(f"wrote {path.relative_to(ROOT)}")

    if problems:
        print("\nStill out of step (these are hand-maintained):", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 1

    print(f"ok: {len(services)} services")
    return 0


if __name__ == "__main__":
    sys.exit(main())
