// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: field_analytics.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "p9e.in/samavaya/agriculture/analytics-service/api/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FieldAnalyticsServiceName is the fully-qualified name of the FieldAnalyticsService service.
	FieldAnalyticsServiceName = "agriculture.field.analytics.v1.FieldAnalyticsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FieldAnalyticsServiceGetHistoricalMetricsProcedure is the fully-qualified name of the
	// FieldAnalyticsService's GetHistoricalMetrics RPC.
	FieldAnalyticsServiceGetHistoricalMetricsProcedure = "/agriculture.field.analytics.v1.FieldAnalyticsService/GetHistoricalMetrics"
	// FieldAnalyticsServiceListFieldAnalyticsProcedure is the fully-qualified name of the
	// FieldAnalyticsService's ListFieldAnalytics RPC.
	FieldAnalyticsServiceListFieldAnalyticsProcedure = "/agriculture.field.analytics.v1.FieldAnalyticsService/ListFieldAnalytics"
	// FieldAnalyticsServiceGetFieldAnalyticsProcedure is the fully-qualified name of the
	// FieldAnalyticsService's GetFieldAnalytics RPC.
	FieldAnalyticsServiceGetFieldAnalyticsProcedure = "/agriculture.field.analytics.v1.FieldAnalyticsService/GetFieldAnalytics"
	// FieldAnalyticsServiceGetSeasonComparisonsProcedure is the fully-qualified name of the
	// FieldAnalyticsService's GetSeasonComparisons RPC.
	FieldAnalyticsServiceGetSeasonComparisonsProcedure = "/agriculture.field.analytics.v1.FieldAnalyticsService/GetSeasonComparisons"
	// FieldAnalyticsServiceGetRotationAnalysisProcedure is the fully-qualified name of the
	// FieldAnalyticsService's GetRotationAnalysis RPC.
	FieldAnalyticsServiceGetRotationAnalysisProcedure = "/agriculture.field.analytics.v1.FieldAnalyticsService/GetRotationAnalysis"
	// FieldAnalyticsServiceGetCrossFieldTrendsProcedure is the fully-qualified name of the
	// FieldAnalyticsService's GetCrossFieldTrends RPC.
	FieldAnalyticsServiceGetCrossFieldTrendsProcedure = "/agriculture.field.analytics.v1.FieldAnalyticsService/GetCrossFieldTrends"
)

// FieldAnalyticsServiceClient is a client for the
// agriculture.field.analytics.v1.FieldAnalyticsService service.
type FieldAnalyticsServiceClient interface {
	// GetHistoricalMetrics returns aggregate metrics with optional farm/field
	// and time-period filters.
	GetHistoricalMetrics(context.Context, *connect.Request[v1.GetHistoricalMetricsRequest]) (*connect.Response[v1.GetHistoricalMetricsResponse], error)
	// ListFieldAnalytics lists analytics summaries for all fields, optionally
	// filtered by farm.
	ListFieldAnalytics(context.Context, *connect.Request[v1.ListFieldAnalyticsRequest]) (*connect.Response[v1.ListFieldAnalyticsResponse], error)
	// GetFieldAnalytics returns detailed analytics for a single field.
	GetFieldAnalytics(context.Context, *connect.Request[v1.GetFieldAnalyticsRequest]) (*connect.Response[v1.GetFieldAnalyticsResponse], error)
	// GetSeasonComparisons returns season-by-season comparison data for a field.
	GetSeasonComparisons(context.Context, *connect.Request[v1.GetSeasonComparisonsRequest]) (*connect.Response[v1.GetSeasonComparisonsResponse], error)
	// GetRotationAnalysis returns crop rotation analysis for a field.
	GetRotationAnalysis(context.Context, *connect.Request[v1.GetRotationAnalysisRequest]) (*connect.Response[v1.GetRotationAnalysisResponse], error)
	// GetCrossFieldTrends returns multi-field trend comparison data.
	GetCrossFieldTrends(context.Context, *connect.Request[v1.GetCrossFieldTrendsRequest]) (*connect.Response[v1.GetCrossFieldTrendsResponse], error)
}

// NewFieldAnalyticsServiceClient constructs a client for the
// agriculture.field.analytics.v1.FieldAnalyticsService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFieldAnalyticsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FieldAnalyticsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	fieldAnalyticsServiceMethods := v1.File_field_analytics_proto.Services().ByName("FieldAnalyticsService").Methods()
	return &fieldAnalyticsServiceClient{
		getHistoricalMetrics: connect.NewClient[v1.GetHistoricalMetricsRequest, v1.GetHistoricalMetricsResponse](
			httpClient,
			baseURL+FieldAnalyticsServiceGetHistoricalMetricsProcedure,
			connect.WithSchema(fieldAnalyticsServiceMethods.ByName("GetHistoricalMetrics")),
			connect.WithClientOptions(opts...),
		),
		listFieldAnalytics: connect.NewClient[v1.ListFieldAnalyticsRequest, v1.ListFieldAnalyticsResponse](
			httpClient,
			baseURL+FieldAnalyticsServiceListFieldAnalyticsProcedure,
			connect.WithSchema(fieldAnalyticsServiceMethods.ByName("ListFieldAnalytics")),
			connect.WithClientOptions(opts...),
		),
		getFieldAnalytics: connect.NewClient[v1.GetFieldAnalyticsRequest, v1.GetFieldAnalyticsResponse](
			httpClient,
			baseURL+FieldAnalyticsServiceGetFieldAnalyticsProcedure,
			connect.WithSchema(fieldAnalyticsServiceMethods.ByName("GetFieldAnalytics")),
			connect.WithClientOptions(opts...),
		),
		getSeasonComparisons: connect.NewClient[v1.GetSeasonComparisonsRequest, v1.GetSeasonComparisonsResponse](
			httpClient,
			baseURL+FieldAnalyticsServiceGetSeasonComparisonsProcedure,
			connect.WithSchema(fieldAnalyticsServiceMethods.ByName("GetSeasonComparisons")),
			connect.WithClientOptions(opts...),
		),
		getRotationAnalysis: connect.NewClient[v1.GetRotationAnalysisRequest, v1.GetRotationAnalysisResponse](
			httpClient,
			baseURL+FieldAnalyticsServiceGetRotationAnalysisProcedure,
			connect.WithSchema(fieldAnalyticsServiceMethods.ByName("GetRotationAnalysis")),
			connect.WithClientOptions(opts...),
		),
		getCrossFieldTrends: connect.NewClient[v1.GetCrossFieldTrendsRequest, v1.GetCrossFieldTrendsResponse](
			httpClient,
			baseURL+FieldAnalyticsServiceGetCrossFieldTrendsProcedure,
			connect.WithSchema(fieldAnalyticsServiceMethods.ByName("GetCrossFieldTrends")),
			connect.WithClientOptions(opts...),
		),
	}
}

// fieldAnalyticsServiceClient implements FieldAnalyticsServiceClient.
type fieldAnalyticsServiceClient struct {
	getHistoricalMetrics *connect.Client[v1.GetHistoricalMetricsRequest, v1.GetHistoricalMetricsResponse]
	listFieldAnalytics   *connect.Client[v1.ListFieldAnalyticsRequest, v1.ListFieldAnalyticsResponse]
	getFieldAnalytics    *connect.Client[v1.GetFieldAnalyticsRequest, v1.GetFieldAnalyticsResponse]
	getSeasonComparisons *connect.Client[v1.GetSeasonComparisonsRequest, v1.GetSeasonComparisonsResponse]
	getRotationAnalysis  *connect.Client[v1.GetRotationAnalysisRequest, v1.GetRotationAnalysisResponse]
	getCrossFieldTrends  *connect.Client[v1.GetCrossFieldTrendsRequest, v1.GetCrossFieldTrendsResponse]
}

// GetHistoricalMetrics calls
// agriculture.field.analytics.v1.FieldAnalyticsService.GetHistoricalMetrics.
func (c *fieldAnalyticsServiceClient) GetHistoricalMetrics(ctx context.Context, req *connect.Request[v1.GetHistoricalMetricsRequest]) (*connect.Response[v1.GetHistoricalMetricsResponse], error) {
	return c.getHistoricalMetrics.CallUnary(ctx, req)
}

// ListFieldAnalytics calls agriculture.field.analytics.v1.FieldAnalyticsService.ListFieldAnalytics.
func (c *fieldAnalyticsServiceClient) ListFieldAnalytics(ctx context.Context, req *connect.Request[v1.ListFieldAnalyticsRequest]) (*connect.Response[v1.ListFieldAnalyticsResponse], error) {
	return c.listFieldAnalytics.CallUnary(ctx, req)
}

// GetFieldAnalytics calls agriculture.field.analytics.v1.FieldAnalyticsService.GetFieldAnalytics.
func (c *fieldAnalyticsServiceClient) GetFieldAnalytics(ctx context.Context, req *connect.Request[v1.GetFieldAnalyticsRequest]) (*connect.Response[v1.GetFieldAnalyticsResponse], error) {
	return c.getFieldAnalytics.CallUnary(ctx, req)
}

// GetSeasonComparisons calls
// agriculture.field.analytics.v1.FieldAnalyticsService.GetSeasonComparisons.
func (c *fieldAnalyticsServiceClient) GetSeasonComparisons(ctx context.Context, req *connect.Request[v1.GetSeasonComparisonsRequest]) (*connect.Response[v1.GetSeasonComparisonsResponse], error) {
	return c.getSeasonComparisons.CallUnary(ctx, req)
}

// GetRotationAnalysis calls
// agriculture.field.analytics.v1.FieldAnalyticsService.GetRotationAnalysis.
func (c *fieldAnalyticsServiceClient) GetRotationAnalysis(ctx context.Context, req *connect.Request[v1.GetRotationAnalysisRequest]) (*connect.Response[v1.GetRotationAnalysisResponse], error) {
	return c.getRotationAnalysis.CallUnary(ctx, req)
}

// GetCrossFieldTrends calls
// agriculture.field.analytics.v1.FieldAnalyticsService.GetCrossFieldTrends.
func (c *fieldAnalyticsServiceClient) GetCrossFieldTrends(ctx context.Context, req *connect.Request[v1.GetCrossFieldTrendsRequest]) (*connect.Response[v1.GetCrossFieldTrendsResponse], error) {
	return c.getCrossFieldTrends.CallUnary(ctx, req)
}

// FieldAnalyticsServiceHandler is an implementation of the
// agriculture.field.analytics.v1.FieldAnalyticsService service.
type FieldAnalyticsServiceHandler interface {
	// GetHistoricalMetrics returns aggregate metrics with optional farm/field
	// and time-period filters.
	GetHistoricalMetrics(context.Context, *connect.Request[v1.GetHistoricalMetricsRequest]) (*connect.Response[v1.GetHistoricalMetricsResponse], error)
	// ListFieldAnalytics lists analytics summaries for all fields, optionally
	// filtered by farm.
	ListFieldAnalytics(context.Context, *connect.Request[v1.ListFieldAnalyticsRequest]) (*connect.Response[v1.ListFieldAnalyticsResponse], error)
	// GetFieldAnalytics returns detailed analytics for a single field.
	GetFieldAnalytics(context.Context, *connect.Request[v1.GetFieldAnalyticsRequest]) (*connect.Response[v1.GetFieldAnalyticsResponse], error)
	// GetSeasonComparisons returns season-by-season comparison data for a field.
	GetSeasonComparisons(context.Context, *connect.Request[v1.GetSeasonComparisonsRequest]) (*connect.Response[v1.GetSeasonComparisonsResponse], error)
	// GetRotationAnalysis returns crop rotation analysis for a field.
	GetRotationAnalysis(context.Context, *connect.Request[v1.GetRotationAnalysisRequest]) (*connect.Response[v1.GetRotationAnalysisResponse], error)
	// GetCrossFieldTrends returns multi-field trend comparison data.
	GetCrossFieldTrends(context.Context, *connect.Request[v1.GetCrossFieldTrendsRequest]) (*connect.Response[v1.GetCrossFieldTrendsResponse], error)
}

// NewFieldAnalyticsServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFieldAnalyticsServiceHandler(svc FieldAnalyticsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	fieldAnalyticsServiceMethods := v1.File_field_analytics_proto.Services().ByName("FieldAnalyticsService").Methods()
	fieldAnalyticsServiceGetHistoricalMetricsHandler := connect.NewUnaryHandler(
		FieldAnalyticsServiceGetHistoricalMetricsProcedure,
		svc.GetHistoricalMetrics,
		connect.WithSchema(fieldAnalyticsServiceMethods.ByName("GetHistoricalMetrics")),
		connect.WithHandlerOptions(opts...),
	)
	fieldAnalyticsServiceListFieldAnalyticsHandler := connect.NewUnaryHandler(
		FieldAnalyticsServiceListFieldAnalyticsProcedure,
		svc.ListFieldAnalytics,
		connect.WithSchema(fieldAnalyticsServiceMethods.ByName("ListFieldAnalytics")),
		connect.WithHandlerOptions(opts...),
	)
	fieldAnalyticsServiceGetFieldAnalyticsHandler := connect.NewUnaryHandler(
		FieldAnalyticsServiceGetFieldAnalyticsProcedure,
		svc.GetFieldAnalytics,
		connect.WithSchema(fieldAnalyticsServiceMethods.ByName("GetFieldAnalytics")),
		connect.WithHandlerOptions(opts...),
	)
	fieldAnalyticsServiceGetSeasonComparisonsHandler := connect.NewUnaryHandler(
		FieldAnalyticsServiceGetSeasonComparisonsProcedure,
		svc.GetSeasonComparisons,
		connect.WithSchema(fieldAnalyticsServiceMethods.ByName("GetSeasonComparisons")),
		connect.WithHandlerOptions(opts...),
	)
	fieldAnalyticsServiceGetRotationAnalysisHandler := connect.NewUnaryHandler(
		FieldAnalyticsServiceGetRotationAnalysisProcedure,
		svc.GetRotationAnalysis,
		connect.WithSchema(fieldAnalyticsServiceMethods.ByName("GetRotationAnalysis")),
		connect.WithHandlerOptions(opts...),
	)
	fieldAnalyticsServiceGetCrossFieldTrendsHandler := connect.NewUnaryHandler(
		FieldAnalyticsServiceGetCrossFieldTrendsProcedure,
		svc.GetCrossFieldTrends,
		connect.WithSchema(fieldAnalyticsServiceMethods.ByName("GetCrossFieldTrends")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agriculture.field.analytics.v1.FieldAnalyticsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FieldAnalyticsServiceGetHistoricalMetricsProcedure:
			fieldAnalyticsServiceGetHistoricalMetricsHandler.ServeHTTP(w, r)
		case FieldAnalyticsServiceListFieldAnalyticsProcedure:
			fieldAnalyticsServiceListFieldAnalyticsHandler.ServeHTTP(w, r)
		case FieldAnalyticsServiceGetFieldAnalyticsProcedure:
			fieldAnalyticsServiceGetFieldAnalyticsHandler.ServeHTTP(w, r)
		case FieldAnalyticsServiceGetSeasonComparisonsProcedure:
			fieldAnalyticsServiceGetSeasonComparisonsHandler.ServeHTTP(w, r)
		case FieldAnalyticsServiceGetRotationAnalysisProcedure:
			fieldAnalyticsServiceGetRotationAnalysisHandler.ServeHTTP(w, r)
		case FieldAnalyticsServiceGetCrossFieldTrendsProcedure:
			fieldAnalyticsServiceGetCrossFieldTrendsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFieldAnalyticsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFieldAnalyticsServiceHandler struct{}

func (UnimplementedFieldAnalyticsServiceHandler) GetHistoricalMetrics(context.Context, *connect.Request[v1.GetHistoricalMetricsRequest]) (*connect.Response[v1.GetHistoricalMetricsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.field.analytics.v1.FieldAnalyticsService.GetHistoricalMetrics is not implemented"))
}

func (UnimplementedFieldAnalyticsServiceHandler) ListFieldAnalytics(context.Context, *connect.Request[v1.ListFieldAnalyticsRequest]) (*connect.Response[v1.ListFieldAnalyticsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.field.analytics.v1.FieldAnalyticsService.ListFieldAnalytics is not implemented"))
}

func (UnimplementedFieldAnalyticsServiceHandler) GetFieldAnalytics(context.Context, *connect.Request[v1.GetFieldAnalyticsRequest]) (*connect.Response[v1.GetFieldAnalyticsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.field.analytics.v1.FieldAnalyticsService.GetFieldAnalytics is not implemented"))
}

func (UnimplementedFieldAnalyticsServiceHandler) GetSeasonComparisons(context.Context, *connect.Request[v1.GetSeasonComparisonsRequest]) (*connect.Response[v1.GetSeasonComparisonsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.field.analytics.v1.FieldAnalyticsService.GetSeasonComparisons is not implemented"))
}

func (UnimplementedFieldAnalyticsServiceHandler) GetRotationAnalysis(context.Context, *connect.Request[v1.GetRotationAnalysisRequest]) (*connect.Response[v1.GetRotationAnalysisResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.field.analytics.v1.FieldAnalyticsService.GetRotationAnalysis is not implemented"))
}

func (UnimplementedFieldAnalyticsServiceHandler) GetCrossFieldTrends(context.Context, *connect.Request[v1.GetCrossFieldTrendsRequest]) (*connect.Response[v1.GetCrossFieldTrendsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.field.analytics.v1.FieldAnalyticsService.GetCrossFieldTrends is not implemented"))
}
