// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: prescription.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrescriptionType int32

const (
	PrescriptionType_PRESCRIPTION_TYPE_UNSPECIFIED PrescriptionType = 0
	PrescriptionType_PRESCRIPTION_TYPE_FERTILIZER  PrescriptionType = 1
	PrescriptionType_PRESCRIPTION_TYPE_IRRIGATION  PrescriptionType = 2
	PrescriptionType_PRESCRIPTION_TYPE_SEEDING     PrescriptionType = 3
	PrescriptionType_PRESCRIPTION_TYPE_LIMING      PrescriptionType = 4
)

// Enum value maps for PrescriptionType.
var (
	PrescriptionType_name = map[int32]string{
		0: "PRESCRIPTION_TYPE_UNSPECIFIED",
		1: "PRESCRIPTION_TYPE_FERTILIZER",
		2: "PRESCRIPTION_TYPE_IRRIGATION",
		3: "PRESCRIPTION_TYPE_SEEDING",
		4: "PRESCRIPTION_TYPE_LIMING",
	}
	PrescriptionType_value = map[string]int32{
		"PRESCRIPTION_TYPE_UNSPECIFIED": 0,
		"PRESCRIPTION_TYPE_FERTILIZER":  1,
		"PRESCRIPTION_TYPE_IRRIGATION":  2,
		"PRESCRIPTION_TYPE_SEEDING":     3,
		"PRESCRIPTION_TYPE_LIMING":      4,
	}
)

func (x PrescriptionType) Enum() *PrescriptionType {
	p := new(PrescriptionType)
	*p = x
	return p
}

func (x PrescriptionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrescriptionType) Descriptor() protoreflect.EnumDescriptor {
	return file_prescription_proto_enumTypes[0].Descriptor()
}

func (PrescriptionType) Type() protoreflect.EnumType {
	return &file_prescription_proto_enumTypes[0]
}

func (x PrescriptionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrescriptionType.Descriptor instead.
func (PrescriptionType) EnumDescriptor() ([]byte, []int) {
	return file_prescription_proto_rawDescGZIP(), []int{0}
}

// RateRow is a single row of rate values (used to represent a 2D grid).
type RateRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateRow) Reset() {
	*x = RateRow{}
	mi := &file_prescription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateRow) ProtoMessage() {}

func (x *RateRow) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateRow.ProtoReflect.Descriptor instead.
func (*RateRow) Descriptor() ([]byte, []int) {
	return file_prescription_proto_rawDescGZIP(), []int{0}
}

func (x *RateRow) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

// SoilDataRow is a single row of soil data values.
type SoilDataRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoilDataRow) Reset() {
	*x = SoilDataRow{}
	mi := &file_prescription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoilDataRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoilDataRow) ProtoMessage() {}

func (x *SoilDataRow) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoilDataRow.ProtoReflect.Descriptor instead.
func (*SoilDataRow) Descriptor() ([]byte, []int) {
	return file_prescription_proto_rawDescGZIP(), []int{1}
}

func (x *SoilDataRow) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

// PrescriptionMap represents one prescription layer (e.g. fertilizer rates).
type PrescriptionMap struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PrescriptionType PrescriptionType       `protobuf:"varint,2,opt,name=prescription_type,json=prescriptionType,proto3,enum=agriculture.prescription.v1.PrescriptionType" json:"prescription_type,omitempty"`
	Unit             string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Rates            []*RateRow             `protobuf:"bytes,4,rep,name=rates,proto3" json:"rates,omitempty"`
	AvgRate          float64                `protobuf:"fixed64,5,opt,name=avg_rate,json=avgRate,proto3" json:"avg_rate,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PrescriptionMap) Reset() {
	*x = PrescriptionMap{}
	mi := &file_prescription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrescriptionMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrescriptionMap) ProtoMessage() {}

func (x *PrescriptionMap) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrescriptionMap.ProtoReflect.Descriptor instead.
func (*PrescriptionMap) Descriptor() ([]byte, []int) {
	return file_prescription_proto_rawDescGZIP(), []int{2}
}

func (x *PrescriptionMap) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PrescriptionMap) GetPrescriptionType() PrescriptionType {
	if x != nil {
		return x.PrescriptionType
	}
	return PrescriptionType_PRESCRIPTION_TYPE_UNSPECIFIED
}

func (x *PrescriptionMap) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *PrescriptionMap) GetRates() []*RateRow {
	if x != nil {
		return x.Rates
	}
	return nil
}

func (x *PrescriptionMap) GetAvgRate() float64 {
	if x != nil {
		return x.AvgRate
	}
	return 0
}

// ZoneSummary summarises prescription rates within a management zone.
type ZoneSummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Zone             string                 `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"` // "Low", "Medium", "High"
	PrescriptionType PrescriptionType       `protobuf:"varint,2,opt,name=prescription_type,json=prescriptionType,proto3,enum=agriculture.prescription.v1.PrescriptionType" json:"prescription_type,omitempty"`
	AreaHectares     float64                `protobuf:"fixed64,3,opt,name=area_hectares,json=areaHectares,proto3" json:"area_hectares,omitempty"`
	MinRate          float64                `protobuf:"fixed64,4,opt,name=min_rate,json=minRate,proto3" json:"min_rate,omitempty"`
	MeanRate         float64                `protobuf:"fixed64,5,opt,name=mean_rate,json=meanRate,proto3" json:"mean_rate,omitempty"`
	MaxRate          float64                `protobuf:"fixed64,6,opt,name=max_rate,json=maxRate,proto3" json:"max_rate,omitempty"`
	TotalAmount      float64                `protobuf:"fixed64,7,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ZoneSummary) Reset() {
	*x = ZoneSummary{}
	mi := &file_prescription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneSummary) ProtoMessage() {}

func (x *ZoneSummary) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneSummary.ProtoReflect.Descriptor instead.
func (*ZoneSummary) Descriptor() ([]byte, []int) {
	return file_prescription_proto_rawDescGZIP(), []int{3}
}

func (x *ZoneSummary) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *ZoneSummary) GetPrescriptionType() PrescriptionType {
	if x != nil {
		return x.PrescriptionType
	}
	return PrescriptionType_PRESCRIPTION_TYPE_UNSPECIFIED
}

func (x *ZoneSummary) GetAreaHectares() float64 {
	if x != nil {
		return x.AreaHectares
	}
	return 0
}

func (x *ZoneSummary) GetMinRate() float64 {
	if x != nil {
		return x.MinRate
	}
	return 0
}

func (x *ZoneSummary) GetMeanRate() float64 {
	if x != nil {
		return x.MeanRate
	}
	return 0
}

func (x *ZoneSummary) GetMaxRate() float64 {
	if x != nil {
		return x.MaxRate
	}
	return 0
}

func (x *ZoneSummary) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

// PrescriptionBundle is the top-level prescription output for a field.
type PrescriptionBundle struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FieldId              string                 `protobuf:"bytes,2,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	FieldName            string                 `protobuf:"bytes,3,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	CropType             string                 `protobuf:"bytes,4,opt,name=crop_type,json=cropType,proto3" json:"crop_type,omitempty"`
	TargetYield          float64                `protobuf:"fixed64,5,opt,name=target_yield,json=targetYield,proto3" json:"target_yield,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	EstimatedCostSavings float64                `protobuf:"fixed64,7,opt,name=estimated_cost_savings,json=estimatedCostSavings,proto3" json:"estimated_cost_savings,omitempty"`
	EstimatedYieldGain   float64                `protobuf:"fixed64,8,opt,name=estimated_yield_gain,json=estimatedYieldGain,proto3" json:"estimated_yield_gain,omitempty"`
	Prescriptions        []*PrescriptionMap     `protobuf:"bytes,9,rep,name=prescriptions,proto3" json:"prescriptions,omitempty"`
	ZoneSummaries        []*ZoneSummary         `protobuf:"bytes,10,rep,name=zone_summaries,json=zoneSummaries,proto3" json:"zone_summaries,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PrescriptionBundle) Reset() {
	*x = PrescriptionBundle{}
	mi := &file_prescription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrescriptionBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrescriptionBundle) ProtoMessage() {}

func (x *PrescriptionBundle) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrescriptionBundle.ProtoReflect.Descriptor instead.
func (*PrescriptionBundle) Descriptor() ([]byte, []int) {
	return file_prescription_proto_rawDescGZIP(), []int{4}
}

func (x *PrescriptionBundle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PrescriptionBundle) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *PrescriptionBundle) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *PrescriptionBundle) GetCropType() string {
	if x != nil {
		return x.CropType
	}
	return ""
}

func (x *PrescriptionBundle) GetTargetYield() float64 {
	if x != nil {
		return x.TargetYield
	}
	return 0
}

func (x *PrescriptionBundle) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PrescriptionBundle) GetEstimatedCostSavings() float64 {
	if x != nil {
		return x.EstimatedCostSavings
	}
	return 0
}

func (x *PrescriptionBundle) GetEstimatedYieldGain() float64 {
	if x != nil {
		return x.EstimatedYieldGain
	}
	return 0
}

func (x *PrescriptionBundle) GetPrescriptions() []*PrescriptionMap {
	if x != nil {
		return x.Prescriptions
	}
	return nil
}

func (x *PrescriptionBundle) GetZoneSummaries() []*ZoneSummary {
	if x != nil {
		return x.ZoneSummaries
	}
	return nil
}

type ListPrescriptionsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PrescriptionType PrescriptionType       `protobuf:"varint,1,opt,name=prescription_type,json=prescriptionType,proto3,enum=agriculture.prescription.v1.PrescriptionType" json:"prescription_type,omitempty"` // optional filter
	PageSize         int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken        string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListPrescriptionsRequest) Reset() {
	*x = ListPrescriptionsRequest{}
	mi := &file_prescription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrescriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrescriptionsRequest) ProtoMessage() {}

func (x *ListPrescriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrescriptionsRequest.ProtoReflect.Descriptor instead.
func (*ListPrescriptionsRequest) Descriptor() ([]byte, []int) {
	return file_prescription_proto_rawDescGZIP(), []int{5}
}

func (x *ListPrescriptionsRequest) GetPrescriptionType() PrescriptionType {
	if x != nil {
		return x.PrescriptionType
	}
	return PrescriptionType_PRESCRIPTION_TYPE_UNSPECIFIED
}

func (x *ListPrescriptionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPrescriptionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListPrescriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prescriptions []*PrescriptionBundle  `protobuf:"bytes,1,rep,name=prescriptions,proto3" json:"prescriptions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrescriptionsResponse) Reset() {
	*x = ListPrescriptionsResponse{}
	mi := &file_prescription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrescriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrescriptionsResponse) ProtoMessage() {}

func (x *ListPrescriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrescriptionsResponse.ProtoReflect.Descriptor instead.
func (*ListPrescriptionsResponse) Descriptor() ([]byte, []int) {
	return file_prescription_proto_rawDescGZIP(), []int{6}
}

func (x *ListPrescriptionsResponse) GetPrescriptions() []*PrescriptionBundle {
	if x != nil {
		return x.Prescriptions
	}
	return nil
}

func (x *ListPrescriptionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetPrescriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrescriptionRequest) Reset() {
	*x = GetPrescriptionRequest{}
	mi := &file_prescription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrescriptionRequest) ProtoMessage() {}

func (x *GetPrescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrescriptionRequest.ProtoReflect.Descriptor instead.
func (*GetPrescriptionRequest) Descriptor() ([]byte, []int) {
	return file_prescription_proto_rawDescGZIP(), []int{7}
}

func (x *GetPrescriptionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPrescriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prescription  *PrescriptionBundle    `protobuf:"bytes,1,opt,name=prescription,proto3" json:"prescription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrescriptionResponse) Reset() {
	*x = GetPrescriptionResponse{}
	mi := &file_prescription_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrescriptionResponse) ProtoMessage() {}

func (x *GetPrescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrescriptionResponse.ProtoReflect.Descriptor instead.
func (*GetPrescriptionResponse) Descriptor() ([]byte, []int) {
	return file_prescription_proto_rawDescGZIP(), []int{8}
}

func (x *GetPrescriptionResponse) GetPrescription() *PrescriptionBundle {
	if x != nil {
		return x.Prescription
	}
	return nil
}

type GeneratePrescriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldId       string                 `protobuf:"bytes,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	CropType      string                 `protobuf:"bytes,2,opt,name=crop_type,json=cropType,proto3" json:"crop_type,omitempty"`
	TargetYield   float64                `protobuf:"fixed64,3,opt,name=target_yield,json=targetYield,proto3" json:"target_yield,omitempty"`
	SoilData      []*SoilDataRow         `protobuf:"bytes,4,rep,name=soil_data,json=soilData,proto3" json:"soil_data,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePrescriptionRequest) Reset() {
	*x = GeneratePrescriptionRequest{}
	mi := &file_prescription_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePrescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePrescriptionRequest) ProtoMessage() {}

func (x *GeneratePrescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePrescriptionRequest.ProtoReflect.Descriptor instead.
func (*GeneratePrescriptionRequest) Descriptor() ([]byte, []int) {
	return file_prescription_proto_rawDescGZIP(), []int{9}
}

func (x *GeneratePrescriptionRequest) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *GeneratePrescriptionRequest) GetCropType() string {
	if x != nil {
		return x.CropType
	}
	return ""
}

func (x *GeneratePrescriptionRequest) GetTargetYield() float64 {
	if x != nil {
		return x.TargetYield
	}
	return 0
}

func (x *GeneratePrescriptionRequest) GetSoilData() []*SoilDataRow {
	if x != nil {
		return x.SoilData
	}
	return nil
}

type GeneratePrescriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prescription  *PrescriptionBundle    `protobuf:"bytes,1,opt,name=prescription,proto3" json:"prescription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePrescriptionResponse) Reset() {
	*x = GeneratePrescriptionResponse{}
	mi := &file_prescription_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePrescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePrescriptionResponse) ProtoMessage() {}

func (x *GeneratePrescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePrescriptionResponse.ProtoReflect.Descriptor instead.
func (*GeneratePrescriptionResponse) Descriptor() ([]byte, []int) {
	return file_prescription_proto_rawDescGZIP(), []int{10}
}

func (x *GeneratePrescriptionResponse) GetPrescription() *PrescriptionBundle {
	if x != nil {
		return x.Prescription
	}
	return nil
}

type ExportPrescriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"` // "csv", "shapefile", "pdf"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportPrescriptionRequest) Reset() {
	*x = ExportPrescriptionRequest{}
	mi := &file_prescription_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportPrescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportPrescriptionRequest) ProtoMessage() {}

func (x *ExportPrescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportPrescriptionRequest.ProtoReflect.Descriptor instead.
func (*ExportPrescriptionRequest) Descriptor() ([]byte, []int) {
	return file_prescription_proto_rawDescGZIP(), []int{11}
}

func (x *ExportPrescriptionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExportPrescriptionRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type ExportPrescriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DownloadUrl   string                 `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportPrescriptionResponse) Reset() {
	*x = ExportPrescriptionResponse{}
	mi := &file_prescription_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportPrescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportPrescriptionResponse) ProtoMessage() {}

func (x *ExportPrescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportPrescriptionResponse.ProtoReflect.Descriptor instead.
func (*ExportPrescriptionResponse) Descriptor() ([]byte, []int) {
	return file_prescription_proto_rawDescGZIP(), []int{12}
}

func (x *ExportPrescriptionResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *ExportPrescriptionResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

var File_prescription_proto protoreflect.FileDescriptor

const file_prescription_proto_rawDesc = "" +
	"\n" +
	"\x12prescription.proto\x12\x1bagriculture.prescription.v1\"!\n" +
	"\aRateRow\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values\"%\n" +
	"\vSoilDataRow\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values\"\xe8\x01\n" +
	"\x0fPrescriptionMap\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12Z\n" +
	"\x11prescription_type\x18\x02 \x01(\x0e2-.agriculture.prescription.v1.PrescriptionTypeR\x10prescriptionType\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12:\n" +
	"\x05rates\x18\x04 \x03(\v2$.agriculture.prescription.v1.RateRowR\x05rates\x12\x19\n" +
	"\bavg_rate\x18\x05 \x01(\x01R\aavgRate\"\x98\x02\n" +
	"\vZoneSummary\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\x12Z\n" +
	"\x11prescription_type\x18\x02 \x01(\x0e2-.agriculture.prescription.v1.PrescriptionTypeR\x10prescriptionType\x12#\n" +
	"\rarea_hectares\x18\x03 \x01(\x01R\fareaHectares\x12\x19\n" +
	"\bmin_rate\x18\x04 \x01(\x01R\aminRate\x12\x1b\n" +
	"\tmean_rate\x18\x05 \x01(\x01R\bmeanRate\x12\x19\n" +
	"\bmax_rate\x18\x06 \x01(\x01R\amaxRate\x12!\n" +
	"\ftotal_amount\x18\a \x01(\x01R\vtotalAmount\"\xca\x03\n" +
	"\x12PrescriptionBundle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bfield_id\x18\x02 \x01(\tR\afieldId\x12\x1d\n" +
	"\n" +
	"field_name\x18\x03 \x01(\tR\tfieldName\x12\x1b\n" +
	"\tcrop_type\x18\x04 \x01(\tR\bcropType\x12!\n" +
	"\ftarget_yield\x18\x05 \x01(\x01R\vtargetYield\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x124\n" +
	"\x16estimated_cost_savings\x18\a \x01(\x01R\x14estimatedCostSavings\x120\n" +
	"\x14estimated_yield_gain\x18\b \x01(\x01R\x12estimatedYieldGain\x12R\n" +
	"\rprescriptions\x18\t \x03(\v2,.agriculture.prescription.v1.PrescriptionMapR\rprescriptions\x12O\n" +
	"\x0ezone_summaries\x18\n" +
	" \x03(\v2(.agriculture.prescription.v1.ZoneSummaryR\rzoneSummaries\"\xb2\x01\n" +
	"\x18ListPrescriptionsRequest\x12Z\n" +
	"\x11prescription_type\x18\x01 \x01(\x0e2-.agriculture.prescription.v1.PrescriptionTypeR\x10prescriptionType\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x9a\x01\n" +
	"\x19ListPrescriptionsResponse\x12U\n" +
	"\rprescriptions\x18\x01 \x03(\v2/.agriculture.prescription.v1.PrescriptionBundleR\rprescriptions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"(\n" +
	"\x16GetPrescriptionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"n\n" +
	"\x17GetPrescriptionResponse\x12S\n" +
	"\fprescription\x18\x01 \x01(\v2/.agriculture.prescription.v1.PrescriptionBundleR\fprescription\"\xbf\x01\n" +
	"\x1bGeneratePrescriptionRequest\x12\x19\n" +
	"\bfield_id\x18\x01 \x01(\tR\afieldId\x12\x1b\n" +
	"\tcrop_type\x18\x02 \x01(\tR\bcropType\x12!\n" +
	"\ftarget_yield\x18\x03 \x01(\x01R\vtargetYield\x12E\n" +
	"\tsoil_data\x18\x04 \x03(\v2(.agriculture.prescription.v1.SoilDataRowR\bsoilData\"s\n" +
	"\x1cGeneratePrescriptionResponse\x12S\n" +
	"\fprescription\x18\x01 \x01(\v2/.agriculture.prescription.v1.PrescriptionBundleR\fprescription\"C\n" +
	"\x19ExportPrescriptionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"\\\n" +
	"\x1aExportPrescriptionResponse\x12!\n" +
	"\fdownload_url\x18\x01 \x01(\tR\vdownloadUrl\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName*\xb6\x01\n" +
	"\x10PrescriptionType\x12!\n" +
	"\x1dPRESCRIPTION_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cPRESCRIPTION_TYPE_FERTILIZER\x10\x01\x12 \n" +
	"\x1cPRESCRIPTION_TYPE_IRRIGATION\x10\x02\x12\x1d\n" +
	"\x19PRESCRIPTION_TYPE_SEEDING\x10\x03\x12\x1c\n" +
	"\x18PRESCRIPTION_TYPE_LIMING\x10\x042\xae\x04\n" +
	"\x13PrescriptionService\x12\x82\x01\n" +
	"\x11ListPrescriptions\x125.agriculture.prescription.v1.ListPrescriptionsRequest\x1a6.agriculture.prescription.v1.ListPrescriptionsResponse\x12|\n" +
	"\x0fGetPrescription\x123.agriculture.prescription.v1.GetPrescriptionRequest\x1a4.agriculture.prescription.v1.GetPrescriptionResponse\x12\x8b\x01\n" +
	"\x14GeneratePrescription\x128.agriculture.prescription.v1.GeneratePrescriptionRequest\x1a9.agriculture.prescription.v1.GeneratePrescriptionResponse\x12\x85\x01\n" +
	"\x12ExportPrescription\x126.agriculture.prescription.v1.ExportPrescriptionRequest\x1a7.agriculture.prescription.v1.ExportPrescriptionResponseB9Z7p9e.in/samavaya/agriculture/prescription-service/api/v1b\x06proto3"

var (
	file_prescription_proto_rawDescOnce sync.Once
	file_prescription_proto_rawDescData []byte
)

func file_prescription_proto_rawDescGZIP() []byte {
	file_prescription_proto_rawDescOnce.Do(func() {
		file_prescription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_prescription_proto_rawDesc), len(file_prescription_proto_rawDesc)))
	})
	return file_prescription_proto_rawDescData
}

var file_prescription_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_prescription_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_prescription_proto_goTypes = []any{
	(PrescriptionType)(0),                // 0: agriculture.prescription.v1.PrescriptionType
	(*RateRow)(nil),                      // 1: agriculture.prescription.v1.RateRow
	(*SoilDataRow)(nil),                  // 2: agriculture.prescription.v1.SoilDataRow
	(*PrescriptionMap)(nil),              // 3: agriculture.prescription.v1.PrescriptionMap
	(*ZoneSummary)(nil),                  // 4: agriculture.prescription.v1.ZoneSummary
	(*PrescriptionBundle)(nil),           // 5: agriculture.prescription.v1.PrescriptionBundle
	(*ListPrescriptionsRequest)(nil),     // 6: agriculture.prescription.v1.ListPrescriptionsRequest
	(*ListPrescriptionsResponse)(nil),    // 7: agriculture.prescription.v1.ListPrescriptionsResponse
	(*GetPrescriptionRequest)(nil),       // 8: agriculture.prescription.v1.GetPrescriptionRequest
	(*GetPrescriptionResponse)(nil),      // 9: agriculture.prescription.v1.GetPrescriptionResponse
	(*GeneratePrescriptionRequest)(nil),  // 10: agriculture.prescription.v1.GeneratePrescriptionRequest
	(*GeneratePrescriptionResponse)(nil), // 11: agriculture.prescription.v1.GeneratePrescriptionResponse
	(*ExportPrescriptionRequest)(nil),    // 12: agriculture.prescription.v1.ExportPrescriptionRequest
	(*ExportPrescriptionResponse)(nil),   // 13: agriculture.prescription.v1.ExportPrescriptionResponse
}
var file_prescription_proto_depIdxs = []int32{
	0,  // 0: agriculture.prescription.v1.PrescriptionMap.prescription_type:type_name -> agriculture.prescription.v1.PrescriptionType
	1,  // 1: agriculture.prescription.v1.PrescriptionMap.rates:type_name -> agriculture.prescription.v1.RateRow
	0,  // 2: agriculture.prescription.v1.ZoneSummary.prescription_type:type_name -> agriculture.prescription.v1.PrescriptionType
	3,  // 3: agriculture.prescription.v1.PrescriptionBundle.prescriptions:type_name -> agriculture.prescription.v1.PrescriptionMap
	4,  // 4: agriculture.prescription.v1.PrescriptionBundle.zone_summaries:type_name -> agriculture.prescription.v1.ZoneSummary
	0,  // 5: agriculture.prescription.v1.ListPrescriptionsRequest.prescription_type:type_name -> agriculture.prescription.v1.PrescriptionType
	5,  // 6: agriculture.prescription.v1.ListPrescriptionsResponse.prescriptions:type_name -> agriculture.prescription.v1.PrescriptionBundle
	5,  // 7: agriculture.prescription.v1.GetPrescriptionResponse.prescription:type_name -> agriculture.prescription.v1.PrescriptionBundle
	2,  // 8: agriculture.prescription.v1.GeneratePrescriptionRequest.soil_data:type_name -> agriculture.prescription.v1.SoilDataRow
	5,  // 9: agriculture.prescription.v1.GeneratePrescriptionResponse.prescription:type_name -> agriculture.prescription.v1.PrescriptionBundle
	6,  // 10: agriculture.prescription.v1.PrescriptionService.ListPrescriptions:input_type -> agriculture.prescription.v1.ListPrescriptionsRequest
	8,  // 11: agriculture.prescription.v1.PrescriptionService.GetPrescription:input_type -> agriculture.prescription.v1.GetPrescriptionRequest
	10, // 12: agriculture.prescription.v1.PrescriptionService.GeneratePrescription:input_type -> agriculture.prescription.v1.GeneratePrescriptionRequest
	12, // 13: agriculture.prescription.v1.PrescriptionService.ExportPrescription:input_type -> agriculture.prescription.v1.ExportPrescriptionRequest
	7,  // 14: agriculture.prescription.v1.PrescriptionService.ListPrescriptions:output_type -> agriculture.prescription.v1.ListPrescriptionsResponse
	9,  // 15: agriculture.prescription.v1.PrescriptionService.GetPrescription:output_type -> agriculture.prescription.v1.GetPrescriptionResponse
	11, // 16: agriculture.prescription.v1.PrescriptionService.GeneratePrescription:output_type -> agriculture.prescription.v1.GeneratePrescriptionResponse
	13, // 17: agriculture.prescription.v1.PrescriptionService.ExportPrescription:output_type -> agriculture.prescription.v1.ExportPrescriptionResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_prescription_proto_init() }
func file_prescription_proto_init() {
	if File_prescription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_prescription_proto_rawDesc), len(file_prescription_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prescription_proto_goTypes,
		DependencyIndexes: file_prescription_proto_depIdxs,
		EnumInfos:         file_prescription_proto_enumTypes,
		MessageInfos:      file_prescription_proto_msgTypes,
	}.Build()
	File_prescription_proto = out.File
	file_prescription_proto_goTypes = nil
	file_prescription_proto_depIdxs = nil
}
