// Package grpc contains the inbound ConnectRPC adapter for the crop-service.
// NOTE: proto types are generated by buf generate.
package grpc

import (
	"context"

	"connectrpc.com/connect"
	"p9e.in/samavaya/packages/errors"
	"p9e.in/samavaya/packages/p9context"
	"p9e.in/samavaya/packages/p9log"

	// Generated by buf generate
	pb "p9e.in/samavaya/agriculture/crop-service/api/v1"
	"p9e.in/samavaya/agriculture/crop-service/api/v1/cropv1connect"
	"p9e.in/samavaya/agriculture/crop-service/internal/mappers"
	cropmodels "p9e.in/samavaya/agriculture/crop-service/internal/models"
	"p9e.in/samavaya/agriculture/crop-service/internal/ports/inbound"
)

// CropHandler is the ConnectRPC inbound adapter.
type CropHandler struct {
	cropv1connect.UnimplementedCropServiceHandler
	svc inbound.CropService
	log *p9log.Helper
}

// NewCropHandler creates a new ConnectRPC crop handler.
func NewCropHandler(svc inbound.CropService, log p9log.Logger) *CropHandler {
	return &CropHandler{
		svc: svc,
		log: p9log.NewHelper(p9log.With(log, "component", "CropHandler")),
	}
}

// CreateCrop handles creation requests.
func (h *CropHandler) CreateCrop(ctx context.Context, req *connect.Request[pb.CreateCropRequest]) (*connect.Response[pb.CreateCropResponse], error) {
	h.log.Infow("msg", "CreateCrop request", "tenant_id", p9context.TenantID(ctx))
	if req.Msg.GetName() == "" {
		return nil, errors.BadRequest("INVALID_ARGUMENT", "name is required")
	}

	userID := p9context.UserID(ctx)
	entity := mappers.CropFromCreateRequest(req.Msg, userID)

	created, err := h.svc.CreateCrop(ctx, entity)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.CreateCropResponse{Crop: mappers.CropToProto(created)}), nil
}

// GetCrop handles get requests.
func (h *CropHandler) GetCrop(ctx context.Context, req *connect.Request[pb.GetCropRequest]) (*connect.Response[pb.GetCropResponse], error) {
	if req.Msg.GetId() == "" {
		return nil, errors.BadRequest("INVALID_ARGUMENT", "id is required")
	}
	tenantID := req.Msg.GetTenantId()
	if tenantID == "" {
		tenantID = p9context.TenantID(ctx)
	}

	entity, err := h.svc.GetCrop(ctx, req.Msg.GetId(), tenantID)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.GetCropResponse{Crop: mappers.CropToProto(entity)}), nil
}

// ListCrops handles list requests.
func (h *CropHandler) ListCrops(ctx context.Context, req *connect.Request[pb.ListCropsRequest]) (*connect.Response[pb.ListCropsResponse], error) {
	tenantID := req.Msg.GetTenantId()
	if tenantID == "" {
		tenantID = p9context.TenantID(ctx)
	}

	var category *string
	if req.Msg.GetCategory() != pb.CropCategory_CROP_CATEGORY_UNSPECIFIED {
		cat := string(mappers.CategoryFromProto(req.Msg.GetCategory()))
		category = &cat
	}
	var searchTerm *string
	if req.Msg.GetSearchTerm() != "" {
		s := req.Msg.GetSearchTerm()
		searchTerm = &s
	}

	entities, total, err := h.svc.ListCrops(ctx, tenantID, category, searchTerm, req.Msg.GetPageSize(), req.Msg.GetPageOffset())
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.ListCropsResponse{
		Crops:      mappers.CropSliceToProto(entities),
		TotalCount: total,
	}), nil
}

// UpdateCrop handles update requests.
func (h *CropHandler) UpdateCrop(ctx context.Context, req *connect.Request[pb.UpdateCropRequest]) (*connect.Response[pb.UpdateCropResponse], error) {
	if req.Msg.GetId() == "" {
		return nil, errors.BadRequest("INVALID_ARGUMENT", "id is required")
	}
	tenantID := req.Msg.GetTenantId()
	if tenantID == "" {
		tenantID = p9context.TenantID(ctx)
	}
	userID := p9context.UserID(ctx)

	entity := &cropmodels.Crop{
		TenantID:               tenantID,
		Name:                   req.Msg.GetName(),
		ScientificName:         req.Msg.GetScientificName(),
		Family:                 req.Msg.GetFamily(),
		Category:               mappers.CategoryFromProto(req.Msg.GetCategory()),
		Description:            req.Msg.GetDescription(),
		ImageURL:               req.Msg.GetImageUrl(),
		DiseaseSusceptibilities: req.Msg.GetDiseaseSusceptibilities(),
		CompanionPlants:        req.Msg.GetCompanionPlants(),
		RotationGroup:          req.Msg.GetRotationGroup(),
		Version:                req.Msg.GetVersion(),
	}
	entity.UUID = req.Msg.GetId()
	entity.UpdatedBy = &userID

	updated, err := h.svc.UpdateCrop(ctx, entity)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.UpdateCropResponse{Crop: mappers.CropToProto(updated)}), nil
}

// DeleteCrop handles delete requests.
func (h *CropHandler) DeleteCrop(ctx context.Context, req *connect.Request[pb.DeleteCropRequest]) (*connect.Response[pb.DeleteCropResponse], error) {
	if req.Msg.GetId() == "" {
		return nil, errors.BadRequest("INVALID_ARGUMENT", "id is required")
	}
	tenantID := req.Msg.GetTenantId()
	if tenantID == "" {
		tenantID = p9context.TenantID(ctx)
	}

	if err := h.svc.DeleteCrop(ctx, req.Msg.GetId(), tenantID); err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.DeleteCropResponse{Success: true}), nil
}

// AddVariety handles add variety requests.
func (h *CropHandler) AddVariety(ctx context.Context, req *connect.Request[pb.AddVarietyRequest]) (*connect.Response[pb.AddVarietyResponse], error) {
	if req.Msg.GetCropId() == "" {
		return nil, errors.BadRequest("INVALID_ARGUMENT", "crop_id is required")
	}
	if req.Msg.GetName() == "" {
		return nil, errors.BadRequest("INVALID_ARGUMENT", "name is required")
	}
	tenantID := req.Msg.GetTenantId()
	if tenantID == "" {
		tenantID = p9context.TenantID(ctx)
	}
	userID := p9context.UserID(ctx)

	// Resolve crop UUID to internal ID for the variety FK.
	crop, err := h.svc.GetCrop(ctx, req.Msg.GetCropId(), tenantID)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}

	variety := mappers.CropVarietyFromAddRequest(req.Msg, crop.ID, userID)
	variety.TenantID = tenantID

	created, err := h.svc.AddVariety(ctx, variety)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	proto := mappers.CropVarietyToProto(created)
	proto.CropId = req.Msg.GetCropId()
	return connect.NewResponse(&pb.AddVarietyResponse{Variety: proto}), nil
}

// ListVarieties handles list varieties requests.
func (h *CropHandler) ListVarieties(ctx context.Context, req *connect.Request[pb.ListVarietiesRequest]) (*connect.Response[pb.ListVarietiesResponse], error) {
	if req.Msg.GetCropId() == "" {
		return nil, errors.BadRequest("INVALID_ARGUMENT", "crop_id is required")
	}
	tenantID := req.Msg.GetTenantId()
	if tenantID == "" {
		tenantID = p9context.TenantID(ctx)
	}

	varieties, total, err := h.svc.ListVarieties(ctx, req.Msg.GetCropId(), tenantID, req.Msg.GetPageSize(), req.Msg.GetPageOffset())
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.ListVarietiesResponse{
		Varieties:  mappers.CropVarietySliceToProto(varieties),
		TotalCount: total,
	}), nil
}

// GetGrowthStages handles get growth stages requests.
func (h *CropHandler) GetGrowthStages(ctx context.Context, req *connect.Request[pb.GetGrowthStagesRequest]) (*connect.Response[pb.GetGrowthStagesResponse], error) {
	if req.Msg.GetCropId() == "" {
		return nil, errors.BadRequest("INVALID_ARGUMENT", "crop_id is required")
	}
	tenantID := req.Msg.GetTenantId()
	if tenantID == "" {
		tenantID = p9context.TenantID(ctx)
	}

	stages, err := h.svc.GetGrowthStages(ctx, req.Msg.GetCropId(), tenantID)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.GetGrowthStagesResponse{
		GrowthStages: mappers.GrowthStageSliceToProto(stages),
	}), nil
}

// GetCropRequirements handles get crop requirements requests.
func (h *CropHandler) GetCropRequirements(ctx context.Context, req *connect.Request[pb.GetCropRequirementsRequest]) (*connect.Response[pb.GetCropRequirementsResponse], error) {
	if req.Msg.GetCropId() == "" {
		return nil, errors.BadRequest("INVALID_ARGUMENT", "crop_id is required")
	}
	tenantID := req.Msg.GetTenantId()
	if tenantID == "" {
		tenantID = p9context.TenantID(ctx)
	}

	reqs, err := h.svc.GetCropRequirements(ctx, req.Msg.GetCropId(), tenantID)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.GetCropRequirementsResponse{
		Requirements: mappers.CropRequirementsToProto(reqs),
	}), nil
}

// GenerateRecommendation handles recommendation generation requests.
func (h *CropHandler) GenerateRecommendation(ctx context.Context, req *connect.Request[pb.GenerateRecommendationRequest]) (*connect.Response[pb.GenerateRecommendationResponse], error) {
	if req.Msg.GetCropId() == "" {
		return nil, errors.BadRequest("INVALID_ARGUMENT", "crop_id is required")
	}
	tenantID := req.Msg.GetTenantId()
	if tenantID == "" {
		tenantID = p9context.TenantID(ctx)
	}

	input := &cropmodels.RecommendationInput{
		CropID:              req.Msg.GetCropId(),
		TenantID:            tenantID,
		RecommendationType:  req.Msg.GetRecommendationType(),
		CurrentGrowthStage:  req.Msg.GetCurrentGrowthStage(),
		CurrentTemperature:  req.Msg.GetCurrentTemperature(),
		CurrentHumidity:     req.Msg.GetCurrentHumidity(),
		CurrentSoilPH:       req.Msg.GetCurrentSoilPh(),
		CurrentSoilMoisture: req.Msg.GetCurrentSoilMoisture(),
	}

	rec, err := h.svc.GenerateRecommendation(ctx, input)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.GenerateRecommendationResponse{
		Recommendation: mappers.CropRecommendationToProto(rec),
	}), nil
}
