// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: diagnosis.proto

package plantdiagnosisv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "p9e.in/samavaya/agriculture/plant-diagnosis-service/api/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PlantDiagnosisServiceName is the fully-qualified name of the PlantDiagnosisService service.
	PlantDiagnosisServiceName = "agriculture.diagnosis.v1.PlantDiagnosisService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PlantDiagnosisServiceSubmitDiagnosisProcedure is the fully-qualified name of the
	// PlantDiagnosisService's SubmitDiagnosis RPC.
	PlantDiagnosisServiceSubmitDiagnosisProcedure = "/agriculture.diagnosis.v1.PlantDiagnosisService/SubmitDiagnosis"
	// PlantDiagnosisServiceGetDiagnosisProcedure is the fully-qualified name of the
	// PlantDiagnosisService's GetDiagnosis RPC.
	PlantDiagnosisServiceGetDiagnosisProcedure = "/agriculture.diagnosis.v1.PlantDiagnosisService/GetDiagnosis"
	// PlantDiagnosisServiceListDiagnosesProcedure is the fully-qualified name of the
	// PlantDiagnosisService's ListDiagnoses RPC.
	PlantDiagnosisServiceListDiagnosesProcedure = "/agriculture.diagnosis.v1.PlantDiagnosisService/ListDiagnoses"
	// PlantDiagnosisServiceGetDiseaseInfoProcedure is the fully-qualified name of the
	// PlantDiagnosisService's GetDiseaseInfo RPC.
	PlantDiagnosisServiceGetDiseaseInfoProcedure = "/agriculture.diagnosis.v1.PlantDiagnosisService/GetDiseaseInfo"
	// PlantDiagnosisServiceGetTreatmentPlanProcedure is the fully-qualified name of the
	// PlantDiagnosisService's GetTreatmentPlan RPC.
	PlantDiagnosisServiceGetTreatmentPlanProcedure = "/agriculture.diagnosis.v1.PlantDiagnosisService/GetTreatmentPlan"
	// PlantDiagnosisServiceListDiseasesProcedure is the fully-qualified name of the
	// PlantDiagnosisService's ListDiseases RPC.
	PlantDiagnosisServiceListDiseasesProcedure = "/agriculture.diagnosis.v1.PlantDiagnosisService/ListDiseases"
	// PlantDiagnosisServiceIdentifySpeciesProcedure is the fully-qualified name of the
	// PlantDiagnosisService's IdentifySpecies RPC.
	PlantDiagnosisServiceIdentifySpeciesProcedure = "/agriculture.diagnosis.v1.PlantDiagnosisService/IdentifySpecies"
	// PlantDiagnosisServiceDetectNutrientDeficiencyProcedure is the fully-qualified name of the
	// PlantDiagnosisService's DetectNutrientDeficiency RPC.
	PlantDiagnosisServiceDetectNutrientDeficiencyProcedure = "/agriculture.diagnosis.v1.PlantDiagnosisService/DetectNutrientDeficiency"
	// PlantDiagnosisServiceDetectPestDamageProcedure is the fully-qualified name of the
	// PlantDiagnosisService's DetectPestDamage RPC.
	PlantDiagnosisServiceDetectPestDamageProcedure = "/agriculture.diagnosis.v1.PlantDiagnosisService/DetectPestDamage"
)

// PlantDiagnosisServiceClient is a client for the agriculture.diagnosis.v1.PlantDiagnosisService
// service.
type PlantDiagnosisServiceClient interface {
	// Submit a new plant diagnosis request with images
	SubmitDiagnosis(context.Context, *connect.Request[v1.SubmitDiagnosisRequest]) (*connect.Response[v1.SubmitDiagnosisResponse], error)
	// Get a diagnosis by ID
	GetDiagnosis(context.Context, *connect.Request[v1.GetDiagnosisRequest]) (*connect.Response[v1.GetDiagnosisResponse], error)
	// List diagnoses with filtering
	ListDiagnoses(context.Context, *connect.Request[v1.ListDiagnosesRequest]) (*connect.Response[v1.ListDiagnosesResponse], error)
	// Get disease information by ID
	GetDiseaseInfo(context.Context, *connect.Request[v1.GetDiseaseInfoRequest]) (*connect.Response[v1.GetDiseaseInfoResponse], error)
	// Get treatment plan for a diagnosis
	GetTreatmentPlan(context.Context, *connect.Request[v1.GetTreatmentPlanRequest]) (*connect.Response[v1.GetTreatmentPlanResponse], error)
	// List all known diseases
	ListDiseases(context.Context, *connect.Request[v1.ListDiseasesRequest]) (*connect.Response[v1.ListDiseasesResponse], error)
	// Identify plant species from images
	IdentifySpecies(context.Context, *connect.Request[v1.IdentifySpeciesRequest]) (*connect.Response[v1.IdentifySpeciesResponse], error)
	// Detect nutrient deficiencies from images
	DetectNutrientDeficiency(context.Context, *connect.Request[v1.DetectNutrientDeficiencyRequest]) (*connect.Response[v1.DetectNutrientDeficiencyResponse], error)
	// Detect pest damage from images
	DetectPestDamage(context.Context, *connect.Request[v1.DetectPestDamageRequest]) (*connect.Response[v1.DetectPestDamageResponse], error)
}

// NewPlantDiagnosisServiceClient constructs a client for the
// agriculture.diagnosis.v1.PlantDiagnosisService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPlantDiagnosisServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PlantDiagnosisServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	plantDiagnosisServiceMethods := v1.File_diagnosis_proto.Services().ByName("PlantDiagnosisService").Methods()
	return &plantDiagnosisServiceClient{
		submitDiagnosis: connect.NewClient[v1.SubmitDiagnosisRequest, v1.SubmitDiagnosisResponse](
			httpClient,
			baseURL+PlantDiagnosisServiceSubmitDiagnosisProcedure,
			connect.WithSchema(plantDiagnosisServiceMethods.ByName("SubmitDiagnosis")),
			connect.WithClientOptions(opts...),
		),
		getDiagnosis: connect.NewClient[v1.GetDiagnosisRequest, v1.GetDiagnosisResponse](
			httpClient,
			baseURL+PlantDiagnosisServiceGetDiagnosisProcedure,
			connect.WithSchema(plantDiagnosisServiceMethods.ByName("GetDiagnosis")),
			connect.WithClientOptions(opts...),
		),
		listDiagnoses: connect.NewClient[v1.ListDiagnosesRequest, v1.ListDiagnosesResponse](
			httpClient,
			baseURL+PlantDiagnosisServiceListDiagnosesProcedure,
			connect.WithSchema(plantDiagnosisServiceMethods.ByName("ListDiagnoses")),
			connect.WithClientOptions(opts...),
		),
		getDiseaseInfo: connect.NewClient[v1.GetDiseaseInfoRequest, v1.GetDiseaseInfoResponse](
			httpClient,
			baseURL+PlantDiagnosisServiceGetDiseaseInfoProcedure,
			connect.WithSchema(plantDiagnosisServiceMethods.ByName("GetDiseaseInfo")),
			connect.WithClientOptions(opts...),
		),
		getTreatmentPlan: connect.NewClient[v1.GetTreatmentPlanRequest, v1.GetTreatmentPlanResponse](
			httpClient,
			baseURL+PlantDiagnosisServiceGetTreatmentPlanProcedure,
			connect.WithSchema(plantDiagnosisServiceMethods.ByName("GetTreatmentPlan")),
			connect.WithClientOptions(opts...),
		),
		listDiseases: connect.NewClient[v1.ListDiseasesRequest, v1.ListDiseasesResponse](
			httpClient,
			baseURL+PlantDiagnosisServiceListDiseasesProcedure,
			connect.WithSchema(plantDiagnosisServiceMethods.ByName("ListDiseases")),
			connect.WithClientOptions(opts...),
		),
		identifySpecies: connect.NewClient[v1.IdentifySpeciesRequest, v1.IdentifySpeciesResponse](
			httpClient,
			baseURL+PlantDiagnosisServiceIdentifySpeciesProcedure,
			connect.WithSchema(plantDiagnosisServiceMethods.ByName("IdentifySpecies")),
			connect.WithClientOptions(opts...),
		),
		detectNutrientDeficiency: connect.NewClient[v1.DetectNutrientDeficiencyRequest, v1.DetectNutrientDeficiencyResponse](
			httpClient,
			baseURL+PlantDiagnosisServiceDetectNutrientDeficiencyProcedure,
			connect.WithSchema(plantDiagnosisServiceMethods.ByName("DetectNutrientDeficiency")),
			connect.WithClientOptions(opts...),
		),
		detectPestDamage: connect.NewClient[v1.DetectPestDamageRequest, v1.DetectPestDamageResponse](
			httpClient,
			baseURL+PlantDiagnosisServiceDetectPestDamageProcedure,
			connect.WithSchema(plantDiagnosisServiceMethods.ByName("DetectPestDamage")),
			connect.WithClientOptions(opts...),
		),
	}
}

// plantDiagnosisServiceClient implements PlantDiagnosisServiceClient.
type plantDiagnosisServiceClient struct {
	submitDiagnosis          *connect.Client[v1.SubmitDiagnosisRequest, v1.SubmitDiagnosisResponse]
	getDiagnosis             *connect.Client[v1.GetDiagnosisRequest, v1.GetDiagnosisResponse]
	listDiagnoses            *connect.Client[v1.ListDiagnosesRequest, v1.ListDiagnosesResponse]
	getDiseaseInfo           *connect.Client[v1.GetDiseaseInfoRequest, v1.GetDiseaseInfoResponse]
	getTreatmentPlan         *connect.Client[v1.GetTreatmentPlanRequest, v1.GetTreatmentPlanResponse]
	listDiseases             *connect.Client[v1.ListDiseasesRequest, v1.ListDiseasesResponse]
	identifySpecies          *connect.Client[v1.IdentifySpeciesRequest, v1.IdentifySpeciesResponse]
	detectNutrientDeficiency *connect.Client[v1.DetectNutrientDeficiencyRequest, v1.DetectNutrientDeficiencyResponse]
	detectPestDamage         *connect.Client[v1.DetectPestDamageRequest, v1.DetectPestDamageResponse]
}

// SubmitDiagnosis calls agriculture.diagnosis.v1.PlantDiagnosisService.SubmitDiagnosis.
func (c *plantDiagnosisServiceClient) SubmitDiagnosis(ctx context.Context, req *connect.Request[v1.SubmitDiagnosisRequest]) (*connect.Response[v1.SubmitDiagnosisResponse], error) {
	return c.submitDiagnosis.CallUnary(ctx, req)
}

// GetDiagnosis calls agriculture.diagnosis.v1.PlantDiagnosisService.GetDiagnosis.
func (c *plantDiagnosisServiceClient) GetDiagnosis(ctx context.Context, req *connect.Request[v1.GetDiagnosisRequest]) (*connect.Response[v1.GetDiagnosisResponse], error) {
	return c.getDiagnosis.CallUnary(ctx, req)
}

// ListDiagnoses calls agriculture.diagnosis.v1.PlantDiagnosisService.ListDiagnoses.
func (c *plantDiagnosisServiceClient) ListDiagnoses(ctx context.Context, req *connect.Request[v1.ListDiagnosesRequest]) (*connect.Response[v1.ListDiagnosesResponse], error) {
	return c.listDiagnoses.CallUnary(ctx, req)
}

// GetDiseaseInfo calls agriculture.diagnosis.v1.PlantDiagnosisService.GetDiseaseInfo.
func (c *plantDiagnosisServiceClient) GetDiseaseInfo(ctx context.Context, req *connect.Request[v1.GetDiseaseInfoRequest]) (*connect.Response[v1.GetDiseaseInfoResponse], error) {
	return c.getDiseaseInfo.CallUnary(ctx, req)
}

// GetTreatmentPlan calls agriculture.diagnosis.v1.PlantDiagnosisService.GetTreatmentPlan.
func (c *plantDiagnosisServiceClient) GetTreatmentPlan(ctx context.Context, req *connect.Request[v1.GetTreatmentPlanRequest]) (*connect.Response[v1.GetTreatmentPlanResponse], error) {
	return c.getTreatmentPlan.CallUnary(ctx, req)
}

// ListDiseases calls agriculture.diagnosis.v1.PlantDiagnosisService.ListDiseases.
func (c *plantDiagnosisServiceClient) ListDiseases(ctx context.Context, req *connect.Request[v1.ListDiseasesRequest]) (*connect.Response[v1.ListDiseasesResponse], error) {
	return c.listDiseases.CallUnary(ctx, req)
}

// IdentifySpecies calls agriculture.diagnosis.v1.PlantDiagnosisService.IdentifySpecies.
func (c *plantDiagnosisServiceClient) IdentifySpecies(ctx context.Context, req *connect.Request[v1.IdentifySpeciesRequest]) (*connect.Response[v1.IdentifySpeciesResponse], error) {
	return c.identifySpecies.CallUnary(ctx, req)
}

// DetectNutrientDeficiency calls
// agriculture.diagnosis.v1.PlantDiagnosisService.DetectNutrientDeficiency.
func (c *plantDiagnosisServiceClient) DetectNutrientDeficiency(ctx context.Context, req *connect.Request[v1.DetectNutrientDeficiencyRequest]) (*connect.Response[v1.DetectNutrientDeficiencyResponse], error) {
	return c.detectNutrientDeficiency.CallUnary(ctx, req)
}

// DetectPestDamage calls agriculture.diagnosis.v1.PlantDiagnosisService.DetectPestDamage.
func (c *plantDiagnosisServiceClient) DetectPestDamage(ctx context.Context, req *connect.Request[v1.DetectPestDamageRequest]) (*connect.Response[v1.DetectPestDamageResponse], error) {
	return c.detectPestDamage.CallUnary(ctx, req)
}

// PlantDiagnosisServiceHandler is an implementation of the
// agriculture.diagnosis.v1.PlantDiagnosisService service.
type PlantDiagnosisServiceHandler interface {
	// Submit a new plant diagnosis request with images
	SubmitDiagnosis(context.Context, *connect.Request[v1.SubmitDiagnosisRequest]) (*connect.Response[v1.SubmitDiagnosisResponse], error)
	// Get a diagnosis by ID
	GetDiagnosis(context.Context, *connect.Request[v1.GetDiagnosisRequest]) (*connect.Response[v1.GetDiagnosisResponse], error)
	// List diagnoses with filtering
	ListDiagnoses(context.Context, *connect.Request[v1.ListDiagnosesRequest]) (*connect.Response[v1.ListDiagnosesResponse], error)
	// Get disease information by ID
	GetDiseaseInfo(context.Context, *connect.Request[v1.GetDiseaseInfoRequest]) (*connect.Response[v1.GetDiseaseInfoResponse], error)
	// Get treatment plan for a diagnosis
	GetTreatmentPlan(context.Context, *connect.Request[v1.GetTreatmentPlanRequest]) (*connect.Response[v1.GetTreatmentPlanResponse], error)
	// List all known diseases
	ListDiseases(context.Context, *connect.Request[v1.ListDiseasesRequest]) (*connect.Response[v1.ListDiseasesResponse], error)
	// Identify plant species from images
	IdentifySpecies(context.Context, *connect.Request[v1.IdentifySpeciesRequest]) (*connect.Response[v1.IdentifySpeciesResponse], error)
	// Detect nutrient deficiencies from images
	DetectNutrientDeficiency(context.Context, *connect.Request[v1.DetectNutrientDeficiencyRequest]) (*connect.Response[v1.DetectNutrientDeficiencyResponse], error)
	// Detect pest damage from images
	DetectPestDamage(context.Context, *connect.Request[v1.DetectPestDamageRequest]) (*connect.Response[v1.DetectPestDamageResponse], error)
}

// NewPlantDiagnosisServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPlantDiagnosisServiceHandler(svc PlantDiagnosisServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	plantDiagnosisServiceMethods := v1.File_diagnosis_proto.Services().ByName("PlantDiagnosisService").Methods()
	plantDiagnosisServiceSubmitDiagnosisHandler := connect.NewUnaryHandler(
		PlantDiagnosisServiceSubmitDiagnosisProcedure,
		svc.SubmitDiagnosis,
		connect.WithSchema(plantDiagnosisServiceMethods.ByName("SubmitDiagnosis")),
		connect.WithHandlerOptions(opts...),
	)
	plantDiagnosisServiceGetDiagnosisHandler := connect.NewUnaryHandler(
		PlantDiagnosisServiceGetDiagnosisProcedure,
		svc.GetDiagnosis,
		connect.WithSchema(plantDiagnosisServiceMethods.ByName("GetDiagnosis")),
		connect.WithHandlerOptions(opts...),
	)
	plantDiagnosisServiceListDiagnosesHandler := connect.NewUnaryHandler(
		PlantDiagnosisServiceListDiagnosesProcedure,
		svc.ListDiagnoses,
		connect.WithSchema(plantDiagnosisServiceMethods.ByName("ListDiagnoses")),
		connect.WithHandlerOptions(opts...),
	)
	plantDiagnosisServiceGetDiseaseInfoHandler := connect.NewUnaryHandler(
		PlantDiagnosisServiceGetDiseaseInfoProcedure,
		svc.GetDiseaseInfo,
		connect.WithSchema(plantDiagnosisServiceMethods.ByName("GetDiseaseInfo")),
		connect.WithHandlerOptions(opts...),
	)
	plantDiagnosisServiceGetTreatmentPlanHandler := connect.NewUnaryHandler(
		PlantDiagnosisServiceGetTreatmentPlanProcedure,
		svc.GetTreatmentPlan,
		connect.WithSchema(plantDiagnosisServiceMethods.ByName("GetTreatmentPlan")),
		connect.WithHandlerOptions(opts...),
	)
	plantDiagnosisServiceListDiseasesHandler := connect.NewUnaryHandler(
		PlantDiagnosisServiceListDiseasesProcedure,
		svc.ListDiseases,
		connect.WithSchema(plantDiagnosisServiceMethods.ByName("ListDiseases")),
		connect.WithHandlerOptions(opts...),
	)
	plantDiagnosisServiceIdentifySpeciesHandler := connect.NewUnaryHandler(
		PlantDiagnosisServiceIdentifySpeciesProcedure,
		svc.IdentifySpecies,
		connect.WithSchema(plantDiagnosisServiceMethods.ByName("IdentifySpecies")),
		connect.WithHandlerOptions(opts...),
	)
	plantDiagnosisServiceDetectNutrientDeficiencyHandler := connect.NewUnaryHandler(
		PlantDiagnosisServiceDetectNutrientDeficiencyProcedure,
		svc.DetectNutrientDeficiency,
		connect.WithSchema(plantDiagnosisServiceMethods.ByName("DetectNutrientDeficiency")),
		connect.WithHandlerOptions(opts...),
	)
	plantDiagnosisServiceDetectPestDamageHandler := connect.NewUnaryHandler(
		PlantDiagnosisServiceDetectPestDamageProcedure,
		svc.DetectPestDamage,
		connect.WithSchema(plantDiagnosisServiceMethods.ByName("DetectPestDamage")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agriculture.diagnosis.v1.PlantDiagnosisService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PlantDiagnosisServiceSubmitDiagnosisProcedure:
			plantDiagnosisServiceSubmitDiagnosisHandler.ServeHTTP(w, r)
		case PlantDiagnosisServiceGetDiagnosisProcedure:
			plantDiagnosisServiceGetDiagnosisHandler.ServeHTTP(w, r)
		case PlantDiagnosisServiceListDiagnosesProcedure:
			plantDiagnosisServiceListDiagnosesHandler.ServeHTTP(w, r)
		case PlantDiagnosisServiceGetDiseaseInfoProcedure:
			plantDiagnosisServiceGetDiseaseInfoHandler.ServeHTTP(w, r)
		case PlantDiagnosisServiceGetTreatmentPlanProcedure:
			plantDiagnosisServiceGetTreatmentPlanHandler.ServeHTTP(w, r)
		case PlantDiagnosisServiceListDiseasesProcedure:
			plantDiagnosisServiceListDiseasesHandler.ServeHTTP(w, r)
		case PlantDiagnosisServiceIdentifySpeciesProcedure:
			plantDiagnosisServiceIdentifySpeciesHandler.ServeHTTP(w, r)
		case PlantDiagnosisServiceDetectNutrientDeficiencyProcedure:
			plantDiagnosisServiceDetectNutrientDeficiencyHandler.ServeHTTP(w, r)
		case PlantDiagnosisServiceDetectPestDamageProcedure:
			plantDiagnosisServiceDetectPestDamageHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPlantDiagnosisServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPlantDiagnosisServiceHandler struct{}

func (UnimplementedPlantDiagnosisServiceHandler) SubmitDiagnosis(context.Context, *connect.Request[v1.SubmitDiagnosisRequest]) (*connect.Response[v1.SubmitDiagnosisResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.diagnosis.v1.PlantDiagnosisService.SubmitDiagnosis is not implemented"))
}

func (UnimplementedPlantDiagnosisServiceHandler) GetDiagnosis(context.Context, *connect.Request[v1.GetDiagnosisRequest]) (*connect.Response[v1.GetDiagnosisResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.diagnosis.v1.PlantDiagnosisService.GetDiagnosis is not implemented"))
}

func (UnimplementedPlantDiagnosisServiceHandler) ListDiagnoses(context.Context, *connect.Request[v1.ListDiagnosesRequest]) (*connect.Response[v1.ListDiagnosesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.diagnosis.v1.PlantDiagnosisService.ListDiagnoses is not implemented"))
}

func (UnimplementedPlantDiagnosisServiceHandler) GetDiseaseInfo(context.Context, *connect.Request[v1.GetDiseaseInfoRequest]) (*connect.Response[v1.GetDiseaseInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.diagnosis.v1.PlantDiagnosisService.GetDiseaseInfo is not implemented"))
}

func (UnimplementedPlantDiagnosisServiceHandler) GetTreatmentPlan(context.Context, *connect.Request[v1.GetTreatmentPlanRequest]) (*connect.Response[v1.GetTreatmentPlanResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.diagnosis.v1.PlantDiagnosisService.GetTreatmentPlan is not implemented"))
}

func (UnimplementedPlantDiagnosisServiceHandler) ListDiseases(context.Context, *connect.Request[v1.ListDiseasesRequest]) (*connect.Response[v1.ListDiseasesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.diagnosis.v1.PlantDiagnosisService.ListDiseases is not implemented"))
}

func (UnimplementedPlantDiagnosisServiceHandler) IdentifySpecies(context.Context, *connect.Request[v1.IdentifySpeciesRequest]) (*connect.Response[v1.IdentifySpeciesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.diagnosis.v1.PlantDiagnosisService.IdentifySpecies is not implemented"))
}

func (UnimplementedPlantDiagnosisServiceHandler) DetectNutrientDeficiency(context.Context, *connect.Request[v1.DetectNutrientDeficiencyRequest]) (*connect.Response[v1.DetectNutrientDeficiencyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.diagnosis.v1.PlantDiagnosisService.DetectNutrientDeficiency is not implemented"))
}

func (UnimplementedPlantDiagnosisServiceHandler) DetectPestDamage(context.Context, *connect.Request[v1.DetectPestDamageRequest]) (*connect.Response[v1.DetectPestDamageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.diagnosis.v1.PlantDiagnosisService.DetectPestDamage is not implemented"))
}
