// Package grpc contains the inbound ConnectRPC adapter for the soil-service.
// NOTE: proto types are generated by buf generate.
package grpc

import (
	"context"

	"connectrpc.com/connect"
	"p9e.in/samavaya/packages/errors"
	"p9e.in/samavaya/packages/p9context"
	"p9e.in/samavaya/packages/p9log"
	"p9e.in/samavaya/packages/ulid"

	// Generated by buf generate
	pb "p9e.in/samavaya/agriculture/soil-service/api/v1"
	"p9e.in/samavaya/agriculture/soil-service/api/v1/soilv1connect"
	"p9e.in/samavaya/agriculture/soil-service/internal/mappers"
	"p9e.in/samavaya/agriculture/soil-service/internal/ports/inbound"
)

// SoilHandler is the ConnectRPC inbound adapter.
type SoilHandler struct {
	soilv1connect.UnimplementedSoilServiceHandler
	svc inbound.SoilService
	log *p9log.Helper
}

// NewSoilHandler creates a new ConnectRPC soil handler.
func NewSoilHandler(svc inbound.SoilService, log p9log.Logger) *SoilHandler {
	return &SoilHandler{
		svc: svc,
		log: p9log.NewHelper(p9log.With(log, "component", "SoilHandler")),
	}
}

// CreateSoilSample handles creation requests.
func (h *SoilHandler) CreateSoilSample(ctx context.Context, req *connect.Request[pb.CreateSoilSampleRequest]) (*connect.Response[pb.CreateSoilSampleResponse], error) {
	h.log.Infow("msg", "CreateSoilSample request", "tenant_id", p9context.TenantID(ctx))
	if req.Msg.GetFieldId() == "" {
		return nil, errors.BadRequest("INVALID_ARGUMENT", "field_id is required")
	}

	userID := p9context.UserID(ctx)
	sample := mappers.SoilSampleFromCreateRequest(req.Msg, ulid.NewString(), userID)

	created, err := h.svc.CreateSoilSample(ctx, sample)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.CreateSoilSampleResponse{Sample: mappers.SoilSampleToProto(created)}), nil
}

// GetSoilSample handles get requests.
func (h *SoilHandler) GetSoilSample(ctx context.Context, req *connect.Request[pb.GetSoilSampleRequest]) (*connect.Response[pb.GetSoilSampleResponse], error) {
	if req.Msg.GetId() == "" {
		return nil, errors.BadRequest("INVALID_ARGUMENT", "id is required")
	}
	tenantID := req.Msg.GetTenantId()
	if tenantID == "" {
		tenantID = p9context.TenantID(ctx)
	}

	entity, err := h.svc.GetSoilSample(ctx, req.Msg.GetId(), tenantID)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.GetSoilSampleResponse{Sample: mappers.SoilSampleToProto(entity)}), nil
}

// ListSoilSamples handles list requests.
func (h *SoilHandler) ListSoilSamples(ctx context.Context, req *connect.Request[pb.ListSoilSamplesRequest]) (*connect.Response[pb.ListSoilSamplesResponse], error) {
	tenantID := req.Msg.GetTenantId()
	if tenantID == "" {
		tenantID = p9context.TenantID(ctx)
	}

	samples, total, err := h.svc.ListSoilSamples(ctx, tenantID, req.Msg.GetFieldId(), req.Msg.GetFarmId(), req.Msg.GetPageSize(), req.Msg.GetPageOffset())
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.ListSoilSamplesResponse{
		Samples:    mappers.SoilSamplesToProto(samples),
		TotalCount: int32(total),
	}), nil
}

// AnalyzeSoil handles analysis requests.
func (h *SoilHandler) AnalyzeSoil(ctx context.Context, req *connect.Request[pb.AnalyzeSoilRequest]) (*connect.Response[pb.AnalyzeSoilResponse], error) {
	if req.Msg.GetSampleId() == "" {
		return nil, errors.BadRequest("INVALID_ARGUMENT", "sample_id is required")
	}
	tenantID := req.Msg.GetTenantId()
	if tenantID == "" {
		tenantID = p9context.TenantID(ctx)
	}

	analysis, err := h.svc.AnalyzeSoil(ctx, req.Msg.GetSampleId(), tenantID, req.Msg.GetAnalysisType())
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.AnalyzeSoilResponse{Analysis: mappers.SoilAnalysisToProto(analysis)}), nil
}

// ListSoilAnalyses handles list analyses requests.
func (h *SoilHandler) ListSoilAnalyses(ctx context.Context, req *connect.Request[pb.ListSoilAnalysesRequest]) (*connect.Response[pb.ListSoilAnalysesResponse], error) {
	tenantID := req.Msg.GetTenantId()
	if tenantID == "" {
		tenantID = p9context.TenantID(ctx)
	}

	analyses, total, err := h.svc.ListSoilAnalyses(ctx, tenantID, req.Msg.GetFieldId(), req.Msg.GetFarmId(), req.Msg.GetSampleId(), req.Msg.GetPageSize(), req.Msg.GetPageOffset())
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.ListSoilAnalysesResponse{
		Analyses:   mappers.SoilAnalysesToProto(analyses),
		TotalCount: int32(total),
	}), nil
}

// GetSoilMap handles get soil map requests.
func (h *SoilHandler) GetSoilMap(ctx context.Context, req *connect.Request[pb.GetSoilMapRequest]) (*connect.Response[pb.GetSoilMapResponse], error) {
	if req.Msg.GetFieldId() == "" {
		return nil, errors.BadRequest("INVALID_ARGUMENT", "field_id is required")
	}
	tenantID := req.Msg.GetTenantId()
	if tenantID == "" {
		tenantID = p9context.TenantID(ctx)
	}

	soilMap, err := h.svc.GetSoilMap(ctx, req.Msg.GetFieldId(), tenantID, req.Msg.GetMapType())
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.GetSoilMapResponse{SoilMap: mappers.SoilMapToProto(soilMap)}), nil
}

// GetSoilHealth handles get soil health requests.
func (h *SoilHandler) GetSoilHealth(ctx context.Context, req *connect.Request[pb.GetSoilHealthRequest]) (*connect.Response[pb.GetSoilHealthResponse], error) {
	if req.Msg.GetFieldId() == "" {
		return nil, errors.BadRequest("INVALID_ARGUMENT", "field_id is required")
	}
	tenantID := req.Msg.GetTenantId()
	if tenantID == "" {
		tenantID = p9context.TenantID(ctx)
	}

	health, err := h.svc.GetSoilHealth(ctx, req.Msg.GetFieldId(), tenantID)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.GetSoilHealthResponse{HealthScore: mappers.SoilHealthScoreToProto(health)}), nil
}

// GetNutrientLevels handles get nutrient levels requests.
func (h *SoilHandler) GetNutrientLevels(ctx context.Context, req *connect.Request[pb.GetNutrientLevelsRequest]) (*connect.Response[pb.GetNutrientLevelsResponse], error) {
	if req.Msg.GetSampleId() == "" {
		return nil, errors.BadRequest("INVALID_ARGUMENT", "sample_id is required")
	}
	tenantID := req.Msg.GetTenantId()
	if tenantID == "" {
		tenantID = p9context.TenantID(ctx)
	}

	nutrients, err := h.svc.GetNutrientLevels(ctx, req.Msg.GetSampleId(), tenantID)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.GetNutrientLevelsResponse{Nutrients: mappers.SoilNutrientsToProto(nutrients)}), nil
}

// GenerateSoilReport handles report generation requests.
func (h *SoilHandler) GenerateSoilReport(ctx context.Context, req *connect.Request[pb.GenerateSoilReportRequest]) (*connect.Response[pb.GenerateSoilReportResponse], error) {
	if req.Msg.GetFieldId() == "" {
		return nil, errors.BadRequest("INVALID_ARGUMENT", "field_id is required")
	}
	tenantID := req.Msg.GetTenantId()
	if tenantID == "" {
		tenantID = p9context.TenantID(ctx)
	}

	report, err := h.svc.GenerateSoilReport(ctx, req.Msg.GetFieldId(), tenantID, req.Msg.GetFarmId())
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return connect.NewResponse(&pb.GenerateSoilReportResponse{
		Report: mappers.SoilReportToProto(report, ulid.NewString(), tenantID, req.Msg.GetFieldId(), req.Msg.GetFarmId()),
	}), nil
}
