// Package grpc contains the inbound ConnectRPC adapter for the soil-service.
// NOTE: proto types are generated by buf generate.
package grpc

import (
	"context"

	"p9e.in/samavaya/packages/errors"
	"p9e.in/samavaya/packages/p9context"
	"p9e.in/samavaya/packages/p9log"

	// Generated by buf generate
	pb "p9e.in/samavaya/agriculture/soil-service/api/v1"
	"p9e.in/samavaya/agriculture/soil-service/internal/domain"
	"p9e.in/samavaya/agriculture/soil-service/internal/ports/inbound"
)

// SoilHandler is the ConnectRPC inbound adapter.
type SoilHandler struct {
	svc inbound.SoilService
	log *p9log.Helper
}

// NewSoilHandler creates a new ConnectRPC soil handler.
func NewSoilHandler(svc inbound.SoilService, log p9log.Logger) *SoilHandler {
	return &SoilHandler{
		svc: svc,
		log: p9log.NewHelper(p9log.With(log, "component", "SoilHandler")),
	}
}

// CreateSoil handles creation requests.
func (h *SoilHandler) CreateSoil(ctx context.Context, req *pb.CreateSoilRequest) (*pb.CreateSoilResponse, error) {
	h.log.Infow("msg", "CreateSoil request", "tenant_id", p9context.TenantID(ctx))
	if req.GetName() == "" {
		return nil, errors.BadRequest("INVALID_ARGUMENT", "name is required")
	}
	entity := &domain.Soil{Name: req.GetName()}
	created, err := h.svc.CreateSoil(ctx, entity)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return &pb.CreateSoilResponse{Soil: soilToProto(created)}, nil
}

// GetSoil handles get requests.
func (h *SoilHandler) GetSoil(ctx context.Context, req *pb.GetSoilRequest) (*pb.GetSoilResponse, error) {
	if req.GetId() == "" {
		return nil, errors.BadRequest("INVALID_ARGUMENT", "id is required")
	}
	entity, err := h.svc.GetSoil(ctx, req.GetId())
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return &pb.GetSoilResponse{Soil: soilToProto(entity)}, nil
}

// ListSoils handles list requests.
func (h *SoilHandler) ListSoils(ctx context.Context, req *pb.ListSoilsRequest) (*pb.ListSoilsResponse, error) {
	params := domain.ListSoilParams{PageSize: req.GetPageSize()}
	entities, total, err := h.svc.ListSoils(ctx, params)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	protos := make([]*pb.Soil, 0, len(entities))
	for i := range entities {
		protos = append(protos, soilToProto(&entities[i]))
	}
	return &pb.ListSoilsResponse{Soils: protos, TotalCount: total}, nil
}

// UpdateSoil handles update requests.
func (h *SoilHandler) UpdateSoil(ctx context.Context, req *pb.UpdateSoilRequest) (*pb.UpdateSoilResponse, error) {
	if req.GetId() == "" {
		return nil, errors.BadRequest("INVALID_ARGUMENT", "id is required")
	}
	entity := &domain.Soil{}
	entity.UUID = req.GetId()
	updated, err := h.svc.UpdateSoil(ctx, entity)
	if err != nil {
		return nil, errors.ToConnectError(err)
	}
	return &pb.UpdateSoilResponse{Soil: soilToProto(updated)}, nil
}

// DeleteSoil handles delete requests.
func (h *SoilHandler) DeleteSoil(ctx context.Context, req *pb.DeleteSoilRequest) (*pb.DeleteSoilResponse, error) {
	if req.GetId() == "" {
		return nil, errors.BadRequest("INVALID_ARGUMENT", "id is required")
	}
	if err := h.svc.DeleteSoil(ctx, req.GetId()); err != nil {
		return nil, errors.ToConnectError(err)
	}
	return &pb.DeleteSoilResponse{Success: true}, nil
}

func soilToProto(e *domain.Soil) *pb.Soil {
	return &pb.Soil{
		Id:       e.UUID,
		TenantId: e.TenantID,
		Name:     e.Name,
		Status:   string(e.Status),
	}
}
