// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: irrigation.proto

package irrigationv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "p9e.in/samavaya/agriculture/irrigation-service/api/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IrrigationServiceName is the fully-qualified name of the IrrigationService service.
	IrrigationServiceName = "agriculture.irrigation.v1.IrrigationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IrrigationServiceCreateScheduleProcedure is the fully-qualified name of the IrrigationService's
	// CreateSchedule RPC.
	IrrigationServiceCreateScheduleProcedure = "/agriculture.irrigation.v1.IrrigationService/CreateSchedule"
	// IrrigationServiceGetScheduleProcedure is the fully-qualified name of the IrrigationService's
	// GetSchedule RPC.
	IrrigationServiceGetScheduleProcedure = "/agriculture.irrigation.v1.IrrigationService/GetSchedule"
	// IrrigationServiceListSchedulesProcedure is the fully-qualified name of the IrrigationService's
	// ListSchedules RPC.
	IrrigationServiceListSchedulesProcedure = "/agriculture.irrigation.v1.IrrigationService/ListSchedules"
	// IrrigationServiceUpdateScheduleProcedure is the fully-qualified name of the IrrigationService's
	// UpdateSchedule RPC.
	IrrigationServiceUpdateScheduleProcedure = "/agriculture.irrigation.v1.IrrigationService/UpdateSchedule"
	// IrrigationServiceDeleteScheduleProcedure is the fully-qualified name of the IrrigationService's
	// DeleteSchedule RPC.
	IrrigationServiceDeleteScheduleProcedure = "/agriculture.irrigation.v1.IrrigationService/DeleteSchedule"
	// IrrigationServiceGenerateIrrigationDecisionProcedure is the fully-qualified name of the
	// IrrigationService's GenerateIrrigationDecision RPC.
	IrrigationServiceGenerateIrrigationDecisionProcedure = "/agriculture.irrigation.v1.IrrigationService/GenerateIrrigationDecision"
	// IrrigationServiceCreateZoneProcedure is the fully-qualified name of the IrrigationService's
	// CreateZone RPC.
	IrrigationServiceCreateZoneProcedure = "/agriculture.irrigation.v1.IrrigationService/CreateZone"
	// IrrigationServiceListZonesProcedure is the fully-qualified name of the IrrigationService's
	// ListZones RPC.
	IrrigationServiceListZonesProcedure = "/agriculture.irrigation.v1.IrrigationService/ListZones"
	// IrrigationServiceRegisterControllerProcedure is the fully-qualified name of the
	// IrrigationService's RegisterController RPC.
	IrrigationServiceRegisterControllerProcedure = "/agriculture.irrigation.v1.IrrigationService/RegisterController"
	// IrrigationServiceListControllersProcedure is the fully-qualified name of the IrrigationService's
	// ListControllers RPC.
	IrrigationServiceListControllersProcedure = "/agriculture.irrigation.v1.IrrigationService/ListControllers"
	// IrrigationServiceTriggerIrrigationProcedure is the fully-qualified name of the
	// IrrigationService's TriggerIrrigation RPC.
	IrrigationServiceTriggerIrrigationProcedure = "/agriculture.irrigation.v1.IrrigationService/TriggerIrrigation"
	// IrrigationServiceStopIrrigationProcedure is the fully-qualified name of the IrrigationService's
	// StopIrrigation RPC.
	IrrigationServiceStopIrrigationProcedure = "/agriculture.irrigation.v1.IrrigationService/StopIrrigation"
	// IrrigationServiceGetWaterUsageProcedure is the fully-qualified name of the IrrigationService's
	// GetWaterUsage RPC.
	IrrigationServiceGetWaterUsageProcedure = "/agriculture.irrigation.v1.IrrigationService/GetWaterUsage"
	// IrrigationServiceGetIrrigationHistoryProcedure is the fully-qualified name of the
	// IrrigationService's GetIrrigationHistory RPC.
	IrrigationServiceGetIrrigationHistoryProcedure = "/agriculture.irrigation.v1.IrrigationService/GetIrrigationHistory"
)

// IrrigationServiceClient is a client for the agriculture.irrigation.v1.IrrigationService service.
type IrrigationServiceClient interface {
	// Schedule management
	CreateSchedule(context.Context, *connect.Request[v1.CreateScheduleRequest]) (*connect.Response[v1.CreateScheduleResponse], error)
	GetSchedule(context.Context, *connect.Request[v1.GetScheduleRequest]) (*connect.Response[v1.GetScheduleResponse], error)
	ListSchedules(context.Context, *connect.Request[v1.ListSchedulesRequest]) (*connect.Response[v1.ListSchedulesResponse], error)
	UpdateSchedule(context.Context, *connect.Request[v1.UpdateScheduleRequest]) (*connect.Response[v1.UpdateScheduleResponse], error)
	DeleteSchedule(context.Context, *connect.Request[v1.DeleteScheduleRequest]) (*connect.Response[v1.DeleteScheduleResponse], error)
	// AI-driven irrigation decisions
	GenerateIrrigationDecision(context.Context, *connect.Request[v1.GenerateIrrigationDecisionRequest]) (*connect.Response[v1.GenerateIrrigationDecisionResponse], error)
	// Zone management
	CreateZone(context.Context, *connect.Request[v1.CreateZoneRequest]) (*connect.Response[v1.CreateZoneResponse], error)
	ListZones(context.Context, *connect.Request[v1.ListZonesRequest]) (*connect.Response[v1.ListZonesResponse], error)
	// Controller management
	RegisterController(context.Context, *connect.Request[v1.RegisterControllerRequest]) (*connect.Response[v1.RegisterControllerResponse], error)
	ListControllers(context.Context, *connect.Request[v1.ListControllersRequest]) (*connect.Response[v1.ListControllersResponse], error)
	// Irrigation control
	TriggerIrrigation(context.Context, *connect.Request[v1.TriggerIrrigationRequest]) (*connect.Response[v1.TriggerIrrigationResponse], error)
	StopIrrigation(context.Context, *connect.Request[v1.StopIrrigationRequest]) (*connect.Response[v1.StopIrrigationResponse], error)
	// Reporting
	GetWaterUsage(context.Context, *connect.Request[v1.GetWaterUsageRequest]) (*connect.Response[v1.GetWaterUsageResponse], error)
	GetIrrigationHistory(context.Context, *connect.Request[v1.GetIrrigationHistoryRequest]) (*connect.Response[v1.GetIrrigationHistoryResponse], error)
}

// NewIrrigationServiceClient constructs a client for the
// agriculture.irrigation.v1.IrrigationService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIrrigationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IrrigationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	irrigationServiceMethods := v1.File_irrigation_proto.Services().ByName("IrrigationService").Methods()
	return &irrigationServiceClient{
		createSchedule: connect.NewClient[v1.CreateScheduleRequest, v1.CreateScheduleResponse](
			httpClient,
			baseURL+IrrigationServiceCreateScheduleProcedure,
			connect.WithSchema(irrigationServiceMethods.ByName("CreateSchedule")),
			connect.WithClientOptions(opts...),
		),
		getSchedule: connect.NewClient[v1.GetScheduleRequest, v1.GetScheduleResponse](
			httpClient,
			baseURL+IrrigationServiceGetScheduleProcedure,
			connect.WithSchema(irrigationServiceMethods.ByName("GetSchedule")),
			connect.WithClientOptions(opts...),
		),
		listSchedules: connect.NewClient[v1.ListSchedulesRequest, v1.ListSchedulesResponse](
			httpClient,
			baseURL+IrrigationServiceListSchedulesProcedure,
			connect.WithSchema(irrigationServiceMethods.ByName("ListSchedules")),
			connect.WithClientOptions(opts...),
		),
		updateSchedule: connect.NewClient[v1.UpdateScheduleRequest, v1.UpdateScheduleResponse](
			httpClient,
			baseURL+IrrigationServiceUpdateScheduleProcedure,
			connect.WithSchema(irrigationServiceMethods.ByName("UpdateSchedule")),
			connect.WithClientOptions(opts...),
		),
		deleteSchedule: connect.NewClient[v1.DeleteScheduleRequest, v1.DeleteScheduleResponse](
			httpClient,
			baseURL+IrrigationServiceDeleteScheduleProcedure,
			connect.WithSchema(irrigationServiceMethods.ByName("DeleteSchedule")),
			connect.WithClientOptions(opts...),
		),
		generateIrrigationDecision: connect.NewClient[v1.GenerateIrrigationDecisionRequest, v1.GenerateIrrigationDecisionResponse](
			httpClient,
			baseURL+IrrigationServiceGenerateIrrigationDecisionProcedure,
			connect.WithSchema(irrigationServiceMethods.ByName("GenerateIrrigationDecision")),
			connect.WithClientOptions(opts...),
		),
		createZone: connect.NewClient[v1.CreateZoneRequest, v1.CreateZoneResponse](
			httpClient,
			baseURL+IrrigationServiceCreateZoneProcedure,
			connect.WithSchema(irrigationServiceMethods.ByName("CreateZone")),
			connect.WithClientOptions(opts...),
		),
		listZones: connect.NewClient[v1.ListZonesRequest, v1.ListZonesResponse](
			httpClient,
			baseURL+IrrigationServiceListZonesProcedure,
			connect.WithSchema(irrigationServiceMethods.ByName("ListZones")),
			connect.WithClientOptions(opts...),
		),
		registerController: connect.NewClient[v1.RegisterControllerRequest, v1.RegisterControllerResponse](
			httpClient,
			baseURL+IrrigationServiceRegisterControllerProcedure,
			connect.WithSchema(irrigationServiceMethods.ByName("RegisterController")),
			connect.WithClientOptions(opts...),
		),
		listControllers: connect.NewClient[v1.ListControllersRequest, v1.ListControllersResponse](
			httpClient,
			baseURL+IrrigationServiceListControllersProcedure,
			connect.WithSchema(irrigationServiceMethods.ByName("ListControllers")),
			connect.WithClientOptions(opts...),
		),
		triggerIrrigation: connect.NewClient[v1.TriggerIrrigationRequest, v1.TriggerIrrigationResponse](
			httpClient,
			baseURL+IrrigationServiceTriggerIrrigationProcedure,
			connect.WithSchema(irrigationServiceMethods.ByName("TriggerIrrigation")),
			connect.WithClientOptions(opts...),
		),
		stopIrrigation: connect.NewClient[v1.StopIrrigationRequest, v1.StopIrrigationResponse](
			httpClient,
			baseURL+IrrigationServiceStopIrrigationProcedure,
			connect.WithSchema(irrigationServiceMethods.ByName("StopIrrigation")),
			connect.WithClientOptions(opts...),
		),
		getWaterUsage: connect.NewClient[v1.GetWaterUsageRequest, v1.GetWaterUsageResponse](
			httpClient,
			baseURL+IrrigationServiceGetWaterUsageProcedure,
			connect.WithSchema(irrigationServiceMethods.ByName("GetWaterUsage")),
			connect.WithClientOptions(opts...),
		),
		getIrrigationHistory: connect.NewClient[v1.GetIrrigationHistoryRequest, v1.GetIrrigationHistoryResponse](
			httpClient,
			baseURL+IrrigationServiceGetIrrigationHistoryProcedure,
			connect.WithSchema(irrigationServiceMethods.ByName("GetIrrigationHistory")),
			connect.WithClientOptions(opts...),
		),
	}
}

// irrigationServiceClient implements IrrigationServiceClient.
type irrigationServiceClient struct {
	createSchedule             *connect.Client[v1.CreateScheduleRequest, v1.CreateScheduleResponse]
	getSchedule                *connect.Client[v1.GetScheduleRequest, v1.GetScheduleResponse]
	listSchedules              *connect.Client[v1.ListSchedulesRequest, v1.ListSchedulesResponse]
	updateSchedule             *connect.Client[v1.UpdateScheduleRequest, v1.UpdateScheduleResponse]
	deleteSchedule             *connect.Client[v1.DeleteScheduleRequest, v1.DeleteScheduleResponse]
	generateIrrigationDecision *connect.Client[v1.GenerateIrrigationDecisionRequest, v1.GenerateIrrigationDecisionResponse]
	createZone                 *connect.Client[v1.CreateZoneRequest, v1.CreateZoneResponse]
	listZones                  *connect.Client[v1.ListZonesRequest, v1.ListZonesResponse]
	registerController         *connect.Client[v1.RegisterControllerRequest, v1.RegisterControllerResponse]
	listControllers            *connect.Client[v1.ListControllersRequest, v1.ListControllersResponse]
	triggerIrrigation          *connect.Client[v1.TriggerIrrigationRequest, v1.TriggerIrrigationResponse]
	stopIrrigation             *connect.Client[v1.StopIrrigationRequest, v1.StopIrrigationResponse]
	getWaterUsage              *connect.Client[v1.GetWaterUsageRequest, v1.GetWaterUsageResponse]
	getIrrigationHistory       *connect.Client[v1.GetIrrigationHistoryRequest, v1.GetIrrigationHistoryResponse]
}

// CreateSchedule calls agriculture.irrigation.v1.IrrigationService.CreateSchedule.
func (c *irrigationServiceClient) CreateSchedule(ctx context.Context, req *connect.Request[v1.CreateScheduleRequest]) (*connect.Response[v1.CreateScheduleResponse], error) {
	return c.createSchedule.CallUnary(ctx, req)
}

// GetSchedule calls agriculture.irrigation.v1.IrrigationService.GetSchedule.
func (c *irrigationServiceClient) GetSchedule(ctx context.Context, req *connect.Request[v1.GetScheduleRequest]) (*connect.Response[v1.GetScheduleResponse], error) {
	return c.getSchedule.CallUnary(ctx, req)
}

// ListSchedules calls agriculture.irrigation.v1.IrrigationService.ListSchedules.
func (c *irrigationServiceClient) ListSchedules(ctx context.Context, req *connect.Request[v1.ListSchedulesRequest]) (*connect.Response[v1.ListSchedulesResponse], error) {
	return c.listSchedules.CallUnary(ctx, req)
}

// UpdateSchedule calls agriculture.irrigation.v1.IrrigationService.UpdateSchedule.
func (c *irrigationServiceClient) UpdateSchedule(ctx context.Context, req *connect.Request[v1.UpdateScheduleRequest]) (*connect.Response[v1.UpdateScheduleResponse], error) {
	return c.updateSchedule.CallUnary(ctx, req)
}

// DeleteSchedule calls agriculture.irrigation.v1.IrrigationService.DeleteSchedule.
func (c *irrigationServiceClient) DeleteSchedule(ctx context.Context, req *connect.Request[v1.DeleteScheduleRequest]) (*connect.Response[v1.DeleteScheduleResponse], error) {
	return c.deleteSchedule.CallUnary(ctx, req)
}

// GenerateIrrigationDecision calls
// agriculture.irrigation.v1.IrrigationService.GenerateIrrigationDecision.
func (c *irrigationServiceClient) GenerateIrrigationDecision(ctx context.Context, req *connect.Request[v1.GenerateIrrigationDecisionRequest]) (*connect.Response[v1.GenerateIrrigationDecisionResponse], error) {
	return c.generateIrrigationDecision.CallUnary(ctx, req)
}

// CreateZone calls agriculture.irrigation.v1.IrrigationService.CreateZone.
func (c *irrigationServiceClient) CreateZone(ctx context.Context, req *connect.Request[v1.CreateZoneRequest]) (*connect.Response[v1.CreateZoneResponse], error) {
	return c.createZone.CallUnary(ctx, req)
}

// ListZones calls agriculture.irrigation.v1.IrrigationService.ListZones.
func (c *irrigationServiceClient) ListZones(ctx context.Context, req *connect.Request[v1.ListZonesRequest]) (*connect.Response[v1.ListZonesResponse], error) {
	return c.listZones.CallUnary(ctx, req)
}

// RegisterController calls agriculture.irrigation.v1.IrrigationService.RegisterController.
func (c *irrigationServiceClient) RegisterController(ctx context.Context, req *connect.Request[v1.RegisterControllerRequest]) (*connect.Response[v1.RegisterControllerResponse], error) {
	return c.registerController.CallUnary(ctx, req)
}

// ListControllers calls agriculture.irrigation.v1.IrrigationService.ListControllers.
func (c *irrigationServiceClient) ListControllers(ctx context.Context, req *connect.Request[v1.ListControllersRequest]) (*connect.Response[v1.ListControllersResponse], error) {
	return c.listControllers.CallUnary(ctx, req)
}

// TriggerIrrigation calls agriculture.irrigation.v1.IrrigationService.TriggerIrrigation.
func (c *irrigationServiceClient) TriggerIrrigation(ctx context.Context, req *connect.Request[v1.TriggerIrrigationRequest]) (*connect.Response[v1.TriggerIrrigationResponse], error) {
	return c.triggerIrrigation.CallUnary(ctx, req)
}

// StopIrrigation calls agriculture.irrigation.v1.IrrigationService.StopIrrigation.
func (c *irrigationServiceClient) StopIrrigation(ctx context.Context, req *connect.Request[v1.StopIrrigationRequest]) (*connect.Response[v1.StopIrrigationResponse], error) {
	return c.stopIrrigation.CallUnary(ctx, req)
}

// GetWaterUsage calls agriculture.irrigation.v1.IrrigationService.GetWaterUsage.
func (c *irrigationServiceClient) GetWaterUsage(ctx context.Context, req *connect.Request[v1.GetWaterUsageRequest]) (*connect.Response[v1.GetWaterUsageResponse], error) {
	return c.getWaterUsage.CallUnary(ctx, req)
}

// GetIrrigationHistory calls agriculture.irrigation.v1.IrrigationService.GetIrrigationHistory.
func (c *irrigationServiceClient) GetIrrigationHistory(ctx context.Context, req *connect.Request[v1.GetIrrigationHistoryRequest]) (*connect.Response[v1.GetIrrigationHistoryResponse], error) {
	return c.getIrrigationHistory.CallUnary(ctx, req)
}

// IrrigationServiceHandler is an implementation of the agriculture.irrigation.v1.IrrigationService
// service.
type IrrigationServiceHandler interface {
	// Schedule management
	CreateSchedule(context.Context, *connect.Request[v1.CreateScheduleRequest]) (*connect.Response[v1.CreateScheduleResponse], error)
	GetSchedule(context.Context, *connect.Request[v1.GetScheduleRequest]) (*connect.Response[v1.GetScheduleResponse], error)
	ListSchedules(context.Context, *connect.Request[v1.ListSchedulesRequest]) (*connect.Response[v1.ListSchedulesResponse], error)
	UpdateSchedule(context.Context, *connect.Request[v1.UpdateScheduleRequest]) (*connect.Response[v1.UpdateScheduleResponse], error)
	DeleteSchedule(context.Context, *connect.Request[v1.DeleteScheduleRequest]) (*connect.Response[v1.DeleteScheduleResponse], error)
	// AI-driven irrigation decisions
	GenerateIrrigationDecision(context.Context, *connect.Request[v1.GenerateIrrigationDecisionRequest]) (*connect.Response[v1.GenerateIrrigationDecisionResponse], error)
	// Zone management
	CreateZone(context.Context, *connect.Request[v1.CreateZoneRequest]) (*connect.Response[v1.CreateZoneResponse], error)
	ListZones(context.Context, *connect.Request[v1.ListZonesRequest]) (*connect.Response[v1.ListZonesResponse], error)
	// Controller management
	RegisterController(context.Context, *connect.Request[v1.RegisterControllerRequest]) (*connect.Response[v1.RegisterControllerResponse], error)
	ListControllers(context.Context, *connect.Request[v1.ListControllersRequest]) (*connect.Response[v1.ListControllersResponse], error)
	// Irrigation control
	TriggerIrrigation(context.Context, *connect.Request[v1.TriggerIrrigationRequest]) (*connect.Response[v1.TriggerIrrigationResponse], error)
	StopIrrigation(context.Context, *connect.Request[v1.StopIrrigationRequest]) (*connect.Response[v1.StopIrrigationResponse], error)
	// Reporting
	GetWaterUsage(context.Context, *connect.Request[v1.GetWaterUsageRequest]) (*connect.Response[v1.GetWaterUsageResponse], error)
	GetIrrigationHistory(context.Context, *connect.Request[v1.GetIrrigationHistoryRequest]) (*connect.Response[v1.GetIrrigationHistoryResponse], error)
}

// NewIrrigationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIrrigationServiceHandler(svc IrrigationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	irrigationServiceMethods := v1.File_irrigation_proto.Services().ByName("IrrigationService").Methods()
	irrigationServiceCreateScheduleHandler := connect.NewUnaryHandler(
		IrrigationServiceCreateScheduleProcedure,
		svc.CreateSchedule,
		connect.WithSchema(irrigationServiceMethods.ByName("CreateSchedule")),
		connect.WithHandlerOptions(opts...),
	)
	irrigationServiceGetScheduleHandler := connect.NewUnaryHandler(
		IrrigationServiceGetScheduleProcedure,
		svc.GetSchedule,
		connect.WithSchema(irrigationServiceMethods.ByName("GetSchedule")),
		connect.WithHandlerOptions(opts...),
	)
	irrigationServiceListSchedulesHandler := connect.NewUnaryHandler(
		IrrigationServiceListSchedulesProcedure,
		svc.ListSchedules,
		connect.WithSchema(irrigationServiceMethods.ByName("ListSchedules")),
		connect.WithHandlerOptions(opts...),
	)
	irrigationServiceUpdateScheduleHandler := connect.NewUnaryHandler(
		IrrigationServiceUpdateScheduleProcedure,
		svc.UpdateSchedule,
		connect.WithSchema(irrigationServiceMethods.ByName("UpdateSchedule")),
		connect.WithHandlerOptions(opts...),
	)
	irrigationServiceDeleteScheduleHandler := connect.NewUnaryHandler(
		IrrigationServiceDeleteScheduleProcedure,
		svc.DeleteSchedule,
		connect.WithSchema(irrigationServiceMethods.ByName("DeleteSchedule")),
		connect.WithHandlerOptions(opts...),
	)
	irrigationServiceGenerateIrrigationDecisionHandler := connect.NewUnaryHandler(
		IrrigationServiceGenerateIrrigationDecisionProcedure,
		svc.GenerateIrrigationDecision,
		connect.WithSchema(irrigationServiceMethods.ByName("GenerateIrrigationDecision")),
		connect.WithHandlerOptions(opts...),
	)
	irrigationServiceCreateZoneHandler := connect.NewUnaryHandler(
		IrrigationServiceCreateZoneProcedure,
		svc.CreateZone,
		connect.WithSchema(irrigationServiceMethods.ByName("CreateZone")),
		connect.WithHandlerOptions(opts...),
	)
	irrigationServiceListZonesHandler := connect.NewUnaryHandler(
		IrrigationServiceListZonesProcedure,
		svc.ListZones,
		connect.WithSchema(irrigationServiceMethods.ByName("ListZones")),
		connect.WithHandlerOptions(opts...),
	)
	irrigationServiceRegisterControllerHandler := connect.NewUnaryHandler(
		IrrigationServiceRegisterControllerProcedure,
		svc.RegisterController,
		connect.WithSchema(irrigationServiceMethods.ByName("RegisterController")),
		connect.WithHandlerOptions(opts...),
	)
	irrigationServiceListControllersHandler := connect.NewUnaryHandler(
		IrrigationServiceListControllersProcedure,
		svc.ListControllers,
		connect.WithSchema(irrigationServiceMethods.ByName("ListControllers")),
		connect.WithHandlerOptions(opts...),
	)
	irrigationServiceTriggerIrrigationHandler := connect.NewUnaryHandler(
		IrrigationServiceTriggerIrrigationProcedure,
		svc.TriggerIrrigation,
		connect.WithSchema(irrigationServiceMethods.ByName("TriggerIrrigation")),
		connect.WithHandlerOptions(opts...),
	)
	irrigationServiceStopIrrigationHandler := connect.NewUnaryHandler(
		IrrigationServiceStopIrrigationProcedure,
		svc.StopIrrigation,
		connect.WithSchema(irrigationServiceMethods.ByName("StopIrrigation")),
		connect.WithHandlerOptions(opts...),
	)
	irrigationServiceGetWaterUsageHandler := connect.NewUnaryHandler(
		IrrigationServiceGetWaterUsageProcedure,
		svc.GetWaterUsage,
		connect.WithSchema(irrigationServiceMethods.ByName("GetWaterUsage")),
		connect.WithHandlerOptions(opts...),
	)
	irrigationServiceGetIrrigationHistoryHandler := connect.NewUnaryHandler(
		IrrigationServiceGetIrrigationHistoryProcedure,
		svc.GetIrrigationHistory,
		connect.WithSchema(irrigationServiceMethods.ByName("GetIrrigationHistory")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agriculture.irrigation.v1.IrrigationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IrrigationServiceCreateScheduleProcedure:
			irrigationServiceCreateScheduleHandler.ServeHTTP(w, r)
		case IrrigationServiceGetScheduleProcedure:
			irrigationServiceGetScheduleHandler.ServeHTTP(w, r)
		case IrrigationServiceListSchedulesProcedure:
			irrigationServiceListSchedulesHandler.ServeHTTP(w, r)
		case IrrigationServiceUpdateScheduleProcedure:
			irrigationServiceUpdateScheduleHandler.ServeHTTP(w, r)
		case IrrigationServiceDeleteScheduleProcedure:
			irrigationServiceDeleteScheduleHandler.ServeHTTP(w, r)
		case IrrigationServiceGenerateIrrigationDecisionProcedure:
			irrigationServiceGenerateIrrigationDecisionHandler.ServeHTTP(w, r)
		case IrrigationServiceCreateZoneProcedure:
			irrigationServiceCreateZoneHandler.ServeHTTP(w, r)
		case IrrigationServiceListZonesProcedure:
			irrigationServiceListZonesHandler.ServeHTTP(w, r)
		case IrrigationServiceRegisterControllerProcedure:
			irrigationServiceRegisterControllerHandler.ServeHTTP(w, r)
		case IrrigationServiceListControllersProcedure:
			irrigationServiceListControllersHandler.ServeHTTP(w, r)
		case IrrigationServiceTriggerIrrigationProcedure:
			irrigationServiceTriggerIrrigationHandler.ServeHTTP(w, r)
		case IrrigationServiceStopIrrigationProcedure:
			irrigationServiceStopIrrigationHandler.ServeHTTP(w, r)
		case IrrigationServiceGetWaterUsageProcedure:
			irrigationServiceGetWaterUsageHandler.ServeHTTP(w, r)
		case IrrigationServiceGetIrrigationHistoryProcedure:
			irrigationServiceGetIrrigationHistoryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIrrigationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIrrigationServiceHandler struct{}

func (UnimplementedIrrigationServiceHandler) CreateSchedule(context.Context, *connect.Request[v1.CreateScheduleRequest]) (*connect.Response[v1.CreateScheduleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.irrigation.v1.IrrigationService.CreateSchedule is not implemented"))
}

func (UnimplementedIrrigationServiceHandler) GetSchedule(context.Context, *connect.Request[v1.GetScheduleRequest]) (*connect.Response[v1.GetScheduleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.irrigation.v1.IrrigationService.GetSchedule is not implemented"))
}

func (UnimplementedIrrigationServiceHandler) ListSchedules(context.Context, *connect.Request[v1.ListSchedulesRequest]) (*connect.Response[v1.ListSchedulesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.irrigation.v1.IrrigationService.ListSchedules is not implemented"))
}

func (UnimplementedIrrigationServiceHandler) UpdateSchedule(context.Context, *connect.Request[v1.UpdateScheduleRequest]) (*connect.Response[v1.UpdateScheduleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.irrigation.v1.IrrigationService.UpdateSchedule is not implemented"))
}

func (UnimplementedIrrigationServiceHandler) DeleteSchedule(context.Context, *connect.Request[v1.DeleteScheduleRequest]) (*connect.Response[v1.DeleteScheduleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.irrigation.v1.IrrigationService.DeleteSchedule is not implemented"))
}

func (UnimplementedIrrigationServiceHandler) GenerateIrrigationDecision(context.Context, *connect.Request[v1.GenerateIrrigationDecisionRequest]) (*connect.Response[v1.GenerateIrrigationDecisionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.irrigation.v1.IrrigationService.GenerateIrrigationDecision is not implemented"))
}

func (UnimplementedIrrigationServiceHandler) CreateZone(context.Context, *connect.Request[v1.CreateZoneRequest]) (*connect.Response[v1.CreateZoneResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.irrigation.v1.IrrigationService.CreateZone is not implemented"))
}

func (UnimplementedIrrigationServiceHandler) ListZones(context.Context, *connect.Request[v1.ListZonesRequest]) (*connect.Response[v1.ListZonesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.irrigation.v1.IrrigationService.ListZones is not implemented"))
}

func (UnimplementedIrrigationServiceHandler) RegisterController(context.Context, *connect.Request[v1.RegisterControllerRequest]) (*connect.Response[v1.RegisterControllerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.irrigation.v1.IrrigationService.RegisterController is not implemented"))
}

func (UnimplementedIrrigationServiceHandler) ListControllers(context.Context, *connect.Request[v1.ListControllersRequest]) (*connect.Response[v1.ListControllersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.irrigation.v1.IrrigationService.ListControllers is not implemented"))
}

func (UnimplementedIrrigationServiceHandler) TriggerIrrigation(context.Context, *connect.Request[v1.TriggerIrrigationRequest]) (*connect.Response[v1.TriggerIrrigationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.irrigation.v1.IrrigationService.TriggerIrrigation is not implemented"))
}

func (UnimplementedIrrigationServiceHandler) StopIrrigation(context.Context, *connect.Request[v1.StopIrrigationRequest]) (*connect.Response[v1.StopIrrigationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.irrigation.v1.IrrigationService.StopIrrigation is not implemented"))
}

func (UnimplementedIrrigationServiceHandler) GetWaterUsage(context.Context, *connect.Request[v1.GetWaterUsageRequest]) (*connect.Response[v1.GetWaterUsageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.irrigation.v1.IrrigationService.GetWaterUsage is not implemented"))
}

func (UnimplementedIrrigationServiceHandler) GetIrrigationHistory(context.Context, *connect.Request[v1.GetIrrigationHistoryRequest]) (*connect.Response[v1.GetIrrigationHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agriculture.irrigation.v1.IrrigationService.GetIrrigationHistory is not implemented"))
}
