apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: yieldpoint

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - kafka.yaml
  - services.yaml
  - ingress.yaml
  - monitoring.yaml

commonLabels:
  app.kubernetes.io/part-of: yieldpoint
