apiVersion: v1
kind: ConfigMap
metadata:
  name: yieldpoint-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "yieldpoint.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
